use crate::hooks::base::HookLibrary;
use crate::hooks::registry::HookRegistry;
use crate::hooks::stub::stub_definitions;

const EXPORTS: &[(&str, &str, usize, crate::hooks::base::CallConv)] = &[
    (
        "advapi32.dll",
        "RegOpenKeyExW",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegOpenKeyExA",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegCreateKeyExW",
        9,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegCreateKeyExA",
        9,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegCreateKeyW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegQueryValueExW",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegQueryValueExA",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegSetValueExW",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegDeleteValueW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegDeleteKeyW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegEnumKeyExW",
        8,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegEnumKeyW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegEnumValueW",
        8,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegQueryValueW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegGetValueA",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegGetValueW",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegQueryInfoKeyW",
        12,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegCloseKey",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegNotifyChangeKeyValue",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "OpenSCManagerA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "OpenSCManagerW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "OpenServiceA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "OpenServiceW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CloseServiceHandle",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "QueryServiceStatus",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "QueryServiceStatusEx",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "QueryServiceConfigA",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "QueryServiceConfigW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "QueryServiceConfig2A",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "QueryServiceConfig2W",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "StartServiceA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "StartServiceW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "ControlService",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "EnumServicesStatusExA",
        10,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "EnumServicesStatusExW",
        10,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "IsTextUnicode",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "OpenProcessToken",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "OpenThreadToken",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "GetTokenInformation",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "ImpersonateSelf",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RevertToSelf",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "AdjustTokenPrivileges",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CreateWellKnownSid",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CopySid",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "AllocateAndInitializeSid",
        11,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "FreeSid",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "GetLengthSid",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "DuplicateToken",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "ImpersonateLoggedOnUser",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "LookupAccountNameA",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "LookupAccountNameW",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "LookupAccountSidA",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "LookupAccountSidW",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "BuildTrusteeWithSidW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "GetEffectiveRightsFromAclW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "GetNamedSecurityInfoW",
        8,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "SetNamedSecurityInfoW",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "SetEntriesInAclW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "GetUserNameA",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "GetUserNameW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CreateProcessAsUserW",
        11,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CreateProcessWithLogonW",
        11,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CryptAcquireContextA",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CryptAcquireContextW",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CryptGenRandom",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CryptHashData",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "CryptReleaseContext",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "ConvertStringSecurityDescriptorToSecurityDescriptorW",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "RegisterEventSourceA",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "ReportEventA",
        9,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "advapi32.dll",
        "DeregisterEventSource",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
];

/// Collects the generated hook definitions for this DLL family.
#[derive(Debug, Default, Clone, Copy)]
pub struct Advapi32HookLibrary;

impl HookLibrary for Advapi32HookLibrary {
    fn collect(&self) -> Vec<crate::hooks::base::HookDefinition> {
        stub_definitions(EXPORTS)
    }
}

/// Registers the generated hook definitions for this DLL family.
pub fn register_advapi32_hooks(registry: &mut HookRegistry) {
    registry.register_library(&Advapi32HookLibrary);
}
