//! Full `HookSignature` table for `bcrypt.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static BCRYPT_SIGNATURES: &[HookSignature] = &[
    // ── Algorithm Provider ────────────────────────────────────────────────
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptOpenAlgorithmProvider",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("phAlgorithm", GuestPtr, Out),
            ParamSpec::new("pszAlgId", PCWStr),
            ParamSpec::new("pszImplementation", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptCloseAlgorithmProvider",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAlgorithm", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Properties ────────────────────────────────────────────────────────
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptGetProperty",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hObject", Handle),
            ParamSpec::new("pszPropertyName", PCWStr),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptSetProperty",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hObject", Handle),
            ParamSpec::new("pszPropertyName", PCWStr),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Hash ──────────────────────────────────────────────────────────────
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptCreateHash",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAlgorithm", Handle),
            ParamSpec::with_dir("phHash", GuestPtr, Out),
            ParamSpec::new("pbHashObject", GuestPtr),
            ParamSpec::new("cbHashObject", U32),
            ParamSpec::new("pbSecret", GuestPtr),
            ParamSpec::new("cbSecret", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptHashData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptFinishHash",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptDestroyHash",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hHash", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptDuplicateHash",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::with_dir("phNewHash", GuestPtr, Out),
            ParamSpec::new("pbHashObject", GuestPtr),
            ParamSpec::new("cbHashObject", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Random ────────────────────────────────────────────────────────────
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptGenRandom",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAlgorithm", Handle),
            ParamSpec::with_dir("pbBuffer", GuestPtr, Out),
            ParamSpec::new("cbBuffer", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Key Management ────────────────────────────────────────────────────
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptGenerateSymmetricKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAlgorithm", Handle),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
            ParamSpec::new("pbKeyObject", GuestPtr),
            ParamSpec::new("cbKeyObject", U32),
            ParamSpec::new("pbSecret", GuestPtr),
            ParamSpec::new("cbSecret", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptImportKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAlgorithm", Handle),
            ParamSpec::new("hImportKey", Handle),
            ParamSpec::new("pszBlobType", PCWStr),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
            ParamSpec::new("pbKeyObject", GuestPtr),
            ParamSpec::new("cbKeyObject", U32),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptImportKeyPair",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAlgorithm", Handle),
            ParamSpec::new("hImportKey", Handle),
            ParamSpec::new("pszBlobType", PCWStr),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptExportKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("hExportKey", Handle),
            ParamSpec::new("pszBlobType", PCWStr),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptDestroyKey",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hKey", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Encrypt / Decrypt ─────────────────────────────────────────────────
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptEncrypt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("pPaddingInfo", GuestPtr),
            ParamSpec::with_dir("pbIV", GuestPtr, InOut),
            ParamSpec::new("cbIV", U32),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "bcrypt.dll",
        function: "BCryptDecrypt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("pPaddingInfo", GuestPtr),
            ParamSpec::with_dir("pbIV", GuestPtr, InOut),
            ParamSpec::new("cbIV", U32),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
];
