//! Full `HookSignature` table for `crypt32.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static CRYPT32_SIGNATURES: &[HookSignature] = &[
    // ── Certificate Store ─────────────────────────────────────────────────
    HookSignature {
        module: "crypt32.dll",
        function: "CertOpenStore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszStoreProvider", GuestPtr),
            ParamSpec::new("dwEncodingType", Hex32),
            ParamSpec::new("hCryptProv", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("pvPara", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertOpenSystemStoreW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProv", Handle),
            ParamSpec::new("szSubsystemProtocol", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertCloseStore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCertStore", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertAddStoreToCollection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCollectionStore", Handle),
            ParamSpec::new("hSiblingStore", Handle),
            ParamSpec::new("dwUpdateFlags", Hex32),
            ParamSpec::new("dwPriority", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Certificate Enumeration / Search ──────────────────────────────────
    HookSignature {
        module: "crypt32.dll",
        function: "CertFindCertificateInStore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCertStore", Handle),
            ParamSpec::new("dwCertEncodingType", Hex32),
            ParamSpec::new("dwFindFlags", Hex32),
            ParamSpec::new("dwFindType", Hex32),
            ParamSpec::new("pvFindPara", GuestPtr),
            ParamSpec::new("pPrevCertContext", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertEnumCertificatesInStore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCertStore", Handle),
            ParamSpec::new("pPrevCertContext", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertFreeCertificateContext",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pCertContext", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Certificate Properties / Name ─────────────────────────────────────
    HookSignature {
        module: "crypt32.dll",
        function: "CertGetCertificateContextProperty",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pCertContext", GuestPtr),
            ParamSpec::new("dwPropId", Hex32),
            ParamSpec::with_dir("pvData", GuestPtr, InOut),
            ParamSpec::with_dir("pcbData", GuestPtrTo(ParamTypeDiscriminant::U32), InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertGetNameStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pCertContext", GuestPtr),
            ParamSpec::new("dwType", U32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("pvTypePara", GuestPtr),
            ParamSpec::with_dir("pszNameString", PWStr, Out),
            ParamSpec::new("cchNameString", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Cryptographic Message Functions ───────────────────────────────────
    HookSignature {
        module: "crypt32.dll",
        function: "CryptDecodeObjectEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwCertEncodingType", Hex32),
            ParamSpec::new("lpszStructType", GuestPtr),
            ParamSpec::new("pbEncoded", GuestPtr),
            ParamSpec::new("cbEncoded", U32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("pfnAlloc", GuestPtr),
            ParamSpec::with_dir("pvStructInfo", GuestPtr, Out),
            ParamSpec::with_dir(
                "pcbStructInfo",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                InOut,
            ),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptDecodeObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwCertEncodingType", Hex32),
            ParamSpec::new("lpszStructType", GuestPtr),
            ParamSpec::new("pbEncoded", GuestPtr),
            ParamSpec::new("cbEncoded", U32),
            ParamSpec::new("lpszStructType2", GuestPtr),
            ParamSpec::with_dir("pvStructInfo", GuestPtr, InOut),
            ParamSpec::with_dir(
                "pcbStructInfo",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                InOut,
            ),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptQueryObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwObjectType", U32),
            ParamSpec::new("pvObject", GuestPtr),
            ParamSpec::new("dwExpectedContentTypeFlags", Hex32),
            ParamSpec::new("dwExpectedFormatTypeFlags", Hex32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pdwMsgAndCertEncodingType", GuestPtr, Out),
            ParamSpec::with_dir("pdwContentType", GuestPtr, Out),
            ParamSpec::with_dir("pdwFormatType", GuestPtr, Out),
            ParamSpec::with_dir("phCertStore", GuestPtr, Out),
            ParamSpec::with_dir("phMsg", GuestPtr, Out),
            ParamSpec::with_dir("ppvContext", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptMsgOpenToDecode",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwMsgEncodingType", Hex32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("dwMsgType", U32),
            ParamSpec::new("hCryptProv", Handle),
            ParamSpec::new("pRecipientInfo", GuestPtr),
            ParamSpec::new("pStreamInfo", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptMsgUpdate",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCryptMsg", Handle),
            ParamSpec::new("pbData", GuestPtr),
            ParamSpec::new("cbData", U32),
            ParamSpec::new("fFinal", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptMsgGetParam",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCryptMsg", Handle),
            ParamSpec::new("dwParamType", U32),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::with_dir("pvData", GuestPtr, Out),
            ParamSpec::with_dir("pcbData", GuestPtrTo(ParamTypeDiscriminant::U32), InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptMsgControl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hCryptMsg", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("dwCtrlType", U32),
            ParamSpec::new("pvCtrlPara", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Certificate Chain ─────────────────────────────────────────────────
    HookSignature {
        module: "crypt32.dll",
        function: "CertGetCertificateChain",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hChainEngine", Handle),
            ParamSpec::new("pCertContext", GuestPtr),
            ParamSpec::new("pTime", FileTimePtr),
            ParamSpec::new("hAdditionalStore", Handle),
            ParamSpec::new("pChainPara", GuestPtr),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("pvReserved", GuestPtr),
            ParamSpec::with_dir("ppChainContext", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CertFreeCertificateChain",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pChainContext", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "crypt32.dll",
        function: "CryptMsgClose",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hCryptMsg", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
