//! Full `HookSignature` table for `ncrypt.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static NCRYPT_SIGNATURES: &[HookSignature] = &[
    // ── Key Storage Provider ──────────────────────────────────────────────
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptOpenStorageProvider",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("phProvider", GuestPtr, Out),
            ParamSpec::new("pszProviderName", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Key Operations ────────────────────────────────────────────────────
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptOpenKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProvider", Handle),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
            ParamSpec::new("pszKeyName", PCWStr),
            ParamSpec::new("dwLegacyKeySpec", Hex32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptCreatePersistedKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProvider", Handle),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
            ParamSpec::new("pszAlgId", PCWStr),
            ParamSpec::new("pszKeyName", PCWStr),
            ParamSpec::new("dwLegacyKeySpec", Hex32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptFinalizeKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptDeleteKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptFreeObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hObject", Handle)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Property Access ───────────────────────────────────────────────────
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptGetProperty",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hObject", Handle),
            ParamSpec::new("pszProperty", PCWStr),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptSetProperty",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hObject", Handle),
            ParamSpec::new("pszProperty", PCWStr),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Cryptographic Operations ──────────────────────────────────────────
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptSignHash",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("pPaddingInfo", GuestPtr),
            ParamSpec::new("pbHashValue", GuestPtr),
            ParamSpec::new("cbHashValue", U32),
            ParamSpec::with_dir("pbSignature", GuestPtr, Out),
            ParamSpec::new("cbSignature", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptVerifySignature",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("pPaddingInfo", GuestPtr),
            ParamSpec::new("pbHashValue", GuestPtr),
            ParamSpec::new("cbHashValue", U32),
            ParamSpec::new("pbSignature", GuestPtr),
            ParamSpec::new("cbSignature", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptEncrypt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("pPaddingInfo", GuestPtr),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptDecrypt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("pbInput", GuestPtr),
            ParamSpec::new("cbInput", U32),
            ParamSpec::new("pPaddingInfo", GuestPtr),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::with_dir("pcbResult", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Key Import / Export ───────────────────────────────────────────────
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptImportKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProvider", Handle),
            ParamSpec::new("hImportKey", Handle),
            ParamSpec::new("pszBlobType", PCWStr),
            ParamSpec::new("pParameterList", GuestPtr),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
            ParamSpec::new("pbData", GuestPtr),
            ParamSpec::new("cbData", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ncrypt.dll",
        function: "NCryptExportKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("hExportKey", Handle),
            ParamSpec::new("pszBlobType", PCWStr),
            ParamSpec::new("pParameterList", GuestPtr),
            ParamSpec::with_dir("pbOutput", GuestPtr, Out),
            ParamSpec::new("cbOutput", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
];
