//! Full `HookSignature` table for `secur32.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static SECUR32_SIGNATURES: &[HookSignature] = &[
    // ── Credential Management ─────────────────────────────────────────────
    HookSignature {
        module: "secur32.dll",
        function: "AcquireCredentialsHandleA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPrincipal", PCStr),
            ParamSpec::new("pszPackage", PCStr),
            ParamSpec::new("fCredentialUse", U32),
            ParamSpec::new("pvLogonId", GuestPtr),
            ParamSpec::new("pAuthData", GuestPtr),
            ParamSpec::new("pGetKeyFn", GuestPtr),
            ParamSpec::new("pvGetKeyArgument", GuestPtr),
            ParamSpec::with_dir("phCredential", GuestPtr, Out),
            ParamSpec::with_dir("ptsExpiry", FileTimePtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "AcquireCredentialsHandleW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPrincipal", PCWStr),
            ParamSpec::new("pszPackage", PCWStr),
            ParamSpec::new("fCredentialUse", U32),
            ParamSpec::new("pvLogonId", GuestPtr),
            ParamSpec::new("pAuthData", GuestPtr),
            ParamSpec::new("pGetKeyFn", GuestPtr),
            ParamSpec::new("pvGetKeyArgument", GuestPtr),
            ParamSpec::with_dir("phCredential", GuestPtr, Out),
            ParamSpec::with_dir("ptsExpiry", FileTimePtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "FreeCredentialsHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("phCredential", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Security Context ──────────────────────────────────────────────────
    HookSignature {
        module: "secur32.dll",
        function: "InitializeSecurityContextA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phCredential", GuestPtr),
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::new("pszTargetName", PCStr),
            ParamSpec::new("fContextReq", Hex32),
            ParamSpec::new("Reserved1", U32),
            ParamSpec::new("TargetDataRep", U32),
            ParamSpec::new("pInput", GuestPtr),
            ParamSpec::new("Reserved2", U32),
            ParamSpec::with_dir("phNewContext", GuestPtr, Out),
            ParamSpec::with_dir("pOutput", GuestPtr, Out),
            ParamSpec::with_dir("pfContextAttr", GuestPtr, Out),
            ParamSpec::with_dir("ptsExpiry", FileTimePtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "InitializeSecurityContextW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phCredential", GuestPtr),
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::new("pszTargetName", PCWStr),
            ParamSpec::new("fContextReq", Hex32),
            ParamSpec::new("Reserved1", U32),
            ParamSpec::new("TargetDataRep", U32),
            ParamSpec::new("pInput", GuestPtr),
            ParamSpec::new("Reserved2", U32),
            ParamSpec::with_dir("phNewContext", GuestPtr, Out),
            ParamSpec::with_dir("pOutput", GuestPtr, Out),
            ParamSpec::with_dir("pfContextAttr", GuestPtr, Out),
            ParamSpec::with_dir("ptsExpiry", FileTimePtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "AcceptSecurityContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phCredential", GuestPtr),
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::new("pInput", GuestPtr),
            ParamSpec::new("fContextReq", Hex32),
            ParamSpec::new("TargetDataRep", U32),
            ParamSpec::with_dir("phNewContext", GuestPtr, Out),
            ParamSpec::with_dir("pOutput", GuestPtr, Out),
            ParamSpec::with_dir("pfContextAttr", GuestPtr, Out),
            ParamSpec::with_dir("ptsExpiry", FileTimePtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "DeleteSecurityContext",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("phContext", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Context Attributes ────────────────────────────────────────────────
    HookSignature {
        module: "secur32.dll",
        function: "QueryContextAttributesA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::new("ulAttribute", U32),
            ParamSpec::with_dir("pBuffer", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "QueryContextAttributesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::new("ulAttribute", U32),
            ParamSpec::with_dir("pBuffer", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Security Package Info ─────────────────────────────────────────────
    HookSignature {
        module: "secur32.dll",
        function: "QuerySecurityPackageInfoA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPackageName", PCStr),
            ParamSpec::with_dir("ppPackageInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "QuerySecurityPackageInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPackageName", PCWStr),
            ParamSpec::with_dir("ppPackageInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "EnumerateSecurityPackagesA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pcPackages", GuestPtr, Out),
            ParamSpec::with_dir("ppPackageInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "EnumerateSecurityPackagesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pcPackages", GuestPtr, Out),
            ParamSpec::with_dir("ppPackageInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "FreeContextBuffer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pvContextBuffer", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Message Security ──────────────────────────────────────────────────
    HookSignature {
        module: "secur32.dll",
        function: "EncryptMessage",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::new("fQOP", U32),
            ParamSpec::with_dir("pMessage", GuestPtr, InOut),
            ParamSpec::new("MessageSeqNo", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "secur32.dll",
        function: "DecryptMessage",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("phContext", GuestPtr),
            ParamSpec::with_dir("pMessage", GuestPtr, InOut),
            ParamSpec::new("MessageSeqNo", U32),
            ParamSpec::with_dir("pfQOP", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
];
