//! Full `HookSignature` table for high-frequency `msvcrt.dll` functions.
//!
//! Covers memory, string, conversion, and file I/O CRT functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static MSVCRT_SIGNATURES: &[HookSignature] = &[
    // ── Memory ────────────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "malloc",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("size", SizeT)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "free",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("ptr", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "realloc",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ptr", GuestPtr),
            ParamSpec::new("size", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "calloc",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("count", SizeT),
            ParamSpec::new("size", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "memcpy",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "memmove",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "memset",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("c", I32),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "memcmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buf1", GuestPtr),
            ParamSpec::new("buf2", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── String ────────────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "strlen",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcslen",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strcmp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str1", PCStr), ParamSpec::new("str2", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcscmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str1", PCWStr),
            ParamSpec::new("str2", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strncmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str1", PCStr),
            ParamSpec::new("str2", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcsncmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str1", PCWStr),
            ParamSpec::new("str2", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strcpy",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PStr), ParamSpec::new("src", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcscpy",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PWStr), ParamSpec::new("src", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strcat",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PStr), ParamSpec::new("src", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcscat",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PWStr), ParamSpec::new("src", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strchr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcschr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strstr",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCStr),
            ParamSpec::new("substr", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcsstr",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCWStr),
            ParamSpec::new("substr", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Conversion ────────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "atoi",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "atol",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strtol",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strtoul",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "toupper",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "tolower",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Sort / Search ─────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "qsort",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("base", GuestPtr),
            ParamSpec::new("nmemb", SizeT),
            ParamSpec::new("size", SizeT),
            ParamSpec::new("compar", FunctionPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "bsearch",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("key", GuestPtr),
            ParamSpec::new("base", GuestPtr),
            ParamSpec::new("nmemb", SizeT),
            ParamSpec::new("size", SizeT),
            ParamSpec::new("compar", FunctionPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── CRT init / control ────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "_initterm",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("pfbegin", GuestPtr),
            ParamSpec::new("pfend", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_amsg_exit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("retCode", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__set_app_type",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("type", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_controlfp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("new", U32), ParamSpec::new("mask", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_controlfp_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::with_dir("currentControl", GuestPtr, Out),
            ParamSpec::new("newControl", U32),
            ParamSpec::new("mask", U32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_set_fmode",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("mode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── File I/O ──────────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "fopen",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("filename", PCStr),
            ParamSpec::new("mode", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "fclose",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("stream", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "fread",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::with_dir("buffer", GuestPtr, Out),
            ParamSpec::new("size", SizeT),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("stream", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "fwrite",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", GuestPtr),
            ParamSpec::new("size", SizeT),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("stream", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "fseek",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("stream", GuestPtr),
            ParamSpec::new("offset", I32),
            ParamSpec::new("origin", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "ftell",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("stream", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Process / CRT lifecycle ──────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "abort",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "exit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("code", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_exit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("code", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_cexit",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "atexit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("func", FunctionPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_crt_atexit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("func", FunctionPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_execute_onexit_table",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("table", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_register_onexit_function",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("table", GuestPtr),
            ParamSpec::new("function", FunctionPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_initialize_onexit_table",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("table", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_initialize_narrow_environment",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_onexit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("func", FunctionPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_purecall",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Error / SEH / Exception ──────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "_errno",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "getenv",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("name", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "strerror",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("errnum", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_XcptFilter",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("xcptnum", I32),
            ParamSpec::new("pxcptinfoptrs", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_seh_filter_dll",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("unrecoverable", U32),
            ParamSpec::new("pxcptinfoptrs", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_seh_filter_exe",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("unrecoverable", U32),
            ParamSpec::new("pxcptinfoptrs", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__C_specific_handler",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("rec", GuestPtr),
            ParamSpec::new("frame", GuestPtr),
            ParamSpec::new("ctx", GuestPtr),
            ParamSpec::new("disp", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__CxxFrameHandler3",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("rec", GuestPtr),
            ParamSpec::new("frame", GuestPtr),
            ParamSpec::new("ctx", GuestPtr),
            ParamSpec::new("disp", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_CxxThrowException",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("pExceptionObject", GuestPtr),
            ParamSpec::new("pThrowInfo", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── CRT Internal ─────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "__getmainargs",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::with_dir("argc", GuestPtr, Out),
            ParamSpec::with_dir("argv", GuestPtr, Out),
            ParamSpec::with_dir("envp", GuestPtr, Out),
            ParamSpec::new("expandWildcards", I32),
            ParamSpec::new("startup", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__wgetmainargs",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::with_dir("argc", GuestPtr, Out),
            ParamSpec::with_dir("argv", GuestPtr, Out),
            ParamSpec::with_dir("envp", GuestPtr, Out),
            ParamSpec::new("expandWildcards", I32),
            ParamSpec::new("startup", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_initterm_e",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("pfbegin", GuestPtr),
            ParamSpec::new("pfend", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__vm_initterm_continue",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_callnewh",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("size", SizeT)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_invalid_parameter_noinfo_noreturn",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__vcrt_initializecriticalsectionex",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("pcs", GuestPtr),
            ParamSpec::new("pinit", GuestPtr),
            ParamSpec::new("pfInitOnce", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── CRT Locale / Character / Misc ────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "setlocale",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("category", I32),
            ParamSpec::new("locale", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__setusermatherr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("pf", FunctionPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_lock",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("locknum", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_unlock",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("locknum", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "terminate",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_ismbblead",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", U32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Math ─────────────────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "srand",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("seed", U32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "rand",
        abi: LogicalAbi::Cdecl,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_time64",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::with_dir("timer", GuestPtr, Out)],
        ret: ReturnSpec::PointerSizedInt,
        flags: HookFlags::empty(),
    },
    // ── Character classification ─────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "iswspace",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── CRT String / Conversion ──────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "_stricmp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str1", PCStr), ParamSpec::new("str2", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_wcsicmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str1", PCWStr),
            ParamSpec::new("str2", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_itow",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I32),
            ParamSpec::new("string", PWStr),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_itow_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I32),
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("sizeInCharacters", SizeT),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcscpy_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PWStr),
            ParamSpec::new("numberOfElements", SizeT),
            ParamSpec::new("src", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_wcsdup",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcsrchr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_wtoi",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_wtol",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcstol",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCWStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("base", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcstoul",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCWStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("base", I32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcstod",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCWStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "wcstok_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PWStr),
            ParamSpec::new("delim", PCWStr),
            ParamSpec::with_dir("context", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── CRT Memory safe ──────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "memcpy_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("destSize", SizeT),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "memmove_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("destSize", SizeT),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Variadic / Printf ────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "_vsnprintf_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PStr),
            ParamSpec::new("sizeOfBuffer", SizeT),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("argptr", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::from_bits(HookFlags::VARIADIC),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "_vsnwprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("format", PCWStr),
            ParamSpec::new("argptr", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::from_bits(HookFlags::VARIADIC),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "swprintf_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("sizeOfBuffer", SizeT),
            ParamSpec::new("format", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::from_bits(HookFlags::VARIADIC),
    },
    // ── CRT Internal 2 ───────────────────────────────────────────────────
    HookSignature {
        module: "msvcrt.dll",
        function: "__dllonexit",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("func", FunctionPtr),
            ParamSpec::with_dir("pbegin", GuestPtr, InOut),
            ParamSpec::with_dir("pend", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__crtGetStringTypeW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dwType", U32),
            ParamSpec::new("Locale", U32),
            ParamSpec::new("pSrc", PCWStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::with_dir("pCharType", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__crtLCMapStringW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwMapFlags", Hex32),
            ParamSpec::new("lpSrcStr", PCWStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::new("lpDestStr", PWStr),
            ParamSpec::new("cchDest", I32),
            ParamSpec::new("dwCodePage", U32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msvcrt.dll",
        function: "__RTDynamicCast",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("inptr", GuestPtr),
            ParamSpec::new("VfDelta", I32),
            ParamSpec::new("srcTypeID", GuestPtr),
            ParamSpec::new("targetTypeID", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
];
