//! Full `HookSignature` table for `msvcp140.dll` functions.
//!
//! msvcp140 exports C++ mangled names. These are stub placeholders with
//! `WinApi` ABI, no typed parameters, and `Void` return.

use crate::hooks::signature::{HookSignature, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi};

/// Helper to generate a stub signature for a C++ mangled export.
const fn cpp_stub(function: &'static str) -> HookSignature {
    HookSignature {
        module: "msvcp140.dll",
        function,
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    }
}

pub(super) static MSVCP140_SIGNATURES: &[HookSignature] = &[
    // ── C++ mangled exports ───────────────────────────────────────────────
    cpp_stub("??0?$basic_ios@DU?$char_traits@D@std@@@std@@IEAA@XZ"),
    cpp_stub("??0?$basic_iostream@DU?$char_traits@D@std@@@std@@QEAA@PEAV?$basic_streambuf@DU?$char_traits@D@std@@@1@@Z"),
    cpp_stub("??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ"),
    cpp_stub("??0_Locinfo@std@@QEAA@PEBD@Z"),
    cpp_stub("??0_Lockit@std@@QEAA@H@Z"),
    cpp_stub("??0ctype_base@std@@QEAA@_K@Z"),
    cpp_stub("??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ"),
    cpp_stub("??1?$basic_iostream@DU?$char_traits@D@std@@@std@@UEAA@XZ"),
    cpp_stub("??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ"),
    cpp_stub("??1_Locinfo@std@@QEAA@XZ"),
    cpp_stub("??1_Lockit@std@@QEAA@XZ"),
    cpp_stub("??1ctype_base@std@@UEAA@XZ"),
    cpp_stub("??5?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@AEAH@Z"),
    cpp_stub("??5?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@AEA_J@Z"),
    cpp_stub("??5?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@AEA_K@Z"),
    cpp_stub("??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@G@Z"),
    cpp_stub("??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@H@Z"),
    cpp_stub("??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@P6AAEAV01@AEAV01@@Z@Z"),
    cpp_stub("??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@P6AAEAVios_base@1@AEAV21@@Z@Z"),
    cpp_stub("??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@_K@Z"),
    cpp_stub("??Bid@locale@std@@QEAA_KXZ"),
    cpp_stub("?_BADOFF@std@@3_JB"),
    cpp_stub("?_Decref@facet@locale@std@@UEAAPEAV_Facet_base@3@XZ"),
    cpp_stub("?_Getctype@_Locinfo@std@@QEBA?AU_Ctypevec@@XZ"),
    cpp_stub("?_Getcvt@_Locinfo@std@@QEBA?AU_Cvtvec@@XZ"),
    cpp_stub("?_Getgloballocale@locale@std@@CAPEAV_Locimp@12@XZ"),
    cpp_stub("?_Incref@facet@locale@std@@UEAAXXZ"),
    cpp_stub("?_Init@locale@std@@CAPEAV_Locimp@12@_N@Z"),
    cpp_stub("?_Ipfx@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAA_N_N@Z"),
    cpp_stub("?_Lock@?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAAXXZ"),
    cpp_stub("?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ"),
    cpp_stub("?_Random_device@std@@YAIXZ"),
    cpp_stub("?_Throw_C_error@std@@YAXH@Z"),
    cpp_stub("?_Throw_Cpp_error@std@@YAXH@Z"),
    cpp_stub("?_Unlock@?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAAXXZ"),
    cpp_stub("?_Xbad_alloc@std@@YAXXZ"),
    cpp_stub("?_Xbad_function_call@std@@YAXXZ"),
    cpp_stub("?_Xlength_error@std@@YAXPEBD@Z"),
    cpp_stub("?_Xout_of_range@std@@YAXPEBD@Z"),
    cpp_stub("?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ"),
    cpp_stub("?gbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXH@Z"),
    cpp_stub("?imbue@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAXAEBVlocale@2@@Z"),
    cpp_stub("?pbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXH@Z"),
    cpp_stub("?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@D@Z"),
    cpp_stub("?sbumpc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ"),
    cpp_stub("?setbuf@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAPEAV12@PEAD_J@Z"),
    cpp_stub("?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z"),
    cpp_stub("?sgetc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ"),
    cpp_stub("?showmanyc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JXZ"),
    cpp_stub("?snextc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHXZ"),
    cpp_stub("?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z"),
    cpp_stub("?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z"),
    cpp_stub("?sync@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAHXZ"),
    cpp_stub("?uflow@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAAHXZ"),
    cpp_stub("?uncaught_exception@std@@YA_NXZ"),
    cpp_stub("?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADD@Z"),
    cpp_stub("?xsgetn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEAD_J@Z"),
    cpp_stub("?xsputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@MEAA_JPEBD_J@Z"),

    // ── C-compatible exports (threading / locale / time) ──────────────────
    cpp_stub("_Cnd_destroy"),
    cpp_stub("_Cnd_destroy_in_situ"),
    cpp_stub("_Cnd_do_broadcast_at_thread_exit"),
    cpp_stub("_Cnd_init"),
    cpp_stub("_Cnd_init_in_situ"),
    cpp_stub("_Cnd_signal"),
    cpp_stub("_Cnd_timedwait"),
    cpp_stub("_Cnd_wait"),
    cpp_stub("_Mtx_current_owns"),
    cpp_stub("_Mtx_destroy"),
    cpp_stub("_Mtx_destroy_in_situ"),
    cpp_stub("_Mtx_init"),
    cpp_stub("_Mtx_init_in_situ"),
    cpp_stub("_Mtx_lock"),
    cpp_stub("_Mtx_unlock"),
    cpp_stub("_Query_perf_counter"),
    cpp_stub("_Query_perf_frequency"),
    cpp_stub("_Thrd_detach"),
    cpp_stub("_Thrd_id"),
    cpp_stub("_Thrd_join"),
    cpp_stub("_Thrd_sleep"),
    cpp_stub("_Thrd_start"),
    cpp_stub("_Tolower"),
    cpp_stub("_Toupper"),
    cpp_stub("_Xtime_get_ticks"),
];
