use crate::hooks::base::HookLibrary;
use crate::hooks::registry::HookRegistry;
use crate::hooks::stub::stub_definitions;

const EXPORTS: &[(&str, &str, usize, crate::hooks::base::CallConv)] = &[
    (
        "msvcrt.dll",
        "?terminate@@YAXXZ",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "terminate",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_controlfp",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__set_app_type",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__p__fmode",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__p__commode",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__setusermatherr",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_amsg_exit",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_initterm",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_initterm_e",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__vm_initterm_continue",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_acmdln",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    ("msvcrt.dll", "exit", 1, crate::hooks::base::CallConv::Cdecl),
    (
        "msvcrt.dll",
        "_XcptFilter",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_seh_filter_dll",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_seh_filter_exe",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_exit",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_cexit",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__getmainargs",
        5,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "memset",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_ismbblead",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_time64",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "srand",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_vsnwprintf",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    ("msvcrt.dll", "rand", 0, crate::hooks::base::CallConv::Cdecl),
    (
        "msvcrt.dll",
        "wcsrchr",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "calloc",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "malloc",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "realloc",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "memmove",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_stricmp",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_wcsicmp",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "atexit",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_crt_atexit",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_execute_onexit_table",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_register_onexit_function",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_errno",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "strerror",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_initialize_onexit_table",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_initialize_narrow_environment",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_invalid_parameter_noinfo_noreturn",
        0,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__vcrt_initializecriticalsectionex",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    ("msvcrt.dll", "atoi", 1, crate::hooks::base::CallConv::Cdecl),
    (
        "msvcrt.dll",
        "_callnewh",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "memcmp",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "strlen",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "strchr",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "strstr",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__C_specific_handler",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "__CxxFrameHandler3",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "_CxxThrowException",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "??2@YAPEAX_K@Z",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "msvcrt.dll",
        "??3@YAXPEAX@Z",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    ("msvcrt.dll", "free", 1, crate::hooks::base::CallConv::Cdecl),
];

#[derive(Debug, Default, Clone, Copy)]
pub struct MsvcrtHookLibrary;

impl HookLibrary for MsvcrtHookLibrary {
    fn collect(&self) -> Vec<crate::hooks::base::HookDefinition> {
        stub_definitions(EXPORTS)
    }
}

pub fn register_msvcrt_hooks(registry: &mut HookRegistry) {
    registry.register_library(&MsvcrtHookLibrary);
}
