//! Full `HookSignature` table for ucrt (api-ms-win-crt-*) functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static UCRT_SIGNATURES: &[HookSignature] = &[
    // ── api-ms-win-crt-runtime-l1-1-0.dll ─────────────────────────────────
    HookSignature {
        module: "api-ms-win-crt-runtime-l1-1-0.dll",
        function: "_configure_narrow_argv",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("mode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-runtime-l1-1-0.dll",
        function: "_configure_wide_argv",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("mode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── api-ms-win-crt-string-l1-1-0.dll ──────────────────────────────────
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "isalnum",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "isalpha",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "isspace",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "strncat_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PStr),
            ParamSpec::new("sizeInBytes", SizeT),
            ParamSpec::new("src", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "strncpy",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PStr),
            ParamSpec::new("src", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "strncpy_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PStr),
            ParamSpec::new("sizeInBytes", SizeT),
            ParamSpec::new("src", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "tolower",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "wcsncat_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PWStr),
            ParamSpec::new("sizeInWords", SizeT),
            ParamSpec::new("src", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-string-l1-1-0.dll",
        function: "wcsncpy_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PWStr),
            ParamSpec::new("sizeInWords", SizeT),
            ParamSpec::new("src", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── api-ms-win-crt-filesystem-l1-1-0.dll ──────────────────────────────
    HookSignature {
        module: "api-ms-win-crt-filesystem-l1-1-0.dll",
        function: "_wchmod",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("path", PCWStr), ParamSpec::new("mode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── api-ms-win-crt-math-l1-1-0.dll ────────────────────────────────────
    HookSignature {
        module: "api-ms-win-crt-math-l1-1-0.dll",
        function: "pow",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("x", GuestPtr), ParamSpec::new("y", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── api-ms-win-crt-time-l1-1-0.dll ────────────────────────────────────
    HookSignature {
        module: "api-ms-win-crt-time-l1-1-0.dll",
        function: "_gmtime64_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("sourceTime", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-time-l1-1-0.dll",
        function: "_localtime64_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("sourceTime", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── api-ms-win-crt-stdio-l1-1-0.dll ───────────────────────────────────
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "_set_fmode",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("mode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "__stdio_common_vsnprintf_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("options", U64),
            ParamSpec::new("buffer", PStr),
            ParamSpec::new("bufferCount", SizeT),
            ParamSpec::new("maxCount", SizeT),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("locale", GuestPtr),
            ParamSpec::new("argList", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "__stdio_common_vsnwprintf_s",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("options", U64),
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("bufferCount", SizeT),
            ParamSpec::new("maxCount", SizeT),
            ParamSpec::new("format", PCWStr),
            ParamSpec::new("locale", GuestPtr),
            ParamSpec::new("argList", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "__stdio_common_vsscanf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("options", U64),
            ParamSpec::new("buffer", PCStr),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("argList", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "fclose",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("stream", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "fopen",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("filename", PCStr),
            ParamSpec::new("mode", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "fread",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", GuestPtr),
            ParamSpec::new("elementSize", SizeT),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("stream", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "fseek",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("stream", GuestPtr),
            ParamSpec::new("offset", I64),
            ParamSpec::new("origin", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "api-ms-win-crt-stdio-l1-1-0.dll",
        function: "ftell",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("stream", GuestPtr)],
        ret: ReturnSpec::I64,
        flags: HookFlags::empty(),
    },
];
