use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static USER32_SIGS_1: &[HookSignature] = &[
    // ── Message Box ───────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "MessageBoxA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("lpText", PCStr),
            ParamSpec::new("lpCaption", PCStr),
            ParamSpec::new("uType", Hex32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "MessageBoxW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("lpText", PCWStr),
            ParamSpec::new("lpCaption", PCWStr),
            ParamSpec::new("uType", Hex32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Window ────────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "FindWindowA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpClassName", PCStr),
            ParamSpec::new("lpWindowName", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "FindWindowW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpClassName", PCWStr),
            ParamSpec::new("lpWindowName", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetDesktopWindow",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetForegroundWindow",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetCursor",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "ShowWindow",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("nCmdShow", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CreateWindowExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwExStyle", Hex32),
            ParamSpec::new("lpClassName", PCWStr),
            ParamSpec::new("lpWindowName", PCWStr),
            ParamSpec::new("dwStyle", Hex32),
            ParamSpec::new("X", I32),
            ParamSpec::new("Y", I32),
            ParamSpec::new("nWidth", I32),
            ParamSpec::new("nHeight", I32),
            ParamSpec::new("hWndParent", Handle),
            ParamSpec::new("hMenu", Handle),
            ParamSpec::new("hInstance", ModuleHandle),
            ParamSpec::new("lpParam", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CreateWindowExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwExStyle", Hex32),
            ParamSpec::new("lpClassName", PCStr),
            ParamSpec::new("lpWindowName", PCStr),
            ParamSpec::new("dwStyle", Hex32),
            ParamSpec::new("X", I32),
            ParamSpec::new("Y", I32),
            ParamSpec::new("nWidth", I32),
            ParamSpec::new("nHeight", I32),
            ParamSpec::new("hWndParent", Handle),
            ParamSpec::new("hMenu", Handle),
            ParamSpec::new("hInstance", ModuleHandle),
            ParamSpec::new("lpParam", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DestroyWindow",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetParent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "MoveWindow",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("X", I32),
            ParamSpec::new("Y", I32),
            ParamSpec::new("nWidth", I32),
            ParamSpec::new("nHeight", I32),
            ParamSpec::new("bRepaint", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "SetWindowPos",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("hWndInsertAfter", Handle),
            ParamSpec::new("X", I32),
            ParamSpec::new("Y", I32),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
            ParamSpec::new("uFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetWindowRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::with_dir("lpRect", OpaqueStructPtr("RECT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetClientRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::with_dir("lpRect", OpaqueStructPtr("RECT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetWindowTextW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("lpString", PWStr),
            ParamSpec::new("nMaxCount", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetWindowThreadProcessId",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::with_dir("lpdwProcessId", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Message ───────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "SendMessageA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("Msg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "SendMessageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("Msg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "PostMessageA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("Msg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "PostMessageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("Msg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "PeekMessageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpMsg", OpaqueStructPtr("MSG"), Out),
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("wMsgFilterMin", U32),
            ParamSpec::new("wMsgFilterMax", U32),
            ParamSpec::new("wRemoveMsg", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetMessageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpMsg", OpaqueStructPtr("MSG"), Out),
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("wMsgFilterMin", U32),
            ParamSpec::new("wMsgFilterMax", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "TranslateMessage",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpMsg", OpaqueStructPtr("MSG"))],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DispatchMessageW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpMsg", OpaqueStructPtr("MSG"))],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DispatchMessageA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpMsg", OpaqueStructPtr("MSG"))],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DefWindowProcW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("Msg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "PostQuitMessage",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("nExitCode", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── System ────────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "GetSystemMetrics",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("nIndex", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "LoadCursorW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstance", ModuleHandle),
            ParamSpec::new("lpCursorName", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "LoadIconW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstance", ModuleHandle),
            ParamSpec::new("lpIconName", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "RegisterClassExW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpwcx", OpaqueStructPtr("WNDCLASSEXW"))],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "RegisterClassExA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpwcx", OpaqueStructPtr("WNDCLASSEXA"))],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetDC",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "ReleaseDC",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("hDC", Handle),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Timer / Hook / Enum ───────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "SetTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("nIDEvent", PointerSizedUInt),
            ParamSpec::new("uElapse", U32),
            ParamSpec::new("lpTimerFunc", FunctionPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "KillTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("uIDEvent", PointerSizedUInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "SetWindowsHookExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("idHook", I32),
            ParamSpec::new("lpfn", FunctionPtr),
            ParamSpec::new("hMod", ModuleHandle),
            ParamSpec::new("dwThreadId", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CallNextHookEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hhk", Handle),
            ParamSpec::new("nCode", I32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "UnhookWindowsHookEx",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hhk", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "EnumWindows",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpEnumFunc", FunctionPtr),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "SystemParametersInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("uiAction", U32),
            ParamSpec::new("uiParam", U32),
            ParamSpec::new("pvParam", GuestPtr),
            ParamSpec::new("fWinIni", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetCursorPos",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "lpPoint",
            OpaqueStructPtr("POINT"),
            Out,
        )],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetKBCodePage",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "BeginPaint",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::with_dir("lpPaint", OpaqueStructPtr("PAINTSTRUCT"), Out),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "EndPaint",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("lpPaint", OpaqueStructPtr("PAINTSTRUCT")),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "IsWindow",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "IsWindowVisible",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "GetActiveWindow",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Window (extended) ────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "AdjustWindowRectEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpRect", OpaqueStructPtr("RECT"), Out),
            ParamSpec::new("dwStyle", Hex32),
            ParamSpec::new("bMenu", Bool32),
            ParamSpec::new("dwExStyle", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "BringWindowToTop",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "ClientToScreen",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::with_dir("lpPoint", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Window Position ──────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "BeginDeferWindowPos",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("nNumWindows", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DeferWindowPos",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWinPosInfo", Handle),
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("hWndInsertAfter", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
            ParamSpec::new("uFlags", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Window Procedure ─────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CallWindowProcW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpPrevWndFunc", FunctionPtr),
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("Msg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DefFrameProcW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("hWndMDIClient", Handle),
            ParamSpec::new("uMsg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DefMDIChildProcW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("uMsg", U32),
            ParamSpec::new("wParam", PointerSizedUInt),
            ParamSpec::new("lParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    // ── Character ────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CharNextA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpsz", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CharNextW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpsz", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CharToOemBuffA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszSrc", PCStr),
            ParamSpec::new("lpszDst", PStr),
            ParamSpec::new("cchDstLength", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CharUpperBuffW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpsz", PWStr),
            ParamSpec::new("cchLength", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CharUpperW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpsz", PWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Clipboard ────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CloseClipboard",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CountClipboardFormats",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Control ──────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CheckDlgButton",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDlg", Handle),
            ParamSpec::new("nIDButton", I32),
            ParamSpec::new("uCheck", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Menu ─────────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "AppendMenuW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hMenu", Handle),
            ParamSpec::new("uFlags", Hex32),
            ParamSpec::new("uIDNewItem", PointerSizedUInt),
            ParamSpec::new("lpNewItem", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CheckMenuItem",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hmenu", Handle),
            ParamSpec::new("uIDCheckItem", U32),
            ParamSpec::new("uCheck", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CreateMenu",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CreatePopupMenu",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DeleteMenu",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hMenu", Handle),
            ParamSpec::new("uPosition", U32),
            ParamSpec::new("uFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DestroyMenu",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMenu", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DrawMenuBar",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Accelerator ──────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CopyAcceleratorTableW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAccelSrc", Handle),
            ParamSpec::new("lpAccelDst", GuestPtr),
            ParamSpec::new("cAccelEntries", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CreateAcceleratorTableW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("paccel", GuestPtr),
            ParamSpec::new("cAccel", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DestroyAcceleratorTable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hAccel", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Icon / Cursor ────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CopyIcon",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hIcon", Handle)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "CopyImage",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("h", Handle),
            ParamSpec::new("type", U32),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
            ParamSpec::new("flags", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DestroyCursor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hCursor", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DestroyIcon",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hIcon", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Gesture ──────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CloseGestureInfoHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hGestureInfo", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Rect ─────────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CopyRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lprcDst", OpaqueStructPtr("RECT"), Out),
            ParamSpec::new("lprcSrc", OpaqueStructPtr("RECT")),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Dialog ───────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "CreateDialogIndirectParamW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstance", ModuleHandle),
            ParamSpec::new("lpTemplate", GuestPtr),
            ParamSpec::new("hWndParent", Handle),
            ParamSpec::new("lpDialogFunc", FunctionPtr),
            ParamSpec::new("dwInitParam", PointerSizedInt),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DialogBoxParamW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstance", ModuleHandle),
            ParamSpec::new("lpTemplateName", PCWStr),
            ParamSpec::new("hWndParent", Handle),
            ParamSpec::new("lpDialogFunc", FunctionPtr),
            ParamSpec::new("dwInitParam", PointerSizedInt),
        ],
        ret: ReturnSpec::PointerSizedInt,
        flags: HookFlags::empty(),
    },
    // ── Drawing ──────────────────────────────────────────────────────────
    HookSignature {
        module: "user32.dll",
        function: "DrawEdge",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("qrc", OpaqueStructPtr("RECT"), Out),
            ParamSpec::new("edge", U32),
            ParamSpec::new("grfFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DrawFocusRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDC", Handle),
            ParamSpec::new("lprc", OpaqueStructPtr("RECT")),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DrawFrameControl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lprc", OpaqueStructPtr("RECT"), Out),
            ParamSpec::new("uType", U32),
            ParamSpec::new("uState", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DrawIcon",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDC", Handle),
            ParamSpec::new("X", I32),
            ParamSpec::new("Y", I32),
            ParamSpec::new("hIcon", Handle),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DrawIconEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("xLeft", I32),
            ParamSpec::new("yTop", I32),
            ParamSpec::new("hIcon", Handle),
            ParamSpec::new("cxWidth", I32),
            ParamSpec::new("cyWidth", I32),
            ParamSpec::new("istepIfAniCur", U32),
            ParamSpec::new("hbrFlickerFreeDraw", Handle),
            ParamSpec::new("diFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "user32.dll",
        function: "DrawStateW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("hbrFore", Handle),
            ParamSpec::new("qfnCallBack", FunctionPtr),
            ParamSpec::new("lData", PointerSizedInt),
            ParamSpec::new("wData", PointerSizedUInt),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
            ParamSpec::new("fuFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
