use super::*;

impl VirtualExecutionEngine {
    /// Nt/Zw/Rtl/Ldr/Csr/Etw/Tp/CRT/BCrypt/ALPC stubs -- mega-stub arm.
    ///
    /// All entries in this group return `Ok(STATUS_SUCCESS as u64)`.
    /// The `_ =>` wildcard stays in the main dispatcher.
    pub(in crate::runtime::engine) fn dispatch_ntdll_stubs(
        &mut self,
        function: &str,
        ctx: &HookContext<'_>,
    ) -> Option<Result<u64, VmError>> {
        let _ = ctx;
        match function {
            // -- Remaining Nt/Zw stubs (iteration 3 batch) --
            "NtAccessCheckByType" | "NtAccessCheckByTypeAndAuditAlarm"
            | "NtAccessCheckByTypeResultList" | "NtAcquireCrossVmMutant"
            | "NtAcquireProcessActivityReference" | "NtAddAtom"
            | "NtAddAtomEx" | "NtAddBootEntry"
            | "NtAddDriverEntry" | "NtAdjustGroupsToken"
            | "NtAdjustTokenClaimsAndDeviceGroups" | "NtAlertThreadByThreadId"
            | "NtAllocateReserveObject" | "NtAllocateUserPhysicalPages"
            | "NtAllocateUserPhysicalPagesEx" | "NtCallbackReturn"
            | "NtCallEnclave" | "NtCancelSynchronousIo"
            | "NtCancelSynchronousIoFile" | "NtCancelTimer2"
            | "NtChangeWnfStateData" | "NtCloseObjectAuditAlarm"
            | "NtCommitComplete" | "NtCommitEnlistment"
            | "NtCommitRegistryTransaction" | "NtCompareObjects"
            | "NtCompareSigningLevels" | "NtCompareTokens"
            | "NtConnectNamedPipe" | "NtContinueEx"
            | "NtCopyFileChunk" | "NtCreateCrossVmEvent"
            | "NtCreateCrossVmMutant" | "NtCreateEnclave"
            | "NtCreateIRTimer" | "NtCreateJobSet"
            | "NtCreateKeyedEvent" | "NtCreateLowBoxToken"
            | "NtCreatePartition" | "NtCreatePrivateNamespace"
            | "NtCreateProfile" | "NtCreateProfileEx"
            | "NtCreateRegistryTransaction" | "NtCreateSectionEx"
            | "NtCreateTimer2" | "NtCreateToken"
            | "NtCreateTokenEx" | "NtCreateWaitCompletionPacket"
            | "NtCreateWnfStateName" | "NtCreateWorkerFactory"
            | "NtDeleteAtom" | "NtDeleteBootEntry"
            | "NtDeleteDriverEntry" | "NtDeleteObjectAuditAlarm"
            | "NtDeletePrivateNamespace" | "NtDeleteWnfStateData"
            | "NtDeleteWnfStateName" | "NtDirectGraphicsCall"
            | "NtDisableLastKnownGood" | "NtdllDefWindowProc_A"
            | "NtdllDefWindowProc_W" | "NtdllDialogWndProc_A"
            | "NtdllDialogWndProc_W" | "NtDrawText"
            | "NtEnableLastKnownGood" | "NtEnumerateBootEntries"
            | "NtEnumerateDriverEntries" | "NtEnumerateSystemEnvironmentValuesEx"
            | "NtEnumerateTransactionObject" | "NtFilterBootOption"
            | "NtFilterToken" | "NtFilterTokenEx"
            | "NtFindAtom" | "NtFlushInstallUILanguage"
            | "NtFlushInstructionCache" | "NtFlushProcessWriteBuffers"
            | "NtFlushWriteBuffer" | "NtFreeUserPhysicalPages"
            | "NtFreezeRegistry" | "NtFreezeTransactions"
            | "NtGetCachedSigningLevel" | "NtGetCompleteWnfStateSubscription"
            | "NtGetCurrentProcessorNumberEx" | "NtGetDevicePowerState"
            | "NtGetMUIRegistryInfo" | "NtGetNlsSectionPtr"
            | "NtGetNotificationResourceManager" | "NtInitializeEnclave"
            | "NtInitializeNlsFiles" | "NtInitializeRegistry"
            | "NtInitiatePowerAction" | "NtIsSystemResumeAutomatic"
            | "NtIsUILanguageComitted" | "NtLoadEnclaveData"
            | "NtLockProductActivationKeys" | "NtManageHotPatch"
            | "NtManagePartition" | "NtMapCMFModule"
            | "NtMapUserPhysicalPages" | "NtMapUserPhysicalPagesScatter"
            | "NtModifyBootEntry" | "NtModifyDriverEntry"
            | "NtNotifyChangeDirectoryFileEx" | "NtNotifyChangeSession"
            | "NtOpenObjectAuditAlarm" | "NtOpenPartition"
            | "NtOpenPrivateNamespace" | "NtOpenRegistryTransaction"
            | "NtOpenSession" | "NtPlugPlayControl"
            | "NtPrepareComplete" | "NtPrepareEnlistment"
            | "NtPrePrepareComplete" | "NtPrePrepareEnlistment"
            | "NtPrivilegedServiceAuditAlarm" | "NtPrivilegeObjectAuditAlarm"
            | "NtPropagationComplete" | "NtPropagationFailed"
            | "NtPssCaptureVaSpaceBulk" | "NtQueryAuxiliaryCounterFrequency"
            | "NtQueryBootEntryOrder" | "NtQueryBootOptions"
            | "NtQueryDebugFilterState" | "NtQueryDriverEntryOrder"
            | "NtQueryInformationAtom" | "NtQueryInformationEnlistment"
            | "NtQueryInformationPort" | "NtQueryInformationResourceManager"
            | "NtQueryInformationTransaction" | "NtQueryInformationTransactionManager"
            | "NtQueryInformationWorkerFactory" | "NtQueryIntervalProfile"
            | "NtQueryIoCompletion" | "NtQueryPortInformationProcess"
            | "NtQuerySecurityAttributesToken" | "NtQuerySecurityPolicy"
            | "NtQuerySystemEnvironmentValue" | "NtQuerySystemEnvironmentValueEx"
            | "NtQueryWnfStateNameInformation" | "NtQueueApcThreadEx"
            | "NtQueueApcThreadEx2" | "NtRaiseException"
            | "NtRaiseHardError" | "NtReadOnlyEnlistment"
            | "NtReadRequestData" | "NtRecoverEnlistment"
            | "NtRecoverResourceManager" | "NtRecoverTransactionManager"
            | "NtRegisterProtocolAddressInformation" | "NtRegisterThreadTerminatePort"
            | "NtReleaseWorkerFactoryWorker" | "NtRemoveIoCompletionEx"
            | "NtRenameTransactionManager" | "NtReplacePartitionUnit"
            | "NtResumeProcess" | "NtRevertContainerImpersonation"
            | "NtRollbackComplete" | "NtRollbackEnlistment"
            | "NtRollbackRegistryTransaction" | "NtRollforwardTransactionManager"
            | "NtSerializeBoot" | "NtSetBootEntryOrder"
            | "NtSetBootOptions" | "NtSetCachedSigningLevel"
            | "NtSetCachedSigningLevel2" | "NtSetDebugFilterState"
            | "NtSetDefaultHardErrorPort" | "NtSetDefaultLocale"
            | "NtSetDefaultUILanguage" | "NtSetDriverEntryOrder"
            | "NtSetEventBoostPriority" | "NtSetHighEventPair"
            | "NtSetHighWaitLowEventPair" | "NtSetInformationEnlistment"
            | "NtSetInformationKey" | "NtSetInformationObject"
            | "NtSetInformationResourceManager" | "NtSetInformationSymbolicLink"
            | "NtSetInformationToken" | "NtSetInformationTransaction"
            | "NtSetInformationTransactionManager" | "NtSetInformationVirtualMemory"
            | "NtSetInformationWorkerFactory" | "NtSetIntervalProfile"
            | "NtSetIoCompletionEx" | "NtSetIRTimer"
            | "NtSetLdtEntries" | "NtSetLowEventPair"
            | "NtSetLowWaitHighEventPair" | "NtSetSystemEnvironmentValue"
            | "NtSetSystemEnvironmentValueEx" | "NtSetSystemPowerState"
            | "NtSetSystemTime" | "NtSetThreadExecutionState"
            | "NtSetTimer2" | "NtSetUuidSeed"
            | "NtSetWnfProcessNotificationEvent" | "NtShutdownSystem"
            | "NtShutdownWorkerFactory" | "NtSinglePhaseReject"
            | "NtStartProfile" | "NtStopProfile"
            | "NtSubscribeWnfStateChange" | "NtSuspendProcess"
            | "NtSystemDebugControl" | "NtTerminateEnclave"
            | "NtThawRegistry" | "NtThawTransactions"
            | "NtTranslateFilePath" | "NtUmsThreadYield"
            | "NtUnsubscribeWnfStateChange" | "NtVdmControl"
            | "NtWaitForAlertByThreadId" | "NtWaitForMultipleObjects32"
            | "NtWaitForWorkViaWorkerFactory" | "NtWaitHighEventPair"
            | "NtWaitLowEventPair" | "NtWorkerFactoryCreate"
            | "NtWorkerFactoryReady" | "NtWorkerFactoryRelease"
            | "NtWorkerFactoryShutdown" | "NtWorkerFactoryWait"
            | "NtWorkerFactoryWorkerReady" | "NtWriteRequestData"
            | "NtYieldExecution"
            // ALPC Nt* stubs
            | "NtAlpcAcceptConnectPort" | "NtAlpcCancelMessage"
            | "NtAlpcConnectPort" | "NtAlpcConnectPortEx"
            | "NtAlpcCreatePort" | "NtAlpcCreatePortSection"
            | "NtAlpcCreateResourceReserve" | "NtAlpcCreateSectionView"
            | "NtAlpcCreateSecurityContext" | "NtAlpcDeletePortSection"
            | "NtAlpcDeleteResourceReserve" | "NtAlpcDeleteSectionView"
            | "NtAlpcDeleteSecurityContext" | "NtAlpcDisconnectPort"
            | "NtAlpcImpersonateClientContainerOfPort" | "NtAlpcImpersonateClientOfPort"
            | "NtAlpcOpenSenderProcess" | "NtAlpcOpenSenderThread"
            | "NtAlpcQueryInformation" | "NtAlpcQueryInformationMessage"
            | "NtAlpcRevokeSecurityContext" | "NtAlpcSendWaitReceivePort"
            | "NtAlpcSetInformation"
            // Remaining Zw* stubs
            | "ZwAlertThreadByThreadId" | "ZwCancelTimer2"
            | "ZwClose" | "ZwDuplicateObject"
            | "ZwGetTickCount" | "ZwRemoveProcessDebug"
            | "ZwSetTimer2" | "ZwWaitForAlertByThreadId"
            // -- Remaining Rtl stubs (iteration 3 batch) --
            | "RtlAbsoluteToSelfRelativeSD" | "RtlAddAccessAllowedAce"
            | "RtlAddAccessAllowedAceEx" | "RtlAddAccessAllowedObjectAce"
            | "RtlAddAccessDeniedAce" | "RtlAddAccessDeniedAceEx"
            | "RtlAddAccessDeniedObjectAce" | "RtlAddAce"
            | "RtlAddAuditAccessAce" | "RtlAddAuditAccessAceEx"
            | "RtlAddAuditAccessObjectAce" | "RtlAddCompoundAce"
            | "RtlAddIntegrityLabelToBoundaryDescriptor" | "RtlAddMandatoryAce"
            | "RtlAddRefMemoryStream" | "RtlAddSIDToBoundaryDescriptor"
            | "RtlAllocateAndInitializeSID" | "RtlAllocateMemoryBlockLookaside"
            | "RtlAllocateMemoryZone" | "RtlAnsiCharToUnicodeChar"
            | "RtlAppendAsciizToString" | "RtlApplyLengthToAcl"
            | "RtlAreAllAccessesGranted" | "RtlAreAnyAccessesGranted"
            | "RtlAreBitsClear" | "RtlAreBitsSet"
            | "RtlAssert" | "RtlBackupEventLog"
            | "RtlBindImageUntrusted" | "RtlBitTestAndComplement"
            | "RtlBitTestAndReset" | "RtlBitTestAndSet"
            | "RtlCrc64" | "RtlCreateAcl"
            | "RtlCreateAndSetSD" | "RtlCreateAtomTable"
            | "RtlCreateRegistryKey" | "RtlCreateSecurityDescriptor"
            | "RtlCreateServiceSid" | "RtlCreateSystemVolumeInformationFolder"
            | "RtlCreateTagHeap" | "RtlCreateTimer"
            | "RtlCreateUserProcess" | "RtlCreateUserSecurityObject"
            | "RtlCreateVirtualAccountSid" | "RtlCustomCPToUnicodeN"
            | "RtlDecompressBufferEx" | "RtlDecompressFragment"
            | "RtlDefaultNpAcl" | "RtlDelete"
            | "RtlDeleteAce" | "RtlDeleteAtomFromAtomTable"
            | "RtlDeleteAtomTable" | "RtlDeleteBoundaryDescriptor"
            | "RtlDeleteElementGenericTableAvl" | "RtlDeleteRegistryValue"
            | "RtlDeleteResource" | "RtlDeleteSecurityObject"
            | "RtlDeleteTimer" | "RtlDeleteTimerQueue"
            | "RtlDeleteTimerQueueEx" | "RtlDeregisterWait"
            | "RtlDestroyHeap" | "RtlDestroyMemoryBlockLookaside"
            | "RtlDetermineDosPathNameType" | "RtlDetermineDosPathNameType_U"
            | "RtlDisableThreadProfiling" | "RtlDosLongPathToNtPathPath_U_WithStatus"
            | "RtlDosSearchPath_U" | "RtlDosSearchPath_Ustr"
            | "RtlDowncaseUnicodeChar" | "RtlDumpResource"
            | "RtlEnableThreadProfiling" | "RtlEnlargedIntegerMultiply"
            | "RtlEnlargedUnsignedDivide" | "RtlEnlargedUnsignedMultiply"
            | "RtlEnumerateEntryHashTable" | "RtlEqualComputerName"
            | "RtlEqualDomainName" | "RtlEqualPrefixSid"
            | "RtlEqualSid" | "RtlEqualString"
            | "RtlExtendedIntegerMultiply" | "RtlExtendedLargeIntegerDivide"
            | "RtlFillMemoryUlong" | "RtlFillMemoryUlonglong"
            | "RtlFindClearBits" | "RtlFindClearBitsAndSet"
            | "RtlFindClearRuns" | "RtlFindFirstRunClear"
            | "RtlFindLastBackwardRunClear" | "RtlFindLongestRunClear"
            | "RtlFindMessage" | "RtlFindNextForwardRunClear"
            | "RtlFindSetBits" | "RtlFindSetBitsAndClear"
            | "RtlFormatCurrentUserKeyPath" | "RtlFormatMessage"
            | "RtlFormatMessageEx" | "RtlFreeMemoryBlockLookaside"
            | "RtlFreeThreadExecutionEnvironment" | "RtlFreeUserThreadStack"
            | "RtlGenerate8dot3Name" | "RtlGetAce"
            | "RtlGetAclInformation" | "RtlGetControlSecurityDescriptor"
            | "RtlGetDaclSecurityDescriptor" | "RtlGetElementGenericTable"
            | "RtlGetElementGenericTableAvl" | "RtlGetFirstEntryHashTable"
            | "RtlGetFrame" | "RtlGetGroupSecurityDescriptor"
            | "RtlGetIntegerAtom" | "RtlGetLengthWithoutLastFullOrBackSlash"
            | "RtlGetLengthWithoutTrailingPathSeperators" | "RtlGetLongestNtPathLength"
            | "RtlGetNativeSystemInformation" | "RtlGetNextEntryHashTable"
            | "RtlGetNtGlobalFlags" | "RtlGetNtProductType"
            | "RtlGetNtVersionNumbers" | "RtlGetOwnerSecurityDescriptor"
            | "RtlGetProcessHeaps" | "RtlGetSaclSecurityDescriptor"
            | "RtlGetSecurityDescriptorRMControl" | "RtlGetSetBootStatusData"
            | "RtlGetSuiteMask" | "RtlGetThreadErrorMode"
            | "RtlIdentifierAuthoritySid" | "RtlImageDirectoryEntryToData"
            | "RtlImageNtHeader" | "RtlImageRvaToSection"
            | "RtlImageRvaToVa" | "RtlInitAnsiStringEx"
            | "RtlInitializeBitMap" | "RtlInitializeContext"
            | "RtlInitializeGenericTable" | "RtlInitializeGenericTableAvl"
            | "RtlInitializeHandleTable" | "RtlInitializeResource"
            | "RtlInitializeSID" | "RtlInitializeSListHead"
            | "RtlInitStringEx" | "RtlInsertElementGenericTable"
            | "RtlInsertElementGenericTableAvl" | "RtlInsertEntryHashTable"
            | "RtlIntegerToUnicodeString" | "RtlIsCloudFilesPlaceholder"
            | "RtlIsDosDeviceName" | "RtlIsGenericTableEmpty"
            | "RtlIsValidHandle" | "RtlIsValidIndexHandle"
            | "RtlIsValidProcessTrustLabelSid" | "RtlLengthRequiredSid"
            | "RtlLengthSecurityDescriptor" | "RtlLengthSid"
            | "RtlLockMemoryStream" | "RtlLockMemoryZone"
            | "RtlLogStackBackTrace" | "RtlLookupElementGenericTable"
            | "RtlLookupElementGenericTableAvl" | "RtlLookupEntryHashTable"
            | "RtlMakeSelfRelativeSD" | "RtlMapGenericMask"
            | "RtlNewSecurityDescriptor" | "RtlNewSecurityObject"
            | "RtlNewSecurityObjectEx" | "RtlNewSecurityObjectWithMultipleInheritance"
            | "RtlNumberGenericTableElementsAvl" | "RtlNumberOfClearBits"
            | "RtlNumberOfSetBits" | "RtlOemCharToUnicodeChar"
            | "RtlpEnsureBufferSize" | "RtlpNotOwnerCriticalSection"

            | "RtlPropertyNameToGuid" | "RtlProtectHeap"
            | "RtlQueryAtomInAtomTable" | "RtlQueryConfiguration"
            | "RtlQueryEnvironmentVariable_U" | "RtlQueryHeapInformation"
            | "RtlQueryInformationAcl" | "RtlQueryInterfaceMemoryStream"
            | "RtlQueryModuleInformation" | "RtlQueryPackageClaims"
            | "RtlQueryPackageIdentity" | "RtlQueryPerformanceCounter"
            | "RtlQueryPerformanceFrequency" | "RtlQueryProcessBackTraceInformation"
            | "RtlQueryProcessDebugInformation" | "RtlQueryProcessHeapInformation"
            | "RtlQueryProcessLockInformation" | "RtlQueryRegistryValues"
            | "RtlQueryRegistryValueWithFallback" | "RtlQuerySecurityObject"
            | "RtlQueryTagHeap" | "RtlQueryThreadProfiling"
            | "RtlQueryTimerResolution" | "RtlQueryTokenHostProtectedValue"
            | "RtlQueryUnicodeConfigFileValue" | "RtlQueryValidationRunCount"
            | "RtlRealPredecessorLength" | "RtlRealSuccessorLength"
            | "RtlRegisterForChangelogs" | "RtlRegisterWait"
            | "RtlReleaseMemoryZone" | "RtlReleasePath"
            | "RtlReleaseRelativeTimer" | "RtlRemoteCall"
            | "RtlRemoveEntryHashTable" | "RtlReplaceSidInSd"
            | "RtlReplaceSecurityObject" | "RtlReserveChunk"
            | "RtlResetMemory" | "RtlRestoreBootStatusDefaults"
            | "RtlRunDecodeUnicodeString"
            | "RtlRunEncodeUnicodeString" | "RtlSeekMemoryStream"
            | "RtlSelfRelativeToAbsoluteSD" | "RtlSelfRelativeToAbsoluteSD2"
            | "RtlSetAllBits" | "RtlSetAttributesSecurityDescriptor"
            | "RtlSetDaclSecurityDescriptor" | "RtlSetEnvironmentStrings"
            | "RtlSetHeapInformation" | "RtlSetInformationAcl"
            | "RtlSetIoCompletionCallback" | "RtlSetMemoryStreamSize"
            | "RtlSetOwnerSecurityDescriptor" | "RtlSetProcessIsCritical"
            | "RtlSetSaclSecurityDescriptor" | "RtlSetSecurityDescriptorRMControl"
            | "RtlSetSecurityObject" | "RtlSetSecurityObjectEx"
            | "RtlSetThreadErrorMode" | "RtlSetThreadIsCritical"
            | "RtlSetTimer" | "RtlSetTimeZoneInformation"
            | "RtlSetUnicodeCallouts" | "RtlSetUserFlagsHeap"
            | "RtlSetUserValueHeap" | "RtlSizeHeap"
            | "RtlSplay" | "RtlStartThreadProfiling"
            | "RtlStatMemoryStream" | "RtlStringFromGUID"
            // "RtlSubAuthorityCountSid" / "RtlSubAuthoritySid" — handled in ntdll_rtl
            | "RtlSubtreePredecessor" | "RtlSubtreeSuccessor"
            | "RtlSystemTimeToLocalTime" | "RtlTimeFieldsToTime"
            | "RtlTimeToElapsedTimeFields" | "RtlTimeToFields"
            | "RtlUlongByteSwap" | "RtlUlonglongByteSwap"
            | "RtlUpcaseUnicodeStringToOemString" | "RtlUpcaseUnicodeToCustomCPN"
            | "RtlUpdateClonedCriticalSection" | "RtlUpdateTimer"
            | "RtlUsageHeap" | "RtlUshortByteSwap"
            | "RtlValidateProcessHeaps"
            | "RtlValidSecurityDescriptor"
            | "RtlWriteMemoryStream" | "RtlWriteRegistryValue"
            | "RtlxAnsiStringToUnicodeSize" | "RtlxOemStringToUnicodeSize"
            | "RtlxUnicodeStringToAnsiSize" | "RtlxUnicodeStringToOemSize"
            // -- Remaining Ldr/Csr/Dbg/Etw stubs (iteration 3) --
            | "LdrAccessResource" | "LdrAddDllDirectory"
            | "LdrAddLoadAsDataTable" | "LdrAddRefDll"
            | "LdrAppxHandleIntegrityFailure" | "LdrCallEnclave"
            | "LdrControlFlowGuardEnforced" | "LdrCreateEnclave"
            | "LdrDeleteEnclave" | "LdrDisableThreadCalloutsForDll"
            | "LdrEnumResources" | "LdrFastFailInLoaderCallout"
            | "LdrFindResourceDirectory_U" | "LdrFindResourceEx_U"
            | "LdrFindResource_U" | "LdrFlushAlternateResourceModules"
            | "LdrGetDllDirectory" | "LdrGetFailureData"
            | "LdrGetFileNameFromLoadAsDataTable" | "LdrGetKnownDllSectionHandle"
            | "LdrInitializeEnclave" | "LdrInitShimEngineDynamic"
            | "LdrIsModuleSxsRedirected" | "LdrLoadAlternateResourceModule"
            | "LdrLoadAlternateResourceModuleEx" | "LdrLoadEnclaveModule"
            | "LdrOpenImageFileOptionsKey" | "LdrpResGetMappingSize"
            | "LdrpResGetResourceDirectory" | "LdrProcessInitializationComplete"
            | "LdrQueryImageFileExecutionOptions" | "LdrQueryImageFileExecutionOptionsEx"
            | "LdrRemoveDllDirectory" | "LdrRemoveLoadAsDataTable"
            | "LdrResGetResourceDirectory" | "LdrResSearchResource"
            | "LdrSetDefaultDllDirectories" | "LdrSetDllDirectory"
            | "LdrSystemDllInitBlock" | "LdrUnloadAlternateResourceModule"
            // Csr* stubs
            | "CsrAllocateCaptureBuffer" | "CsrAllocateMessagePointer"
            | "CsrCaptureMessageBuffer" | "CsrCaptureMessageMultiUnicodeStringsInPlace"
            | "CsrCaptureMessageString" | "CsrCaptureTimeout"
            | "CsrClientCallServer" | "CsrClientConnectToServer"
            | "CsrFreeCaptureBuffer" | "CsrGetProcessId"
            | "CsrIdentifyAlertableThread" | "CsrSetPriorityClass"
            | "CsrVerifyRegion"
            // Etw* stubs
            | "EtwCheckCoverage" | "EtwCreateTraceInstanceId"
            | "EtwDeliverDataBlock" | "EtwEnumerateProcessRegGuids"
            | "EtwEventActivityIdControl" | "EtwEventEnabled"
            | "EtwEventProviderEnabled" | "EtwEventRegister"
            | "EtwEventSetInformation" | "EtwEventUnregister"
            | "EtwEventWriteFull" | "EtwEventWriteNoRegistration"
            | "EtwEventWriteStartScenario" | "EtwGetTraceEnableFlags"
            | "EtwGetTraceEnableLevel" | "EtwGetTraceLoggerHandle"
            | "EtwLogTraceEvent" | "EtwNotificationRegister"
            | "EtwNotificationUnregister" | "EtwProcessPrivateLoggerRequest"
            | "EtwQueryLastWriteTimeStamp" | "EtwRegisterSecurityProvider"
            | "EtwRegisterTraceGuids" | "EtwReplyNotification"
            | "EtwSendNotification" | "EtwSetTraceTimestamp"
            | "EtwTraceEvent" | "EtwTraceEventInstance"
            | "EtwTraceMessage" | "EtwTraceMessageVa"
            | "EtwUnregisterTraceGuids" | "EtwWriteUMSecurityEvent"
            | "EtwWriteUMSecurityEventWithSA"
            // Remaining misc stubs
            | "ApiSetQueryApiSetPresence" | "ApiSetQueryApiSetPresenceEx"
            | "A_SHAFinal" | "A_SHAInit"
            | "A_SHAUpdate" | "__C_specific_handler"
            | "__chkstk" | "_errno"
            | "NlsMbCodePageTag" | "NlsOemCodePageTag"
            | "PssNtCaptureSnapshot" | "PssNtDuplicateSnapshot"
            | "PssNtFreeSnapshot" | "PssNtQuerySnapshot"
            | "PssNtValidateDescriptor" | "T2Embed4"
            | "TpAllocAlpcCompletion" | "TpAllocAlpcCompletionEx"
            | "TpAllocCleanupGroup" | "TpAllocIoCompletion"
            | "TpAllocJobNotification" | "TpAllocPool"
            | "TpAllocTimer" | "TpAllocWait"
            | "TpAllocWork" | "TpCallbackDetachedUnregisterWin32Thread"
            | "TpCallbackIndependent" | "TpCallbackLeaveCriticalSectionOnFinalRelease"
            | "TpCallbackMayRunLong" | "TpCallbackReleaseAlpcCompletionOnFailure"
            | "TpCallbackReleaseCleanupGroupOnFailure" | "TpCallbackReleaseMutexOnFailure"
            | "TpCallbackReleaseSemaphoreOnFailure" | "TpCallbackSendAlpcMessageOnFailure"
            | "TpCallbackSetEventOnCompletion" | "TpCallbackUnloadDllOnFailure"
            | "TpCancelAsync" | "TpCaptureCaller"
            | "TpCheckTerminateWorker" | "TpDbgDumpPool"
            | "TpDbgDumpPoolStub" | "TpDisablePoolCallbackChecks"
            | "TpPostWork"
            | "TpQueryPoolStackInformation" | "TpReleaseAlpcCompletion"
            | "TpReleaseCleanupGroup" | "TpReleaseCleanupGroupMembers"
            | "TpReleaseIoCompletion" | "TpReleaseJobNotification"
            | "TpReleasePool" | "TpReleaseTimer"
            | "TpReleaseWait" | "TpReleaseWork"
            | "TpSetPoolMaxThreads" | "TpSetPoolMinThreads"
            | "TpSetTimer" | "TpSetTimerEx"
            | "TpSetWait" | "TpSetWaitEx"
            | "TpSimpleTryPost" | "TpStartAsync"
            | "TpWaitForAlpcCompletion" | "TpWaitForIoCompletion"
            | "TpWaitForTimer" | "TpWaitForWait"
            | "TpWaitForWork"
            | "WinSqmAddToAverageDWORD" | "WinSqmAddToStream"
            | "WinSqmCommonDLLStartup" | "WinSqmDisableSession"
            | "WinSqmEnableSession" | "WinSqmEventEnabled"
            | "WinSqmEventWrite" | "WinSqmGetEscalationInfo"
            | "WinSqmGetInstrumentedProperty" | "WinSqmIsOptedIn"
            | "WinSqmIsOptedInEx" | "WinSqmQueryFreshStartData"
            | "WinSqmSetDWORD" | "WinSqmSetDWORD64"
            | "WinSqmSetIfMaxDWORD" | "WinSqmSetIfMinDWORD"
            | "WinSqmSetStream" | "WinSqmStartSession"
            | "WinSqmStartSessionForPartition" | "WinSqmStopSession"
            | "WinSqmTriggerOff" | "WinSqmTriggerOn"
            // CRT math/stdlib stubs
            | "abs" | "atan" | "atan2"
            | "atoi" | "_atoi64" | "atol"
            | "bsearch_s" | "ceil"
            | "cos" | "fabs" | "floor"
            | "isalpha" | "isdigit" | "islower"
            | "isprint" | "isspace" | "isupper"
            | "isxdigit" | "labs" | "log"
            | "log10" | "longjmp"
            | "memcmp"
            | "qsort" | "qsort_s"
            | "sin" | "sprintf" | "sscanf"
            | "sqrt"
            | "strcmp" | "strcspn"
            | "strlen" | "strncmp"
            | "strnlen"
            | "strspn"
            | "strtod" | "strtol" | "strtoul"
            | "swprintf" | "tan" | "tolower"
            | "toupper" | "towlower" | "towupper"
            | "vsprintf" | "vswprintf"
            | "wcscmp" | "wcscspn"
            | "wcslen" | "wcsncmp"
            | "wcsnlen"
            | "wcsspn"
            | "wcstod" | "wcstol" | "wcstoul"
            | "_wcsicmp" | "_wcsnicmp" | "_stricmp"
            | "_strnicmp"
            // Crypto/hash stubs
            | "BCryptCloseAlgorithmProvider" | "BCryptCreateHash"
            | "BCryptDecrypt" | "BCryptDestroyHash"
            | "BCryptDestroyKey" | "BCryptEncrypt"
            | "BCryptFinishHash" | "BCryptGenerateSymmetricKey"
            | "BCryptGenRandom" | "BCryptGetProperty"
            | "BCryptHash" | "BCryptHashData"
            | "BCryptImportKeyPair" | "BCryptOpenAlgorithmProvider"
            | "BCryptSetProperty" | "BCryptSignHash"
            | "BCryptVerifySignature"
            // -- Iteration 4: final remaining stubs --
            // ALPC helpers
            | "AlpcFreeCompletionListMessage" | "AlpcGetCompletionListMessageAttributes"
            | "AlpcGetHeaderSize" | "AlpcGetMessageAttribute"
            | "AlpcGetMessageFromCompletionList" | "AlpcInitializeMessageAttribute"
            | "AlpcMaxAllowedMessageLength" | "AlpcRegisterCompletionList"
            | "AlpcRegisterCompletionListWorkerThread" | "AlpcRundownCompletionList"
            | "AlpcUnregisterCompletionList"
            // Etw remaining
            | "EtwEventWriteTransfer" | "EtwpCreateEtwThread"
            | "EtwpGetCpuSpeed" | "EtwRegisterTraceGuidsA"
            | "EtwRegisterTraceGuidsW" | "EtwSetMark"
            | "EvtIntReportAuthzEventAndSourceAsync" | "EvtIntReportEventAndSourceAsync"
            // Interlocked SList
            | "ExpInterlockedPopEntrySListEnd" | "ExpInterlockedPopEntrySListFault"
            | "ExpInterlockedPopEntrySListResume"
            // Ki* dispatchers
            | "KiRaiseUserExceptionDispatcher" | "KiUserApcDispatcher"
            | "KiUserCallbackDispatcher" | "KiUserInvertedFunctionTable"
            // Ldr remaining
            | "LdrProcessRelocationBlock" | "LdrProcessRelocationBlockEx"
            | "LdrQueryImageFileKeyOption" | "LdrQueryOptionalDelayLoadedAPI"
            | "LdrQueryProcessModuleInformation" | "LdrResFindResource"
            | "LdrResFindResourceDirectory" | "LdrResGetRCConfig"
            | "LdrResolveDelayLoadedAPI" | "LdrResolveDelayLoadsFromDll"
            | "LdrResRelease" | "LdrRscIsTypeExist"
            | "LdrSetAppCompatDllRedirectionCallback" | "LdrSetDllManifestProber"
            | "LdrSetImplicitPathOptions" | "LdrSetMUICacheType"
            | "LdrStandardizeSystemPath" | "LdrUpdatePackageSearchPath"
            | "LdrVerifyImageMatchesChecksumEx"
            // MD4/MD5
            | "MD4Final" | "MD4Init" | "MD4Update"
            | "MD5Final" | "MD5Init" | "MD5Update"
            // NLS
            | "NlsAnsiCodePage" | "NlsMbOemCodePageTag"
            // Pfx prefix tree
            | "PfxFindPrefix" | "PfxInitialize"
            | "PfxInsertPrefix" | "PfxRemovePrefix"
            // Pss process snapshot remaining
            | "PssNtFreeRemoteSnapshot" | "PssNtFreeWalkMarker"
            | "PssNtWalkSnapshot"
            // Rtl remaining (batch 1: A-C)
            | "RtlAbortRXact" | "RtlAbsoluteToSelfRelativeToSD2"
            | "RtlAcquirePrivilege" | "RtlAcquireReleaseSRWLockExclusive"
            | "RtlAcquireResourceExclusive" | "RtlAcquireResourceShared"
            | "RtlAcquireSRWLockExclusive" | "RtlAcquireSRWLockShared"
            | "RtlActivateActivationContext" | "RtlActivateActivationContextEx"
            | "RtlActivateActivationContextUnsafeFast" | "RtlAddAccessFilterAce"
            | "RtlAddActionToRXact" | "RtlAddAtomToAtomTable"
            | "RtlAddAttributeActionToRXact" | "RtlAddFunctionTable"
            | "RtlAddGrowableFunctionTable" | "RtlAddProcessTrustLabelAce"
            | "RtlAddRefActivationContext" | "RtlAddResourceAttributeAce"
            | "RtlAddressInSectionTable" | "RtlAllocateActivationContextStack"
            | "RtlAllocateAndInitializeSid" | "RtlAllocateAndInitializeSidEx"
            | "RtlAllocateHandle" | "RtlAllocateWnfSerializationGroup"
            | "RtlAnsiStringToUnicodeSize" | "RtlAppendPathElement"
            | "RtlAppendStringToString" | "RtlApplicationVerifierStop"
            | "RtlApplyRXact" | "RtlApplyRXactNoFlush"
            | "RtlAppxIsFileOwnedByTrustedInstaller"
            // Rtl remaining (batch 2: B-C)
            | "RtlAreBitsClearEx" | "RtlAreLongPathsEnabled"
            | "RtlAvlInsertNodeEx" | "RtlAvlRemoveNode"
            | "RtlBarrier" | "RtlBarrierForDelete"
            | "RtlCallEnclaveReturn"
            | "RtlCanonicalizeDomainName" | "RtlCapabilityCheck"
            | "RtlCapabilityCheckForSingleSessionSku" | "RtlCaptureContext2"
            | "RtlCheckBootStatusIntegrity" | "RtlCheckForOrphanedCriticalSections"
            | "RtlCheckPortableOperatingSystem" | "RtlCheckRegistryKey"
            | "RtlCheckSandboxedToken" | "RtlCheckSystemBootStatusIntegrity"
            | "RtlCheckTokenCapability" | "RtlCheckTokenMembership"
            | "RtlCheckTokenMembershipEx" | "RtlCleanUpTEBLangLists"
            | "RtlClearAllBits" | "RtlClearAllBitsEx"
            | "RtlClearBit" | "RtlClearBitEx"
            | "RtlClearBits" | "RtlClearBitsEx"
            | "RtlClearThreadWorkOnBehalfTicket" | "RtlCloneMemoryStream"
            | "RtlCloneUserProcess" | "RtlCmDecodeMemIoResource"
            | "RtlCmEncodeMemIoResource" | "RtlCommitDebugInfo"
            | "RtlCommitMemoryStream" | "RtlCompactHeap"
            | "RtlCompareAltitudes" | "RtlCompareMemoryUlong"
            | "RtlCompareString" | "RtlCompareUnicodeStrings"
            | "RtlCompleteProcessCloning" | "RtlComputeImportTableHash"
            | "RtlComputePrivatizedDllName_U" | "RtlConnectToSm"
            | "RtlConstructCrossVmEventPath" | "RtlConstructCrossVmMutexPath"
            | "RtlContractHashTable"
            // Rtl remaining (batch 3: C)
            | "RtlConvertDeviceFamilyInfoToString" | "RtlConvertExclusiveToShared"
            | "RtlConvertLCIDToString" | "RtlConvertSharedToExclusive"
            | "RtlConvertSidToUnicodeString" | "RtlConvertSRWLockExclusiveToShared"
            | "RtlConvertToAutoInheritSecurityObject" | "RtlCopyBitMap"
            | "RtlCopyContext" | "RtlCopyExtendedContext"
            | "RtlCopyLuid" | "RtlCopyLuidAndAttributesArray"
            | "RtlCopyMappedMemory" | "RtlCopyMemoryNonTemporal"
            | "RtlCopyMemoryStreamTo" | "RtlCopyOutOfProcessMemoryStreamTo"
            | "RtlCopySecurityDescriptor" | "RtlCopySid"
            | "RtlCopySidAndAttributesArray" | "RtlCopyString"
            | "RtlCopyUnicodeString" | "RtlCreateActivationContext"
            | "RtlCreateBootStatusDataFile" | "RtlCreateHashTable"
            | "RtlCreateHashTableEx" | "RtlCreateProcessReflection"
            | "RtlCreateUmsCompletionList" | "RtlCreateUmsThreadContext"
            | "RtlCreateUserFiberShadowStack" | "RtlCreateUserProcessEx"
            | "RtlDecryptMemory" | "RtlDestroyAtomTable"
            | "RtlDestroyQueryDebugBuffer" | "RtlEncryptMemory"
            // Rtl remaining (batch 4: F-L)
            | "RtlFreeSid"
            | "RtlGetEnabledExtendedFeatures" | "RtlGetExtendedContextLength"
            | "RtlGetExtendedFeaturesMask" | "RtlGetUserInfoHeap"
            | "RtlGUIDFromString" | "RtlInitCodePageTable"
            | "RtlInitializeSid" | "RtlInitNlsTables"
            | "RtlInitUnicodeStringEx"
            | "RtlIpv4AddressToStringExA"
            | "RtlIpv4StringToAddressA" | "RtlIpv4StringToAddressExA"
            | "RtlIpv6AddressToStringExA"
            | "RtlIpv6StringToAddressA" | "RtlIpv6StringToAddressExA"
            | "RtlLengthAce"

            | "RtlLookupAtomInAtomTable"
            // Rtl remaining (batch 5: O-W)
            | "RtlOpenCurrentUser" | "RtlPinAtomInAtomTable"
            | "RtlPublishWnfStateData" | "RtlQueryWnfStateData"
            | "RtlReleasePrivilege" | "RtlSetEnvironmentVariable_U"
            | "RtlSetExtendedFeaturesMask" | "RtlSleepConditionVariableCS"
            | "RtlSleepConditionVariableSRW" | "RtlSubscribeWnfStateChangeNotification"
            | "RtlUpperUnicodeString"
            | "RtlWakeAllConditionVariable"
            | "RtlWakeConditionVariable"
            // CRT remaining
            | "isalnum" | "iscntrl" | "isgraph"
            | "ispunct"

            | "wcstombs"
            | "wmemcmp"

            // Tp remaining
            | "TpDisassociateCallback" | "TpPostIoCompletion"
            // Recovered entries accidentally removed during dedup
            | "DbgBreakPoint" | "DbgUiRemoteBreakin"
            | "EtwEventWriteEndScenario" | "LdrQueryModuleServiceTags"
            | "LdrUnloadAlternateResourceModuleEx" | "LdrVerifyImageMatchesChecksum"
            | "RtlAddScopedPolicyIDAce" | "RtlCreateBoundaryDescriptor"
            | "RtlCreateMemoryBlockLookaside" | "RtlCreateMemoryZone"
            | "RtlCreateTimerQueue"
            | "RtlQueryDepthSList" | "RtlQueueWorkItem"
            | "RtlRandom" | "RtlSetGroupSecurityDescriptor"
            | "RtlUpcaseUnicodeChar"
            | "RtlVerifyVersionInfo" | "RtlWalkHeap"
            => Some(Ok(STATUS_SUCCESS as u64)),
            _ => None,
        }
    }
}
