/// Returns representative exported names used by registry-integration tests.
pub fn representative_hook_exports() -> &'static [(&'static str, &'static str)] {
    &[
        ("advapi32.dll", "RegOpenKeyExW"),
        ("apphelp.dll", "ApphelpCheckShellObject"),
        (
            "api-ms-win-appmodel-runtime-l1-1-2.dll",
            "AppPolicyGetProcessTerminationMethod",
        ),
        ("bcrypt.dll", "BCryptOpenAlgorithmProvider"),
        ("cabinet.dll", "CreateCompressor"),
        ("cfgmgr32.dll", "CM_Locate_DevNodeA"),
        ("combase.dll", "CoInitializeEx"),
        ("comctl32.dll", "InitCommonControlsEx"),
        ("comdlg32.dll", "CommDlgExtendedError"),
        ("crypt32.dll", "CertOpenStore"),
        ("cryptnet.dll", "CryptRetrieveObjectByUrlA"),
        ("cryptui.dll", "CryptUIDlgViewContext"),
        ("dbgcore.dll", "MiniDumpWriteDump"),
        ("dbghelp.dll", "SymInitialize"),
        ("dnsapi.dll", "DnsQuery_A"),
        ("fwpuclnt.dll", "FwpmEngineOpen0"),
        ("gdi32.dll", "BitBlt"),
        ("gdiplus.dll", "GdiplusStartup"),
        ("imm32.dll", "ImmGetContext"),
        ("iphlpapi.dll", "GetBestInterface"),
        ("mpr.dll", "WNetAddConnection2A"),
        ("msi.dll", "DllCanUnloadNow"),
        ("msimg32.dll", "AlphaBlend"),
        ("ncrypt.dll", "NCryptOpenStorageProvider"),
        ("netapi32.dll", "Netbios"),
        ("netutils.dll", "NetApiBufferFree"),
        ("ole32.dll", "CoCreateGuid"),
        ("oleacc.dll", "AccessibleObjectFromWindow"),
        ("oleaut32.dll", "SysAllocString"),
        ("oledlg.dll", "OleUIBusyW"),
        ("psapi.dll", "EnumProcesses"),
        ("rasapi32.dll", "RasDialA"),
        ("rpcrt4.dll", "UuidCreate"),
        ("secur32.dll", "AcquireCredentialsHandleA"),
        ("setupapi.dll", "SetupDiGetClassDevsA"),
        ("shlwapi.dll", "PathFileExistsW"),
        ("taskschd.dll", "DllCanUnloadNow"),
        ("urlmon.dll", "URLDownloadToFileA"),
        ("uxtheme.dll", "IsAppThemed"),
        ("user32.dll", "MessageBoxA"),
        ("version.dll", "GetFileVersionInfoSizeA"),
        ("wevtapi.dll", "EvtOpenSession"),
        ("wer.dll", "WerReportCreate"),
        ("winhttp.dll", "WinHttpOpen"),
        ("wininet.dll", "InternetOpenA"),
        ("winmm.dll", "timeGetTime"),
        ("winspool.drv", "OpenPrinterA"),
        ("winspool.dll", "OpenPrinterA"),
        ("wintrust.dll", "WinVerifyTrust"),
        ("wlanapi.dll", "WlanOpenHandle"),
        ("wldap32.dll", "ldap_openA"),
        ("ws2_32.dll", "WSAStartup"),
        ("wtsapi32.dll", "WTSOpenServerA"),
    ]
}
