//! Full `HookSignature` table for `msi.dll` functions.
//!
//! Covers the Windows Installer API: package management, database access,
//! product/component enumeration, and summary information queries.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static MSI_SIGNATURES: &[HookSignature] = &[
    // ── DLL lifecycle (COM self-registration) ───────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "DllCanUnloadNow",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "DllGetClassObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rclsid", GuidPtr),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::with_dir("ppv", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Handle management ───────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiCloseHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hAny", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiCloseAllHandles",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Package open ────────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiOpenPackageA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szPackagePath", PCStr),
            ParamSpec::with_dir("hProduct", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiOpenPackageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szPackagePath", PCWStr),
            ParamSpec::with_dir("hProduct", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiOpenPackageExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szPackagePath", PCStr),
            ParamSpec::new("dwOptions", U32),
            ParamSpec::with_dir("hProduct", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiOpenPackageExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szPackagePath", PCWStr),
            ParamSpec::new("dwOptions", U32),
            ParamSpec::with_dir("hProduct", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Database open ───────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiOpenDatabaseA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szDatabasePath", PCStr),
            ParamSpec::new("szPersist", PCStr),
            ParamSpec::with_dir("hDatabase", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiOpenDatabaseW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szDatabasePath", PCWStr),
            ParamSpec::new("szPersist", PCWStr),
            ParamSpec::with_dir("hDatabase", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Property access ─────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetPropertyA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("szName", PCStr),
            ParamSpec::with_dir("szValueBuf", OutBuffer { len_param: 3 }, Out),
            ParamSpec::with_dir("pcchValueBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetPropertyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("szName", PCWStr),
            ParamSpec::with_dir("szValueBuf", OutBuffer { len_param: 3 }, Out),
            ParamSpec::with_dir("pcchValueBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiSetPropertyA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("szName", PCStr),
            ParamSpec::new("szValue", PCStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiSetPropertyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("szName", PCWStr),
            ParamSpec::new("szValue", PCWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Execution ───────────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetMode",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("iRunMode", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiDoActionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("szAction", PCStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiDoActionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("szAction", PCWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiProcessMessage",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInstall", Handle),
            ParamSpec::new("eMessageType", U32),
            ParamSpec::new("hRecord", Handle),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Product state query ─────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiQueryProductStateA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("szProduct", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiQueryProductStateW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("szProduct", PCWStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Product enumeration ─────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiEnumProductsA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("iProductIndex", U32),
            ParamSpec::with_dir("lpProductBuf", OutBuffer { len_param: 1 }, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiEnumProductsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("iProductIndex", U32),
            ParamSpec::with_dir("lpProductBuf", OutBuffer { len_param: 1 }, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiEnumProductsExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProductCode", PCStr),
            ParamSpec::new("szUserSid", PCStr),
            ParamSpec::new("dwContext", U32),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::with_dir("szInstalledProductCode", OutBuffer { len_param: 5 }, Out),
            ParamSpec::with_dir("pcchInstalledProductCode", GuestPtr, InOut),
            ParamSpec::with_dir("pdwInstalledContext", GuestPtr, Out),
            ParamSpec::with_dir("szSid", OutBuffer { len_param: 7 }, Out),
            // NOTE: param 7 is pcchSid (InOut) — not a separate OutBuffer length param
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiEnumProductsExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProductCode", PCWStr),
            ParamSpec::new("szUserSid", PCWStr),
            ParamSpec::new("dwContext", U32),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::with_dir("szInstalledProductCode", OutBuffer { len_param: 5 }, Out),
            ParamSpec::with_dir("pcchInstalledProductCode", GuestPtr, InOut),
            ParamSpec::with_dir("pdwInstalledContext", GuestPtr, Out),
            ParamSpec::with_dir("szSid", OutBuffer { len_param: 7 }, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Product info ────────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetProductInfoA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProduct", PCStr),
            ParamSpec::new("szAttribute", PCStr),
            ParamSpec::with_dir("szValueBuf", OutBuffer { len_param: 3 }, Out),
            ParamSpec::with_dir("pcchValueBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetProductInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProduct", PCWStr),
            ParamSpec::new("szAttribute", PCWStr),
            ParamSpec::with_dir("szValueBuf", OutBuffer { len_param: 3 }, Out),
            ParamSpec::with_dir("pcchValueBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetProductInfoExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProductCode", PCStr),
            ParamSpec::new("szUserSid", PCStr),
            ParamSpec::new("dwContext", U32),
            ParamSpec::new("szProperty", PCStr),
            ParamSpec::with_dir("szValue", OutBuffer { len_param: 5 }, Out),
            ParamSpec::with_dir("pcchValue", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetProductInfoExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProductCode", PCWStr),
            ParamSpec::new("szUserSid", PCWStr),
            ParamSpec::new("dwContext", U32),
            ParamSpec::new("szProperty", PCWStr),
            ParamSpec::with_dir("szValue", OutBuffer { len_param: 5 }, Out),
            ParamSpec::with_dir("pcchValue", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── File version ────────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetFileVersionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szFilePath", PCStr),
            ParamSpec::with_dir("szVersionBuf", OutBuffer { len_param: 2 }, Out),
            ParamSpec::with_dir("pcchVersionBuf", GuestPtr, InOut),
            ParamSpec::with_dir("szLangBuf", OutBuffer { len_param: 4 }, Out),
            ParamSpec::with_dir("pcchLangBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetFileVersionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szFilePath", PCWStr),
            ParamSpec::with_dir("szVersionBuf", OutBuffer { len_param: 2 }, Out),
            ParamSpec::with_dir("pcchVersionBuf", GuestPtr, InOut),
            ParamSpec::with_dir("szLangBuf", OutBuffer { len_param: 4 }, Out),
            ParamSpec::with_dir("pcchLangBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Component path ──────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetComponentPathA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProduct", PCStr),
            ParamSpec::new("szComponent", PCStr),
            ParamSpec::with_dir("szPathBuf", OutBuffer { len_param: 3 }, Out),
            ParamSpec::with_dir("pcchBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetComponentPathW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szProduct", PCWStr),
            ParamSpec::new("szComponent", PCWStr),
            ParamSpec::with_dir("szPathBuf", OutBuffer { len_param: 3 }, Out),
            ParamSpec::with_dir("pcchBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Locate component ────────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiLocateComponentA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szComponent", PCStr),
            ParamSpec::with_dir("szPathBuf", OutBuffer { len_param: 2 }, Out),
            ParamSpec::with_dir("pcchBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiLocateComponentW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szComponent", PCWStr),
            ParamSpec::with_dir("szPathBuf", OutBuffer { len_param: 2 }, Out),
            ParamSpec::with_dir("pcchBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Product code from component ─────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetProductCodeA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szComponent", PCStr),
            ParamSpec::with_dir("szProductBuf", OutBuffer { len_param: 1 }, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetProductCodeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("szComponent", PCWStr),
            ParamSpec::with_dir("szProductBuf", OutBuffer { len_param: 1 }, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Summary information ─────────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiGetSummaryInformationA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDatabase", Handle),
            ParamSpec::new("szDatabasePath", PCStr),
            ParamSpec::new("uiUpdateCount", U32),
            ParamSpec::with_dir("phSummaryInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiGetSummaryInformationW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDatabase", Handle),
            ParamSpec::new("szDatabasePath", PCWStr),
            ParamSpec::new("uiUpdateCount", U32),
            ParamSpec::with_dir("phSummaryInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Summary info property ───────────────────────────────────────────────
    HookSignature {
        module: "msi.dll",
        function: "MsiSummaryInfoGetPropertyA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSummaryInfo", Handle),
            ParamSpec::new("uiProperty", U32),
            ParamSpec::with_dir("puiDataType", GuestPtr, Out),
            ParamSpec::with_dir("iValue", GuestPtr, Out),
            ParamSpec::with_dir("ftValue", FileTimePtr, Out),
            ParamSpec::with_dir("szValueBuf", OutBuffer { len_param: 6 }, Out),
            ParamSpec::with_dir("pcchValueBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "msi.dll",
        function: "MsiSummaryInfoGetPropertyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSummaryInfo", Handle),
            ParamSpec::new("uiProperty", U32),
            ParamSpec::with_dir("puiDataType", GuestPtr, Out),
            ParamSpec::with_dir("iValue", GuestPtr, Out),
            ParamSpec::with_dir("ftValue", FileTimePtr, Out),
            ParamSpec::with_dir("szValueBuf", OutBuffer { len_param: 6 }, Out),
            ParamSpec::with_dir("pcchValueBuf", GuestPtr, InOut),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
];
