//! Full `HookSignature` table for `cabinet.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static CABINET_SIGNATURES: &[HookSignature] = &[
    // ── Compressor API ──────────────────────────────────────────────────
    HookSignature {
        module: "cabinet.dll",
        function: "CreateCompressor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Algorithm", U32),
            ParamSpec::new("pMemoryRestriction", GuestPtr),
            ParamSpec::with_dir("CompressorHandle", Handle, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "SetCompressorInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompressorHandle", Handle),
            ParamSpec::new("CompressInformationClass", U32),
            ParamSpec::new("CompressInformation", GuestPtr),
            ParamSpec::new("CompressInformationSize", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "QueryCompressorInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompressorHandle", Handle),
            ParamSpec::new("CompressInformationClass", U32),
            ParamSpec::with_dir("CompressInformation", OutBuffer { len_param: 3 }, Out),
            ParamSpec::new("CompressInformationSize", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "Compress",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompressorHandle", Handle),
            ParamSpec::new("UncompressedData", Buffer { len_param: 2 }),
            ParamSpec::new("UncompressedDataSize", SizeT),
            ParamSpec::with_dir("CompressedBuffer", OutBuffer { len_param: 4 }, Out),
            ParamSpec::new("CompressedBufferSize", SizeT),
            ParamSpec::with_dir("CompressedDataSize", SizeT, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "ResetCompressor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CompressorHandle", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "CloseCompressor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CompressorHandle", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Decompressor API ────────────────────────────────────────────────
    HookSignature {
        module: "cabinet.dll",
        function: "CreateDecompressor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Algorithm", U32),
            ParamSpec::new("pMemoryRestriction", GuestPtr),
            ParamSpec::with_dir("DecompressorHandle", Handle, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "SetDecompressorInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DecompressorHandle", Handle),
            ParamSpec::new("DecompressInformationClass", U32),
            ParamSpec::new("DecompressInformation", GuestPtr),
            ParamSpec::new("DecompressInformationSize", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "QueryDecompressorInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DecompressorHandle", Handle),
            ParamSpec::new("DecompressInformationClass", U32),
            ParamSpec::with_dir("DecompressInformation", OutBuffer { len_param: 3 }, Out),
            ParamSpec::new("DecompressInformationSize", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "Decompress",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DecompressorHandle", Handle),
            ParamSpec::new("CompressedData", Buffer { len_param: 2 }),
            ParamSpec::new("CompressedDataSize", SizeT),
            ParamSpec::with_dir("UncompressedBuffer", OutBuffer { len_param: 4 }, Out),
            ParamSpec::new("UncompressedBufferSize", SizeT),
            ParamSpec::with_dir("UncompressedDataSize", SizeT, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "ResetDecompressor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("DecompressorHandle", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "CloseDecompressor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("DecompressorHandle", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── FDI (File Decompression Interface) ──────────────────────────────
    HookSignature {
        module: "cabinet.dll",
        function: "FDICreate",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pfnalloc", FunctionPtr),
            ParamSpec::new("pfnfree", FunctionPtr),
            ParamSpec::new("pfnopen", FunctionPtr),
            ParamSpec::new("pfnread", FunctionPtr),
            ParamSpec::new("pfnwrite", FunctionPtr),
            ParamSpec::new("pfnclose", FunctionPtr),
            ParamSpec::new("pfnseek", FunctionPtr),
            ParamSpec::new("cpuType", I32),
            ParamSpec::new("perType", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FDIIsCabinet",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hfdi", GuestPtr),
            ParamSpec::new("hf", I32),
            ParamSpec::with_dir("pfdici", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FDICopy",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hfdi", GuestPtr),
            ParamSpec::new("pszCabinet", PCStr),
            ParamSpec::new("pszCabPath", PCStr),
            ParamSpec::new("flags", U32),
            ParamSpec::new("pfnfdin", FunctionPtr),
            ParamSpec::new("pfnfdid", FunctionPtr),
            ParamSpec::new("pvUser", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FDIDestroy",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hfdi", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── FCI (File Compression Interface) ────────────────────────────────
    HookSignature {
        module: "cabinet.dll",
        function: "FCICreate",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("perf", GuestPtr),
            ParamSpec::new("pfnfiledest", FunctionPtr),
            ParamSpec::new("pfnalloc", FunctionPtr),
            ParamSpec::new("pfnfree", FunctionPtr),
            ParamSpec::new("pfnopen", FunctionPtr),
            ParamSpec::new("pfnread", FunctionPtr),
            ParamSpec::new("pfnwrite", FunctionPtr),
            ParamSpec::new("pfnclose", FunctionPtr),
            ParamSpec::new("pfnseek", FunctionPtr),
            ParamSpec::new("pfndelete", FunctionPtr),
            ParamSpec::new("pfnfcigfci", FunctionPtr),
            ParamSpec::new("pfnfcigtemp", FunctionPtr),
            ParamSpec::new("pv", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FCIAddFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hfci", GuestPtr),
            ParamSpec::new("pszSourceFile", PCStr),
            ParamSpec::new("pszFileName", PCStr),
            ParamSpec::new("fExecute", Bool32),
            ParamSpec::new("pfnfcignc", FunctionPtr),
            ParamSpec::new("pfnfcis", FunctionPtr),
            ParamSpec::new("pfncb", FunctionPtr),
            ParamSpec::new("pv", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FCIFlushCabinet",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hfci", GuestPtr),
            ParamSpec::new("fGetNextCab", Bool32),
            ParamSpec::new("pfnfcignc", FunctionPtr),
            ParamSpec::new("pfnfcis", FunctionPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FCIFlushFolder",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hfci", GuestPtr),
            ParamSpec::new("pfnfcignc", FunctionPtr),
            ParamSpec::new("pfnfcis", FunctionPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "cabinet.dll",
        function: "FCIDestroy",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hfci", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
