use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::GuestPtr};

pub(super) static ORDINALS_5_SIGS: &[HookSignature] = &[
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4899",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4901",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4945",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4946",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4947",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4952",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4964",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4974",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4981",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4983",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4984",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4987",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4988",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_4989",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5001",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5007",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5008",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5009",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5016",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5018",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5021",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5034",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5055",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5058",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5064",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5065",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5068",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5077",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5084",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5090",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5091",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5100",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5149",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5215",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5216",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5229",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5232",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5244",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5245",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5249",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5252",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5253",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5282",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5288",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5293",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5297",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5306",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5312",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5317",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5324",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5331",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5336",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5341",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5354",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5362",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5363",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5364",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5366",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5367",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5368",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5369",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5370",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5386",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5397",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5400",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5406",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5408",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5410",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5411",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5420",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5425",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5430",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5431",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5432",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5433",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5436",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5441",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5453",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5467",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5484",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5495",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5496",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5506",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5509",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5511",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5513",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5519",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5521",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5524",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5527",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5529",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5567",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5575",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5582",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5586",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5602",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5614",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5615",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5622",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5630",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5636",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5637",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5654",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5656",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5659",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5662",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5663",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5670",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5672",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5674",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5680",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5682",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5683",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5687",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5690",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5694",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5699",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5700",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
];
