use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::GuestPtr};

pub(super) static ORDINALS_6_SIGS: &[HookSignature] = &[
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5701",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5702",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5704",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5711",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5712",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5714",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5722",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5723",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5724",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5730",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5804",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5807",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5815",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5821",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5838",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5839",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5870",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5871",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5878",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5880",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5886",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5887",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5894",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5896",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5956",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5980",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5986",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5987",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_5989",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6015",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6021",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6050",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6053",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6071",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6076",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6078",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6092",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6096",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6099",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6102",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6114",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6123",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6130",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6131",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6133",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6136",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6138",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6174",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6216",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6221",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6228",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6229",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6235",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6238",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6243",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6299",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6328",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6331",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6351",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6374",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6379",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6398",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6407",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6415",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6416",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6437",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6440",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6448",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6455",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6456",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6464",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6474",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6510",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6511",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6517",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6518",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6520",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6524",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6525",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6538",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6541",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6556",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6577",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6586",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6593",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6599",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6603",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6607",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6609",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6610",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6612",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6614",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6632",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6634",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6661",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6704",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6705",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6739",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6760",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6767",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6769",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6772",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6773",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6780",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6801",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6806",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6812",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6813",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6814",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6815",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6821",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6823",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6832",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6834",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6840",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6841",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6851",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6880",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6886",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6887",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_6888",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "__vm_mfc42u_ordinal_3997_callback",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
            ParamSpec::new("p3", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "__vm_mfc42u_object_method_40",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "__vm_mfc42u_object_method_80",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
            ParamSpec::new("p3", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "__vm_mfc42u_object_method_a8",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("p1", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
];
