use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::GuestPtr};

pub(super) static ORDINALS_1_SIGS: &[HookSignature] = &[
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_270",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_286",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_287",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_292",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_310",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_311",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_312",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_318",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_321",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_328",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_331",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_336",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_337",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_338",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_354",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_367",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_371",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_376",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_387",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_408",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_433",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_451",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_464",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_465",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_488",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_491",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_494",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_495",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_504",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_505",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_506",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_507",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_508",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_509",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_524",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_525",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_528",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_540",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_542",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_544",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_598",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_613",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_620",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_622",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_624",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_625",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_626",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_650",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_659",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_660",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_665",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_799",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_815",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_822",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_826",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_827",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_832",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_834",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_837",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_851",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_852",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_865",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_877",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_890",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_904",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_911",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_927",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_946",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_955",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_966",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_969",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_971",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_972",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_977",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_978",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_979",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_981",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_984",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_992",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_994",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_995",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1027",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1029",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1033",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1035",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1036",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1040",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1055",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1061",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1063",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1067",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1073",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1082",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1122",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1126",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1264",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1284",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1286",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1287",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1297",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1316",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1344",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1361",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1375",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1387",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1388",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1404",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1410",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1422",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1425",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1428",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1436",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1441",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1442",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1443",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1447",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1448",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_1463",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
];
