use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::GuestPtr};

pub(super) static ORDINALS_3_SIGS: &[HookSignature] = &[
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2596",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2613",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2629",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2644",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2647",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2657",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2661",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2665",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2670",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2671",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2676",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2750",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2752",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2754",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2756",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2757",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2764",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2767",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2775",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2781",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2783",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2801",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2802",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2812",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2827",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2829",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2845",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2846",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2856",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2876",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2895",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2900",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2906",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2909",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2919",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2920",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2925",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2939",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2975",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2977",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_2979",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3007",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3030",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3038",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3046",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3049",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3052",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3059",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3068",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3099",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3114",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3141",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3142",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3147",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3159",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3164",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3166",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3174",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3177",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3180",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3191",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3222",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3231",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3234",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3243",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3258",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3262",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3266",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3270",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3280",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3282",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3306",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3361",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3362",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3365",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3366",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3373",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3386",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3387",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3414",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3416",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3440",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3468",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3481",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3484",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3491",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3516",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3535",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3536",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3540",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3556",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3586",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3593",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3595",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3597",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3601",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3604",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3638",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3639",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3647",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3662",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3675",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3680",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3681",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3732",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3742",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3743",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3748",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3751",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3753",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3760",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3761",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3778",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3780",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3783",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3790",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3805",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mfc42u.dll",
        function: "ordinal_3830",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
];
