use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static CRT_ZW_SIGS: &[HookSignature] = &[
    // ── CRT wide/integer conversion ──────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "_ui64toa",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", U64),
            ParamSpec::new("str", PStr),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_ui64tow",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", U64),
            ParamSpec::new("str", PWStr),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ultoa",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", U32),
            ParamSpec::new("str", PStr),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_ultow",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", U32),
            ParamSpec::new("str", PWStr),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_vsnprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PStr),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("argptr", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_vsnwprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("format", PCWStr),
            ParamSpec::new("argptr", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "vsprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PStr),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("argptr", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcscat",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PWStr), ParamSpec::new("src", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcschr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr), ParamSpec::new("c", U32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcscmp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCWStr), ParamSpec::new("s2", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcscpy",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PWStr), ParamSpec::new("src", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcscspn",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCWStr), ParamSpec::new("s2", PCWStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wcsdup",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wcserror",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("errnum", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wcsicmp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCWStr), ParamSpec::new("s2", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcslen",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s", PCWStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsncat",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PWStr),
            ParamSpec::new("src", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsncmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("s1", PCWStr),
            ParamSpec::new("s2", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsncpy",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PWStr),
            ParamSpec::new("src", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wcsnicmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("s1", PCWStr),
            ParamSpec::new("s2", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsnlen",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s", PCWStr), ParamSpec::new("maxlen", SizeT)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcspbrk",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCWStr), ParamSpec::new("s2", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsrchr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr), ParamSpec::new("c", U32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsspn",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCWStr), ParamSpec::new("s2", PCWStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcsstr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCWStr), ParamSpec::new("s2", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcstol",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCWStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("base", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcstombs",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("mbstr", PStr),
            ParamSpec::new("wcstr", PCWStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wcstoul",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCWStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("base", I32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wmemchr",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ptr", GuestPtr),
            ParamSpec::new("c", U32),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wmemcmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("s1", GuestPtr),
            ParamSpec::new("s2", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wmemcpy",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wmemmove",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "wmemset",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("c", U32),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wtoi",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wtoi64",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::I64,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_wtol",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Zw* syscall wrappers ─────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "ZwAdjustPrivilegesToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("DisableAllPrivileges", Bool32),
            ParamSpec::new("NewState", GuestPtr),
            ParamSpec::new("BufferLength", U32),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwAlertThreadByThreadId",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ThreadId", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwAllocateLocallyUniqueId",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("Luid", GuestPtr, Out)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCancelTimer2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("Parameters", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Zw* mirrors of Nt* functions ────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "ZwClose",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwContinue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Context", OpaqueStructPtr("CONTEXT")),
            ParamSpec::new("TestAlert", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("EventHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("EventType", I32),
            ParamSpec::new("InitialState", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("FileHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("AllocationSize", GuestPtr),
            ParamSpec::new("FileAttributes", U32),
            ParamSpec::new("ShareAccess", U32),
            ParamSpec::new("CreateDisposition", U32),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::new("EaBuffer", GuestPtr),
            ParamSpec::new("EaLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("TitleIndex", U32),
            ParamSpec::new("Class", UnicodeStringStruct),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::with_dir("Disposition", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateMutant",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MutantHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("InitialOwner", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ParentProcess", Handle),
            ParamSpec::new("InheritObjectTable", Bool32),
            ParamSpec::new("SectionHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateProcessEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ParentProcess", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("DebugPort", Handle),
            ParamSpec::new("ExceptionPort", Handle),
            ParamSpec::new("Reserved", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SectionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("MaximumSize", GuestPtr),
            ParamSpec::new("SectionPageProtection", Hex32),
            ParamSpec::new("AllocationAttributes", Hex32),
            ParamSpec::new("FileHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateUserProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("ProcessDesiredAccess", Hex32),
            ParamSpec::new("ThreadDesiredAccess", Hex32),
            ParamSpec::new("ProcessObjectAttributes", GuestPtr),
            ParamSpec::new("ThreadObjectAttributes", GuestPtr),
            ParamSpec::new("ProcessFlags", U32),
            ParamSpec::new("ThreadFlags", U32),
            ParamSpec::new("ProcessParameters", GuestPtr),
            ParamSpec::new("CreateInfo", GuestPtr),
            ParamSpec::new("AttributeList", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDebugActiveProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DebugObjectHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDelayExecution",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("DelayInterval", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDeleteFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ObjectAttributes", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDeleteKey",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("KeyHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDeleteValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueName", UnicodeStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDeviceIoControlFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", FunctionPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("IoControlCode", Hex32),
            ParamSpec::new("InputBuffer", GuestPtr),
            ParamSpec::new("InputBufferLength", U32),
            ParamSpec::new("OutputBuffer", GuestPtr),
            ParamSpec::new("OutputBufferLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDuplicateObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SourceProcessHandle", Handle),
            ParamSpec::new("SourceHandle", Handle),
            ParamSpec::new("TargetProcessHandle", Handle),
            ParamSpec::with_dir("TargetHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("HandleAttributes", Hex32),
            ParamSpec::new("Options", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwDuplicateToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ExistingTokenHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("EffectiveOnly", Bool32),
            ParamSpec::new("TokenType", I32),
            ParamSpec::with_dir("NewTokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwEnumerateKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("Index", U32),
            ParamSpec::new("KeyInformationClass", I32),
            ParamSpec::new("KeyInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwEnumerateValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("Index", U32),
            ParamSpec::new("KeyValueInformationClass", I32),
            ParamSpec::new("KeyValueInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwFsControlFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("FsControlCode", U32),
            ParamSpec::new("InputBuffer", GuestPtr),
            ParamSpec::new("InputBufferLength", U32),
            ParamSpec::new("OutputBuffer", GuestPtr),
            ParamSpec::new("OutputBufferLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwGetContextThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("Context", OpaqueStructPtr("CONTEXT"), InOut),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwMapViewOfSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::new("ZeroBits", PointerSizedUInt),
            ParamSpec::new("CommitSize", SizeT),
            ParamSpec::new("SectionOffset", GuestPtr),
            ParamSpec::with_dir("ViewSize", GuestPtr, InOut),
            ParamSpec::new("InheritDisposition", U32),
            ParamSpec::new("AllocationType", Hex32),
            ParamSpec::new("Win32Protect", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("FileHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("ShareAccess", U32),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenKeyEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenProcessToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::with_dir("TokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SectionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ClientId", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenThreadToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("OpenAsSelf", Bool32),
            ParamSpec::with_dir("TokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryDirectoryFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("FileInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FileInformationClass", U32),
            ParamSpec::new("ReturnSingleEntry", Bool32),
            ParamSpec::new("FileName", UnicodeStringStruct),
            ParamSpec::new("RestartScan", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryInformationFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("FileInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FileInformationClass", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryInformationThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ThreadInformationClass", U32),
            ParamSpec::with_dir("ThreadInformation", GuestPtr, Out),
            ParamSpec::new("ThreadInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryInformationToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("TokenInformationClass", U32),
            ParamSpec::with_dir("TokenInformation", GuestPtr, Out),
            ParamSpec::new("TokenInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryLicenseValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Name", UnicodeStringStruct),
            ParamSpec::new("Type", GuestPtr),
            ParamSpec::with_dir("Data", GuestPtr, Out),
            ParamSpec::new("DataSize", U32),
            ParamSpec::with_dir("ResultDataSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Handle", Handle),
            ParamSpec::new("ObjectInformationClass", U32),
            ParamSpec::with_dir("ObjectInformation", GuestPtr, Out),
            ParamSpec::new("ObjectInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryPerformanceCounter",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PerformanceCounter", GuestPtr, Out),
            ParamSpec::with_dir("PerformanceFrequency", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueName", UnicodeStringStruct),
            ParamSpec::new("KeyValueInformationClass", U32),
            ParamSpec::with_dir("KeyValueInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueueApcThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ApcRoutine", FunctionPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("ApcStatusBlock", GuestPtr),
            ParamSpec::new("ApcRoutineAddress", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwReadFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("ByteOffset", GuestPtr),
            ParamSpec::new("Key", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Zw* mirrors (final batch) ─────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "ZwReadVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::new("NumberOfBytesToRead", SizeT),
            ParamSpec::with_dir("NumberOfBytesRead", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwReleaseMutant",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("MutantHandle", Handle),
            ParamSpec::with_dir("PreviousCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwRemoveProcessDebug",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DebugObjectHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwResumeThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("PreviousSuspendCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetContextThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("Context", OpaqueStructPtr("CONTEXT")),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EventHandle", Handle),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetInformationFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("FileInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FileInformationClass", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetInformationKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("KeySetInformationClass", U32),
            ParamSpec::new("KeySetInformation", GuestPtr),
            ParamSpec::new("KeySetInformationLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetInformationThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ThreadInformationClass", U32),
            ParamSpec::new("ThreadInformation", GuestPtr),
            ParamSpec::new("ThreadInformationLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetTimer2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("DueTime", GuestPtr),
            ParamSpec::new("ExpirationTime", GuestPtr),
            ParamSpec::new("Parameters", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetTimerEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("TimerSetInformationClass", U32),
            ParamSpec::new("TimerSetInformation", GuestPtr),
            ParamSpec::new("TimerSetInformationLength", U32),
            ParamSpec::new("ReturnLength", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSetValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueName", GuestPtr),
            ParamSpec::new("TitleIndex", U32),
            ParamSpec::new("Type", U32),
            ParamSpec::new("Data", GuestPtr),
            ParamSpec::new("DataSize", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwSuspendThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("PreviousSuspendCount", GuestPtr, Out),
            ParamSpec::with_dir("PreviousCount2", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwTerminateProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("ExitStatus", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwTerminateThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ExitStatus", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwUnmapViewOfSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwWaitForAlertByThreadId",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwWaitForMultipleObjects",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Count", U32),
            ParamSpec::new("Handles", GuestPtr),
            ParamSpec::new("WaitType", U32),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwWaitForSingleObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Handle", Handle),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::new("Timeout2", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwWriteFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("ByteOffset", GuestPtr),
            ParamSpec::new("Key", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwWriteVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("NumberOfBytesToWrite", SizeT),
            ParamSpec::with_dir("NumberOfBytesWritten", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
];
