use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static CRT_LDR_SIGS: &[HookSignature] = &[
    // ── Batch AA: CRT utility + Ldr + misc ────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "abs",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("n", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "atoi",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_atoi64",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "atol",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "bsearch",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("key", GuestPtr),
            ParamSpec::new("base", GuestPtr),
            ParamSpec::new("nmemb", SizeT),
            ParamSpec::new("size", SizeT),
            ParamSpec::new("compar", FunctionPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "DbgPrint",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("Format", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "DbgPrintEx",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ComponentId", U32),
            ParamSpec::new("Level", U32),
            ParamSpec::new("Format", PCStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "DbgUiSetThreadDebugObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("DebugObjectHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "EtwEventWrite",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RegHandle", U64),
            ParamSpec::new("EventDescriptor", GuestPtr),
            ParamSpec::new("UserDataCount", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_i64toa",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I64),
            ParamSpec::with_dir("str", PStr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_i64tow",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I64),
            ParamSpec::with_dir("str", PWStr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isalnum",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isalpha",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "__isascii",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "iscntrl",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isdigit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isgraph",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "islower",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isprint",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ispunct",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isspace",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isupper",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "isxdigit",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "itoa",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I32),
            ParamSpec::with_dir("str", PStr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_itow",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I32),
            ParamSpec::with_dir("str", PWStr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "KiUserApcDispatcher",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ExceptionInfo", GuestPtr),
            ParamSpec::new("Context1", GuestPtr),
            ParamSpec::new("Context2", GuestPtr),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "labs",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("n", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrEnumerateLoadedModules",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Reserved", Bool32),
            ParamSpec::new("EnumProc", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrFindEntryForAddress",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::with_dir("ModuleEntry", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrGetDllHandleByName",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ModuleFileName", UnicodeStringStruct)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrGetDllHandleEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("PathToFile", UnicodeStringStruct),
            ParamSpec::new("BaseName", UnicodeStringStruct),
            ParamSpec::new("ModuleFileName", UnicodeStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrGetProcedureAddressForCaller",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ModuleHandle", ModuleHandle),
            ParamSpec::new("FunctionName", AnsiStringStruct),
            ParamSpec::new("Ordinal", U32),
            ParamSpec::with_dir("FunctionAddress", GuestPtr, Out),
            ParamSpec::new("Callback", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrLockLoaderLock",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::with_dir("Disposition", GuestPtr, Out),
            ParamSpec::with_dir("Cookie", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrRegisterDllNotification",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("NotificationFunction", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::with_dir("Cookie", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrUnlockLoaderLock",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("Cookie", PointerSizedUInt),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrUnregisterDllNotification",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Cookie", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ltoa",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I32),
            ParamSpec::with_dir("str", PStr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_ltow",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("value", I32),
            ParamSpec::with_dir("str", PWStr, Out),
            ParamSpec::new("radix", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "memchr",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ptr", GuestPtr),
            ParamSpec::new("value", I32),
            ParamSpec::new("num", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "memcmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("s1", GuestPtr),
            ParamSpec::new("s2", GuestPtr),
            ParamSpec::new("n", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── CRT Memory Utilities ──────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "memcpy",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "memmove",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", GuestPtr),
            ParamSpec::new("src", GuestPtr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "memset",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ptr", GuestPtr),
            ParamSpec::new("value", I32),
            ParamSpec::new("num", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Nt* System Calls (batch 2) ───────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtAcceptConnectPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("PortContext", GuestPtr),
            ParamSpec::new("ConnectionRequest", GuestPtr),
            ParamSpec::new("Accept", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAccessCheck",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("ClientToken", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("GenericMapping", GuestPtr),
            ParamSpec::new("PrivilegeSet", GuestPtr),
            ParamSpec::with_dir("PrivilegeSetLength", GuestPtr, Out),
            ParamSpec::with_dir("GrantedAccess", GuestPtr, Out),
            ParamSpec::with_dir("AccessStatus", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAccessCheckAndAuditAlarm",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SubsystemName", GuestPtr),
            ParamSpec::new("HandleId", Handle),
            ParamSpec::new("ObjectTypeName", GuestPtr),
            ParamSpec::new("ObjectName", GuestPtr),
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("GenericMapping", GuestPtr),
            ParamSpec::new("ObjectCreation", Bool32),
            ParamSpec::with_dir("GrantedAccess", GuestPtr, Out),
            ParamSpec::with_dir("AccessStatus", GuestPtr, Out),
            ParamSpec::with_dir("GenerateOnClose", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAddAtom",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AtomString", PWStr),
            ParamSpec::new("StringLength", U32),
            ParamSpec::with_dir("Atom", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAdjustPrivilegesToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("DisableAllPrivileges", Bool32),
            ParamSpec::new("NewState", GuestPtr),
            ParamSpec::new("BufferLength", U32),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlertThreadByThreadId",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ThreadId", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAllocateLocallyUniqueId",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("Luid", GuestPtr, Out)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAllocateReserveObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MemoryReserveHandle", GuestPtr, Out),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("Type", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAllocateUuids",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
            ParamSpec::new("p3", GuestPtr),
            ParamSpec::new("p4", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAllocateVirtualMemoryEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("AllocationType", Hex32),
            ParamSpec::new("PageProtection", Hex32),
            ParamSpec::new("ExtendedParameters", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcAcceptConnectPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("ConnectionPortHandle", Handle),
            ParamSpec::new("ConnectionMessageAttributes", U32),
            ParamSpec::new("ConnectionMessage", GuestPtr),
            ParamSpec::new("PortContext", GuestPtr),
            ParamSpec::new("MessageAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcConnectPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("PortName", GuestPtr),
            ParamSpec::new("ConnectionMessage", GuestPtr),
            ParamSpec::new("MessageAttribute", GuestPtr),
            ParamSpec::new("OutMessageAttributes", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::with_dir("BufferLength", GuestPtr, InOut),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("PortAttributes", GuestPtr),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcConnectPortEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("ConnectionPortObjectAttributes", GuestPtr),
            ParamSpec::new("ClientPortObjectAttributes", GuestPtr),
            ParamSpec::new("PortAttributes", GuestPtr),
            ParamSpec::new("MessageAttributes", GuestPtr),
            ParamSpec::new("ConnectionMessage", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::with_dir("BufferLength", GuestPtr, InOut),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcCreatePort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("PortAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcCreatePortSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("SectionSize", SizeT),
            ParamSpec::with_dir("AlpcPortSectionHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcCreateResourceReserve",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("MessageSize", SizeT),
            ParamSpec::with_dir("ResourceReserveHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcCreateSecurityContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("SecurityContext", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcDeletePortSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("SectionHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcDeleteResourceReserve",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("ResourceReserveHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcDeleteSecurityContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("SecurityContextHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcDisconnectPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcQueryInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("InformationClass", U32),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("BufferLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcSendWaitReceivePort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("SendMessage", GuestPtr),
            ParamSpec::new("SendMessageAttributes", GuestPtr),
            ParamSpec::new("ReceiveMessage", GuestPtr),
            ParamSpec::new("ReceiveMessageAttributes", GuestPtr),
            ParamSpec::with_dir("BufferLength", GuestPtr, InOut),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAlpcSetInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("InformationClass", U32),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("BufferLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtApphelpCacheControl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Operation", U32),
            ParamSpec::new("Data", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAssignProcessToJobObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("JobHandle", Handle),
            ParamSpec::new("ProcessHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtAssociateWaitCompletionPacket",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("WaitCompletionPacketHandle", Handle),
            ParamSpec::new("IoCompletionHandle", Handle),
            ParamSpec::new("TargetObjectHandle", Handle),
            ParamSpec::new("KeyContext", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::with_dir("AlreadySignaled", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCancelIoFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCancelIoFileEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusToCancel", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCancelSynchronousIo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("IoRequestToCancel", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCancelTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::with_dir("CurrentState", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCancelTimer2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("Parameters", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtChangeWnfStateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StateName", U64),
            ParamSpec::new("ChangeStamp", U32),
            ParamSpec::new("Data", GuestPtr),
            ParamSpec::new("DataSize", U32),
            ParamSpec::new("TypeId", GuestPtr),
            ParamSpec::new("TypeIdSize", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtClearEvent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("EventHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCommitComplete",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCommitEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCommitTransaction",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TransactionHandle", Handle),
            ParamSpec::new("Wait", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
];
