use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static MEMORY_PROCESS_SIGS: &[HookSignature] = &[
    // ── Memory ────────────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtAllocateVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::new("ZeroBits", PointerSizedUInt),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("AllocationType", Hex32),
            ParamSpec::new("Protect", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwAllocateVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::new("ZeroBits", PointerSizedUInt),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("AllocationType", Hex32),
            ParamSpec::new("Protect", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtFreeVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("FreeType", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwFreeVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("FreeType", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtProtectVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("NewProtect", Hex32),
            ParamSpec::with_dir("OldProtect", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwProtectVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::with_dir("RegionSize", GuestPtr, InOut),
            ParamSpec::new("NewProtect", Hex32),
            ParamSpec::with_dir("OldProtect", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("MemoryInformationClass", U32),
            ParamSpec::with_dir("MemoryInformation", GuestPtr, Out),
            ParamSpec::new("MemoryInformationLength", SizeT),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("MemoryInformationClass", U32),
            ParamSpec::with_dir("MemoryInformation", GuestPtr, Out),
            ParamSpec::new("MemoryInformationLength", SizeT),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Process / Thread ──────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ClientId", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwOpenProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ClientId", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateThreadEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("StartRoutine", FunctionPtr),
            ParamSpec::new("Argument", GuestPtr),
            ParamSpec::new("CreateFlags", Hex32),
            ParamSpec::new("ZeroBits", SizeT),
            ParamSpec::new("StackSize", SizeT),
            ParamSpec::new("MaximumStackSize", SizeT),
            ParamSpec::new("AttributeList", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwCreateThreadEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("StartRoutine", FunctionPtr),
            ParamSpec::new("Argument", GuestPtr),
            ParamSpec::new("CreateFlags", Hex32),
            ParamSpec::new("ZeroBits", SizeT),
            ParamSpec::new("StackSize", SizeT),
            ParamSpec::new("MaximumStackSize", SizeT),
            ParamSpec::new("AttributeList", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInformationProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("ProcessInformationClass", U32),
            ParamSpec::with_dir("ProcessInformation", GuestPtr, Out),
            ParamSpec::new("ProcessInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQueryInformationProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("ProcessInformationClass", U32),
            ParamSpec::with_dir("ProcessInformation", GuestPtr, Out),
            ParamSpec::new("ProcessInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQuerySystemInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SystemInformationClass", U32),
            ParamSpec::with_dir("SystemInformation", GuestPtr, Out),
            ParamSpec::new("SystemInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "ZwQuerySystemInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SystemInformationClass", U32),
            ParamSpec::with_dir("SystemInformation", GuestPtr, Out),
            ParamSpec::new("SystemInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtGetContextThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("Context", OpaqueStructPtr("CONTEXT"), InOut),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetContextThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("Context", OpaqueStructPtr("CONTEXT")),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtClose",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtContinue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Context", OpaqueStructPtr("CONTEXT")),
            ParamSpec::new("TestAlert", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "KiUserExceptionDispatcher",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ExceptionRecord", GuestPtr),
            ParamSpec::new("Context", OpaqueStructPtr("CONTEXT")),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Heap ──────────────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAllocateHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", Hex32),
            ParamSpec::new("Size", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFreeHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", Hex32),
            ParamSpec::new("MemoryPointer", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlReAllocateHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", Hex32),
            ParamSpec::new("MemoryPointer", GuestPtr),
            ParamSpec::new("Size", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", Hex32),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("SizeToReserve", SizeT),
            ParamSpec::new("SizeToCommit", SizeT),
            ParamSpec::new("Lock", GuestPtr),
            ParamSpec::new("Parameters", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDestroyHeap",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("HeapHandle", Handle)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Loader ────────────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "LdrLoadDll",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PathToFile", GuestPtr),
            ParamSpec::new("Flags", GuestPtr),
            ParamSpec::new("ModuleFileName", UnicodeStringStruct),
            ParamSpec::with_dir("ModuleHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrGetProcedureAddress",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ModuleHandle", ModuleHandle),
            ParamSpec::new("FunctionName", AnsiStringStruct),
            ParamSpec::new("Ordinal", U32),
            ParamSpec::with_dir("FunctionAddress", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "LdrGetDllHandle",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PathToFile", GuestPtr),
            ParamSpec::new("Flags", GuestPtr),
            ParamSpec::new("ModuleFileName", UnicodeStringStruct),
            ParamSpec::with_dir("ModuleHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Section / File mapping ────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SectionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("MaximumSize", GuestPtr),
            ParamSpec::new("SectionPageProtection", Hex32),
            ParamSpec::new("AllocationAttributes", Hex32),
            ParamSpec::new("FileHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtMapViewOfSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::with_dir("BaseAddress", GuestPtr, InOut),
            ParamSpec::new("ZeroBits", PointerSizedUInt),
            ParamSpec::new("CommitSize", SizeT),
            ParamSpec::new("SectionOffset", GuestPtr),
            ParamSpec::with_dir("ViewSize", GuestPtr, InOut),
            ParamSpec::new("InheritDisposition", U32),
            ParamSpec::new("AllocationType", Hex32),
            ParamSpec::new("Win32Protect", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtUnmapViewOfSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Memory I/O ────────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtReadVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::new("NumberOfBytesToRead", SizeT),
            ParamSpec::with_dir("NumberOfBytesRead", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWriteVirtualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("NumberOfBytesToWrite", SizeT),
            ParamSpec::with_dir("NumberOfBytesWritten", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Unicode / String ──────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", UnicodeStringStruct, Out),
            ParamSpec::new("SourceString", PCWStr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateUnicodeStringFromAsciiz",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", UnicodeStringStruct, Out),
            ParamSpec::new("SourceString", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFreeUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("UnicodeString", UnicodeStringStruct)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Exception / Context ───────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCaptureContext",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "ContextRecord",
            OpaqueStructPtr("CONTEXT"),
            Out,
        )],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRestoreContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ContextRecord", OpaqueStructPtr("CONTEXT")),
            ParamSpec::new("ExceptionRecord", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnwind",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TargetFrame", GuestPtr),
            ParamSpec::new("TargetIp", GuestPtr),
            ParamSpec::new("ExceptionRecord", GuestPtr),
            ParamSpec::new("ReturnValue", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnwindEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TargetFrame", GuestPtr),
            ParamSpec::new("TargetIp", GuestPtr),
            ParamSpec::new("ExceptionRecord", GuestPtr),
            ParamSpec::new("ReturnValue", GuestPtr),
            ParamSpec::new("ContextRecord", OpaqueStructPtr("CONTEXT")),
            ParamSpec::new("HistoryTable", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLookupFunctionEntry",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ControlPc", U64),
            ParamSpec::with_dir("ImageBase", GuestPtr, Out),
            ParamSpec::new("HistoryTable", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlVirtualUnwind",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", Hex32),
            ParamSpec::new("ImageBase", U64),
            ParamSpec::new("ControlPc", U64),
            ParamSpec::new("FunctionEntry", GuestPtr),
            ParamSpec::with_dir("ContextRecord", OpaqueStructPtr("CONTEXT"), Out),
            ParamSpec::with_dir("HandlerData", GuestPtr, Out),
            ParamSpec::with_dir("EstablisherFrame", GuestPtr, Out),
            ParamSpec::with_dir("NestedFrame", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlPcToFileHeader",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PcValue", U64),
            ParamSpec::with_dir("BaseOfImage", GuestPtr, Out),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Version ───────────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetVersion",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "lpVersionInformation",
            OpaqueStructPtr("RTL_OSVERSIONINFOW"),
            InOut,
        )],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── Misc ──────────────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEncodePointer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Pointer", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDecodePointer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Pointer", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRandomEx",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("Seed", GuestPtr, InOut)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDuplicateObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SourceProcessHandle", Handle),
            ParamSpec::new("SourceHandle", Handle),
            ParamSpec::new("TargetProcessHandle", Handle),
            ParamSpec::with_dir("TargetHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("HandleAttributes", Hex32),
            ParamSpec::new("Options", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueueApcThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ApcRoutine", FunctionPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("ApcStatusBlock", GuestPtr),
            ParamSpec::new("ApcRoutineAddress", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
];
