use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static NT_SYSCALLS_2_SIGS: &[HookSignature] = &[
    HookSignature {
        module: "ntdll.dll",
        function: "NtPrePrepareComplete",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtPrePrepareEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtPulseEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EventHandle", Handle),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryAttributesFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::with_dir("FileInformation", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryDirectoryFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("FileInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FileInformationClass", U32),
            ParamSpec::new("ReturnSingleEntry", Bool32),
            ParamSpec::new("FileName", UnicodeStringStruct),
            ParamSpec::new("RestartScan", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryDirectoryObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DirectoryHandle", Handle),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("ReturnSingleEntry", Bool32),
            ParamSpec::new("RestartScan", Bool32),
            ParamSpec::with_dir("Context", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryEaFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("ReturnSingleEntry", Bool32),
            ParamSpec::new("EaList", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryFullAttributesFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::with_dir("FileInformation", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInformationAtom",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Atom", U32),
            ParamSpec::new("InformationClass", U32),
            ParamSpec::with_dir("AtomInformation", GuestPtr, Out),
            ParamSpec::new("AtomInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInformationFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("FileInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FileInformationClass", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInformationJobObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("JobHandle", Handle),
            ParamSpec::new("JobObjectInformationClass", U32),
            ParamSpec::with_dir("JobObjectInformation", GuestPtr, Out),
            ParamSpec::new("JobObjectInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInformationThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ThreadInformationClass", U32),
            ParamSpec::with_dir("ThreadInformation", GuestPtr, Out),
            ParamSpec::new("ThreadInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInformationToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("TokenInformationClass", U32),
            ParamSpec::with_dir("TokenInformation", GuestPtr, Out),
            ParamSpec::new("TokenInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryInstallTimeStamp",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("TimeStamp", GuestPtr, Out)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("KeyInformationClass", U32),
            ParamSpec::with_dir("KeyInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryLicenseValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Name", UnicodeStringStruct),
            ParamSpec::new("Type", GuestPtr),
            ParamSpec::with_dir("Data", GuestPtr, Out),
            ParamSpec::new("DataSize", U32),
            ParamSpec::with_dir("ResultDataSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryMultipleValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueEntries", GuestPtr),
            ParamSpec::new("EntryCount", U32),
            ParamSpec::with_dir("ValueBuffer", GuestPtr, Out),
            ParamSpec::with_dir("BufferLength", GuestPtr, InOut),
            ParamSpec::with_dir("RequiredBufferLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Handle", Handle),
            ParamSpec::new("ObjectInformationClass", U32),
            ParamSpec::with_dir("ObjectInformation", GuestPtr, Out),
            ParamSpec::new("ObjectInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryPerformanceCounter",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PerformanceCounter", GuestPtr, Out),
            ParamSpec::with_dir("PerformanceFrequency", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQuerySection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("SectionInformationClass", U32),
            ParamSpec::with_dir("SectionInformation", GuestPtr, Out),
            ParamSpec::new("SectionInformationLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQuerySecurityObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Handle", Handle),
            ParamSpec::new("SecurityInformation", U32),
            ParamSpec::with_dir("SecurityDescriptor", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("LengthNeeded", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQuerySymbolicLinkObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SymbolicLinkHandle", Handle),
            ParamSpec::new("LinkTarget", UnicodeStringStruct),
            ParamSpec::with_dir("ReturnedLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("TimerInformationClass", U32),
            ParamSpec::with_dir("TimerInformation", GuestPtr, Out),
            ParamSpec::new("TimerInformationLength", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryTimerResolution",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MaximumResolution", GuestPtr, Out),
            ParamSpec::with_dir("MinimumResolution", GuestPtr, Out),
            ParamSpec::with_dir("CurrentResolution", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueName", UnicodeStringStruct),
            ParamSpec::new("KeyValueInformationClass", U32),
            ParamSpec::with_dir("KeyValueInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryVolumeInformationFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("FsInformation", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FsInformationClass", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtQueryWnfStateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StateName", GuestPtr),
            ParamSpec::new("TypeId", GuestPtr),
            ParamSpec::new("ExplicitScope", GuestPtr),
            ParamSpec::with_dir("ChangeStamp", GuestPtr, Out),
            ParamSpec::with_dir("Buffer", GuestPtr, InOut),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReadFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::new("Length", U32),
            ParamSpec::new("ByteOffset", GuestPtr),
            ParamSpec::new("Key", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReadOnlyEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRecoverResourceManager",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ResourceManagerHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRecoverTransactionManager",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("TmHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReleaseKeyedEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyedEventHandle", Handle),
            ParamSpec::new("KeyValue", GuestPtr),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReleaseMutant",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("MutantHandle", Handle),
            ParamSpec::with_dir("PreviousCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReleaseSemaphore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SemaphoreHandle", Handle),
            ParamSpec::new("ReleaseCount", I32),
            ParamSpec::with_dir("PreviousCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRemoveIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("IoCompletionHandle", Handle),
            ParamSpec::with_dir("KeyContext", GuestPtr, Out),
            ParamSpec::with_dir("ApcContext", GuestPtr, Out),
            ParamSpec::with_dir("IoStatusBlock", GuestPtr, Out),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRemoveProcessDebug",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DebugObjectHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReplyPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("ReplyMessage", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtReplyWaitReplyPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("ReplyMessage", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRequestPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("RequestMessage", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRequestWaitReplyPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("RequestMessage", GuestPtr),
            ParamSpec::new("ReplyMessage", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtResetEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EventHandle", Handle),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtResumeThread .. qsort (batch 4) ──────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtResumeThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("PreviousSuspendCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRollbackComplete",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRollbackEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtRollbackTransaction",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TransactionHandle", Handle),
            ParamSpec::new("Wait", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetEaFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("EaBuffer", GuestPtr),
            ParamSpec::new("EaBufferSize", U32),
            ParamSpec::new("EaList", GuestPtr),
            ParamSpec::new("EaListLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EventHandle", Handle),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetInformationFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("FileInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FileInformationClass", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetInformationJobObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("JobHandle", Handle),
            ParamSpec::new("JobObjectInformationClass", U32),
            ParamSpec::new("JobObjectInformation", GuestPtr),
            ParamSpec::new("JobObjectInformationLength", U32),
            ParamSpec::new("ReturnLength", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetInformationProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("ProcessInformationClass", U32),
            ParamSpec::new("ProcessInformation", GuestPtr),
            ParamSpec::new("ProcessInformationLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetInformationThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ThreadInformationClass", U32),
            ParamSpec::new("ThreadInformation", GuestPtr),
            ParamSpec::new("ThreadInformationLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetInformationToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("TokenInformationClass", U32),
            ParamSpec::new("TokenInformation", GuestPtr),
            ParamSpec::new("TokenInformationLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("IoCompletionHandle", Handle),
            ParamSpec::new("KeyContext", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatus", U32),
            ParamSpec::new("IoStatusInformation", PointerSizedUInt),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetSecurityObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Handle", Handle),
            ParamSpec::new("SecurityInformation", U32),
            ParamSpec::new("SecurityDescriptor", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetSystemInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SystemInformationClass", U32),
            ParamSpec::new("SystemInformation", GuestPtr),
            ParamSpec::new("SystemInformationLength", U32),
            ParamSpec::new("ReturnLength", PointerSizedUInt),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetTimer2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("DueTime", GuestPtr),
            ParamSpec::new("ExpirationTime", GuestPtr),
            ParamSpec::new("Parameters", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("DueTime", GuestPtr),
            ParamSpec::new("TimerApcRoutine", GuestPtr),
            ParamSpec::new("TimerContext", GuestPtr),
            ParamSpec::new("ResumeTimer", Bool32),
            ParamSpec::new("Period", I32),
            ParamSpec::with_dir("PreviousState", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetTimerEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerHandle", Handle),
            ParamSpec::new("TimerSetInformationClass", U32),
            ParamSpec::new("TimerSetInformation", GuestPtr),
            ParamSpec::new("TimerSetInformationLength", U32),
            ParamSpec::new("ReturnLength", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueName", GuestPtr),
            ParamSpec::new("TitleIndex", U32),
            ParamSpec::new("Type", U32),
            ParamSpec::new("Data", GuestPtr),
            ParamSpec::new("DataSize", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSetVolumeInformationFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("FsInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("FsInformationClass", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSignalAndWaitForSingleObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SignalObject", Handle),
            ParamSpec::new("WaitObject", Handle),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::new("Timeout2", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtSuspendThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("PreviousSuspendCount", GuestPtr, Out),
            ParamSpec::with_dir("PreviousSuspendCount2", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtTerminateJobObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("JobHandle", Handle),
            ParamSpec::new("ExitStatus", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtTerminateProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("ExitStatus", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtTerminateThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("ExitStatus", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtTraceControl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FunctionCode", U32),
            ParamSpec::new("InBuffer", GuestPtr),
            ParamSpec::new("InBufferLength", U32),
            ParamSpec::new("OutBuffer", GuestPtr),
            ParamSpec::new("OutBufferLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtTraceEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TraceHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("FieldSize", U32),
            ParamSpec::new("Fields", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtUnloadDriver",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("DriverServiceName", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtUnlockFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("ByteOffset", GuestPtr),
            ParamSpec::new("Length", GuestPtr),
            ParamSpec::new("Key", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtUpdateWnfStateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StateName", GuestPtr),
            ParamSpec::new("Data", GuestPtr),
            ParamSpec::new("DataSize", U32),
            ParamSpec::new("TypeId", GuestPtr),
            ParamSpec::new("ExplicitScope", GuestPtr),
            ParamSpec::new("MatchingChangeStamp", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWaitForAlertByThreadId",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWaitForKeyedEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyedEventHandle", Handle),
            ParamSpec::new("KeyValue", GuestPtr),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWaitForMultipleObjects",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Count", U32),
            ParamSpec::new("Handles", GuestPtr),
            ParamSpec::new("WaitType", U32),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWaitForSingleObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Handle", Handle),
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::new("Timeout2", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWorkerFactoryCreate",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("WorkerFactoryHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("CompletionPort", Handle),
            ParamSpec::new("CompletionKey", GuestPtr),
            ParamSpec::new("StartingAddress", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWorkerFactoryReady",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("WorkerFactoryHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWorkerFactoryRelease",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("WorkerFactoryHandle", Handle),
            ParamSpec::new("Reserved", GuestPtr),
            ParamSpec::new("Count", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWorkerFactoryShutdown",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("WorkerFactoryHandle", Handle),
            ParamSpec::new("CancelPending", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWorkerFactoryWait",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("WorkerFactoryHandle", Handle),
            ParamSpec::new("WaitReason", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtWriteFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("ByteOffset", GuestPtr),
            ParamSpec::new("Key", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "qsort",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("base", GuestPtr),
            ParamSpec::new("nmemb", SizeT),
            ParamSpec::new("size", SizeT),
            ParamSpec::new("compar", FunctionPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
];
