use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static NT_SYSCALLS_1_SIGS: &[HookSignature] = &[
    // ── NtCompleteConnectPort .. NtEnumerateValueKey ──────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtCompleteConnectPort",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("PortHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtConnectNamedPipe",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("NamedPipeHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateDirectoryObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DirectoryHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("EnlistmentHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ResourceManagerHandle", Handle),
            ParamSpec::new("TransactionHandle", Handle),
            ParamSpec::new("CreateGuid", GuestPtr),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::new("Reserved", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("EventHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("EventType", I32),
            ParamSpec::new("InitialState", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("FileHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("AllocationSize", GuestPtr),
            ParamSpec::new("FileAttributes", U32),
            ParamSpec::new("ShareAccess", U32),
            ParamSpec::new("CreateDisposition", U32),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::new("EaBuffer", GuestPtr),
            ParamSpec::new("EaLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("IoCompletionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("NumberOfConcurrentThreads", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateJobObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("JobHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("TitleIndex", U32),
            ParamSpec::new("Class", UnicodeStringStruct),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::with_dir("Disposition", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateKeyedEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyedEventHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateMailslotFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MailslotFileHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("FileAttributes", U32),
            ParamSpec::new("ShareAccess", U32),
            ParamSpec::new("MaximumMessageSize", U32),
            ParamSpec::new("ReadTimeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateMutant",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MutantHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("InitialOwner", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateNamedPipeFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("FileHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("ShareAccess", U32),
            ParamSpec::new("CreateDisposition", U32),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::new("NamedPipeType", Bool32),
            ParamSpec::new("ReadMode", Bool32),
            ParamSpec::new("CompletionMode", Bool32),
            ParamSpec::new("MaximumInstances", U32),
            ParamSpec::new("InboundQuota", U32),
            ParamSpec::new("OutboundQuota", U32),
            ParamSpec::new("DefaultTimeout", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreatePagingFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileName", UnicodeStringStruct),
            ParamSpec::new("MinimumSize", GuestPtr),
            ParamSpec::new("MaximumSize", GuestPtr),
            ParamSpec::new("Priority", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreatePort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("MaxDataLength", U32),
            ParamSpec::new("MaxMessageLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ParentProcess", Handle),
            ParamSpec::new("InheritObjectTable", Bool32),
            ParamSpec::new("SectionHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateProcessEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ParentProcess", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("DebugPort", Handle),
            ParamSpec::new("ExceptionPort", Handle),
            ParamSpec::new("Reserved", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateResourceManager",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ResourceManagerHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("TmHandle", Handle),
            ParamSpec::new("Description", UnicodeStringStruct),
            ParamSpec::new("CreateGuid", GuestPtr),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateSemaphore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SemaphoreHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("InitialCount", I32),
            ParamSpec::new("MaximumCount", I32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateSymbolicLinkObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SymbolicLinkHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("LinkTarget", UnicodeStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("ClientId", GuestPtr),
            ParamSpec::new("ThreadContext", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TimerHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("TimerType", I32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateTransaction",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TransactionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("Description", UnicodeStringStruct),
            ParamSpec::new("Uow", GuestPtr),
            ParamSpec::new("TmHandle", Handle),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::new("IsolationLevel", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateTransactionManager",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TmHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("LogFileName", UnicodeStringStruct),
            ParamSpec::new("CreateOptions", U32),
            ParamSpec::new("CommitStrength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateUserProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessHandle", GuestPtr, Out),
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("ProcessDesiredAccess", Hex32),
            ParamSpec::new("ThreadDesiredAccess", Hex32),
            ParamSpec::new("ProcessObjectAttributes", GuestPtr),
            ParamSpec::new("ThreadObjectAttributes", GuestPtr),
            ParamSpec::new("ProcessFlags", U32),
            ParamSpec::new("ThreadFlags", U32),
            ParamSpec::new("ProcessParameters", GuestPtr),
            ParamSpec::new("CreateInfo", GuestPtr),
            ParamSpec::new("AttributeList", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateWaitablePort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PortHandle", GuestPtr, Out),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("MaxDataLength", U32),
            ParamSpec::new("MaxMessageLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtCreateWnfStateName",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("StateName", GuestPtr, Out),
            ParamSpec::new("NameLifetime", U32),
            ParamSpec::new("DataScope", GuestPtr),
            ParamSpec::new("MaximumStateSize", U32),
            ParamSpec::new("CreatorId", GuestPtr),
            ParamSpec::new("PrimaryClientId", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDebugActiveProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DebugObjectHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDebugContinue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DebugObjectHandle", Handle),
            ParamSpec::new("ClientId", GuestPtr),
            ParamSpec::new("ContinueStatus", I32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDelayExecution",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Alertable", Bool32),
            ParamSpec::new("DelayInterval", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeleteAtom",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Atom", U32)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeleteFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ObjectAttributes", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeleteKey",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("KeyHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeleteValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("ValueName", UnicodeStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeleteWnfStateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StateName", GuestPtr),
            ParamSpec::new("ExplicitScope", GuestPtr),
            ParamSpec::new("MatchingClass", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeleteWnfStateName",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("StateName", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDeviceIoControlFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", FunctionPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("IoControlCode", Hex32),
            ParamSpec::new("InputBuffer", GuestPtr),
            ParamSpec::new("InputBufferLength", U32),
            ParamSpec::new("OutputBuffer", GuestPtr),
            ParamSpec::new("OutputBufferLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtDuplicateToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ExistingTokenHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("EffectiveOnly", Bool32),
            ParamSpec::new("TokenType", I32),
            ParamSpec::with_dir("NewTokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtEnumerateKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("Index", U32),
            ParamSpec::new("KeyInformationClass", I32),
            ParamSpec::new("KeyInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "NtEnumerateValueKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("Index", U32),
            ParamSpec::new("KeyValueInformationClass", I32),
            ParamSpec::new("KeyValueInformation", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::with_dir("ResultLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtExitProcess ────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtExitProcess",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ExitStatus", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── NtExtendSection ─────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtExtendSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SectionHandle", Handle),
            ParamSpec::new("NewSectionSize", GuestPtr),
            ParamSpec::with_dir("NewSectionSizeHigh", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtFindAtom ──────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtFindAtom",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AtomName", PCWStr),
            ParamSpec::new("AtomNameLength", U32),
            ParamSpec::with_dir("Atom", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtFlushBuffersFile ──────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtFlushBuffersFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("IoStatusBlock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtFlushBuffersFileEx ────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtFlushBuffersFileEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("Parameters", GuestPtr),
            ParamSpec::new("ParametersSize", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtFsControlFile ─────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtFsControlFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("FsControlCode", U32),
            ParamSpec::new("InputBuffer", GuestPtr),
            ParamSpec::new("InputBufferLength", U32),
            ParamSpec::new("OutputBuffer", GuestPtr),
            ParamSpec::new("OutputBufferLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtGetNextProcess ────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtGetNextProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("HandleAttributes", U32),
            ParamSpec::new("Flags", U32),
            ParamSpec::with_dir("NewProcessHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtGetNotificationResourceManager ────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtGetNotificationResourceManager",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ResourceManagerHandle", Handle),
            ParamSpec::new("TransactionNotification", GuestPtr),
            ParamSpec::new("NotificationLength", U32),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
            ParamSpec::new("Asynchronous", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtImpersonateAnonymousToken ─────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtImpersonateAnonymousToken",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ThreadHandle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtListenPort ────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtListenPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PortHandle", Handle),
            ParamSpec::new("ConnectionRequest", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtLoadDriver ────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtLoadDriver",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DriverServiceName", UnicodeStringStruct),
            ParamSpec::new("DriverObject", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtLockFile ──────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtLockFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("ByteOffset", GuestPtr),
            ParamSpec::new("Length", GuestPtr),
            ParamSpec::new("Key", U32),
            ParamSpec::new("FailImmediately", Bool32),
            ParamSpec::new("ExclusiveLock", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtMakePermanentObject ───────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtMakePermanentObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtMakeTemporaryObject ───────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtMakeTemporaryObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handle", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtNotifyChangeDirectoryFile ─────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtNotifyChangeDirectoryFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("WatchTree", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtNotifyChangeKey ───────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtNotifyChangeKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("KeyHandle", Handle),
            ParamSpec::new("Event", Handle),
            ParamSpec::new("ApcRoutine", GuestPtr),
            ParamSpec::new("ApcContext", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("WatchTree", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenDirectoryObject ───────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenDirectoryObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DirectoryHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenEnlistment ────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("EnlistmentHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ResourceManagerHandle", Handle),
            ParamSpec::new("EnlistmentGuid", GuestPtr),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenEvent ─────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("EventHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenFile ──────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("FileHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("IoStatusBlock", GuestPtr),
            ParamSpec::new("ShareAccess", U32),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenIoCompletion ──────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("IoCompletionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenJobObject ─────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenJobObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("JobHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenKey ───────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenKeyedEvent ────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenKeyedEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyedEventHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenKeyEx ─────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenKeyEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("KeyHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenMutant ────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenMutant",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MutantHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenProcessToken ──────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenProcessToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::with_dir("TokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenProcessTokenEx ────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenProcessTokenEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("HandleAttributes", U32),
            ParamSpec::with_dir("TokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenResourceManager ───────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenResourceManager",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ResourceManagerHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("TmHandle", Handle),
            ParamSpec::new("ResourceManagerGuid", GuestPtr),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenSection ───────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SectionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenSymbolicLinkObject ────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenSymbolicLinkObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SymbolicLinkHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenThread ────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("ClientId", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenThreadToken ───────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenThreadToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("OpenAsSelf", Bool32),
            ParamSpec::with_dir("TokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenThreadTokenEx ─────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenThreadTokenEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("OpenAsSelf", Bool32),
            ParamSpec::new("HandleAttributes", U32),
            ParamSpec::with_dir("TokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenTimer ─────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TimerHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenTransaction ───────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenTransaction",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TransactionHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("Description", UnicodeStringStruct),
            ParamSpec::new("Uow", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtOpenTransactionManager ────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtOpenTransactionManager",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TmHandle", GuestPtr, Out),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("ObjectAttributes", GuestPtr),
            ParamSpec::new("LogFileName", UnicodeStringStruct),
            ParamSpec::new("TmIdentity", GuestPtr),
            ParamSpec::new("OpenOptions", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtPrepareComplete ───────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtPrepareComplete",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtPrepareEnlistment ─────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "NtPrepareEnlistment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("EnlistmentHandle", Handle),
            ParamSpec::new("TmVirtualClock", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    // ── NtPrePrepareComplete ────────────────────────────────────────────
];
