use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static RTL_1_SIGS: &[HookSignature] = &[
    // ── Rtl* functions (batch 1) ─────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAbsoluteToSelfRelativeSD",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AbsoluteSecurityDescriptor", GuestPtr),
            ParamSpec::with_dir("SelfRelativeSecurityDescriptor", GuestPtr, Out),
            ParamSpec::with_dir("BufferLength", GuestPtr, InOut),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAbsoluteToSelfRelativeToSD2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("SecurityDescriptor", GuestPtr, InOut),
            ParamSpec::with_dir("BufferLength", GuestPtr, InOut),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAcquirePrivilege",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RequiredPrivileges", GuestPtr),
            ParamSpec::with_dir("PreviousPrivileges", GuestPtr, Out),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAddAce",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Acl", GuestPtr),
            ParamSpec::new("AceRevision", U32),
            ParamSpec::new("StartingAceIndex", U32),
            ParamSpec::new("AceList", GuestPtr),
            ParamSpec::new("AceListLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAddAtomToAtomTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AtomTable", GuestPtr),
            ParamSpec::new("AtomName", PCWStr),
            ParamSpec::with_dir("Atom", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAddVectoredContinueHandler",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("First", U32),
            ParamSpec::new("Handler", FunctionPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAddVectoredExceptionHandler",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("First", U32),
            ParamSpec::new("Handler", FunctionPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAdjustPrivilege",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Privilege", U32),
            ParamSpec::new("Enable", Bool32),
            ParamSpec::with_dir("Enabled", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAllocateAndInitializeSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("IdentifierAuthority", GuestPtr),
            ParamSpec::new("SubAuthorityCount", U32),
            ParamSpec::new("SubAuthority0", U32),
            ParamSpec::new("SubAuthority1", U32),
            ParamSpec::new("SubAuthority2", U32),
            ParamSpec::new("SubAuthority3", U32),
            ParamSpec::new("SubAuthority4", U32),
            ParamSpec::with_dir("Sid", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAnsiStringToUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", GuestPtr, Out),
            ParamSpec::new("SourceString", AnsiStringStruct),
            ParamSpec::new("AllocateDestinationString", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAppendAnsiStringToString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", AnsiStringStruct),
            ParamSpec::new("Source", AnsiStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAppendAsciizToString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", AnsiStringStruct),
            ParamSpec::new("Source", PCStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAppendStringToString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", AnsiStringStruct),
            ParamSpec::new("Source", AnsiStringStruct),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAppendUnicodeStringToString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", UnicodeStringStruct),
            ParamSpec::new("Source", UnicodeStringStruct),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlAppendUnicodeToString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", UnicodeStringStruct),
            ParamSpec::new("Source", PCWStr),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCancelTimer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("TimerQueue", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCaptureStackBackTrace",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FramesToSkip", U32),
            ParamSpec::new("FramesToCapture", U32),
            ParamSpec::with_dir("BackTrace", GuestPtr, Out),
            ParamSpec::with_dir("BackTraceHash", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCharToInteger",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", PCStr),
            ParamSpec::new("Base", U32),
            ParamSpec::with_dir("Value", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCheckRegistryKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RelativeTo", U32),
            ParamSpec::new("Path", PCWStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCheckTokenCapability",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("CapabilitySid", GuestPtr),
            ParamSpec::with_dir("HasCapability", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCheckTokenMembership",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("SidToCheck", GuestPtr),
            ParamSpec::with_dir("IsMember", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCheckTokenMembershipEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("SidToCheck", GuestPtr),
            ParamSpec::new("Flags", U32),
            ParamSpec::with_dir("IsMember", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCompactHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCompareMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Source1", GuestPtr),
            ParamSpec::new("Source2", GuestPtr),
            ParamSpec::new("Length", SizeT),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCompareMemoryUlong",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Source", GuestPtr),
            ParamSpec::new("Length", SizeT),
            ParamSpec::new("Pattern", U32),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCompareString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String1", AnsiStringStruct),
            ParamSpec::new("String2", AnsiStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCompareUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String1", UnicodeStringStruct),
            ParamSpec::new("String2", UnicodeStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCompressBuffer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompressionFormatAndEngine", U32),
            ParamSpec::new("UncompressedBuffer", GuestPtr),
            ParamSpec::new("UncompressedBufferSize", U32),
            ParamSpec::with_dir("CompressedBuffer", GuestPtr, Out),
            ParamSpec::new("CompressedBufferSize", U32),
            ParamSpec::new("UncompressedChunkSize", U32),
            ParamSpec::with_dir("FinalCompressedSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlComputeCrc32",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PartialCrc", U32),
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCopyMappedMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Source", GuestPtr),
            ParamSpec::new("Length", SizeT),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCopyMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Source", GuestPtr),
            ParamSpec::new("Length", SizeT),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCopySecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Source", GuestPtr),
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCopySid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationSidLength", U32),
            ParamSpec::new("DestinationSid", GuestPtr),
            ParamSpec::new("SourceSid", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCopyUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationString", UnicodeStringStruct),
            ParamSpec::new("SourceString", UnicodeStringStruct),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCrc32",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("InitialCrc", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCrc64",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Buffer", GuestPtr),
            ParamSpec::new("Length", U32),
            ParamSpec::new("InitialCrc", U64),
        ],
        ret: ReturnSpec::U64,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateAcl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Acl", GuestPtr),
            ParamSpec::new("AclLength", U32),
            ParamSpec::new("AclRevision", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateAtomTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("NumberOfBuckets", U32),
            ParamSpec::with_dir("AtomTable", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateEnvironment",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CloneCurrentEnvironment", Bool32),
            ParamSpec::with_dir("Environment", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateProcessParametersEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("ProcessParameters", GuestPtr, Out),
            ParamSpec::new("ImagePathName", UnicodeStringStruct),
            ParamSpec::new("DllPath", UnicodeStringStruct),
            ParamSpec::new("CurrentDirectory", UnicodeStringStruct),
            ParamSpec::new("CommandLine", UnicodeStringStruct),
            ParamSpec::new("Environment", GuestPtr),
            ParamSpec::new("WindowTitle", UnicodeStringStruct),
            ParamSpec::new("DesktopInfo", UnicodeStringStruct),
            ParamSpec::new("ShellInfo", UnicodeStringStruct),
            ParamSpec::new("RuntimeData", UnicodeStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateQueryDebugBuffer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Size", U32),
            ParamSpec::new("EventPair", Bool32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateRegistryKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RelativeTo", U32),
            ParamSpec::new("Path", PCWStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("Revision", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateServiceSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ServiceName", UnicodeStringStruct),
            ParamSpec::new("ServiceSid", SidPtr),
            ParamSpec::with_dir("ServiceSidLength", GuestPtr, InOut),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerQueue", Handle),
            ParamSpec::with_dir("TimerHandle", GuestPtr, Out),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateTimerQueue",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("TimerQueueHandle", GuestPtr, Out)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", UnicodeStringStruct),
            ParamSpec::new("Source", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlCreateUserThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("CreateSuspended", Bool32),
            ParamSpec::new("StackZeroBits", U32),
            ParamSpec::new("StackReserved", SizeT),
            ParamSpec::new("StackCommit", SizeT),
            ParamSpec::new("StartAddress", FunctionPtr),
            ParamSpec::new("Parameter", GuestPtr),
            ParamSpec::with_dir("ThreadHandle", GuestPtr, Out),
            ParamSpec::with_dir("ClientId", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDecodeSystemPointer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Pointer", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDecompressBuffer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompressionFormat", U32),
            ParamSpec::with_dir("UncompressedBuffer", GuestPtr, Out),
            ParamSpec::new("UncompressedBufferSize", U32),
            ParamSpec::new("CompressedBuffer", GuestPtr),
            ParamSpec::new("CompressedBufferSize", U32),
            ParamSpec::with_dir("FinalUncompressedSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDecryptMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Memory", GuestPtr),
            ParamSpec::new("MemorySize", U32),
            ParamSpec::new("OptionFlags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDefaultNpAcl",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Acl", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteAce",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Acl", GuestPtr),
            ParamSpec::new("AceIndex", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteAtomFromAtomTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AtomTable", GuestPtr),
            ParamSpec::new("Atom", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteRegistryValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RelativeTo", U32),
            ParamSpec::new("Path", PCWStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerQueue", Handle),
            ParamSpec::new("Timer", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteTimerQueue",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("TimerQueue", Handle)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeleteTimerQueueEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerQueue", Handle),
            ParamSpec::new("CompletionEvent", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDeNormalizeProcessParams",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ProcessParameters", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDestroyAtomTable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("AtomTable", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDestroyEnvironment",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Environment", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDestroyProcessParameters",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ProcessParameters", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDestroyQueryDebugBuffer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Buffer", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDoesFileExists_U",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("FileName", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDoesFileExists_UEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("FileName", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDosPathNameToNtPathName_U",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DosPathName", PCWStr),
            ParamSpec::with_dir("NtPathName", GuestPtr, Out),
            ParamSpec::with_dir("NtFileNamePart", GuestPtr, Out),
            ParamSpec::with_dir("DirectoryInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDosPathNameToNtPathName_U_WithStatus",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DosPathName", PCWStr),
            ParamSpec::with_dir("NtPathName", GuestPtr, Out),
            ParamSpec::with_dir("NtFileNamePart", GuestPtr, Out),
            ParamSpec::with_dir("DirectoryInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDowncaseUnicodeChar",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SourceCharacter", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDowncaseUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", GuestPtr, Out),
            ParamSpec::new("SourceString", UnicodeStringStruct),
            ParamSpec::new("AllocateDestinationString", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlDuplicateUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("SourceString", UnicodeStringStruct),
            ParamSpec::with_dir("DestinationString", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEncodeSystemPointer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Pointer", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEncryptMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Memory", GuestPtr),
            ParamSpec::new("MemorySize", U32),
            ParamSpec::new("OptionFlags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEnterCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEqualMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Source1", GuestPtr),
            ParamSpec::new("Source2", GuestPtr),
            ParamSpec::new("Length", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEqualPrefixSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Sid1", SidPtr),
            ParamSpec::new("Sid2", SidPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEqualSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Sid1", SidPtr),
            ParamSpec::new("Sid2", SidPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEqualString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String1", AnsiStringStruct),
            ParamSpec::new("String2", AnsiStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEqualUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String1", UnicodeStringStruct),
            ParamSpec::new("String2", UnicodeStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlEraseUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("String", UnicodeStringStruct)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlExitUserProcess",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ExitStatus", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlExpandEnvironmentStrings",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Source", PCWStr),
            ParamSpec::with_dir("Destination", GuestPtr, Out),
            ParamSpec::new("Size", U32),
            ParamSpec::with_dir("ReturnedSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlExpandEnvironmentStrings_U",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Environment", GuestPtr),
            ParamSpec::new("Source", UnicodeStringStruct),
            ParamSpec::with_dir("Destination", GuestPtr, Out),
            ParamSpec::with_dir("ReturnedLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFillMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Length", SizeT),
            ParamSpec::new("Fill", U32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFillMemoryUlong",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Length", SizeT),
            ParamSpec::new("Pattern", U32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFillMemoryUlonglong",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Length", SizeT),
            ParamSpec::new("Pattern", U64),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFirstEntrySList",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ListHead", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFormatCurrentUserKeyPath",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Path", UnicodeStringStruct)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFreeAnsiString",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("AnsiString", AnsiStringStruct)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFreeOemString",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("OemString", AnsiStringStruct)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFreeSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Sid", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlFreeString",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("String", AnsiStringStruct)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetAce",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Acl", GuestPtr),
            ParamSpec::new("AceIndex", U32),
            ParamSpec::with_dir("Ace", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetCompressionWorkSpaceSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompressionFormatAndEngine", U32),
            ParamSpec::with_dir("CompressBufferWorkSpaceSize", GuestPtr, Out),
            ParamSpec::with_dir("CompressFragmentWorkSpaceSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetCriticalSectionRecursionCount",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetCurrentDirectory_U",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("BufferLength", U32),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetDaclSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::with_dir("DaclPresent", GuestPtr, Out),
            ParamSpec::with_dir("Dacl", GuestPtr, Out),
            ParamSpec::with_dir("DaclDefaulted", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetEnabledExtendedFeatures",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("FeatureMask", U32)],
        ret: ReturnSpec::U64,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetExtendedContextLength",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::with_dir("Length", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetExtendedFeaturesMask",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Context", GuestPtr)],
        ret: ReturnSpec::U64,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetFullPathName_U",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileName", PCWStr),
            ParamSpec::new("BufferSize", U32),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::with_dir("FilePart", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetFullPathName_UEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("FileName", PCWStr),
            ParamSpec::new("BufferSize", U32),
            ParamSpec::with_dir("Buffer", GuestPtr, Out),
            ParamSpec::with_dir("FilePart", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetGroupSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::with_dir("Group", GuestPtr, Out),
            ParamSpec::with_dir("GroupDefaulted", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetOwnerSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::with_dir("Owner", GuestPtr, Out),
            ParamSpec::with_dir("OwnerDefaulted", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetProcessHeaps",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("NumberOfHeaps", U32),
            ParamSpec::with_dir("ProcessHeaps", GuestPtr, Out),
            ParamSpec::new("Extra", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGetUserInfoHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::with_dir("UserValue", GuestPtr, Out),
            ParamSpec::with_dir("UserFlags", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlGUIDFromString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("GuidString", UnicodeStringStruct),
            ParamSpec::with_dir("Guid", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlHashUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", UnicodeStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
            ParamSpec::new("HashAlgorithm", U32),
            ParamSpec::with_dir("HashValue", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlImpersonateSelf",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ImpersonationLevel", U32)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlImpersonateSelfEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ImpersonationLevel", U32),
            ParamSpec::new("ThreadHandle", Handle),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitAnsiString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationString", AnsiStringStruct),
            ParamSpec::new("SourceString", PCStr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitAnsiStringEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationString", AnsiStringStruct),
            ParamSpec::new("SourceString", PCStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitCodePageTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Table", GuestPtr),
            ParamSpec::new("CodePageTable", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitializeCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitializeCriticalSectionAndSpinCount",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CriticalSection", GuestPtr),
            ParamSpec::new("SpinCount", U32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitializeSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Sid", SidPtr),
            ParamSpec::new("IdentifierAuthority", GuestPtr),
            ParamSpec::new("SubAuthorityCount", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitializeSListHead",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ListHead", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitNlsTables",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AnsiTable", GuestPtr),
            ParamSpec::new("OemTable", GuestPtr),
            ParamSpec::new("CaseTable", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationString", AnsiStringStruct),
            ParamSpec::new("SourceString", PCStr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInitUnicodeStringEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationString", UnicodeStringStruct),
            ParamSpec::new("SourceString", PCWStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInt64ToUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Value", U64),
            ParamSpec::new("Base", U32),
            ParamSpec::new("String", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIntegerToChar",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Value", U32),
            ParamSpec::new("Base", U32),
            ParamSpec::new("OutputLength", I32),
            ParamSpec::new("String", PStr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIntegerToUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Value", U32),
            ParamSpec::new("Base", U32),
            ParamSpec::new("String", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInterlockedPopEntrySList",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ListHead", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlInterlockedPushEntrySList",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ListHead", GuestPtr),
            ParamSpec::new("ListEntry", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv4AddressToStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("String", PStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv4AddressToStringExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("Port", U32),
            ParamSpec::new("String", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv4AddressToStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("String", PWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv4StringToAddressA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", PCStr),
            ParamSpec::new("Strict", Bool32),
            ParamSpec::new("Terminator", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv4StringToAddressExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", PCStr),
            ParamSpec::new("Strict", Bool32),
            ParamSpec::new("Address", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv6AddressToStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("String", PStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv6AddressToStringExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("ScopeId", U32),
            ParamSpec::new("String", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv6StringToAddressA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", PCStr),
            ParamSpec::new("Terminator", GuestPtr),
            ParamSpec::new("Address", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIpv6StringToAddressExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", PCStr),
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("ScopeId", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
];
