use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static RTL_2_SIGS: &[HookSignature] = &[
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIsCriticalSectionLocked",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIsCriticalSectionLockedByThread",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlIsNameInExpression",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Expression", UnicodeStringStruct),
            ParamSpec::new("Name", UnicodeStringStruct),
            ParamSpec::new("IgnoreCase", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLeaveCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLengthAce",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Ace", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLengthRequiredSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SubAuthorityCount", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLengthSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SecurityDescriptor", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLengthSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Sid", SidPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLocateExtendedFeature",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("FeatureId", U32),
            ParamSpec::new("Offset", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLocateLegacyContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("Length", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLockHeap",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("HeapHandle", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLookupAtomInAtomTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AtomTable", GuestPtr),
            ParamSpec::new("AtomName", PCWStr),
            ParamSpec::new("Atom", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlLowerChar",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Ch", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlMakeSelfRelativeSD",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AbsoluteSecurityDescriptor", GuestPtr),
            ParamSpec::new("SelfRelativeSecurityDescriptor", GuestPtr),
            ParamSpec::new("BufferLength", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlMoveMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Source", GuestPtr),
            ParamSpec::new("Length", SizeT),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlMultiByteToUnicodeN",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("UnicodeString", GuestPtr),
            ParamSpec::new("MaxBytesInUnicodeString", U32),
            ParamSpec::new("BytesInUnicodeString", GuestPtr),
            ParamSpec::new("MultiByteString", GuestPtr),
            ParamSpec::new("BytesInMultiByteString", U32),
            ParamSpec::new("BytesInUnicodeString2", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlMultiByteToUnicodeSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("BytesInUnicodeString", GuestPtr),
            ParamSpec::new("MultiByteString", GuestPtr),
            ParamSpec::new("BytesInMultiByteString", U32),
            ParamSpec::new("BytesInUnicodeString2", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlNormalizeProcessParams",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ProcessParameters", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlNtPathNameToDosPathName",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("Path", UnicodeStringStruct),
            ParamSpec::new("DosPath", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlNtStatusToDosError",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Status", Hex32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlNtStatusToDosErrorNoTeb",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Status", Hex32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlOemStringToUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DestinationString", GuestPtr),
            ParamSpec::new("SourceString", AnsiStringStruct),
            ParamSpec::new("AllocateDestinationString", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlOemToUnicodeN",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("UnicodeString", GuestPtr),
            ParamSpec::new("MaxBytesInUnicodeString", U32),
            ParamSpec::new("BytesInUnicodeString", GuestPtr),
            ParamSpec::new("OemString", GuestPtr),
            ParamSpec::new("BytesInOemString", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlOpenCurrentUser",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("KeyHandle", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlPinAtomInAtomTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("AtomTable", GuestPtr),
            ParamSpec::new("Atom", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlPrefixString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String1", AnsiStringStruct),
            ParamSpec::new("String2", AnsiStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Rtl continued ──────────────────────────────────────────────────────
    HookSignature {
        module: "ntdll.dll",
        function: "RtlPrefixUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String1", UnicodeStringStruct),
            ParamSpec::new("String2", UnicodeStringStruct),
            ParamSpec::new("CaseInSensitive", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlPublishWnfStateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StateName", GuestPtr),
            ParamSpec::new("ChangeStamp", U32),
            ParamSpec::new("Data", GuestPtr),
            ParamSpec::new("TypeId", GuestPtr),
            ParamSpec::new("ExplicitScope", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryDepthSList",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ListHead", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryEnvironmentVariable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Environment", GuestPtr),
            ParamSpec::new("Name", PCWStr),
            ParamSpec::new("NameLength", U32),
            ParamSpec::with_dir("Value", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryEnvironmentVariable_U",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Environment", GuestPtr),
            ParamSpec::new("Name", UnicodeStringStruct),
            ParamSpec::with_dir("Value", UnicodeStringStruct, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryProcessDebugInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessId", Handle),
            ParamSpec::new("DebugInfoClassMask", U32),
            ParamSpec::new("DebugBuffer", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryRegistryValues",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RelativeTo", U32),
            ParamSpec::new("Path", PCWStr),
            ParamSpec::new("QueryTable", GuestPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("Environment", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryThreadProfiling",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::with_dir("Enabled", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueryWnfStateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StateName", GuestPtr),
            ParamSpec::new("TypeId", GuestPtr),
            ParamSpec::new("ExplicitScope", GuestPtr),
            ParamSpec::with_dir("ChangeStamp", GuestPtr, Out),
            ParamSpec::with_dir("Buffer", GuestPtr, InOut),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlQueueWorkItem",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Function", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("Unknown1", GuestPtr),
            ParamSpec::new("Unknown2", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRaiseException",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ExceptionRecord", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRaiseStatus",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Status", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRandom",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("Seed", GuestPtr, InOut)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlReleasePrivilege",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("PreviousPrivileges", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRemoveVectoredContinueHandler",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handler", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRemoveVectoredExceptionHandler",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handler", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRunDecodeUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Seed", GuestPtr),
            ParamSpec::new("String", UnicodeStringStruct),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlRunEncodeUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Seed", GuestPtr),
            ParamSpec::new("String", UnicodeStringStruct),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSelfRelativeToAbsoluteSD",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SelfRelativeSecurityDescriptor", GuestPtr),
            ParamSpec::new("AbsoluteSecurityDescriptor", GuestPtr),
            ParamSpec::new("AbsoluteSecurityDescriptorSize", GuestPtr),
            ParamSpec::new("Dacl", GuestPtr),
            ParamSpec::new("DaclSize", GuestPtr),
            ParamSpec::new("Sacl", GuestPtr),
            ParamSpec::new("SaclSize", GuestPtr),
            ParamSpec::new("Owner", GuestPtr),
            ParamSpec::new("OwnerSize", GuestPtr),
            ParamSpec::new("PrimaryGroup", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetCriticalSectionSpinCount",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CriticalSection", GuestPtr),
            ParamSpec::new("SpinCount", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetCurrentDirectory_U",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Path", UnicodeStringStruct)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetDaclSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("DaclPresent", Bool32),
            ParamSpec::new("Dacl", GuestPtr),
            ParamSpec::new("DaclDefaulted", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetEnvironmentVariable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("Environment", GuestPtr, InOut),
            ParamSpec::new("Name", PCWStr),
            ParamSpec::new("Value", PCWStr),
            ParamSpec::new("Unknown", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetEnvironmentVariable_U",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("Environment", GuestPtr, InOut),
            ParamSpec::new("Name", UnicodeStringStruct),
            ParamSpec::new("Value", UnicodeStringStruct),
            ParamSpec::new("Unknown", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetExtendedFeaturesMask",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("FeatureMask", U64),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetGroupSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("Group", SidPtr),
            ParamSpec::new("GroupDefaulted", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetOwnerSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("Owner", SidPtr),
            ParamSpec::new("OwnerDefaulted", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TimerQueue", Handle),
            ParamSpec::new("Timer", Handle),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("DueTime", U32),
            ParamSpec::new("Period", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetUnhandledExceptionFilter",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Filter", FunctionPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetUserFlagsHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("UserFlags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSetUserValueHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("BaseAddress", GuestPtr),
            ParamSpec::new("UserValue", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSizeHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("BaseAddress", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSleepConditionVariableCS",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ConditionVariable", GuestPtr),
            ParamSpec::new("CriticalSection", GuestPtr),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSleepConditionVariableSRW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ConditionVariable", GuestPtr),
            ParamSpec::new("SRWLock", GuestPtr),
            ParamSpec::new("Timeout", GuestPtr),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlStringFromGUID",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Guid", GuidPtr),
            ParamSpec::with_dir("GuidString", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSubAuthorityCountSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Sid", SidPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSubAuthoritySid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Sid", SidPtr),
            ParamSpec::new("SubAuthority", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlSubscribeWnfStateChangeNotification",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("Subscription", GuestPtr, Out),
            ParamSpec::new("StateName", GuestPtr),
            ParamSpec::new("ChangeStamp", U32),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("CallbackContext", GuestPtr),
            ParamSpec::new("SerialNumber", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlTryEnterCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CriticalSection", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnhandledExceptionFilter2",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ExceptionInfo", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeStringToAnsiString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", GuestPtr, Out),
            ParamSpec::new("SourceString", UnicodeStringStruct),
            ParamSpec::new("AllocateDestinationString", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeStringToInteger",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("String", UnicodeStringStruct),
            ParamSpec::new("Base", U32),
            ParamSpec::with_dir("Value", GuestPtr, Out),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeStringToOemString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", GuestPtr, Out),
            ParamSpec::new("SourceString", UnicodeStringStruct),
            ParamSpec::new("AllocateDestinationString", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeToMultiByteN",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("MultiByteString", GuestPtr, Out),
            ParamSpec::new("MaxBytesInMultiByteString", U32),
            ParamSpec::with_dir("BytesInMultiByteString", GuestPtr, Out),
            ParamSpec::new("UnicodeString", GuestPtr),
            ParamSpec::new("BytesInUnicodeString", U32),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeToMultiByteSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("BytesInMultiByteString", GuestPtr, Out),
            ParamSpec::new("UnicodeString", GuestPtr),
            ParamSpec::new("BytesInUnicodeString", U32),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeToOemN",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("OemString", GuestPtr, Out),
            ParamSpec::new("MaxBytesInOemString", U32),
            ParamSpec::with_dir("BytesInOemString", GuestPtr, Out),
            ParamSpec::new("UnicodeString", GuestPtr),
            ParamSpec::new("BytesInUnicodeString", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnicodeToUTF8N",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("UTF8String", GuestPtr, Out),
            ParamSpec::new("MaxBytesInUTF8String", U32),
            ParamSpec::with_dir("BytesInUTF8String", GuestPtr, Out),
            ParamSpec::new("UnicodeString", GuestPtr),
            ParamSpec::new("BytesInUnicodeString", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnlockHeap",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("HeapHandle", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUnsubscribeWnfStateChangeNotification",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Subscription", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUpcaseUnicodeChar",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SourceCharacter", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUpcaseUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("DestinationString", GuestPtr, Out),
            ParamSpec::new("SourceString", UnicodeStringStruct),
            ParamSpec::new("AllocateDestinationString", Bool32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUpperChar",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Character", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUpperUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("DestinationString", UnicodeStringStruct)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlUTF8ToUnicodeN",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("UnicodeString", GuestPtr, Out),
            ParamSpec::new("MaxBytesInUnicodeString", U32),
            ParamSpec::with_dir("BytesInUnicodeString", GuestPtr, Out),
            ParamSpec::new("UTF8String", GuestPtr),
            ParamSpec::new("BytesInUTF8String", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlValidAcl",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Acl", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlValidateHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("BaseAddress", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlValidateUnicodeString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Flags", U32),
            ParamSpec::new("String", UnicodeStringStruct),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlValidRelativeSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SecurityDescriptor", GuestPtr),
            ParamSpec::new("SecurityDescriptorLength", U32),
            ParamSpec::new("RequiredInformation", U32),
            ParamSpec::new("Reserved", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlValidSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SecurityDescriptor", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlValidSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Sid", SidPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlVerifyVersionInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("VersionInfo", GuestPtr),
            ParamSpec::new("TypeMask", U32),
            ParamSpec::new("ConditionMask", U64),
            ParamSpec::new("Reserved", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlWakeAllConditionVariable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ConditionVariable", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlWakeConditionVariable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ConditionVariable", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlWalkFrameChain",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("Callers", GuestPtr, Out),
            ParamSpec::new("Count", U32),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlWalkHeap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("Entry", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlWriteRegistryValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RelativeTo", U32),
            ParamSpec::new("Path", PCWStr),
            ParamSpec::new("ValueName", PCWStr),
            ParamSpec::new("ValueType", U32),
            ParamSpec::new("ValueData", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "RtlZeroMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Length", SizeT),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_snprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PStr),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("args", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_snwprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("count", SizeT),
            ParamSpec::new("format", PCWStr),
            ParamSpec::new("args", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "sprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PStr),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("args", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "sscanf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PCStr),
            ParamSpec::new("format", PCStr),
            ParamSpec::new("args", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strcat",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PStr), ParamSpec::new("src", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strchr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strcmp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCStr), ParamSpec::new("s2", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strcpy",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("dest", PStr), ParamSpec::new("src", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strcspn",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCStr), ParamSpec::new("s2", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_strdup",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_strerror",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", GuestPtr),
            ParamSpec::new("errnum", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_stricmp",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCStr), ParamSpec::new("s2", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strlen",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s", PCStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strncat",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PStr),
            ParamSpec::new("src", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strncmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("s1", PCStr),
            ParamSpec::new("s2", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strncpy",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("dest", PStr),
            ParamSpec::new("src", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "_strnicmp",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("s1", PCStr),
            ParamSpec::new("s2", PCStr),
            ParamSpec::new("count", SizeT),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strnlen",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s", PCStr), ParamSpec::new("maxlen", SizeT)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strpbrk",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCStr), ParamSpec::new("s2", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strrchr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strrev",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strset",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strspn",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCStr), ParamSpec::new("s2", PCStr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strstr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("s1", PCStr), ParamSpec::new("s2", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strtol",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("base", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "strtoul",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("str", PCStr),
            ParamSpec::with_dir("endptr", GuestPtr, Out),
            ParamSpec::new("base", I32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "swprintf",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("buffer", PWStr),
            ParamSpec::new("format", PCWStr),
            ParamSpec::new("arg1", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "__toascii",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "tolower",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "toupper",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("c", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpAllocCleanupGroup",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("CleanupGroup", GuestPtr, Out)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpAllocIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("IoReturn", GuestPtr, Out),
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpAllocPool",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("PoolReturn", GuestPtr, Out),
            ParamSpec::new("Reserved", GuestPtr),
            ParamSpec::new("arg3", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpAllocTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("TimerReturn", GuestPtr, Out),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("CallbackEnviron", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpAllocWait",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("WaitReturn", GuestPtr, Out),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("CallbackEnviron", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpAllocWork",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("WorkReturn", GuestPtr, Out),
            ParamSpec::new("Callback", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("CallbackEnviron", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpCallbackMayRunLong",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Instance", GuestPtr)],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpDisassociateCallback",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Instance", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpIsTimerSet",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Timer", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpPostIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Io", GuestPtr),
            ParamSpec::new("NumberOfBytesTransferred", U32),
            ParamSpec::new("IoKey", PointerSizedUInt),
            ParamSpec::new("Overlapped", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpPostWork",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Work", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleaseCleanupGroup",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CleanupGroup", GuestPtr),
            ParamSpec::new("arg2", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleaseCleanupGroupMembers",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CleanupGroup", GuestPtr),
            ParamSpec::new("CancelPendingCallbacks", Bool32),
            ParamSpec::new("CleanupParameter", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleaseIoCompletion",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Io", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleasePool",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Pool", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleaseTimer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Timer", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleaseWait",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Wait", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpReleaseWork",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Work", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpSetTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Timer", GuestPtr),
            ParamSpec::new("DueTime", GuestPtr),
            ParamSpec::new("Period", U32),
            ParamSpec::new("WindowLength", U32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpSetTimerEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Timer", GuestPtr),
            ParamSpec::new("DueTime", GuestPtr),
            ParamSpec::new("Period", U32),
            ParamSpec::new("WindowLength", U32),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpWaitForTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Timer", GuestPtr),
            ParamSpec::new("CancelPendingCallbacks", Bool32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpWaitForWait",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Wait", GuestPtr),
            ParamSpec::new("CancelPendingCallbacks", Bool32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ntdll.dll",
        function: "TpWaitForWork",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Work", GuestPtr),
            ParamSpec::new("CancelPendingCallbacks", Bool32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
];
