//! Full `HookSignature` table for `gdi32.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static GDI32_SIGNATURES: &[HookSignature] = &[
    // ── Bit-Block Transfer ────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "BitBlt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
            ParamSpec::new("hdcSrc", Handle),
            ParamSpec::new("x1", I32),
            ParamSpec::new("y1", I32),
            ParamSpec::new("rop", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Region Operations ─────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CombineRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hrgnDst", Handle),
            ParamSpec::new("hrgnSrc1", Handle),
            ParamSpec::new("hrgnSrc2", Handle),
            ParamSpec::new("iMode", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Metafile ──────────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CopyMetaFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hmf", Handle),
            ParamSpec::new("lpFileName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Bitmap Creation ───────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreateBitmap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nWidth", I32),
            ParamSpec::new("nHeight", I32),
            ParamSpec::new("nPlanes", U32),
            ParamSpec::new("nBitCount", U32),
            ParamSpec::new("lpBits", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateCompatibleBitmap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateDIBSection",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("pbmi", OpaqueStructPtr("BITMAPINFO")),
            ParamSpec::new("iUsage", U32),
            ParamSpec::with_dir("ppvBits", GuestPtr, Out),
            ParamSpec::new("hSection", Handle),
            ParamSpec::new("dwOffset", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateDIBitmap",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("pbmih", GuestPtr),
            ParamSpec::new("fdwInit", U32),
            ParamSpec::new("pjInit", GuestPtr),
            ParamSpec::new("pbmi", OpaqueStructPtr("BITMAPINFO")),
            ParamSpec::new("iUsage", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── DC Creation ───────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreateCompatibleDC",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateDCW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pwszDriver", PCWStr),
            ParamSpec::new("pwszDevice", PCWStr),
            ParamSpec::new("pszPort", GuestPtr),
            ParamSpec::new("pdvm", OpaqueStructPtr("DEVMODE")),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Region Creation ───────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreateEllipticRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("x1", I32),
            ParamSpec::new("y1", I32),
            ParamSpec::new("x2", I32),
            ParamSpec::new("y2", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreatePolygonRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pptl", OpaqueStructPtr("POINT")),
            ParamSpec::new("cPoint", I32),
            ParamSpec::new("iMode", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateRectRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("x1", I32),
            ParamSpec::new("y1", I32),
            ParamSpec::new("x2", I32),
            ParamSpec::new("y2", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateRectRgnIndirect",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lprc", OpaqueStructPtr("RECT"))],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateRoundRectRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("x1", I32),
            ParamSpec::new("y1", I32),
            ParamSpec::new("x2", I32),
            ParamSpec::new("y2", I32),
            ParamSpec::new("w", I32),
            ParamSpec::new("h", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Brush / Pen Creation ──────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreateHatchBrush",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("iHatch", I32), ParamSpec::new("color", U32)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreatePatternBrush",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hbm", Handle)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreatePen",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("iStyle", I32),
            ParamSpec::new("cWidth", I32),
            ParamSpec::new("color", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateSolidBrush",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("color", U32)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Palette ───────────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreatePalette",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("plpal", GuestPtr)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Font Creation ─────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreateFontIndirectW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lplf", OpaqueStructPtr("LOGFONT"))],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateFontW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("cHeight", I32),
            ParamSpec::new("cWidth", I32),
            ParamSpec::new("cEscapement", I32),
            ParamSpec::new("cOrientation", I32),
            ParamSpec::new("cWeight", I32),
            ParamSpec::new("bItalic", U32),
            ParamSpec::new("bUnderline", U32),
            ParamSpec::new("bStrikeOut", U32),
            ParamSpec::new("iCharSet", U32),
            ParamSpec::new("iOutPrecision", U32),
            ParamSpec::new("iClipPrecision", U32),
            ParamSpec::new("iQuality", U32),
            ParamSpec::new("iPitchAndFamily", U32),
            ParamSpec::new("pszFaceName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Coordinate Transforms ─────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "DPtoLP",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), InOut),
            ParamSpec::new("c", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "LPtoDP",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), InOut),
            ParamSpec::new("c", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── DC / Object Cleanup ───────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "DeleteDC",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "DeleteObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ho", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Shape Drawing ─────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "Ellipse",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("left", I32),
            ParamSpec::new("top", I32),
            ParamSpec::new("right", I32),
            ParamSpec::new("bottom", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "Rectangle",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("left", I32),
            ParamSpec::new("top", I32),
            ParamSpec::new("right", I32),
            ParamSpec::new("bottom", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "RoundRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("left", I32),
            ParamSpec::new("top", I32),
            ParamSpec::new("right", I32),
            ParamSpec::new("bottom", I32),
            ParamSpec::new("width", I32),
            ParamSpec::new("height", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Line Drawing ──────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "LineTo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "MoveToEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Polygon / Polyline ────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "Polygon",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("apt", OpaqueStructPtr("POINT")),
            ParamSpec::new("cpt", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "Polyline",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("apt", OpaqueStructPtr("POINT")),
            ParamSpec::new("cpt", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Font Enumeration ──────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "EnumFontFamiliesExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("lpLogfont", OpaqueStructPtr("LOGFONT")),
            ParamSpec::new("lpEnumFunc", FunctionPtr),
            ParamSpec::new("lParam", PointerSizedUInt),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "EnumFontFamiliesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("lpLogfont", PCWStr),
            ParamSpec::new("lpEnumFunc", FunctionPtr),
            ParamSpec::new("lParam", PointerSizedUInt),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Escape ────────────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "Escape",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("iEscape", I32),
            ParamSpec::new("cjIn", I32),
            ParamSpec::new("pvIn", GuestPtr),
            ParamSpec::with_dir("pvOut", GuestPtr, Out),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Clipping ──────────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "ExcludeClipRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("left", I32),
            ParamSpec::new("top", I32),
            ParamSpec::new("right", I32),
            ParamSpec::new("bottom", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "ExtSelectClipRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("hrgn", Handle),
            ParamSpec::new("iMode", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "IntersectClipRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("left", I32),
            ParamSpec::new("top", I32),
            ParamSpec::new("right", I32),
            ParamSpec::new("bottom", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SelectClipRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("hrgn", Handle),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetRectRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hrgn", Handle),
            ParamSpec::new("left", I32),
            ParamSpec::new("top", I32),
            ParamSpec::new("right", I32),
            ParamSpec::new("bottom", I32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Fill / Flood ──────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "ExtFloodFill",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("color", U32),
            ParamSpec::new("iFillType", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "FillRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("hrgn", Handle),
            ParamSpec::new("hbr", Handle),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "FrameRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("hrgn", Handle),
            ParamSpec::new("hbr", Handle),
            ParamSpec::new("w", I32),
            ParamSpec::new("h", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Text Drawing ──────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "ExtTextOutW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("fuOptions", U32),
            ParamSpec::new("lprc", OpaqueStructPtr("RECT")),
            ParamSpec::new("lpString", PCWStr),
            ParamSpec::new("c", U32),
            ParamSpec::new("lpDx", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "TextOutW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("lpString", PCWStr),
            ParamSpec::new("c", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── DC Attribute Getters ──────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GetBkColor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetTextColor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetDeviceCaps",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("iCapability", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetLayout",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetMapMode",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetObjectType",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("h", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetStockObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("i", I32)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetPixel",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Object Info ───────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GetObjectW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("h", Handle),
            ParamSpec::new("c", I32),
            ParamSpec::with_dir("pv", GuestPtr, Out),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Bounds / Clip Query ───────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GetBoundsRect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lprc", OpaqueStructPtr("RECT"), Out),
            ParamSpec::new("flags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetClipBox",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lprc", OpaqueStructPtr("RECT"), Out),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetRgnBox",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hrgn", Handle),
            ParamSpec::with_dir("lprc", OpaqueStructPtr("RECT"), Out),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Palette Functions ─────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GetNearestPaletteIndex",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hpal", Handle), ParamSpec::new("color", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetPaletteEntries",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hpal", Handle),
            ParamSpec::new("iStartIndex", U32),
            ParamSpec::new("cEntries", U32),
            ParamSpec::with_dir("lppe", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetSystemPaletteEntries",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("iStartIndex", U32),
            ParamSpec::new("cEntries", U32),
            ParamSpec::with_dir("lppe", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "RealizePalette",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetPaletteEntries",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hpal", Handle),
            ParamSpec::new("iStartIndex", U32),
            ParamSpec::new("cEntries", U32),
            ParamSpec::new("lppe", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Text Metrics / Charset ────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GetTextCharsetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lpSig", GuestPtr, Out),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetTextExtentPoint32W",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("lpString", PCWStr),
            ParamSpec::new("c", I32),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetTextFaceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("c", I32),
            ParamSpec::with_dir("lpFaceName", PWStr, Out),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetTextMetricsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lptm", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Viewport / Window Extents & Origins ───────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GetViewportExtEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetViewportOrgEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetWindowExtEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetWindowOrgEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Region Offset / Query ─────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "OffsetRgn",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hrgn", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "PtInRegion",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hrgn", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "PtVisible",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "RectVisible",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("lprc", OpaqueStructPtr("RECT")),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── DC State Save / Restore ───────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "SaveDC",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "RestoreDC",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("iSavedDC", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Viewport / Window Offset ──────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "OffsetViewportOrgEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "OffsetWindowOrgEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Pattern Block Transfer ────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "PatBlt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("cx", I32),
            ParamSpec::new("cy", I32),
            ParamSpec::new("rop", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Stretch BitBlt ────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "StretchBlt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdcDst", Handle),
            ParamSpec::new("xDst", I32),
            ParamSpec::new("yDst", I32),
            ParamSpec::new("wDst", I32),
            ParamSpec::new("hDst", I32),
            ParamSpec::new("hdcSrc", Handle),
            ParamSpec::new("xSrc", I32),
            ParamSpec::new("ySrc", I32),
            ParamSpec::new("wSrc", I32),
            ParamSpec::new("hSrc", I32),
            ParamSpec::new("rop", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Select Object ─────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "SelectObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("h", Handle)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SelectPalette",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("hpal", Handle),
            ParamSpec::new("bForceBkgd", Bool32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── DC Attribute Setters ──────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "SetBkColor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("color", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetBkMode",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("iMode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetLayout",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("dwLayout", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetMapMode",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("iMode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetPolyFillMode",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("iMode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetROP2",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("iMode", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetTextAlign",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("fMode", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetTextColor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle), ParamSpec::new("color", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Pixel Setters ─────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "SetPixel",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("color", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetPixelV",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::new("color", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── DIB Color Table ───────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "SetDIBColorTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("iStart", U32),
            ParamSpec::new("cEntries", U32),
            ParamSpec::new("prgbq", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Viewport / Window Extent & Origin Setters ─────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "ScaleViewportExtEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("xn", I32),
            ParamSpec::new("xd", I32),
            ParamSpec::new("yn", I32),
            ParamSpec::new("yd", I32),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "ScaleWindowExtEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("xn", I32),
            ParamSpec::new("xd", I32),
            ParamSpec::new("yn", I32),
            ParamSpec::new("yd", I32),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetViewportExtEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetViewportOrgEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetWindowExtEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lpSize", OpaqueStructPtr("SIZE"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetWindowOrgEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("x", I32),
            ParamSpec::new("y", I32),
            ParamSpec::with_dir("lppt", OpaqueStructPtr("POINT"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Enhanced Metafile ─────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CloseEnhMetaFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateEnhMetaFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdcRef", Handle),
            ParamSpec::new("lpFilename", PCWStr),
            ParamSpec::new("lpRect", OpaqueStructPtr("RECT")),
            ParamSpec::new("lpDescription", PCWStr),
            ParamSpec::new("lpCustom", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "DeleteEnhMetaFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hemf", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Legacy Metafile ───────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CloseMetaFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hdc", Handle)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "CreateMetaFileA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszFile", PCStr)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "DeleteMetaFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hmf", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "GetMetaFileBitsEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hmf", Handle),
            ParamSpec::new("cbBuffer", U32),
            ParamSpec::with_dir("lpvData", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "gdi32.dll",
        function: "SetMetaFileBitsEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("cbBuffer", U32),
            ParamSpec::new("lpvData", GuestPtr),
            ParamSpec::new("fMode", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Information Context ───────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "CreateICW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszDriver", PCWStr),
            ParamSpec::new("pszDevice", PCWStr),
            ParamSpec::new("pszPort", PCWStr),
            ParamSpec::new("pdvm", OpaqueStructPtr("DEVMODE")),
            ParamSpec::new("lpCustom", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Gradient Fill ─────────────────────────────────────────────────────
    HookSignature {
        module: "gdi32.dll",
        function: "GdiGradientFill",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hdc", Handle),
            ParamSpec::new("pVertex", GuestPtr),
            ParamSpec::new("nVertex", U32),
            ParamSpec::new("pMesh", GuestPtr),
            ParamSpec::new("nCount", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
