use crate::hooks::base::HookLibrary;
use crate::hooks::registry::HookRegistry;
use crate::hooks::stub::stdcall_definitions;

const EXPORTS: &[(&str, usize)] = &[
    ("BitBlt", 9),
    ("CombineRgn", 4),
    ("CopyMetaFileW", 2),
    ("CreateBitmap", 5),
    ("CreateCompatibleBitmap", 3),
    ("CreateCompatibleDC", 1),
    ("CreateDCW", 4),
    ("CreateDIBSection", 6),
    ("CreateDIBitmap", 6),
    ("CreateEllipticRgn", 4),
    ("CreateFontIndirectW", 1),
    ("CreateHatchBrush", 2),
    ("CreatePalette", 1),
    ("CreatePatternBrush", 1),
    ("CreatePen", 3),
    ("CreatePolygonRgn", 3),
    ("CreateRectRgn", 4),
    ("CreateRectRgnIndirect", 1),
    ("CreateRoundRectRgn", 6),
    ("CreateSolidBrush", 1),
    ("DPtoLP", 3),
    ("DeleteDC", 1),
    ("DeleteObject", 1),
    ("Ellipse", 5),
    ("EnumFontFamiliesExW", 5),
    ("EnumFontFamiliesW", 4),
    ("Escape", 5),
    ("ExcludeClipRect", 5),
    ("ExtFloodFill", 5),
    ("ExtSelectClipRgn", 3),
    ("ExtTextOutW", 8),
    ("FillRgn", 3),
    ("FrameRgn", 5),
    ("GetBkColor", 1),
    ("GetBoundsRect", 3),
    ("GetClipBox", 2),
    ("GetDeviceCaps", 2),
    ("GetLayout", 1),
    ("GetMapMode", 1),
    ("GetNearestPaletteIndex", 2),
    ("GetObjectType", 1),
    ("GetObjectW", 3),
    ("GetPaletteEntries", 4),
    ("GetPixel", 3),
    ("GetRgnBox", 2),
    ("GetStockObject", 1),
    ("GetSystemPaletteEntries", 4),
    ("GetTextCharsetInfo", 3),
    ("GetTextColor", 1),
    ("GetTextExtentPoint32W", 4),
    ("GetTextFaceW", 3),
    ("GetTextMetricsW", 2),
    ("GetViewportExtEx", 2),
    ("GetViewportOrgEx", 2),
    ("GetWindowExtEx", 2),
    ("GetWindowOrgEx", 2),
    ("IntersectClipRect", 5),
    ("LPtoDP", 3),
    ("LineTo", 3),
    ("MoveToEx", 4),
    ("OffsetRgn", 3),
    ("OffsetViewportOrgEx", 4),
    ("OffsetWindowOrgEx", 4),
    ("PatBlt", 6),
    ("Polygon", 3),
    ("Polyline", 3),
    ("PtInRegion", 3),
    ("PtVisible", 3),
    ("RealizePalette", 1),
    ("RectVisible", 2),
    ("Rectangle", 5),
    ("RestoreDC", 2),
    ("RoundRect", 7),
    ("SaveDC", 1),
    ("ScaleViewportExtEx", 6),
    ("ScaleWindowExtEx", 6),
    ("SelectClipRgn", 2),
    ("SelectObject", 2),
    ("SelectPalette", 3),
    ("SetBkColor", 2),
    ("SetBkMode", 2),
    ("SetDIBColorTable", 4),
    ("SetLayout", 2),
    ("SetMapMode", 2),
    ("SetPaletteEntries", 4),
    ("SetPixel", 4),
    ("SetPixelV", 4),
    ("SetPolyFillMode", 2),
    ("SetROP2", 2),
    ("SetRectRgn", 5),
    ("SetTextAlign", 2),
    ("SetTextColor", 2),
    ("SetViewportExtEx", 4),
    ("SetViewportOrgEx", 4),
    ("SetWindowExtEx", 4),
    ("SetWindowOrgEx", 4),
    ("StretchBlt", 11),
    ("TextOutW", 5),
];

/// Collects the generated hook definitions for this DLL family.
#[derive(Debug, Default, Clone, Copy)]
pub struct Gdi32HookLibrary;

impl HookLibrary for Gdi32HookLibrary {
    fn collect(&self) -> Vec<crate::hooks::base::HookDefinition> {
        stdcall_definitions("gdi32.dll", EXPORTS)
    }
}

/// Registers the generated hook definitions for this DLL family.
pub fn register_gdi32_hooks(registry: &mut HookRegistry) {
    registry.register_library(&Gdi32HookLibrary);
}
