//! Full `HookSignature` table for `shell32.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static SHELL32_SIGNATURES: &[HookSignature] = &[
    // ── Rust-backed hooks ─────────────────────────────────────────────────
    HookSignature {
        module: "shell32.dll",
        function: "IsUserAnAdmin",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "CommandLineToArgvW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpCmdLine", PCWStr),
            ParamSpec::with_dir("pNumArgs", GuestPtrTo(ParamTypeDiscriminant::I32), Out),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "ShellExecuteW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwnd", Handle),
            ParamSpec::new("lpOperation", PCWStr),
            ParamSpec::new("lpFile", PCWStr),
            ParamSpec::new("lpParameters", PCWStr),
            ParamSpec::new("lpDirectory", PCWStr),
            ParamSpec::new("nShowCmd", I32),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "ShellExecuteA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwnd", Handle),
            ParamSpec::new("lpOperation", PCStr),
            ParamSpec::new("lpFile", PCStr),
            ParamSpec::new("lpParameters", PCStr),
            ParamSpec::new("lpDirectory", PCStr),
            ParamSpec::new("nShowCmd", I32),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "ShellExecuteExW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new(
            "pExecInfo",
            OpaqueStructPtr("SHELLEXECUTEINFOW"),
        )],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHBrowseForFolderA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpbi", OpaqueStructPtr("BROWSEINFOA"))],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetFolderPathW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwnd", Handle),
            ParamSpec::new("csidl", I32),
            ParamSpec::new("hToken", Handle),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("pszPath", PWStr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetKnownFolderPath",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rfid", GuidPtr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("hToken", Handle),
            ParamSpec::with_dir("ppszPath", GuestPtrTo(ParamTypeDiscriminant::GuestPtr), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetImageList",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("iImageList", I32),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::with_dir("ppvObj", GuestPtrTo(ParamTypeDiscriminant::GuestPtr), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── IMalloc vtable methods ────────────────────────────────────────────
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_QueryInterface",
        abi: LogicalAbi::ComMethod,
        params: &[
            ParamSpec::new("this", GuestPtr),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::with_dir("ppvObj", GuestPtrTo(ParamTypeDiscriminant::GuestPtr), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_AddRef",
        abi: LogicalAbi::ComMethod,
        params: &[ParamSpec::new("this", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_Release",
        abi: LogicalAbi::ComMethod,
        params: &[ParamSpec::new("this", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_Alloc",
        abi: LogicalAbi::ComMethod,
        params: &[
            ParamSpec::new("this", GuestPtr),
            ParamSpec::new("cb", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_Realloc",
        abi: LogicalAbi::ComMethod,
        params: &[
            ParamSpec::new("this", GuestPtr),
            ParamSpec::new("pv", GuestPtr),
            ParamSpec::new("cb", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_Free",
        abi: LogicalAbi::ComMethod,
        params: &[
            ParamSpec::new("this", GuestPtr),
            ParamSpec::new("pv", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_GetSize",
        abi: LogicalAbi::ComMethod,
        params: &[
            ParamSpec::new("this", GuestPtr),
            ParamSpec::new("pv", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_DidAlloc",
        abi: LogicalAbi::ComMethod,
        params: &[
            ParamSpec::new("this", GuestPtr),
            ParamSpec::new("pv", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "IMalloc_HeapMinimize",
        abi: LogicalAbi::ComMethod,
        params: &[ParamSpec::new("this", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Stub exports ──────────────────────────────────────────────────────
    HookSignature {
        module: "shell32.dll",
        function: "DragFinish",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hDrop", Handle)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "DragQueryFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDrop", Handle),
            ParamSpec::new("iFile", U32),
            ParamSpec::new("lpszFile", PWStr),
            ParamSpec::new("cch", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHAppBarMessage",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwMessage", U32),
            ParamSpec::new("pData", OpaqueStructPtr("APPBARDATA")),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHBrowseForFolderW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpbi", OpaqueStructPtr("BROWSEINFOW"))],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetDesktopFolder",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "ppshf",
            GuestPtrTo(ParamTypeDiscriminant::GuestPtr),
            Out,
        )],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetFileInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPath", PCWStr),
            ParamSpec::new("dwFileAttributes", U32),
            ParamSpec::new("psfi", OpaqueStructPtr("SHFILEINFOW")),
            ParamSpec::new("cbFileInfo", U32),
            ParamSpec::new("uFlags", U32),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetMalloc",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "ppMalloc",
            GuestPtrTo(ParamTypeDiscriminant::GuestPtr),
            Out,
        )],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetPathFromIDListW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pidl", GuestPtr),
            ParamSpec::new("pszPath", PWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetSpecialFolderLocation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwnd", Handle),
            ParamSpec::new("csidl", I32),
            ParamSpec::with_dir("ppidl", GuestPtrTo(ParamTypeDiscriminant::GuestPtr), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "ordinal_165",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("arg1", GuestPtr),
            ParamSpec::new("arg2", GuestPtr),
            ParamSpec::new("arg3", U32),
            ParamSpec::new("arg4", GuestPtr),
            ParamSpec::new("arg5", U32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHAddToRecentDocs",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("uFlags", U32),
            ParamSpec::new("pv", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHCreateItemFromParsingName",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPath", PCWStr),
            ParamSpec::new("pbc", GuestPtr),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::with_dir("ppv", GuestPtrTo(ParamTypeDiscriminant::GuestPtr), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHCreateItemInKnownFolder",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rfid", GuidPtr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("pszItem", PCWStr),
            ParamSpec::new("riid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "ShellAboutW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("szApp", PCWStr),
            ParamSpec::new("szOtherStuff", PCWStr),
            ParamSpec::new("hIcon", Handle),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shell32.dll",
        function: "SHGetSpecialFolderPathW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwnd", Handle),
            ParamSpec::new("pszPath", PWStr),
            ParamSpec::new("csidl", I32),
            ParamSpec::new("fCreate", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
