//! Full `HookSignature` table for `shlwapi.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(crate) static SHLWAPI_SIGNATURES: &[HookSignature] = &[
    // ── Path manipulation ─────────────────────────────────────────────────
    HookSignature {
        module: "shlwapi.dll",
        function: "PathFileExistsW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathAppendW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszPath", PWStr),
            ParamSpec::new("pszMore", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathAddBackslashW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathCombineW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszDest", PWStr),
            ParamSpec::new("pszDir", PCWStr),
            ParamSpec::new("pszFile", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathFindFileNameW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathFindExtensionW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PCWStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathIsUNCW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathRemoveFileSpecW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathStripToRootW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathMatchSpecA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszFile", PCStr),
            ParamSpec::new("pszSpec", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "PathIsFileSpecW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pszPath", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── String comparison / search ────────────────────────────────────────
    HookSignature {
        module: "shlwapi.dll",
        function: "StrCmpIW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("psz1", PCWStr),
            ParamSpec::new("psz2", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "StrCmpNIW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("psz1", PCWStr),
            ParamSpec::new("psz2", PCWStr),
            ParamSpec::new("nChar", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "StrStrIW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszFirst", PCWStr),
            ParamSpec::new("pszSrch", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "StrStrIA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszFirst", PCStr),
            ParamSpec::new("pszSrch", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "StrRChrW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszStart", PCWStr),
            ParamSpec::new("pszEnd", PCWStr),
            ParamSpec::new("wMatch", U16),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "StrTrimA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("psz", PStr),
            ParamSpec::new("pszTrimChars", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "HashData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pbData", Buffer { len_param: 1 }),
            ParamSpec::new("cbData", U32),
            ParamSpec::new("pbHash", OutBuffer { len_param: 3 }),
            ParamSpec::new("cbHash", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "StrFormatKBSizeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("qdw", I64),
            ParamSpec::new("pszBuf", PWStr),
            ParamSpec::new("cchBuf", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "SHStrDupW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszSource", PCWStr),
            ParamSpec::new("ppwsz", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Registry helpers ──────────────────────────────────────────────────
    HookSignature {
        module: "shlwapi.dll",
        function: "SHGetValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hkey", Handle),
            ParamSpec::new("pszSubKey", PCWStr),
            ParamSpec::new("pszValue", PCWStr),
            ParamSpec::new("pdwType", GuestPtr),
            ParamSpec::new("pvData", GuestPtr),
            ParamSpec::new("pcbData", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "SHGetValueA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hkey", Handle),
            ParamSpec::new("pszSubKey", PCStr),
            ParamSpec::new("pszValue", PCStr),
            ParamSpec::new("pdwType", GuestPtr),
            ParamSpec::new("pvData", GuestPtr),
            ParamSpec::new("pcbData", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "SHSetValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hkey", Handle),
            ParamSpec::new("pszSubKey", PCWStr),
            ParamSpec::new("pszValue", PCWStr),
            ParamSpec::new("dwType", U32),
            ParamSpec::new("pvData", GuestPtr),
            ParamSpec::new("cbData", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "SHSetValueA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hkey", Handle),
            ParamSpec::new("pszSubKey", PCStr),
            ParamSpec::new("pszValue", PCStr),
            ParamSpec::new("dwType", U32),
            ParamSpec::new("pvData", GuestPtr),
            ParamSpec::new("cbData", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Stream helpers ────────────────────────────────────────────────────
    HookSignature {
        module: "shlwapi.dll",
        function: "SHCreateStreamOnFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszFile", PCWStr),
            ParamSpec::new("grfMode", U32),
            ParamSpec::new("ppstm", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "SHCreateStreamOnFileEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszFile", PCWStr),
            ParamSpec::new("grfMode", U32),
            ParamSpec::new("dwAttributes", U32),
            ParamSpec::new("fCreate", Bool32),
            ParamSpec::new("pstmTemplate", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Ordinal exports ───────────────────────────────────────────────────
    HookSignature {
        module: "shlwapi.dll",
        function: "ordinal_12",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("arg1", GuestPtr),
            ParamSpec::new("arg2", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "shlwapi.dll",
        function: "ordinal_158",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("arg1", GuestPtr),
            ParamSpec::new("arg2", GuestPtr),
            ParamSpec::new("arg3", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
];
