//! Full `HookSignature` table for `wtsapi32.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static WTSAPI32_SIGNATURES: &[HookSignature] = &[
    // ── Server handle management ──────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSOpenServerA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pServerName", PCStr)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSOpenServerW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pServerName", PCWStr)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSCloseServer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hServer", Handle)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Session enumeration ───────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSEnumerateSessionsA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("Version", U32),
            ParamSpec::new("ppSessionInfo", GuestPtr),
            ParamSpec::new("pCount", GuestPtr),
            ParamSpec::new("arg6", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSEnumerateSessionsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("Version", U32),
            ParamSpec::new("ppSessionInfo", GuestPtr),
            ParamSpec::new("pCount", GuestPtr),
            ParamSpec::new("arg6", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Session information ───────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSQuerySessionInformationA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("WTSInfoClass", U32),
            ParamSpec::new("ppBuffer", GuestPtr),
            ParamSpec::new("pBytesReturned", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSQuerySessionInformationW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("WTSInfoClass", U32),
            ParamSpec::new("ppBuffer", GuestPtr),
            ParamSpec::new("pBytesReturned", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Memory management ─────────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSFreeMemory",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pMemory", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSFreeMemoryExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pMemory", GuestPtr),
            ParamSpec::new("uSize", U32),
            ParamSpec::new("Type", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSFreeMemoryExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pMemory", GuestPtr),
            ParamSpec::new("uSize", U32),
            ParamSpec::new("Type", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Token / notification ──────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSQueryUserToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("phToken", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSRegisterSessionNotification",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hWnd", Handle),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSUnRegisterSessionNotification",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hWnd", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Messaging ─────────────────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSSendMessageA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("pTitle", PCStr),
            ParamSpec::new("TitleLength", U32),
            ParamSpec::new("pMessage", PCStr),
            ParamSpec::new("MessageLength", U32),
            ParamSpec::new("Style", U32),
            ParamSpec::new("Timeout", U32),
            ParamSpec::new("pResponse", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSSendMessageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("pTitle", PCWStr),
            ParamSpec::new("TitleLength", U32),
            ParamSpec::new("pMessage", PCWStr),
            ParamSpec::new("MessageLength", U32),
            ParamSpec::new("Style", U32),
            ParamSpec::new("Timeout", U32),
            ParamSpec::new("pResponse", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Session control ───────────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSDisconnectSession",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("bWait", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSLogoffSession",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("SessionId", U32),
            ParamSpec::new("bWait", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Process enumeration ───────────────────────────────────────────────
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSEnumerateProcessesA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("Version", U32),
            ParamSpec::new("ppProcessInfo", GuestPtr),
            ParamSpec::new("pCount", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSEnumerateProcessesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("Version", U32),
            ParamSpec::new("ppProcessInfo", GuestPtr),
            ParamSpec::new("pCount", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSEnumerateProcessesExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("Version", U32),
            ParamSpec::new("ppProcessInfo", GuestPtr),
            ParamSpec::new("pCount", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wtsapi32.dll",
        function: "WTSEnumerateProcessesExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServer", Handle),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("Version", U32),
            ParamSpec::new("ppProcessInfo", GuestPtr),
            ParamSpec::new("pCount", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
