use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static KERNEL32_SIGS_4: &[HookSignature] = &[
    HookSignature {
        module: "kernel32.dll",
        function: "RtlUnwind",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TargetFrame", GuestPtr),
            ParamSpec::new("TargetIp", GuestPtr),
            ParamSpec::new("ExceptionRecord", GuestPtr),
            ParamSpec::new("ReturnValue", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Batch 5: final 40 kernel32.dll functions ──────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "RtlUnwindEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TargetFrame", GuestPtr),
            ParamSpec::new("TargetIp", GuestPtr),
            ParamSpec::new("ExceptionRecord", GuestPtr),
            ParamSpec::new("ReturnValue", GuestPtr),
            ParamSpec::new("ContextRecord", GuestPtr),
            ParamSpec::new("HistoryTable", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RtlVirtualUnwind",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HandlerType", U32),
            ParamSpec::new("ImageBase", PointerSizedUInt),
            ParamSpec::new("ControlPc", PointerSizedUInt),
            ParamSpec::new("FunctionEntry", GuestPtr),
            ParamSpec::new("ContextRecord", GuestPtr),
            ParamSpec::with_dir("HandlerData", GuestPtr, Out),
            ParamSpec::with_dir("EstablisherFrame", GuestPtr, Out),
            ParamSpec::new("ContextPointers", GuestPtr),
        ],
        ret: ReturnSpec::NtStatus,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SearchPathW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpPath", PCWStr),
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::new("lpExtension", PCWStr),
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::with_dir("lpFilePart", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetConsoleCtrlHandler",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HandlerRoutine", FunctionPtr),
            ParamSpec::new("Add", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetDllDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpPathName", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetErrorMode",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("uMode", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetFileAttributesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::new("dwFileAttributes", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetFileAttributesA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCStr),
            ParamSpec::new("dwFileAttributes", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetHandleCount",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("uNumber", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetNamedPipeHandleState",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hNamedPipe", Handle),
            ParamSpec::new("lpMode", GuestPtr),
            ParamSpec::new("lpMaxCollectionCount", GuestPtr),
            ParamSpec::new("lpCollectDataTimeout", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetPriorityClass",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("dwPriorityClass", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetProcessAffinityMask",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("dwProcessAffinityMask", PointerSizedUInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetProcessWorkingSetSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("dwMinimumWorkingSetSize", SizeT),
            ParamSpec::new("dwMaximumWorkingSetSize", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetThreadAffinityMask",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::new("dwThreadAffinityMask", PointerSizedUInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetThreadContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::new("lpContext", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetThreadPriority",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::new("nPriority", I32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetWaitableTimer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hTimer", Handle),
            ParamSpec::new("lpDueTime", GuestPtr),
            ParamSpec::new("lPeriod", I32),
            ParamSpec::new("pfnCompletionRoutine", FunctionPtr),
            ParamSpec::new("lpArgToCompletionRoutine", GuestPtr),
            ParamSpec::new("fResume", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SignalObjectAndWait",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hObjectToSignal", Handle),
            ParamSpec::new("hObjectToWaitOn", Handle),
            ParamSpec::new("dwMilliseconds", U32),
            ParamSpec::new("bAlertable", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SizeofResource",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("hResInfo", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SleepConditionVariableCS",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ConditionVariable", GuestPtr),
            ParamSpec::new("CriticalSection", GuestPtr),
            ParamSpec::new("dwMilliseconds", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SleepConditionVariableSRW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ConditionVariable", GuestPtr),
            ParamSpec::new("SRWLock", GuestPtr),
            ParamSpec::new("dwMilliseconds", U32),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SwitchToThread",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SystemTimeToFileTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemTime", SystemTimePtr),
            ParamSpec::with_dir("lpFileTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SystemTimeToTzSpecificLocalTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpTimeZoneInformation", GuestPtr),
            ParamSpec::new("lpUniversalTime", SystemTimePtr),
            ParamSpec::with_dir("lpLocalTime", SystemTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "TryEnterCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpCriticalSection", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UnhandledExceptionFilter",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ExceptionInfo", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UnlockFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("dwFileOffsetLow", U32),
            ParamSpec::new("dwFileOffsetHigh", U32),
            ParamSpec::new("nNumberOfBytesToUnlockLow", U32),
            ParamSpec::new("nNumberOfBytesToUnlockHigh", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UnregisterApplicationRecoveryCallback",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UnregisterApplicationRestart",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UnregisterWaitEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("WaitHandle", Handle),
            ParamSpec::new("CompletionEvent", Handle),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UpdateProcThreadAttribute",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAttributeList", GuestPtr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("Attribute", PointerSizedUInt),
            ParamSpec::new("lpValue", GuestPtr),
            ParamSpec::new("cbSize", SizeT),
            ParamSpec::new("lpPreviousValue", GuestPtr),
            ParamSpec::with_dir("lpReturnSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VerifyVersionInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpVersionInformation", GuestPtr),
            ParamSpec::new("dwTypeMask", U32),
            ParamSpec::new("dwlConditionMaskLow", U32),
            ParamSpec::new("dwlConditionMaskHigh", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VerLanguageNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("wLang", U32),
            ParamSpec::new("szLang", PWStr),
            ParamSpec::new("cchLang", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitForDebugEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpDebugEvent", GuestPtr, Out),
            ParamSpec::new("dwMilliseconds", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitNamedPipeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNamedPipeName", PCWStr),
            ParamSpec::new("nTimeOut", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitOnAddress",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Address", GuestPtr),
            ParamSpec::new("CompareAddress", GuestPtr),
            ParamSpec::new("AddressSize", SizeT),
            ParamSpec::new("dwMilliseconds", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WakeAllConditionVariable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ConditionVariable", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WakeByAddressAll",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Address", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WakeByAddressSingle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Address", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WakeConditionVariable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ConditionVariable", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WritePrivateProfileStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAppName", PCWStr),
            ParamSpec::new("lpKeyName", PCWStr),
            ParamSpec::new("lpString", PCWStr),
            ParamSpec::new("lpFileName", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WritePrivateProfileStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAppName", PCStr),
            ParamSpec::new("lpKeyName", PCStr),
            ParamSpec::new("lpString", PCStr),
            ParamSpec::new("lpFileName", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
