use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static KERNEL32_SIGS_1: &[HookSignature] = &[
    // ── File I/O ──────────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "CreateFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("dwShareMode", Hex32),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
            ParamSpec::new("dwCreationDisposition", U32),
            ParamSpec::new("dwFlagsAndAttributes", Hex32),
            ParamSpec::new("hTemplateFile", Handle),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateFileA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("dwShareMode", Hex32),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
            ParamSpec::new("dwCreationDisposition", U32),
            ParamSpec::new("dwFlagsAndAttributes", Hex32),
            ParamSpec::new("hTemplateFile", Handle),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReadFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpBuffer", OutBuffer { len_param: 2 }),
            ParamSpec::new("nNumberOfBytesToRead", U32),
            ParamSpec::with_dir(
                "lpNumberOfBytesRead",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
            ParamSpec::new("lpOverlapped", OverlappedPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WriteFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpBuffer", Buffer { len_param: 2 }),
            ParamSpec::new("nNumberOfBytesToWrite", U32),
            ParamSpec::with_dir(
                "lpNumberOfBytesWritten",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
            ParamSpec::new("lpOverlapped", OverlappedPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CloseHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hObject", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileType",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hFile", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::with_dir("lpFileSizeHigh", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileSizeEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::with_dir("lpFileSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetFilePointer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lDistanceToMove", I32),
            ParamSpec::with_dir("lpDistanceToMoveHigh", GuestPtr, InOut),
            ParamSpec::new("dwMoveMethod", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetFilePointerEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("liDistanceToMove", I64),
            ParamSpec::with_dir("lpNewFilePointer", GuestPtr, Out),
            ParamSpec::new("dwMoveMethod", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlushFileBuffers",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hFile", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetEndOfFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hFile", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateFileMappingW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpFileMappingAttributes", SecurityAttributesPtr),
            ParamSpec::new("flProtect", Hex32),
            ParamSpec::new("dwMaximumSizeHigh", U32),
            ParamSpec::new("dwMaximumSizeLow", U32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateFileMappingA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpFileMappingAttributes", SecurityAttributesPtr),
            ParamSpec::new("flProtect", Hex32),
            ParamSpec::new("dwMaximumSizeHigh", U32),
            ParamSpec::new("dwMaximumSizeLow", U32),
            ParamSpec::new("lpName", PCStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "MapViewOfFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFileMappingObject", Handle),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("dwFileOffsetHigh", U32),
            ParamSpec::new("dwFileOffsetLow", U32),
            ParamSpec::new("dwNumberOfBytesToMap", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "UnmapViewOfFile",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpBaseAddress", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenFileMappingW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenFileMappingA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("lpName", PCStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTempPathW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTempPathA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTempFileNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpPathName", PCWStr),
            ParamSpec::new("lpPrefixString", PCWStr),
            ParamSpec::new("uUnique", U32),
            ParamSpec::new("lpTempFileName", PWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTempFileNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpPathName", PCStr),
            ParamSpec::new("lpPrefixString", PCStr),
            ParamSpec::new("uUnique", U32),
            ParamSpec::new("lpTempFileName", PStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ExpandEnvironmentStringsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSrc", PCWStr),
            ParamSpec::new("lpDst", PWStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ExpandEnvironmentStringsA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSrc", PCStr),
            ParamSpec::new("lpDst", PStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindFirstFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::with_dir("lpFindFileData", OpaqueStructPtr("WIN32_FIND_DATAW"), Out),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindFirstFileA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCStr),
            ParamSpec::with_dir("lpFindFileData", OpaqueStructPtr("WIN32_FIND_DATAA"), Out),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindNextFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFindFile", Handle),
            ParamSpec::with_dir("lpFindFileData", OpaqueStructPtr("WIN32_FIND_DATAW"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindNextFileA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFindFile", Handle),
            ParamSpec::with_dir("lpFindFileData", OpaqueStructPtr("WIN32_FIND_DATAA"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindClose",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hFindFile", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeleteFileW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpFileName", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeleteFileA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpFileName", PCStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpPathName", PCWStr),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateDirectoryA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpPathName", PCStr),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CopyFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpExistingFileName", PCWStr),
            ParamSpec::new("lpNewFileName", PCWStr),
            ParamSpec::new("bFailIfExists", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileAttributesW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpFileName", PCWStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileAttributesA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpFileName", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileAttributesExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::new("fInfoLevelId", U32),
            ParamSpec::with_dir("lpFileInformation", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeviceIoControl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hDevice", Handle),
            ParamSpec::new("dwIoControlCode", Hex32),
            ParamSpec::new("lpInBuffer", GuestPtr),
            ParamSpec::new("nInBufferSize", U32),
            ParamSpec::with_dir("lpOutBuffer", GuestPtr, Out),
            ParamSpec::new("nOutBufferSize", U32),
            ParamSpec::with_dir("lpBytesReturned", GuestPtr, Out),
            ParamSpec::new("lpOverlapped", OverlappedPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Memory ────────────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
            ParamSpec::new("flAllocationType", Hex32),
            ParamSpec::new("flProtect", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualAllocEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
            ParamSpec::new("flAllocationType", Hex32),
            ParamSpec::new("flProtect", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualFree",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
            ParamSpec::new("dwFreeType", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualFreeEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
            ParamSpec::new("dwFreeType", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualProtect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
            ParamSpec::new("flNewProtect", Hex32),
            ParamSpec::with_dir("lpflOldProtect", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualProtectEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
            ParamSpec::new("flNewProtect", Hex32),
            ParamSpec::with_dir("lpflOldProtect", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualQuery",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::with_dir("lpBuffer", OpaqueStructPtr("MEMORY_BASIC_INFORMATION"), Out),
            ParamSpec::new("dwLength", SizeT),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VirtualQueryEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpAddress", GuestPtr),
            ParamSpec::with_dir("lpBuffer", OpaqueStructPtr("MEMORY_BASIC_INFORMATION"), Out),
            ParamSpec::new("dwLength", SizeT),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReadProcessMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpBaseAddress", GuestPtr),
            ParamSpec::with_dir("lpBuffer", GuestPtr, Out),
            ParamSpec::new("nSize", SizeT),
            ParamSpec::with_dir("lpNumberOfBytesRead", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WriteProcessMemory",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpBaseAddress", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("nSize", SizeT),
            ParamSpec::with_dir("lpNumberOfBytesWritten", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Heap ──────────────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "HeapAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHeap", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("dwBytes", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapCreate",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("flOptions", Hex32),
            ParamSpec::new("dwInitialSize", SizeT),
            ParamSpec::new("dwMaximumSize", SizeT),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapDestroy",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hHeap", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapFree",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHeap", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpMem", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapReAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHeap", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpMem", GuestPtr),
            ParamSpec::new("dwBytes", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHeap", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpMem", GuestPtr),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    // ── Global memory ─────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("uFlags", Hex32),
            ParamSpec::new("dwBytes", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMem", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalLock",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMem", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalUnlock",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMem", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalReAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hMem", GuestPtr),
            ParamSpec::new("dwBytes", SizeT),
            ParamSpec::new("uFlags", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalSize",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMem", GuestPtr)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pMem", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalFlags",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMem", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LocalAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("uFlags", Hex32),
            ParamSpec::new("uBytes", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LocalFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMem", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LocalReAlloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hMem", GuestPtr),
            ParamSpec::new("uBytes", SizeT),
            ParamSpec::new("uFlags", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Process / Thread ──────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "CreateProcessW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpApplicationName", PCWStr),
            ParamSpec::new("lpCommandLine", PWStr),
            ParamSpec::new("lpProcessAttributes", SecurityAttributesPtr),
            ParamSpec::new("lpThreadAttributes", SecurityAttributesPtr),
            ParamSpec::new("bInheritHandles", Bool32),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::new("lpEnvironment", GuestPtr),
            ParamSpec::new("lpCurrentDirectory", PCWStr),
            ParamSpec::new("lpStartupInfo", StartupInfoPtr),
            ParamSpec::with_dir("lpProcessInformation", ProcessInformationPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateProcessA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpApplicationName", PCStr),
            ParamSpec::new("lpCommandLine", PStr),
            ParamSpec::new("lpProcessAttributes", SecurityAttributesPtr),
            ParamSpec::new("lpThreadAttributes", SecurityAttributesPtr),
            ParamSpec::new("bInheritHandles", Bool32),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::new("lpEnvironment", GuestPtr),
            ParamSpec::new("lpCurrentDirectory", PCStr),
            ParamSpec::new("lpStartupInfo", StartupInfoPtr),
            ParamSpec::with_dir("lpProcessInformation", ProcessInformationPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WinExec",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpCmdLine", PCStr),
            ParamSpec::new("uCmdShow", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpThreadAttributes", SecurityAttributesPtr),
            ParamSpec::new("dwStackSize", SizeT),
            ParamSpec::new("lpStartAddress", FunctionPtr),
            ParamSpec::new("lpParameter", GuestPtr),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::with_dir("lpThreadId", GuestPtr, Out),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateRemoteThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpThreadAttributes", SecurityAttributesPtr),
            ParamSpec::new("dwStackSize", SizeT),
            ParamSpec::new("lpStartAddress", FunctionPtr),
            ParamSpec::new("lpParameter", GuestPtr),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::with_dir("lpThreadId", GuestPtr, Out),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateRemoteThreadEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpThreadAttributes", SecurityAttributesPtr),
            ParamSpec::new("dwStackSize", SizeT),
            ParamSpec::new("lpStartAddress", FunctionPtr),
            ParamSpec::new("lpParameter", GuestPtr),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::with_dir("lpThreadId", GuestPtr, Out),
            ParamSpec::new("lpAttributeList", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ExitProcess",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("uExitCode", U32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ExitThread",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwExitCode", U32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "TerminateProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("uExitCode", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCurrentProcess",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCurrentProcessId",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCurrentThread",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCurrentThreadId",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("dwProcessId", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("dwThreadId", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitOnceExecuteOnce",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("InitOnce", GuestPtr),
            ParamSpec::new("InitFn", FunctionPtr),
            ParamSpec::new("Parameter", GuestPtr),
            ParamSpec::with_dir("Context", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ResumeThread",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hThread", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SuspendThread",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hThread", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "TerminateThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::new("dwExitCode", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProcessId",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hProcess", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetExitCodeProcess",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::with_dir("lpExitCode", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetExitCodeThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::with_dir("lpExitCode", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DuplicateHandle",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSourceProcessHandle", Handle),
            ParamSpec::new("hSourceHandle", Handle),
            ParamSpec::new("hTargetProcessHandle", Handle),
            ParamSpec::with_dir("lpTargetHandle", GuestPtr, Out),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("dwOptions", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Module ────────────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "GetModuleHandleW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpModuleName", PCWStr)],
        ret: ReturnSpec::ModuleHandle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetModuleHandleA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpModuleName", PCStr)],
        ret: ReturnSpec::ModuleHandle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetModuleHandleExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpModuleName", PCWStr),
            ParamSpec::with_dir("phModule", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetModuleFileNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("lpFilename", PWStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetModuleFileNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("lpFilename", PStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LoadLibraryW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpLibFileName", PCWStr)],
        ret: ReturnSpec::ModuleHandle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LoadLibraryA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpLibFileName", PCStr)],
        ret: ReturnSpec::ModuleHandle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LoadLibraryExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLibFileName", PCWStr),
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::ModuleHandle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LoadLibraryExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLibFileName", PCStr),
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::ModuleHandle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProcAddress",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("lpProcName", ProcName),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FreeLibrary",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hLibModule", ModuleHandle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FreeLibraryAndExitThread",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hLibModule", ModuleHandle),
            ParamSpec::new("dwExitCode", U32),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Synchronization ───────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "CreateEventW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpEventAttributes", SecurityAttributesPtr),
            ParamSpec::new("bManualReset", Bool32),
            ParamSpec::new("bInitialState", Bool32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateEventA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpEventAttributes", SecurityAttributesPtr),
            ParamSpec::new("bManualReset", Bool32),
            ParamSpec::new("bInitialState", Bool32),
            ParamSpec::new("lpName", PCStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenEventW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetEvent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hEvent", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ResetEvent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hEvent", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitForSingleObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHandle", Handle),
            ParamSpec::new("dwMilliseconds", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitForSingleObjectEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHandle", Handle),
            ParamSpec::new("dwMilliseconds", U32),
            ParamSpec::new("bAlertable", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitForMultipleObjects",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nCount", U32),
            ParamSpec::new("lpHandles", GuestPtr),
            ParamSpec::new("bWaitAll", Bool32),
            ParamSpec::new("dwMilliseconds", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WaitForMultipleObjectsEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nCount", U32),
            ParamSpec::new("lpHandles", GuestPtr),
            ParamSpec::new("bWaitAll", Bool32),
            ParamSpec::new("dwMilliseconds", U32),
            ParamSpec::new("bAlertable", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReleaseMutex",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hMutex", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateMutexW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpMutexAttributes", SecurityAttributesPtr),
            ParamSpec::new("bInitialOwner", Bool32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateMutexA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpMutexAttributes", SecurityAttributesPtr),
            ParamSpec::new("bInitialOwner", Bool32),
            ParamSpec::new("lpName", PCStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateMutexExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpMutexAttributes", SecurityAttributesPtr),
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("dwDesiredAccess", Hex32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateSemaphoreW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSemaphoreAttributes", SecurityAttributesPtr),
            ParamSpec::new("lInitialCount", I32),
            ParamSpec::new("lMaximumCount", I32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateSemaphoreExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSemaphoreAttributes", SecurityAttributesPtr),
            ParamSpec::new("lInitialCount", I32),
            ParamSpec::new("lMaximumCount", I32),
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Sleep",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwMilliseconds", U32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SleepEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwMilliseconds", U32),
            ParamSpec::new("bAlertable", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── TLS / FLS ─────────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "TlsAlloc",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "TlsFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwTlsIndex", U32)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "TlsGetValue",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwTlsIndex", U32)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "TlsSetValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwTlsIndex", U32),
            ParamSpec::new("lpTlsValue", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlsAlloc",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpCallback", FunctionPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlsFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwFlsIndex", U32)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlsGetValue",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwFlsIndex", U32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlsSetValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlsIndex", U32),
            ParamSpec::new("lpFlsValue", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Console / Std ─────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "GetStdHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("nStdHandle", U32)],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetStdHandle",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nStdHandle", U32),
            ParamSpec::new("hHandle", Handle),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
