use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(super) static KERNEL32_SIGS_2: &[HookSignature] = &[
    HookSignature {
        module: "kernel32.dll",
        function: "GetConsoleMode",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hConsoleHandle", Handle),
            ParamSpec::with_dir("lpMode", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WriteConsoleW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hConsoleOutput", Handle),
            ParamSpec::new("lpBuffer", PCWStr),
            ParamSpec::new("nNumberOfCharsToWrite", U32),
            ParamSpec::with_dir(
                "lpNumberOfCharsWritten",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
            ParamSpec::new("lpReserved", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WriteConsoleA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hConsoleOutput", Handle),
            ParamSpec::new("lpBuffer", PCStr),
            ParamSpec::new("nNumberOfCharsToWrite", U32),
            ParamSpec::with_dir(
                "lpNumberOfCharsWritten",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
            ParamSpec::new("lpReserved", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReadConsoleW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hConsoleInput", Handle),
            ParamSpec::with_dir("lpBuffer", GuestPtr, Out),
            ParamSpec::new("nNumberOfCharsToRead", U32),
            ParamSpec::with_dir(
                "lpNumberOfCharsRead",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
            ParamSpec::new("pInputControl", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Environment / Command Line ────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "GetCommandLineW",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCommandLineA",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetEnvironmentVariableW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetEnvironmentVariableA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCStr),
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetEnvironmentVariableW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("lpValue", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetEnvironmentVariableA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCStr),
            ParamSpec::new("lpValue", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetStartupInfoW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpStartupInfo", StartupInfoPtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetStartupInfoA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpStartupInfo", StartupInfoPtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── String / Locale ───────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "MultiByteToWideChar",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CodePage", U32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpMultiByteStr", PCStr),
            ParamSpec::new("cbMultiByte", I32),
            ParamSpec::new("lpWideCharStr", PWStr),
            ParamSpec::new("cchWideChar", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "WideCharToMultiByte",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CodePage", U32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpWideCharStr", PCWStr),
            ParamSpec::new("cchWideChar", I32),
            ParamSpec::new("lpMultiByteStr", PStr),
            ParamSpec::new("cbMultiByte", I32),
            ParamSpec::new("lpDefaultChar", PCStr),
            ParamSpec::with_dir(
                "lpfUsedDefaultChar",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrlenW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpString", PCWStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrlenA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpString", PCStr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "uaw_wcsrchr",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("str", PCWStr), ParamSpec::new("c", I32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcmpW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PCWStr),
            ParamSpec::new("lpString2", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcmpA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PCStr),
            ParamSpec::new("lpString2", PCStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcmpiA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PCStr),
            ParamSpec::new("lpString2", PCStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcpyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PWStr),
            ParamSpec::new("lpString2", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcpyA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PStr),
            ParamSpec::new("lpString2", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcpynA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PStr),
            ParamSpec::new("lpString2", PCStr),
            ParamSpec::new("iMaxLength", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcatW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PWStr),
            ParamSpec::new("lpString2", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcatA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PStr),
            ParamSpec::new("lpString2", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CompareStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwCmpFlags", Hex32),
            ParamSpec::new("lpString1", PCWStr),
            ParamSpec::new("cchCount1", I32),
            ParamSpec::new("lpString2", PCWStr),
            ParamSpec::new("cchCount2", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FormatMessageW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpSource", GuestPtr),
            ParamSpec::new("dwMessageId", U32),
            ParamSpec::new("dwLanguageId", U32),
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("nSize", U32),
            ParamSpec::new("Arguments", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FormatMessageA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("lpSource", GuestPtr),
            ParamSpec::new("dwMessageId", U32),
            ParamSpec::new("dwLanguageId", U32),
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::new("nSize", U32),
            ParamSpec::new("Arguments", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Error / Info ──────────────────────────────────────────────────────
    HookSignature {
        module: "kernel32.dll",
        function: "GetLastError",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetLastError",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwErrCode", U32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProcessHeap",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryPerformanceCounter",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpPerformanceCount", GuestPtr, Out)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryPerformanceFrequency",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpFrequency", GuestPtr, Out)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemInfo",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "lpSystemInfo",
            OpaqueStructPtr("SYSTEM_INFO"),
            Out,
        )],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetNativeSystemInfo",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "lpSystemInfo",
            OpaqueStructPtr("SYSTEM_INFO"),
            Out,
        )],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTickCount",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "IsDebuggerPresent",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OutputDebugStringA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpOutputString", PCStr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OutputDebugStringW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpOutputString", PCWStr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RaiseException",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwExceptionCode", U32),
            ParamSpec::new("dwExceptionFlags", Hex32),
            ParamSpec::new("nNumberOfArguments", U32),
            ParamSpec::new("lpArguments", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetUnhandledExceptionFilter",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpTopLevelExceptionFilter", FunctionPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "AddVectoredExceptionHandler",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("First", U32),
            ParamSpec::new("Handler", FunctionPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RemoveVectoredExceptionHandler",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Handle", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "VerSetConditionMask",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ConditionMask", U64),
            ParamSpec::new("TypeMask", U32),
            ParamSpec::new("Condition", U32),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFullPathNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::with_dir("lpFilePart", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFullPathNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCStr),
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::with_dir("lpFilePart", GuestPtr, Out),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCurrentDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetCurrentDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpPathName", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetWindowsDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetWindowsDirectoryA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemDirectoryA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryFullProcessImageNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpExeName", PWStr),
            ParamSpec::with_dir("lpdwSize", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryFullProcessImageNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpExeName", PStr),
            ParamSpec::with_dir("lpdwSize", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetVersion",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetVersionExW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "lpVersionInformation",
            OpaqueStructPtr("OSVERSIONINFOW"),
            InOut,
        )],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetVersionExA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir(
            "lpVersionInformation",
            OpaqueStructPtr("OSVERSIONINFOA"),
            InOut,
        )],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileInformationByHandle",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::with_dir(
                "lpFileInformation",
                OpaqueStructPtr("BY_HANDLE_FILE_INFORMATION"),
                Out,
            ),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileInformationByHandleEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("FileInformationClass", U32),
            ParamSpec::with_dir("lpFileInformation", GuestPtr, Out),
            ParamSpec::new("dwBufferSize", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetFileTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::with_dir("lpCreationTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpLastAccessTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpLastWriteTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "SetFileTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpCreationTime", FileTimePtr),
            ParamSpec::new("lpLastAccessTime", FileTimePtr),
            ParamSpec::new("lpLastWriteTime", FileTimePtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "MoveFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpExistingFileName", PCWStr),
            ParamSpec::new("lpNewFileName", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "MoveFileA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpExistingFileName", PCStr),
            ParamSpec::new("lpNewFileName", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "MoveFileExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpExistingFileName", PCWStr),
            ParamSpec::new("lpNewFileName", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RemoveDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpPathName", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlushViewOfFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBaseAddress", GuestPtr),
            ParamSpec::new("dwNumberOfBytesToFlush", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreatePipe",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("hReadPipe", GuestPtr, Out),
            ParamSpec::with_dir("hWritePipe", GuestPtr, Out),
            ParamSpec::new("lpPipeAttributes", SecurityAttributesPtr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "PeekNamedPipe",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hNamedPipe", Handle),
            ParamSpec::with_dir("lpBuffer", GuestPtr, Out),
            ParamSpec::new("nBufferSize", U32),
            ParamSpec::with_dir("lpBytesRead", GuestPtr, Out),
            ParamSpec::with_dir("lpTotalBytesAvail", GuestPtr, Out),
            ParamSpec::with_dir("lpBytesLeftThisMessage", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateToolhelp32Snapshot",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::new("th32ProcessID", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "MulDiv",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nNumber", I32),
            ParamSpec::new("nNumerator", I32),
            ParamSpec::new("nDenominator", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "AcquireSRWLockExclusive",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpSRWLock", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ActivateActCtx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hActCtx", Handle),
            ParamSpec::with_dir("lpCookie", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "AddAtomW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpString", PCWStr)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ApplicationRecoveryFinished",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pvParameter", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ApplicationRecoveryInProgress",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("pbCancelled", GuestPtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "AreFileApisANSI",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CancelIo",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hFile", Handle)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CompareFileTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileTime1", FileTimePtr),
            ParamSpec::new("lpFileTime2", FileTimePtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CompareStringOrdinal",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PCWStr),
            ParamSpec::new("cchCount1", I32),
            ParamSpec::new("lpString2", PCWStr),
            ParamSpec::new("cchCount2", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ConnectNamedPipe",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hNamedPipe", Handle),
            ParamSpec::new("lpOverlapped", OverlappedPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ContinueDebugEvent",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwProcessId", U32),
            ParamSpec::new("dwThreadId", U32),
            ParamSpec::new("dwContinueStatus", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateActCtxW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pActCtx", OpaqueStructPtr("ACTCTXW"))],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateIoCompletionPort",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FileHandle", Handle),
            ParamSpec::new("ExistingCompletionPort", Handle),
            ParamSpec::new("CompletionKey", PointerSizedUInt),
            ParamSpec::new("NumberOfConcurrentThreads", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateNamedPipeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("dwOpenMode", Hex32),
            ParamSpec::new("dwPipeMode", Hex32),
            ParamSpec::new("nMaxInstances", U32),
            ParamSpec::new("nOutBufferSize", U32),
            ParamSpec::new("nInBufferSize", U32),
            ParamSpec::new("nDefaultTimeOut", U32),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CreateWaitableTimerW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpTimerAttributes", SecurityAttributesPtr),
            ParamSpec::new("bManualReset", Bool32),
            ParamSpec::new("lpTimerName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "CxIZKa",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("arg0", GuestPtr),
            ParamSpec::new("arg1", GuestPtr),
            ParamSpec::new("arg2", GuestPtr),
            ParamSpec::new("arg3", GuestPtr),
            ParamSpec::new("arg4", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeactivateActCtx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("ulCookie", PointerSizedUInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DebugBreak",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DecodePointer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Ptr", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeleteAtom",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("nAtom", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeleteCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpCriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DeleteProcThreadAttributeList",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpAttributeList", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "DisconnectNamedPipe",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hNamedPipe", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EncodePointer",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Ptr", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EnterCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpCriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EnumDateFormatsExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpDateFmtEnumProcEx", FunctionPtr),
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EnumSystemFirmwareTables",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FirmwareTableProviderSignature", U32),
            ParamSpec::new("FirmwareTableID", U32),
            ParamSpec::new("pFirmwareTableBuffer", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EnumSystemLocalesA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocaleEnumProc", FunctionPtr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EnumSystemLocalesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocaleEnumProc", FunctionPtr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "EnumTimeFormatsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpTimeFmtEnumProc", FunctionPtr),
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FileTimeToDosDateTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileTime", FileTimePtr),
            ParamSpec::with_dir("lpFatDate", GuestPtr, Out),
            ParamSpec::with_dir("lpFatTime", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FileTimeToLocalFileTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileTime", FileTimePtr),
            ParamSpec::with_dir("lpLocalFileTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FileTimeToSystemTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileTime", FileTimePtr),
            ParamSpec::with_dir("lpSystemTime", SystemTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindActCtxSectionStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpExtensionGuid", GuidPtr),
            ParamSpec::new("ulSectionId", U32),
            ParamSpec::new("lpStringToFind", PCWStr),
            ParamSpec::with_dir("lpReturnedData", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindFirstFileExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCStr),
            ParamSpec::new("fInfoLevelId", U32),
            ParamSpec::with_dir("lpFindFileData", GuestPtr, Out),
            ParamSpec::new("fSearchOp", U32),
            ParamSpec::new("lpSearchFilter", GuestPtr),
            ParamSpec::new("dwAdditionalFlags", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindFirstFileExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFileName", PCWStr),
            ParamSpec::new("fInfoLevelId", U32),
            ParamSpec::with_dir("lpFindFileData", GuestPtr, Out),
            ParamSpec::new("fSearchOp", U32),
            ParamSpec::new("lpSearchFilter", GuestPtr),
            ParamSpec::new("dwAdditionalFlags", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindFirstVolumeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszVolumeName", PWStr),
            ParamSpec::new("cchBufferLength", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindNextVolumeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFindVolume", Handle),
            ParamSpec::new("lpszVolumeName", PWStr),
            ParamSpec::new("cchBufferLength", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindResourceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("lpName", PCStr),
            ParamSpec::new("lpType", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindResourceExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("lpType", PCWStr),
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("wLanguage", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindResourceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("lpType", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FindVolumeClose",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hFindVolume", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlsGetValue2",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwFlsIndex", U32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FlushInstructionCache",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::new("lpBaseAddress", GuestPtr),
            ParamSpec::new("dwSize", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FreeConsole",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FreeEnvironmentStringsA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpszEnvironmentBlock", PCStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FreeEnvironmentStringsW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpszEnvironmentBlock", PCWStr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "FreeResource",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hResData", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetACP",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetComputerNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::with_dir("nSize", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetComputerNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::with_dir("nSize", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetConsoleCP",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetConsoleOutputCP",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetCPInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CodePage", U32),
            ParamSpec::with_dir("lpCPInfo", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetDateFormatW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpDate", SystemTimePtr),
            ParamSpec::new("lpFormat", PCWStr),
            ParamSpec::new("lpDateStr", PWStr),
            ParamSpec::new("cchDate", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetDiskFreeSpaceExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpDirectoryName", PCWStr),
            ParamSpec::with_dir("lpFreeBytesAvailableToCaller", GuestPtr, Out),
            ParamSpec::with_dir("lpTotalNumberOfBytes", GuestPtr, Out),
            ParamSpec::with_dir("lpTotalNumberOfFreeBytes", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetDllDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetDriveTypeA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpRootPathName", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetDriveTypeW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpRootPathName", PCWStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetEnvironmentStringsA",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetEnvironmentStringsW",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetLocaleInfoA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("LCType", U32),
            ParamSpec::new("lpLCData", PStr),
            ParamSpec::new("cchData", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
];
