use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static KERNEL32_SIGS_3: &[HookSignature] = &[
    HookSignature {
        module: "kernel32.dll",
        function: "GetLocaleInfoEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocaleName", PCWStr),
            ParamSpec::new("LCType", U32),
            ParamSpec::new("lpLCData", PWStr),
            ParamSpec::new("cchData", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetLocaleInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("LCType", U32),
            ParamSpec::new("lpLCData", PWStr),
            ParamSpec::new("cchData", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetLocalTime",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpSystemTime", SystemTimePtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetLogicalDriveStringsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nBufferLength", U32),
            ParamSpec::new("lpBuffer", PWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetLongPathNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszShortPath", PCWStr),
            ParamSpec::new("lpszLongPath", PWStr),
            ParamSpec::new("cchBuffer", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetNumberFormatEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocaleName", PCWStr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpValue", PCWStr),
            ParamSpec::new("lpFormat", GuestPtr),
            ParamSpec::new("lpNumberStr", PWStr),
            ParamSpec::new("cchNumber", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetOEMCP",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetOverlappedResult",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpOverlapped", OverlappedPtr),
            ParamSpec::with_dir("lpNumberOfBytesTransferred", GuestPtr, Out),
            ParamSpec::new("bWait", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetPriorityClass",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hProcess", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetPrivateProfileIntW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAppName", PCWStr),
            ParamSpec::new("lpKeyName", PCWStr),
            ParamSpec::new("nDefault", I32),
            ParamSpec::new("lpFileName", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetPrivateProfileStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAppName", PCWStr),
            ParamSpec::new("lpKeyName", PCWStr),
            ParamSpec::new("lpDefault", PCWStr),
            ParamSpec::new("lpReturnedString", PWStr),
            ParamSpec::new("nSize", U32),
            ParamSpec::new("lpFileName", PCWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetPrivateProfileStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAppName", PCStr),
            ParamSpec::new("lpKeyName", PCStr),
            ParamSpec::new("lpDefault", PCStr),
            ParamSpec::new("lpReturnedString", PStr),
            ParamSpec::new("nSize", U32),
            ParamSpec::new("lpFileName", PCStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProcessAffinityMask",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::with_dir("lpProcessAffinityMask", GuestPtr, Out),
            ParamSpec::with_dir("lpSystemAffinityMask", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProcessTimes",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::with_dir("lpCreationTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpExitTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpKernelTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpUserTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetThreadTimes",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::with_dir("lpCreationTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpExitTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpKernelTime", FileTimePtr, Out),
            ParamSpec::with_dir("lpUserTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProcessWorkingSetSize",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::with_dir("lpMinimumWorkingSetSize", GuestPtr, Out),
            ParamSpec::with_dir("lpMaximumWorkingSetSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetProfileIntW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpAppName", PCWStr),
            ParamSpec::new("lpKeyName", PCWStr),
            ParamSpec::new("nDefault", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetQueuedCompletionStatus",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompletionPort", Handle),
            ParamSpec::with_dir("lpNumberOfBytesTransferred", GuestPtr, Out),
            ParamSpec::with_dir("lpCompletionKey", GuestPtr, Out),
            ParamSpec::with_dir("lpOverlapped", GuestPtr, Out),
            ParamSpec::new("dwMilliseconds", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetShortPathNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszLongPath", PCWStr),
            ParamSpec::new("lpszShortPath", PWStr),
            ParamSpec::new("cchBuffer", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetStringTypeA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwInfoType", U32),
            ParamSpec::new("lpSrcStr", PCStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::with_dir("lpCharType", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetStringTypeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwInfoType", U32),
            ParamSpec::new("lpSrcStr", PCWStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::with_dir("lpCharType", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemDefaultLangID",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemDefaultUILanguage",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemFirmwareTable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("FirmwareTableProviderSignature", U32),
            ParamSpec::new("FirmwareTableID", U32),
            ParamSpec::with_dir("pFirmwareTableBuffer", GuestPtr, Out),
            ParamSpec::new("BufferSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemTime",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpSystemTime", SystemTimePtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemTimeAsFileTime",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpFileTime", FileTimePtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemTimePreciseAsFileTime",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpFileTime", FileTimePtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemWindowsDirectoryA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemWindowsDirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetSystemWow64DirectoryW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("uSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetThreadContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hThread", Handle),
            ParamSpec::with_dir("lpContext", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetThreadLocale",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetThreadPreferredUILanguages",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", U32),
            ParamSpec::with_dir("pulNumLanguages", GuestPtr, Out),
            ParamSpec::new("pwszLanguagesBuffer", PWStr),
            ParamSpec::with_dir("pcchLanguagesBuffer", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTimeFormatW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpTime", SystemTimePtr),
            ParamSpec::new("lpFormat", PCWStr),
            ParamSpec::new("lpTimeStr", PWStr),
            ParamSpec::new("cchTime", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetTimeZoneInformation",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("lpTimeZoneInformation", GuestPtr, Out)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetUserDefaultLCID",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetUserDefaultUILanguage",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetVolumeInformationA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpRootPathName", PCStr),
            ParamSpec::new("lpVolumeNameBuffer", PStr),
            ParamSpec::new("nVolumeNameSize", U32),
            ParamSpec::with_dir("lpVolumeSerialNumber", GuestPtr, Out),
            ParamSpec::with_dir("lpMaximumComponentLength", GuestPtr, Out),
            ParamSpec::with_dir("lpFileSystemFlags", GuestPtr, Out),
            ParamSpec::new("lpFileSystemNameBuffer", PStr),
            ParamSpec::new("nFileSystemNameSize", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GetVolumeInformationW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpRootPathName", PCWStr),
            ParamSpec::new("lpVolumeNameBuffer", PWStr),
            ParamSpec::new("nVolumeNameSize", U32),
            ParamSpec::with_dir("lpVolumeSerialNumber", GuestPtr, Out),
            ParamSpec::with_dir("lpMaximumComponentLength", GuestPtr, Out),
            ParamSpec::with_dir("lpFileSystemFlags", GuestPtr, Out),
            ParamSpec::new("lpFileSystemNameBuffer", PWStr),
            ParamSpec::new("nFileSystemNameSize", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalAddAtomW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpString", PCWStr)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalDeleteAtom",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("nAtom", U32)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalFindAtomW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpString", PCWStr)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "GlobalGetAtomNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nAtom", U32),
            ParamSpec::new("lpBuffer", PWStr),
            ParamSpec::new("nSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapLock",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hHeap", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapQueryInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("HeapInformationClass", U32),
            ParamSpec::with_dir("HeapInformation", GuestPtr, Out),
            ParamSpec::new("HeapInformationLength", SizeT),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapSetInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HeapHandle", Handle),
            ParamSpec::new("HeapInformationClass", U32),
            ParamSpec::new("HeapInformation", GuestPtr),
            ParamSpec::new("HeapInformationLength", SizeT),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapUnlock",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hHeap", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "HeapWalk",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHeap", Handle),
            ParamSpec::with_dir("lpEntry", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeConditionVariable",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpConditionVariable", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpCriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeCriticalSectionAndSpinCount",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpCriticalSection", GuestPtr),
            ParamSpec::new("dwSpinCount", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeCriticalSectionEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpCriticalSection", GuestPtr),
            ParamSpec::new("dwSpinCount", U32),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeProcThreadAttributeList",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpAttributeList", GuestPtr, Out),
            ParamSpec::new("dwAttributeCount", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::with_dir("lpSize", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeSListHead",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ListHead", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InitializeSRWLock",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SRWLock", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedCompareExchange",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Destination", GuestPtr),
            ParamSpec::new("Exchange", PointerSizedUInt),
            ParamSpec::new("Comparand", PointerSizedUInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedDecrement",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpAddend", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedExchange",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Target", GuestPtr),
            ParamSpec::new("Value", PointerSizedUInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedExchangeAdd",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Addend", GuestPtr),
            ParamSpec::new("Value", PointerSizedUInt),
        ],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedFlushSList",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ListHead", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedIncrement",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpAddend", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "InterlockedPushEntrySList",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ListHead", GuestPtr),
            ParamSpec::new("ListEntry", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "IsBadReadPtr",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lp", GuestPtr), ParamSpec::new("ucb", U32)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "IsProcessorFeaturePresent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ProcessorFeature", U32)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "IsValidCodePage",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("CodePage", U32)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "IsValidLocale",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "IsWow64Process",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProcess", Handle),
            ParamSpec::with_dir("Wow64Process", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LCMapStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwMapFlags", U32),
            ParamSpec::new("lpSrcStr", PCStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::new("lpDestStr", PStr),
            ParamSpec::new("cchDest", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LCMapStringEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocaleName", PCWStr),
            ParamSpec::new("dwMapFlags", U32),
            ParamSpec::new("lpSrcStr", PCWStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::new("lpDestStr", PWStr),
            ParamSpec::new("cchDest", I32),
            ParamSpec::new("lpVersionInformation", GuestPtr),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::new("sortHandle", U32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LCMapStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Locale", U32),
            ParamSpec::new("dwMapFlags", U32),
            ParamSpec::new("lpSrcStr", PCWStr),
            ParamSpec::new("cchSrc", I32),
            ParamSpec::new("lpDestStr", PWStr),
            ParamSpec::new("cchDest", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LeaveCriticalSection",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpCriticalSection", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LoadResource",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hModule", ModuleHandle),
            ParamSpec::new("hResInfo", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LocalFileTimeToFileTime",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocalFileTime", FileTimePtr),
            ParamSpec::with_dir("lpFileTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LockFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("dwFileOffsetLow", U32),
            ParamSpec::new("dwFileOffsetHigh", U32),
            ParamSpec::new("nNumberOfBytesToLockLow", U32),
            ParamSpec::new("nNumberOfBytesToLockHigh", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "LockResource",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hResData", GuestPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "lstrcmpiW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpString1", PCWStr),
            ParamSpec::new("lpString2", PCWStr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenMutexA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", U32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("lpName", PCStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenMutexW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", U32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "OpenSemaphoreW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwDesiredAccess", U32),
            ParamSpec::new("bInheritHandle", Bool32),
            ParamSpec::new("lpName", PCWStr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "PostQueuedCompletionStatus",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("CompletionPort", Handle),
            ParamSpec::new("dwNumberOfBytesTransferred", U32),
            ParamSpec::new("dwCompletionKey", PointerSizedUInt),
            ParamSpec::new("lpOverlapped", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Process32First",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSnapshot", Handle),
            ParamSpec::with_dir("lppe", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Process32FirstA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSnapshot", Handle),
            ParamSpec::with_dir("lppe", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Process32FirstW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSnapshot", Handle),
            ParamSpec::with_dir("lppe", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Process32Next",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSnapshot", Handle),
            ParamSpec::with_dir("lppe", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Process32NextA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSnapshot", Handle),
            ParamSpec::with_dir("lppe", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "Process32NextW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSnapshot", Handle),
            ParamSpec::with_dir("lppe", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ProcessIdToSessionId",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwProcessId", U32),
            ParamSpec::with_dir("pSessionId", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryActCtxW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("hActCtx", Handle),
            ParamSpec::new("pvSubInstance", GuestPtr),
            ParamSpec::new("ulFlags", U32),
            ParamSpec::with_dir("pvData", GuestPtr, Out),
            ParamSpec::new("cbData", SizeT),
            ParamSpec::with_dir("pcbWritten", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryDosDeviceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpDeviceName", PCStr),
            ParamSpec::new("lpTargetPath", PStr),
            ParamSpec::new("ucchMax", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueryDosDeviceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpDeviceName", PCWStr),
            ParamSpec::new("lpTargetPath", PWStr),
            ParamSpec::new("ucchMax", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueueUserAPC",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pfnAPC", FunctionPtr),
            ParamSpec::new("hThread", Handle),
            ParamSpec::new("dwData", PointerSizedUInt),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "QueueUserWorkItem",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Function", FunctionPtr),
            ParamSpec::new("Context", GuestPtr),
            ParamSpec::new("Flags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RegisterApplicationRecoveryCallback",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pRecoveryCallback", FunctionPtr),
            ParamSpec::new("pvParameter", GuestPtr),
            ParamSpec::new("dwPingInterval", U32),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RegisterApplicationRestart",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pwzCommandline", PCWStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReleaseSemaphore",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSemaphore", Handle),
            ParamSpec::new("lReleaseCount", I32),
            ParamSpec::with_dir("lpPreviousCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReleaseSRWLockExclusive",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("SRWLock", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "ReplaceFileW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpReplacedFileName", PCWStr),
            ParamSpec::new("lpReplacementFileName", PCWStr),
            ParamSpec::new("lpBackupFileName", PCWStr),
            ParamSpec::new("dwReplaceFlags", Hex32),
            ParamSpec::new("lpExclude", GuestPtr),
            ParamSpec::new("lpReserved", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RtlCaptureContext",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("ContextRecord", GuestPtr, Out)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RtlLookupFunctionEntry",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ControlPc", PointerSizedUInt),
            ParamSpec::with_dir("ImageBase", GuestPtr, Out),
            ParamSpec::with_dir("HistoryTable", GuestPtr, Out),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RtlPcToFileHeader",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("PcValue", PointerSizedUInt),
            ParamSpec::with_dir("BaseOfImage", GuestPtr, Out),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "kernel32.dll",
        function: "RtlRestoreContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ContextRecord", GuestPtr),
            ParamSpec::new("ExceptionRecord", GuestPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
];
