//! Full `HookSignature` table for `ole32.dll` functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(crate) static OLE32_SIGNATURES: &[HookSignature] = &[
    // ── CLSID / GUID helpers ──────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "CLSIDFromProgID",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszProgID", PCWStr),
            ParamSpec::new("lpclsid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CLSIDFromString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpsz", PCWStr),
            ParamSpec::new("pclsid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoCreateGuid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pguid", GuidPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "IIDFromString",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpsz", PCWStr),
            ParamSpec::new("lpiid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "StringFromCLSID",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rclsid", GuidPtr),
            ParamSpec::new("lplpsz", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "StringFromGUID2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rguid", GuidPtr),
            ParamSpec::new("lpszw", PWStr),
            ParamSpec::new("cchMax", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "ProgIDFromCLSID",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("clsid", GuidPtr),
            ParamSpec::new("lplpszProgID", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── COM Initialization ────────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "CoInitialize",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pvReserved", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoInitializeEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pvReserved", GuestPtr),
            ParamSpec::new("dwCoInit", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoUninitialize",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── COM Object Creation ───────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "CoCreateInstance",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rclsid", GuidPtr),
            ParamSpec::new("pUnkOuter", GuestPtr),
            ParamSpec::new("dwClsCtx", U32),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::new("ppv", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoCreateFreeThreadedMarshaler",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("punkOuter", GuestPtr),
            ParamSpec::new("ppunkMarshal", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoGetClassObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rclsid", GuidPtr),
            ParamSpec::new("dwClsCtx", U32),
            ParamSpec::new("pvReserved", GuestPtr),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::new("ppv", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoGetObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pszName", PCWStr),
            ParamSpec::new("pBindingOptions", GuestPtr),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::new("ppv", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoDisconnectObject",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pUnk", GuestPtr),
            ParamSpec::new("dwReserved", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoFreeUnusedLibraries",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoLockObjectExternal",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pUnk", GuestPtr),
            ParamSpec::new("fLock", Bool32),
            ParamSpec::new("fLastUnlockReleases", Bool32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoRegisterMessageFilter",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpMessageFilter", GuestPtr),
            ParamSpec::new("lplpMessageFilter", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoRevokeClassObject",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("dwRegister", U32)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoRegisterActivationFilter",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pActivationFilter", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── COM Memory Allocation ─────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "CoTaskMemAlloc",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("cb", SizeT)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoTaskMemFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pv", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoTaskMemRealloc",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pv", GuestPtr), ParamSpec::new("cb", SizeT)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Storage ───────────────────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "CreateILockBytesOnHGlobal",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hGlobal", GuestPtr),
            ParamSpec::new("fDeleteOnRelease", Bool32),
            ParamSpec::new("ppLkbyt", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CreateStreamOnHGlobal",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hGlobal", GuestPtr),
            ParamSpec::new("fDeleteOnRelease", Bool32),
            ParamSpec::new("ppstm", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "StgCreateDocfileOnILockBytes",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("plkbyt", GuestPtr),
            ParamSpec::new("grfMode", U32),
            ParamSpec::new("reserved", U32),
            ParamSpec::new("ppstgOpen", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "StgOpenStorageOnILockBytes",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("plkbyt", GuestPtr),
            ParamSpec::new("pstgPriority", GuestPtr),
            ParamSpec::new("grfMode", U32),
            ParamSpec::new("snbExclude", GuestPtr),
            ParamSpec::new("reserved", U32),
            ParamSpec::new("ppstgOpen", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "StgOpenStorage",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pwcsName", PCWStr),
            ParamSpec::new("pstgPriority", GuestPtr),
            ParamSpec::new("grfMode", U32),
            ParamSpec::new("snbExclude", GuestPtr),
            ParamSpec::new("reserved", U32),
            ParamSpec::new("ppstgOpen", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "StgOpenStorageEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pwcsName", PCWStr),
            ParamSpec::new("grfMode", U32),
            ParamSpec::new("stgfmt", U32),
            ParamSpec::new("grfAttrs", U32),
            ParamSpec::new("pStgOptions", GuestPtr),
            ParamSpec::new("ppstgOpen", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "ReadClassStg",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pStg", GuestPtr),
            ParamSpec::new("pclsid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "WriteClassStg",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pStg", GuestPtr),
            ParamSpec::new("rclsid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── OLE / Clipboard ───────────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "OleInitialize",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pvReserved", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleUninitialize",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleGetClipboard",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ppDataObj", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleFlushClipboard",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleIsCurrentClipboard",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pDataObj", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleLoad",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pStg", GuestPtr),
            ParamSpec::new("riid", GuidPtr),
            ParamSpec::new("pClientSite", GuestPtr),
            ParamSpec::new("ppvObj", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleSave",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pPS", GuestPtr),
            ParamSpec::new("pStg", GuestPtr),
            ParamSpec::new("fSameAsLoad", Bool32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleRegGetUserType",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("rclsid", GuidPtr),
            ParamSpec::new("dwFormOfType", U32),
            ParamSpec::new("pszUserType", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleLockRunning",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pUnknown", GuestPtr),
            ParamSpec::new("fLock", Bool32),
            ParamSpec::new("fLastUnlockCloses", Bool32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Drag & Drop ───────────────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "RegisterDragDrop",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwnd", GuestPtr),
            ParamSpec::new("pDropTarget", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "RevokeDragDrop",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hwnd", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "DoDragDrop",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pDataObj", GuestPtr),
            ParamSpec::new("pDropSource", GuestPtr),
            ParamSpec::new("dwOKEffects", U32),
            ParamSpec::new("pdwEffect", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Menu / Accelerator ────────────────────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "IsAccelerator",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hAccel", GuestPtr),
            ParamSpec::new("cAccelEntries", I32),
            ParamSpec::new("lpMsg", GuestPtr),
            ParamSpec::new("lpwCmd", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleCreateMenuDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hmenuCombined", GuestPtr),
            ParamSpec::new("lpMenuWidths", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleDestroyMenuDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("holemenu", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleTranslateAccelerator",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpFrame", GuestPtr),
            ParamSpec::new("lpFrameInfo", GuestPtr),
            ParamSpec::new("lpMsg", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "OleDuplicateData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSrc", GuestPtr),
            ParamSpec::new("cfFormat", U32),
            ParamSpec::new("uiFlags", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── PropVariant / StgMedium / IMalloc ──────────────────────────────────
    HookSignature {
        module: "ole32.dll",
        function: "ReleaseStgMedium",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pMedium", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "PropVariantClear",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pvar", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "PropVariantCopy",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pvarDest", GuestPtr),
            ParamSpec::new("pvarSrc", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ole32.dll",
        function: "CoGetMalloc",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwMemContext", U32),
            ParamSpec::new("ppMalloc", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
];
