use crate::hooks::registry::HookRegistry;
use crate::hooks::types::LogicalAbi;

const EXPORTS: &[(&str, LogicalAbi)] = &[
    ("CLSIDFromProgID", LogicalAbi::WinApi),
    ("CLSIDFromString", LogicalAbi::WinApi),
    ("CoCreateGuid", LogicalAbi::WinApi),
    ("CoCreateFreeThreadedMarshaler", LogicalAbi::WinApi),
    ("CoCreateInstance", LogicalAbi::WinApi),
    ("CoDisconnectObject", LogicalAbi::WinApi),
    ("CoFreeUnusedLibraries", LogicalAbi::WinApi),
    ("CoGetClassObject", LogicalAbi::WinApi),
    ("CoGetObject", LogicalAbi::WinApi),
    ("CoInitialize", LogicalAbi::WinApi),
    ("CoInitializeEx", LogicalAbi::WinApi),
    ("CoLockObjectExternal", LogicalAbi::WinApi),
    ("CoRegisterMessageFilter", LogicalAbi::WinApi),
    ("CoRevokeClassObject", LogicalAbi::WinApi),
    ("CoTaskMemAlloc", LogicalAbi::WinApi),
    ("CoTaskMemFree", LogicalAbi::WinApi),
    ("CoTaskMemRealloc", LogicalAbi::WinApi),
    ("CoUninitialize", LogicalAbi::WinApi),
    ("CreateILockBytesOnHGlobal", LogicalAbi::WinApi),
    ("CreateStreamOnHGlobal", LogicalAbi::WinApi),
    ("DoDragDrop", LogicalAbi::WinApi),
    ("IsAccelerator", LogicalAbi::WinApi),
    ("OleCreateMenuDescriptor", LogicalAbi::WinApi),
    ("OleDestroyMenuDescriptor", LogicalAbi::WinApi),
    ("OleDuplicateData", LogicalAbi::WinApi),
    ("OleFlushClipboard", LogicalAbi::WinApi),
    ("OleGetClipboard", LogicalAbi::WinApi),
    ("OleInitialize", LogicalAbi::WinApi),
    ("OleIsCurrentClipboard", LogicalAbi::WinApi),
    ("OleLockRunning", LogicalAbi::WinApi),
    ("OleTranslateAccelerator", LogicalAbi::WinApi),
    ("OleUninitialize", LogicalAbi::WinApi),
    ("RegisterDragDrop", LogicalAbi::WinApi),
    ("ReleaseStgMedium", LogicalAbi::WinApi),
    ("RevokeDragDrop", LogicalAbi::WinApi),
    ("StgCreateDocfileOnILockBytes", LogicalAbi::WinApi),
    ("StgOpenStorageOnILockBytes", LogicalAbi::WinApi),
    ("CoGetMalloc", LogicalAbi::WinApi),
    ("CoRegisterActivationFilter", LogicalAbi::WinApi),
    ("IIDFromString", LogicalAbi::WinApi),
    ("OleLoad", LogicalAbi::WinApi),
    ("OleRegGetUserType", LogicalAbi::WinApi),
    ("OleSave", LogicalAbi::WinApi),
    ("ProgIDFromCLSID", LogicalAbi::WinApi),
    ("PropVariantClear", LogicalAbi::WinApi),
    ("PropVariantCopy", LogicalAbi::WinApi),
    ("ReadClassStg", LogicalAbi::WinApi),
    ("StgOpenStorage", LogicalAbi::WinApi),
    ("StgOpenStorageEx", LogicalAbi::WinApi),
    ("StringFromCLSID", LogicalAbi::WinApi),
    ("StringFromGUID2", LogicalAbi::WinApi),
    ("WriteClassStg", LogicalAbi::WinApi),
];

/// Registers the generated hook definitions for this DLL family.
pub fn register_ole32_hooks(registry: &mut HookRegistry) {
    registry.register_function_stubs("ole32.dll", &EXPORTS);
    registry.register_signatures(super::ole32_signatures::OLE32_SIGNATURES);
}
