use crate::hooks::registry::HookRegistry;
use crate::hooks::types::LogicalAbi;

const EXPORTS: &[(&str, LogicalAbi)] = &[
    ("SysAllocString", LogicalAbi::WinApi),
    ("SysAllocStringLen", LogicalAbi::WinApi),
    ("SysAllocStringByteLen", LogicalAbi::WinApi),
    ("SysReAllocString", LogicalAbi::WinApi),
    ("SysReAllocStringLen", LogicalAbi::WinApi),
    ("SysFreeString", LogicalAbi::WinApi),
    ("SysStringLen", LogicalAbi::WinApi),
    ("SysStringByteLen", LogicalAbi::WinApi),
    ("VariantInit", LogicalAbi::WinApi),
    ("VariantClear", LogicalAbi::WinApi),
    ("VariantCopy", LogicalAbi::WinApi),
    ("VariantChangeType", LogicalAbi::WinApi),
    ("VarBstrFromDate", LogicalAbi::WinApi),
    ("VarUI4FromStr", LogicalAbi::WinApi),
    ("SafeArrayCreate", LogicalAbi::WinApi),
    ("SafeArrayCreateVector", LogicalAbi::WinApi),
    ("SafeArrayDestroy", LogicalAbi::WinApi),
    ("SafeArrayGetDim", LogicalAbi::WinApi),
    ("SafeArrayGetElemsize", LogicalAbi::WinApi),
    ("SafeArrayAccessData", LogicalAbi::WinApi),
    ("SafeArrayUnaccessData", LogicalAbi::WinApi),
    ("SafeArrayLock", LogicalAbi::WinApi),
    ("SafeArrayUnlock", LogicalAbi::WinApi),
    ("SafeArrayGetUBound", LogicalAbi::WinApi),
    ("SafeArrayGetLBound", LogicalAbi::WinApi),
    ("SafeArrayPutElement", LogicalAbi::WinApi),
    ("SafeArrayGetElement", LogicalAbi::WinApi),
    ("SafeArrayPtrOfIndex", LogicalAbi::WinApi),
    ("LoadTypeLib", LogicalAbi::WinApi),
    ("SystemTimeToVariantTime", LogicalAbi::WinApi),
    ("VariantTimeToSystemTime", LogicalAbi::WinApi),
    ("OleCreateFontIndirect", LogicalAbi::WinApi),
    ("ordinal_2", LogicalAbi::WinApi),
    ("ordinal_4", LogicalAbi::WinApi),
    ("ordinal_6", LogicalAbi::WinApi),
    ("ordinal_7", LogicalAbi::WinApi),
    ("ordinal_8", LogicalAbi::WinApi),
    ("ordinal_9", LogicalAbi::WinApi),
    ("ordinal_10", LogicalAbi::WinApi),
    ("ordinal_11", LogicalAbi::WinApi),
    ("ordinal_12", LogicalAbi::WinApi),
    ("ordinal_15", LogicalAbi::WinApi),
    ("ordinal_16", LogicalAbi::WinApi),
    ("ordinal_17", LogicalAbi::WinApi),
    ("ordinal_18", LogicalAbi::WinApi),
    ("ordinal_19", LogicalAbi::WinApi),
    ("ordinal_20", LogicalAbi::WinApi),
    ("ordinal_21", LogicalAbi::WinApi),
    ("ordinal_22", LogicalAbi::WinApi),
    ("ordinal_23", LogicalAbi::WinApi),
    ("ordinal_24", LogicalAbi::WinApi),
    ("ordinal_25", LogicalAbi::WinApi),
    ("ordinal_26", LogicalAbi::WinApi),
    ("ordinal_114", LogicalAbi::WinApi),
    ("ordinal_148", LogicalAbi::WinApi),
    ("ordinal_161", LogicalAbi::WinApi),
    ("ordinal_184", LogicalAbi::WinApi),
    ("ordinal_185", LogicalAbi::WinApi),
    ("ordinal_420", LogicalAbi::WinApi),
    ("ordinal_27", LogicalAbi::WinApi),
    ("ordinal_149", LogicalAbi::WinApi),
    ("ordinal_192", LogicalAbi::WinApi),
    ("ordinal_194", LogicalAbi::WinApi),
    ("ordinal_220", LogicalAbi::WinApi),
    ("ordinal_411", LogicalAbi::WinApi),
];

/// Registers the generated hook definitions for this DLL family.
pub fn register_oleaut32_hooks(registry: &mut HookRegistry) {
    registry.register_function_stubs("oleaut32.dll", &EXPORTS);
    registry.register_signatures(super::oleaut32_signatures::OLEAUT32_SIGNATURES);
}
