//! Full `HookSignature` table for `rpcrt4.dll` functions.
//!
//! Covers UUID, RPC binding, string binding, and memory allocation functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static RPCRT4_SIGNATURES: &[HookSignature] = &[
    // ── UUID Creation ─────────────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidCreate",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Uuid", GuidPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidCreateSequential",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Uuid", GuidPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── UUID Comparison / Query ───────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidCompare",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Uuid1", GuidPtr),
            ParamSpec::new("Uuid2", GuidPtr),
            ParamSpec::new("Status", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidEqual",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Uuid1", GuidPtr),
            ParamSpec::new("Uuid2", GuidPtr),
            ParamSpec::new("Status", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidIsNil",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Uuid", GuidPtr),
            ParamSpec::new("Status", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidHash",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Uuid", GuidPtr),
            ParamSpec::new("Status", GuestPtr),
        ],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    // ── UUID String Conversion ────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidFromStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringUuid", PCStr),
            ParamSpec::new("Uuid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidFromStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringUuid", PCWStr),
            ParamSpec::new("Uuid", GuidPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidToStringA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Uuid", GuidPtr),
            ParamSpec::new("StringUuid", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "UuidToStringW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Uuid", GuidPtr),
            ParamSpec::new("StringUuid", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── RPC String Free ───────────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcStringFreeA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("String", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcStringFreeW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("String", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── RPC Binding ───────────────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcBindingFromStringBindingA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringBinding", PCStr),
            ParamSpec::new("Binding", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcBindingFromStringBindingW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringBinding", PCWStr),
            ParamSpec::new("Binding", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcBindingFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Binding", GuestPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcBindingSetAuthInfoA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Binding", GuestPtr),
            ParamSpec::new("ServerPrincName", PCStr),
            ParamSpec::new("AuthnLevel", U32),
            ParamSpec::new("AuthnSvc", U32),
            ParamSpec::new("AuthIdentity", GuestPtr),
            ParamSpec::new("AuthzSvc", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcBindingSetAuthInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Binding", GuestPtr),
            ParamSpec::new("ServerPrincName", PCWStr),
            ParamSpec::new("AuthnLevel", U32),
            ParamSpec::new("AuthnSvc", U32),
            ParamSpec::new("AuthIdentity", GuestPtr),
            ParamSpec::new("AuthzSvc", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcBindingSetAuthInfoExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Binding", GuestPtr),
            ParamSpec::new("ServerPrincName", PCWStr),
            ParamSpec::new("AuthnLevel", U32),
            ParamSpec::new("AuthnSvc", U32),
            ParamSpec::new("AuthIdentity", GuestPtr),
            ParamSpec::new("AuthzSvc", U32),
            ParamSpec::new("pSecurityQos", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── RPC String Binding ────────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcStringBindingComposeA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ObjUuid", PCStr),
            ParamSpec::new("ProtSeq", PCStr),
            ParamSpec::new("NetworkAddr", PCStr),
            ParamSpec::new("EndPoint", PCStr),
            ParamSpec::new("Options", PCStr),
            ParamSpec::new("StringBinding", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcStringBindingComposeW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ObjUuid", PCWStr),
            ParamSpec::new("ProtSeq", PCWStr),
            ParamSpec::new("NetworkAddr", PCWStr),
            ParamSpec::new("EndPoint", PCWStr),
            ParamSpec::new("Options", PCWStr),
            ParamSpec::new("StringBinding", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcStringBindingParseA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringBinding", PCStr),
            ParamSpec::new("ObjUuid", GuestPtr),
            ParamSpec::new("ProtSeq", GuestPtr),
            ParamSpec::new("NetworkAddr", GuestPtr),
            ParamSpec::new("EndPoint", GuestPtr),
            ParamSpec::new("NetworkOptions", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcStringBindingParseW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringBinding", PCWStr),
            ParamSpec::new("ObjUuid", GuestPtr),
            ParamSpec::new("ProtSeq", GuestPtr),
            ParamSpec::new("NetworkAddr", GuestPtr),
            ParamSpec::new("EndPoint", GuestPtr),
            ParamSpec::new("NetworkOptions", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── RPC Memory Allocation ─────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "I_RpcAllocate",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Size", SizeT)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "I_RpcFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Object", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "NdrOleAllocate",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Size", SizeT)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "NdrOleFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("NodeToFree", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── RPC Async / NDR ───────────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "NdrAsyncClientCall",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pStubDescriptor", GuestPtr),
            ParamSpec::new("pFormat", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcAsyncInitializeHandle",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pAsync", GuestPtr),
            ParamSpec::new("Size", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcAsyncCompleteCall",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pAsync", GuestPtr),
            ParamSpec::new("Reply", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "RpcRaiseException",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("exception", U32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── RPC Error ─────────────────────────────────────────────────────────
    HookSignature {
        module: "rpcrt4.dll",
        function: "DceErrorInqTextA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RpcStatus", U32),
            ParamSpec::new("ErrorText", PStr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "rpcrt4.dll",
        function: "DceErrorInqTextW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RpcStatus", U32),
            ParamSpec::new("ErrorText", PWStr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
];
