use crate::hooks::types::LogicalAbi;

pub(super) static STUBS_2: &[(&str, LogicalAbi)] = &[
    ("RtlCreateUserStack", LogicalAbi::WinApi),
    ("RtlCreateVirtualAccountSid", LogicalAbi::WinApi),
    ("RtlCultureNameToLCID", LogicalAbi::WinApi),
    ("RtlCustomCPToUnicodeN", LogicalAbi::WinApi),
    ("RtlCutoverTimeToSystemTime", LogicalAbi::WinApi),
    ("RtlDeCommitDebugInfo", LogicalAbi::WinApi),
    ("RtlDeactivateActivationContext", LogicalAbi::WinApi),
    (
        "RtlDeactivateActivationContextUnsafeFast",
        LogicalAbi::WinApi,
    ),
    ("RtlDebugPrintTimes", LogicalAbi::WinApi),
    ("RtlDecodeRemotePointer", LogicalAbi::WinApi),
    ("RtlDecompressBufferEx", LogicalAbi::WinApi),
    ("RtlDecompressFragment", LogicalAbi::WinApi),
    ("RtlDelete", LogicalAbi::WinApi),
    ("RtlDeleteBarrier", LogicalAbi::WinApi),
    ("RtlDeleteBoundaryDescriptor", LogicalAbi::WinApi),
    ("RtlDeleteElementGenericTable", LogicalAbi::WinApi),
    ("RtlDeleteElementGenericTableAvl", LogicalAbi::WinApi),
    ("RtlDeleteElementGenericTableAvlEx", LogicalAbi::WinApi),
    ("RtlDeleteFunctionTable", LogicalAbi::WinApi),
    ("RtlDeleteGrowableFunctionTable", LogicalAbi::WinApi),
    ("RtlDeleteHashTable", LogicalAbi::WinApi),
    ("RtlDeleteNoSplay", LogicalAbi::WinApi),
    ("RtlDeleteResource", LogicalAbi::WinApi),
    ("RtlDeleteSecurityObject", LogicalAbi::WinApi),
    ("RtlDeleteUmsCompletionList", LogicalAbi::WinApi),
    ("RtlDeleteUmsThreadContext", LogicalAbi::WinApi),
    ("RtlDequeueUmsCompletionListItems", LogicalAbi::WinApi),
    ("RtlDeregisterSecureMemoryCacheCallback", LogicalAbi::WinApi),
    ("RtlDeregisterWait", LogicalAbi::WinApi),
    ("RtlDeregisterWaitEx", LogicalAbi::WinApi),
    ("RtlDeriveCapabilitySidsFromName", LogicalAbi::WinApi),
    ("RtlDestroyHandleTable", LogicalAbi::WinApi),
    ("RtlDestroyMemoryBlockLookaside", LogicalAbi::WinApi),
    ("RtlDestroyMemoryZone", LogicalAbi::WinApi),
    ("RtlDetectHeapLeaks", LogicalAbi::WinApi),
    ("RtlDetermineDosPathNameType_U", LogicalAbi::WinApi),
    ("RtlDisableThreadProfiling", LogicalAbi::WinApi),
    ("RtlDisownModuleHeapAllocation", LogicalAbi::WinApi),
    ("RtlDllShutdownInProgress", LogicalAbi::WinApi),
    ("RtlDnsHostNameToComputerName", LogicalAbi::WinApi),
    ("RtlDoesNameContainWildCards", LogicalAbi::WinApi),
    (
        "RtlDosApplyFileIsolationRedirection_Ustr",
        LogicalAbi::WinApi,
    ),
    (
        "RtlDosLongPathNameToNtPathName_U_WithStatus",
        LogicalAbi::WinApi,
    ),
    (
        "RtlDosLongPathNameToRelativeNtPathName_U_WithStatus",
        LogicalAbi::WinApi,
    ),
    ("RtlDosPathNameToRelativeNtPathName_U", LogicalAbi::WinApi),
    (
        "RtlDosPathNameToRelativeNtPathName_U_WithStatus",
        LogicalAbi::WinApi,
    ),
    ("RtlDosSearchPath_U", LogicalAbi::WinApi),
    ("RtlDosSearchPath_Ustr", LogicalAbi::WinApi),
    ("RtlDrainNonVolatileFlush", LogicalAbi::WinApi),
    ("RtlDumpResource", LogicalAbi::WinApi),
    ("RtlEmptyAtomTable", LogicalAbi::WinApi),
    (
        "RtlEnableEarlyCriticalSectionEventCreation",
        LogicalAbi::WinApi,
    ),
    ("RtlEnableThreadProfiling", LogicalAbi::WinApi),
    ("RtlEnclaveCallDispatch", LogicalAbi::WinApi),
    ("RtlEnclaveCallDispatchReturn", LogicalAbi::WinApi),
    ("RtlEncodeRemotePointer", LogicalAbi::WinApi),
    ("RtlEndEnumerationHashTable", LogicalAbi::WinApi),
    ("RtlEndStrongEnumerationHashTable", LogicalAbi::WinApi),
    ("RtlEndWeakEnumerationHashTable", LogicalAbi::WinApi),
    ("RtlEnterUmsSchedulingMode", LogicalAbi::WinApi),
    ("RtlEnumProcessHeaps", LogicalAbi::WinApi),
    ("RtlEnumerateEntryHashTable", LogicalAbi::WinApi),
    ("RtlEnumerateGenericTable", LogicalAbi::WinApi),
    ("RtlEnumerateGenericTableAvl", LogicalAbi::WinApi),
    ("RtlEnumerateGenericTableLikeADirectory", LogicalAbi::WinApi),
    (
        "RtlEnumerateGenericTableWithoutSplaying",
        LogicalAbi::WinApi,
    ),
    (
        "RtlEnumerateGenericTableWithoutSplayingAvl",
        LogicalAbi::WinApi,
    ),
    ("RtlEqualComputerName", LogicalAbi::WinApi),
    ("RtlEqualDomainName", LogicalAbi::WinApi),
    ("RtlEqualLuid", LogicalAbi::WinApi),
    ("RtlEqualWnfChangeStamps", LogicalAbi::WinApi),
    ("RtlEthernetAddressToStringA", LogicalAbi::WinApi),
    ("RtlEthernetAddressToStringW", LogicalAbi::WinApi),
    ("RtlEthernetStringToAddressA", LogicalAbi::WinApi),
    ("RtlEthernetStringToAddressW", LogicalAbi::WinApi),
    ("RtlExecuteUmsThread", LogicalAbi::WinApi),
    ("RtlExitUserThread", LogicalAbi::WinApi),
    ("RtlExpandHashTable", LogicalAbi::WinApi),
    ("RtlExtendCorrelationVector", LogicalAbi::WinApi),
    ("RtlExtendMemoryBlockLookaside", LogicalAbi::WinApi),
    ("RtlExtendMemoryZone", LogicalAbi::WinApi),
    ("RtlExtractBitMap", LogicalAbi::WinApi),
    ("RtlFillMemoryNonTemporal", LogicalAbi::WinApi),
    ("RtlFillNonVolatileMemory", LogicalAbi::WinApi),
    (
        "RtlFinalReleaseOutOfProcessMemoryStream",
        LogicalAbi::WinApi,
    ),
    ("RtlFindAceByType", LogicalAbi::WinApi),
    ("RtlFindActivationContextSectionGuid", LogicalAbi::WinApi),
    ("RtlFindActivationContextSectionString", LogicalAbi::WinApi),
    ("RtlFindCharInUnicodeString", LogicalAbi::WinApi),
    ("RtlFindClearBits", LogicalAbi::WinApi),
    ("RtlFindClearBitsAndSet", LogicalAbi::WinApi),
    ("RtlFindClearBitsEx", LogicalAbi::WinApi),
    ("RtlFindClearRuns", LogicalAbi::WinApi),
    ("RtlFindClosestEncodableLength", LogicalAbi::WinApi),
    ("RtlFindExportedRoutineByName", LogicalAbi::WinApi),
    ("RtlFindLastBackwardRunClear", LogicalAbi::WinApi),
    ("RtlFindLeastSignificantBit", LogicalAbi::WinApi),
    ("RtlFindLongestRunClear", LogicalAbi::WinApi),
    ("RtlFindMessage", LogicalAbi::WinApi),
    ("RtlFindMostSignificantBit", LogicalAbi::WinApi),
    ("RtlFindNextForwardRunClear", LogicalAbi::WinApi),
    ("RtlFindSetBits", LogicalAbi::WinApi),
    ("RtlFindSetBitsAndClear", LogicalAbi::WinApi),
    ("RtlFindSetBitsAndClearEx", LogicalAbi::WinApi),
    ("RtlFindSetBitsEx", LogicalAbi::WinApi),
    ("RtlFindUnicodeSubstring", LogicalAbi::WinApi),
    ("RtlFirstFreeAce", LogicalAbi::WinApi),
    ("RtlFlsAlloc", LogicalAbi::WinApi),
    ("RtlFlsFree", LogicalAbi::WinApi),
    ("RtlFlsGetValue", LogicalAbi::WinApi),
    ("RtlFlsSetValue", LogicalAbi::WinApi),
    ("RtlFlushHeaps", LogicalAbi::WinApi),
    ("RtlFlushNonVolatileMemory", LogicalAbi::WinApi),
    ("RtlFlushNonVolatileMemoryRanges", LogicalAbi::WinApi),
    ("RtlFlushSecureMemoryCache", LogicalAbi::WinApi),
    ("RtlFormatMessage", LogicalAbi::WinApi),
    ("RtlFormatMessageEx", LogicalAbi::WinApi),
    ("RtlFreeActivationContextStack", LogicalAbi::WinApi),
    ("RtlFreeHandle", LogicalAbi::WinApi),
    ("RtlFreeMemoryBlockLookaside", LogicalAbi::WinApi),
    ("RtlFreeNonVolatileToken", LogicalAbi::WinApi),
    ("RtlFreeThreadActivationContextStack", LogicalAbi::WinApi),
    ("RtlFreeUTF8String", LogicalAbi::WinApi),
    ("RtlFreeUserFiberShadowStack", LogicalAbi::WinApi),
    ("RtlFreeUserStack", LogicalAbi::WinApi),
    ("RtlGenerate8dot3Name", LogicalAbi::WinApi),
    ("RtlGetActiveActivationContext", LogicalAbi::WinApi),
    ("RtlGetActiveConsoleId", LogicalAbi::WinApi),
    ("RtlGetAppContainerNamedObjectPath", LogicalAbi::WinApi),
    ("RtlGetAppContainerParent", LogicalAbi::WinApi),
    ("RtlGetAppContainerSidType", LogicalAbi::WinApi),
    ("RtlGetCallersAddress", LogicalAbi::WinApi),
    (
        "RtlGetConsoleSessionForegroundProcessId",
        LogicalAbi::WinApi,
    ),
    ("RtlGetControlSecurityDescriptor", LogicalAbi::WinApi),
    ("RtlGetCurrentPeb", LogicalAbi::WinApi),
    ("RtlGetCurrentProcessorNumber", LogicalAbi::WinApi),
    ("RtlGetCurrentProcessorNumberEx", LogicalAbi::WinApi),
    ("RtlGetCurrentServiceSessionId", LogicalAbi::WinApi),
    ("RtlGetCurrentTransaction", LogicalAbi::WinApi),
    ("RtlGetCurrentUmsThread", LogicalAbi::WinApi),
    ("RtlGetDeviceFamilyInfoEnum", LogicalAbi::WinApi),
    ("RtlGetElementGenericTable", LogicalAbi::WinApi),
    ("RtlGetElementGenericTableAvl", LogicalAbi::WinApi),
    ("RtlGetExePath", LogicalAbi::WinApi),
    ("RtlGetExtendedContextLength2", LogicalAbi::WinApi),
    ("RtlGetFileMUIPath", LogicalAbi::WinApi),
    ("RtlGetFrame", LogicalAbi::WinApi),
    ("RtlGetFullPathName_UstrEx", LogicalAbi::WinApi),
    ("RtlGetFunctionTableListHead", LogicalAbi::WinApi),
    ("RtlGetIntegerAtom", LogicalAbi::WinApi),
    ("RtlGetInterruptTimePrecise", LogicalAbi::WinApi),
    ("RtlGetLastNtStatus", LogicalAbi::WinApi),
    ("RtlGetLastWin32Error", LogicalAbi::WinApi),
    (
        "RtlGetLengthWithoutLastFullDosOrNtPathElement",
        LogicalAbi::WinApi,
    ),
    (
        "RtlGetLengthWithoutTrailingPathSeperators",
        LogicalAbi::WinApi,
    ),
    ("RtlGetLocaleFileMappingAddress", LogicalAbi::WinApi),
    ("RtlGetLongestNtPathLength", LogicalAbi::WinApi),
    ("RtlGetMultiTimePrecise", LogicalAbi::WinApi),
    ("RtlGetNativeSystemInformation", LogicalAbi::WinApi),
    ("RtlGetNextEntryHashTable", LogicalAbi::WinApi),
    ("RtlGetNextUmsListItem", LogicalAbi::WinApi),
    ("RtlGetNonVolatileToken", LogicalAbi::WinApi),
    ("RtlGetNtGlobalFlags", LogicalAbi::WinApi),
    ("RtlGetNtProductType", LogicalAbi::WinApi),
    ("RtlGetNtSystemRoot", LogicalAbi::WinApi),
    ("RtlGetNtVersionNumbers", LogicalAbi::WinApi),
    ("RtlGetParentLocaleName", LogicalAbi::WinApi),
    ("RtlGetPersistedStateLocation", LogicalAbi::WinApi),
    ("RtlGetProcessPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlGetProductInfo", LogicalAbi::WinApi),
    ("RtlGetReturnAddressHijackTarget", LogicalAbi::WinApi),
    ("RtlGetSaclSecurityDescriptor", LogicalAbi::WinApi),
    ("RtlGetSearchPath", LogicalAbi::WinApi),
    ("RtlGetSecurityDescriptorRMControl", LogicalAbi::WinApi),
    ("RtlGetSessionProperties", LogicalAbi::WinApi),
    ("RtlGetSetBootStatusData", LogicalAbi::WinApi),
    ("RtlGetSuiteMask", LogicalAbi::WinApi),
    ("RtlGetSystemBootStatus", LogicalAbi::WinApi),
    ("RtlGetSystemBootStatusEx", LogicalAbi::WinApi),
    ("RtlGetSystemPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlGetSystemTimeAndBias", LogicalAbi::WinApi),
    ("RtlGetSystemTimePrecise", LogicalAbi::WinApi),
    ("RtlGetThreadErrorMode", LogicalAbi::WinApi),
    ("RtlGetThreadLangIdByIndex", LogicalAbi::WinApi),
    ("RtlGetThreadPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlGetThreadWorkOnBehalfTicket", LogicalAbi::WinApi),
    ("RtlGetTokenNamedObjectPath", LogicalAbi::WinApi),
    ("RtlGetUILanguageInfo", LogicalAbi::WinApi),
    ("RtlGetUmsCompletionListEvent", LogicalAbi::WinApi),
    ("RtlGetUnloadEventTrace", LogicalAbi::WinApi),
    ("RtlGetUnloadEventTraceEx", LogicalAbi::WinApi),
    ("RtlGetUserPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlGrowFunctionTable", LogicalAbi::WinApi),
    ("RtlGuardCheckLongJumpTarget", LogicalAbi::WinApi),
    ("RtlHeapTrkInitialize", LogicalAbi::WinApi),
    ("RtlIdentifierAuthoritySid", LogicalAbi::WinApi),
    ("RtlIdnToAscii", LogicalAbi::WinApi),
    ("RtlIdnToNameprepUnicode", LogicalAbi::WinApi),
    ("RtlIdnToUnicode", LogicalAbi::WinApi),
    ("RtlImageDirectoryEntryToData", LogicalAbi::WinApi),
    ("RtlImageNtHeader", LogicalAbi::WinApi),
    ("RtlImageNtHeaderEx", LogicalAbi::WinApi),
    ("RtlImageRvaToSection", LogicalAbi::WinApi),
    ("RtlImageRvaToVa", LogicalAbi::WinApi),
    ("RtlIncrementCorrelationVector", LogicalAbi::WinApi),
    ("RtlInitBarrier", LogicalAbi::WinApi),
    ("RtlInitEnumerationHashTable", LogicalAbi::WinApi),
    ("RtlInitMemoryStream", LogicalAbi::WinApi),
    ("RtlInitOutOfProcessMemoryStream", LogicalAbi::WinApi),
    ("RtlInitStringEx", LogicalAbi::WinApi),
    ("RtlInitStrongEnumerationHashTable", LogicalAbi::WinApi),
    ("RtlInitUTF8String", LogicalAbi::WinApi),
    ("RtlInitUTF8StringEx", LogicalAbi::WinApi),
    ("RtlInitWeakEnumerationHashTable", LogicalAbi::WinApi),
    ("RtlInitializeAtomPackage", LogicalAbi::WinApi),
    ("RtlInitializeBitMap", LogicalAbi::WinApi),
    ("RtlInitializeBitMapEx", LogicalAbi::WinApi),
    ("RtlInitializeConditionVariable", LogicalAbi::WinApi),
    ("RtlInitializeContext", LogicalAbi::WinApi),
    ("RtlInitializeCorrelationVector", LogicalAbi::WinApi),
    ("RtlInitializeCriticalSectionEx", LogicalAbi::WinApi),
    ("RtlInitializeExtendedContext", LogicalAbi::WinApi),
    ("RtlInitializeExtendedContext2", LogicalAbi::WinApi),
    ("RtlInitializeGenericTable", LogicalAbi::WinApi),
    ("RtlInitializeGenericTableAvl", LogicalAbi::WinApi),
    ("RtlInitializeHandleTable", LogicalAbi::WinApi),
    ("RtlInitializeNtUserPfn", LogicalAbi::WinApi),
    ("RtlInitializeRXact", LogicalAbi::WinApi),
    ("RtlInitializeResource", LogicalAbi::WinApi),
    ("RtlInitializeSRWLock", LogicalAbi::WinApi),
    ("RtlInitializeSidEx", LogicalAbi::WinApi),
    ("RtlInsertElementGenericTable", LogicalAbi::WinApi),
    ("RtlInsertElementGenericTableAvl", LogicalAbi::WinApi),
    ("RtlInsertElementGenericTableFull", LogicalAbi::WinApi),
    ("RtlInsertElementGenericTableFullAvl", LogicalAbi::WinApi),
    ("RtlInsertEntryHashTable", LogicalAbi::WinApi),
    ("RtlInstallFunctionTableCallback", LogicalAbi::WinApi),
    ("RtlInterlockedClearBitRun", LogicalAbi::WinApi),
    ("RtlInterlockedFlushSList", LogicalAbi::WinApi),
    ("RtlInterlockedPushListSList", LogicalAbi::WinApi),
    ("RtlInterlockedPushListSListEx", LogicalAbi::WinApi),
    ("RtlInterlockedSetBitRun", LogicalAbi::WinApi),
    ("RtlIoDecodeMemIoResource", LogicalAbi::WinApi),
    ("RtlIoEncodeMemIoResource", LogicalAbi::WinApi),
    ("RtlIpv4AddressToStringExW", LogicalAbi::WinApi),
    ("RtlIpv4AddressToStringW", LogicalAbi::WinApi),
    ("RtlIpv4StringToAddressExW", LogicalAbi::WinApi),
    ("RtlIpv4StringToAddressW", LogicalAbi::WinApi),
    ("RtlIpv6AddressToStringExW", LogicalAbi::WinApi),
    ("RtlIpv6AddressToStringW", LogicalAbi::WinApi),
    ("RtlIpv6StringToAddressExW", LogicalAbi::WinApi),
    ("RtlIpv6StringToAddressW", LogicalAbi::WinApi),
    ("RtlIsActivationContextActive", LogicalAbi::WinApi),
    ("RtlIsCapabilitySid", LogicalAbi::WinApi),
    ("RtlIsCloudFilesPlaceholder", LogicalAbi::WinApi),
    ("RtlIsCurrentProcess", LogicalAbi::WinApi),
    ("RtlIsCurrentThread", LogicalAbi::WinApi),
    ("RtlIsCurrentThreadAttachExempt", LogicalAbi::WinApi),
    ("RtlIsDosDeviceName_U", LogicalAbi::WinApi),
    ("RtlIsElevatedRid", LogicalAbi::WinApi),
    ("RtlIsGenericTableEmpty", LogicalAbi::WinApi),
    ("RtlIsGenericTableEmptyAvl", LogicalAbi::WinApi),
    ("RtlIsMultiSessionSku", LogicalAbi::WinApi),
    ("RtlIsMultiUsersInSessionSku", LogicalAbi::WinApi),
    ("RtlIsNameInUnUpcasedExpression", LogicalAbi::WinApi),
    ("RtlIsNameLegalDOS8Dot3", LogicalAbi::WinApi),
    (
        "RtlIsNonEmptyDirectoryReparsePointAllowed",
        LogicalAbi::WinApi,
    ),
    ("RtlIsNormalizedString", LogicalAbi::WinApi),
    ("RtlIsPackageSid", LogicalAbi::WinApi),
    ("RtlIsParentOfChildAppContainer", LogicalAbi::WinApi),
    ("RtlIsPartialPlaceholder", LogicalAbi::WinApi),
    ("RtlIsPartialPlaceholderFileHandle", LogicalAbi::WinApi),
    ("RtlIsPartialPlaceholderFileInfo", LogicalAbi::WinApi),
    ("RtlIsProcessorFeaturePresent", LogicalAbi::WinApi),
    ("RtlIsStateSeparationEnabled", LogicalAbi::WinApi),
    ("RtlIsTextUnicode", LogicalAbi::WinApi),
    ("RtlIsThreadWithinLoaderCallout", LogicalAbi::WinApi),
    ("RtlIsUntrustedObject", LogicalAbi::WinApi),
    ("RtlIsValidHandle", LogicalAbi::WinApi),
    ("RtlIsValidIndexHandle", LogicalAbi::WinApi),
    ("RtlIsValidLocaleName", LogicalAbi::WinApi),
    ("RtlIsValidProcessTrustLabelSid", LogicalAbi::WinApi),
    ("RtlIsZeroMemory", LogicalAbi::WinApi),
    ("RtlKnownExceptionFilter", LogicalAbi::WinApi),
    ("RtlLCIDToCultureName", LogicalAbi::WinApi),
    ("RtlLargeIntegerToChar", LogicalAbi::WinApi),
    ("RtlLcidToLocaleName", LogicalAbi::WinApi),
    ("RtlLengthSidAsUnicodeString", LogicalAbi::WinApi),
    ("RtlLoadString", LogicalAbi::WinApi),
    ("RtlLocalTimeToSystemTime", LogicalAbi::WinApi),
    ("RtlLocaleNameToLcid", LogicalAbi::WinApi),
    ("RtlLocateExtendedFeature2", LogicalAbi::WinApi),
    ("RtlLockBootStatusData", LogicalAbi::WinApi),
    ("RtlLockCurrentThread", LogicalAbi::WinApi),
    ("RtlLockMemoryBlockLookaside", LogicalAbi::WinApi),
    ("RtlLockMemoryStreamRegion", LogicalAbi::WinApi),
    ("RtlLockMemoryZone", LogicalAbi::WinApi),
    ("RtlLockModuleSection", LogicalAbi::WinApi),
    ("RtlLogStackBackTrace", LogicalAbi::WinApi),
    ("RtlLookupElementGenericTable", LogicalAbi::WinApi),
    ("RtlLookupElementGenericTableAvl", LogicalAbi::WinApi),
    ("RtlLookupElementGenericTableFull", LogicalAbi::WinApi),
    ("RtlLookupElementGenericTableFullAvl", LogicalAbi::WinApi),
    ("RtlLookupEntryHashTable", LogicalAbi::WinApi),
    (
        "RtlLookupFirstMatchingElementGenericTableAvl",
        LogicalAbi::WinApi,
    ),
    ("RtlLookupFunctionTable", LogicalAbi::WinApi),
    ("RtlMapGenericMask", LogicalAbi::WinApi),
    ("RtlMapSecurityErrorToNtStatus", LogicalAbi::WinApi),
    ("RtlMultiAppendUnicodeStringBuffer", LogicalAbi::WinApi),
    ("RtlMultipleAllocateHeap", LogicalAbi::WinApi),
    ("RtlMultipleFreeHeap", LogicalAbi::WinApi),
    ("RtlNewInstanceSecurityObject", LogicalAbi::WinApi),
    ("RtlNewSecurityGrantedAccess", LogicalAbi::WinApi),
    ("RtlNewSecurityObject", LogicalAbi::WinApi),
    ("RtlNewSecurityObjectEx", LogicalAbi::WinApi),
    (
        "RtlNewSecurityObjectWithMultipleInheritance",
        LogicalAbi::WinApi,
    ),
    ("RtlNormalizeSecurityDescriptor", LogicalAbi::WinApi),
    ("RtlNormalizeString", LogicalAbi::WinApi),
    ("RtlNotifyFeatureUsage", LogicalAbi::WinApi),
    ("RtlNtdllName", LogicalAbi::WinApi),
    ("RtlNumberGenericTableElements", LogicalAbi::WinApi),
    ("RtlNumberGenericTableElementsAvl", LogicalAbi::WinApi),
    ("RtlNumberOfClearBits", LogicalAbi::WinApi),
    ("RtlNumberOfClearBitsEx", LogicalAbi::WinApi),
    ("RtlNumberOfClearBitsInRange", LogicalAbi::WinApi),
    ("RtlNumberOfSetBits", LogicalAbi::WinApi),
    ("RtlNumberOfSetBitsEx", LogicalAbi::WinApi),
    ("RtlNumberOfSetBitsInRange", LogicalAbi::WinApi),
    ("RtlNumberOfSetBitsUlongPtr", LogicalAbi::WinApi),
    ("RtlOemStringToUnicodeSize", LogicalAbi::WinApi),
    ("RtlOsDeploymentState", LogicalAbi::WinApi),
    ("RtlOwnerAcesPresent", LogicalAbi::WinApi),
    ("RtlPopFrame", LogicalAbi::WinApi),
    ("RtlPrepareForProcessCloning", LogicalAbi::WinApi),
    ("RtlProcessFlsData", LogicalAbi::WinApi),
    ("RtlProtectHeap", LogicalAbi::WinApi),
    ("RtlPushFrame", LogicalAbi::WinApi),
    (
        "RtlQueryActivationContextApplicationSettings",
        LogicalAbi::WinApi,
    ),
    ("RtlQueryAllFeatureConfigurations", LogicalAbi::WinApi),
    ("RtlQueryAtomInAtomTable", LogicalAbi::WinApi),
    ("RtlQueryCriticalSectionOwner", LogicalAbi::WinApi),
    ("RtlQueryDynamicTimeZoneInformation", LogicalAbi::WinApi),
    ("RtlQueryElevationFlags", LogicalAbi::WinApi),
    ("RtlQueryFeatureConfiguration", LogicalAbi::WinApi),
    (
        "RtlQueryFeatureConfigurationChangeStamp",
        LogicalAbi::WinApi,
    ),
    (
        "RtlQueryFeatureUsageNotificationSubscriptions",
        LogicalAbi::WinApi,
    ),
    ("RtlQueryHeapInformation", LogicalAbi::WinApi),
    ("RtlQueryImageMitigationPolicy", LogicalAbi::WinApi),
    ("RtlQueryInformationAcl", LogicalAbi::WinApi),
    ("RtlQueryInformationActivationContext", LogicalAbi::WinApi),
    (
        "RtlQueryInformationActiveActivationContext",
        LogicalAbi::WinApi,
    ),
    ("RtlQueryInterfaceMemoryStream", LogicalAbi::WinApi),
    ("RtlQueryModuleInformation", LogicalAbi::WinApi),
    ("RtlQueryPackageClaims", LogicalAbi::WinApi),
    ("RtlQueryPackageIdentity", LogicalAbi::WinApi),
    ("RtlQueryPackageIdentityEx", LogicalAbi::WinApi),
    ("RtlQueryPerformanceCounter", LogicalAbi::WinApi),
    ("RtlQueryPerformanceFrequency", LogicalAbi::WinApi),
    ("RtlQueryProcessBackTraceInformation", LogicalAbi::WinApi),
    ("RtlQueryProcessHeapInformation", LogicalAbi::WinApi),
    ("RtlQueryProcessLockInformation", LogicalAbi::WinApi),
    (
        "RtlQueryProcessPlaceholderCompatibilityMode",
        LogicalAbi::WinApi,
    ),
    ("RtlQueryProtectedPolicy", LogicalAbi::WinApi),
    ("RtlQueryRegistryValueWithFallback", LogicalAbi::WinApi),
    ("RtlQueryRegistryValuesEx", LogicalAbi::WinApi),
    ("RtlQueryResourcePolicy", LogicalAbi::WinApi),
    ("RtlQuerySecurityObject", LogicalAbi::WinApi),
    ("RtlQueryTagHeap", LogicalAbi::WinApi),
    (
        "RtlQueryThreadPlaceholderCompatibilityMode",
        LogicalAbi::WinApi,
    ),
    ("RtlQueryTimeZoneInformation", LogicalAbi::WinApi),
    ("RtlQueryTokenHostIdAsUlong64", LogicalAbi::WinApi),
    ("RtlQueryUmsThreadInformation", LogicalAbi::WinApi),
    ("RtlQueryUnbiasedInterruptTime", LogicalAbi::WinApi),
    ("RtlQueryValidationRunlevel", LogicalAbi::WinApi),
    ("RtlQueryWnfMetaNotification", LogicalAbi::WinApi),
    ("RtlQueryWnfStateDataWithExplicitScope", LogicalAbi::WinApi),
    ("RtlQueueApcWow64Thread", LogicalAbi::WinApi),
    ("RtlRaiseCustomSystemEventTrigger", LogicalAbi::WinApi),
    (
        "RtlRaiseExceptionForReturnAddressHijack",
        LogicalAbi::WinApi,
    ),
    ("RtlRaiseNoncontinuableException", LogicalAbi::WinApi),
    ("RtlRbInsertNodeEx", LogicalAbi::WinApi),
    ("RtlRbRemoveNode", LogicalAbi::WinApi),
    ("RtlReadMemoryStream", LogicalAbi::WinApi),
    ("RtlReadOutOfProcessMemoryStream", LogicalAbi::WinApi),
    ("RtlReadThreadProfilingData", LogicalAbi::WinApi),
    ("RtlRealPredecessor", LogicalAbi::WinApi),
    ("RtlRealSuccessor", LogicalAbi::WinApi),
    (
        "RtlRegisterFeatureConfigurationChangeNotification",
        LogicalAbi::WinApi,
    ),
    ("RtlRegisterForWnfMetaNotification", LogicalAbi::WinApi),
    ("RtlRegisterSecureMemoryCacheCallback", LogicalAbi::WinApi),
    ("RtlRegisterThreadWithCsrss", LogicalAbi::WinApi),
    ("RtlRegisterWait", LogicalAbi::WinApi),
    ("RtlReleaseActivationContext", LogicalAbi::WinApi),
    ("RtlReleaseMemoryStream", LogicalAbi::WinApi),
    ("RtlReleasePath", LogicalAbi::WinApi),
    ("RtlReleaseRelativeName", LogicalAbi::WinApi),
    ("RtlReleaseResource", LogicalAbi::WinApi),
    ("RtlReleaseSRWLockExclusive", LogicalAbi::WinApi),
    ("RtlReleaseSRWLockShared", LogicalAbi::WinApi),
    ("RtlRemoteCall", LogicalAbi::WinApi),
    ("RtlRemoveEntryHashTable", LogicalAbi::WinApi),
    ("RtlRemovePrivileges", LogicalAbi::WinApi),
    ("RtlReplaceSidInSd", LogicalAbi::WinApi),
    ("RtlReplaceSystemDirectoryInPath", LogicalAbi::WinApi),
    ("RtlReportException", LogicalAbi::WinApi),
    ("RtlReportExceptionEx", LogicalAbi::WinApi),
    ("RtlReportSilentProcessExit", LogicalAbi::WinApi),
    ("RtlReportSqmEscalation", LogicalAbi::WinApi),
    ("RtlResetMemoryBlockLookaside", LogicalAbi::WinApi),
    ("RtlResetMemoryZone", LogicalAbi::WinApi),
    ("RtlResetNtUserPfn", LogicalAbi::WinApi),
    ("RtlResetRtlTranslations", LogicalAbi::WinApi),
    ("RtlRestoreBootStatusDefaults", LogicalAbi::WinApi),
    ("RtlRestoreLastWin32Error", LogicalAbi::WinApi),
    ("RtlRestoreSystemBootStatusDefaults", LogicalAbi::WinApi),
    ("RtlRestoreThreadPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlRetrieveNtUserPfn", LogicalAbi::WinApi),
    ("RtlRevertMemoryStream", LogicalAbi::WinApi),
    ("RtlRunOnceBeginInitialize", LogicalAbi::WinApi),
    ("RtlRunOnceComplete", LogicalAbi::WinApi),
    ("RtlRunOnceExecuteOnce", LogicalAbi::WinApi),
    ("RtlRunOnceInitialize", LogicalAbi::WinApi),
    ("RtlSecondsSince1970ToTime", LogicalAbi::WinApi),
    ("RtlSecondsSince1980ToTime", LogicalAbi::WinApi),
    ("RtlSeekMemoryStream", LogicalAbi::WinApi),
    ("RtlSelfRelativeToAbsoluteSD2", LogicalAbi::WinApi),
    ("RtlSendMsgToSm", LogicalAbi::WinApi),
    ("RtlSetAllBits", LogicalAbi::WinApi),
    ("RtlSetAllBitsEx", LogicalAbi::WinApi),
    ("RtlSetAttributesSecurityDescriptor", LogicalAbi::WinApi),
    ("RtlSetBit", LogicalAbi::WinApi),
    ("RtlSetBitEx", LogicalAbi::WinApi),
    ("RtlSetBits", LogicalAbi::WinApi),
    ("RtlSetBitsEx", LogicalAbi::WinApi),
    ("RtlSetControlSecurityDescriptor", LogicalAbi::WinApi),
    ("RtlSetCurrentEnvironment", LogicalAbi::WinApi),
    ("RtlSetCurrentTransaction", LogicalAbi::WinApi),
    ("RtlSetDynamicTimeZoneInformation", LogicalAbi::WinApi),
    ("RtlSetEnvironmentStrings", LogicalAbi::WinApi),
    ("RtlSetEnvironmentVar", LogicalAbi::WinApi),
    ("RtlSetFeatureConfigurations", LogicalAbi::WinApi),
    ("RtlSetHeapInformation", LogicalAbi::WinApi),
    ("RtlSetImageMitigationPolicy", LogicalAbi::WinApi),
    ("RtlSetInformationAcl", LogicalAbi::WinApi),
    ("RtlSetIoCompletionCallback", LogicalAbi::WinApi),
    ("RtlSetLastWin32Error", LogicalAbi::WinApi),
    (
        "RtlSetLastWin32ErrorAndNtStatusFromNtStatus",
        LogicalAbi::WinApi,
    ),
    ("RtlSetMemoryStreamSize", LogicalAbi::WinApi),
    ("RtlSetPortableOperatingSystem", LogicalAbi::WinApi),
    ("RtlSetProcessDebugInformation", LogicalAbi::WinApi),
    ("RtlSetProcessIsCritical", LogicalAbi::WinApi),
    (
        "RtlSetProcessPlaceholderCompatibilityMode",
        LogicalAbi::WinApi,
    ),
    ("RtlSetProcessPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlSetProtectedPolicy", LogicalAbi::WinApi),
    ("RtlSetProxiedProcessId", LogicalAbi::WinApi),
    ("RtlSetSaclSecurityDescriptor", LogicalAbi::WinApi),
    ("RtlSetSearchPathMode", LogicalAbi::WinApi),
    ("RtlSetSecurityDescriptorRMControl", LogicalAbi::WinApi),
    ("RtlSetSecurityObject", LogicalAbi::WinApi),
    ("RtlSetSecurityObjectEx", LogicalAbi::WinApi),
    ("RtlSetSystemBootStatus", LogicalAbi::WinApi),
    ("RtlSetSystemBootStatusEx", LogicalAbi::WinApi),
    ("RtlSetThreadErrorMode", LogicalAbi::WinApi),
    ("RtlSetThreadIsCritical", LogicalAbi::WinApi),
    (
        "RtlSetThreadPlaceholderCompatibilityMode",
        LogicalAbi::WinApi,
    ),
    ("RtlSetThreadPoolStartFunc", LogicalAbi::WinApi),
    ("RtlSetThreadPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlSetThreadPreferredUILanguages2", LogicalAbi::WinApi),
    ("RtlSetThreadSubProcessTag", LogicalAbi::WinApi),
    ("RtlSetThreadWorkOnBehalfTicket", LogicalAbi::WinApi),
    ("RtlSetTimeZoneInformation", LogicalAbi::WinApi),
    ("RtlSetUmsThreadInformation", LogicalAbi::WinApi),
    ("RtlSidDominates", LogicalAbi::WinApi),
    ("RtlSidDominatesForTrust", LogicalAbi::WinApi),
    ("RtlSidEqualLevel", LogicalAbi::WinApi),
    ("RtlSidHashInitialize", LogicalAbi::WinApi),
    ("RtlSidHashLookup", LogicalAbi::WinApi),
    ("RtlSidIsHigherLevel", LogicalAbi::WinApi),
    ("RtlSplay", LogicalAbi::WinApi),
    ("RtlStartRXact", LogicalAbi::WinApi),
    ("RtlStatMemoryStream", LogicalAbi::WinApi),
    ("RtlStringFromGUIDEx", LogicalAbi::WinApi),
    ("RtlStronglyEnumerateEntryHashTable", LogicalAbi::WinApi),
    (
        "RtlSubscribeForFeatureUsageNotification",
        LogicalAbi::WinApi,
    ),
    ("RtlSubtreePredecessor", LogicalAbi::WinApi),
    ("RtlSubtreeSuccessor", LogicalAbi::WinApi),
    ("RtlSwitchedVVI", LogicalAbi::WinApi),
    ("RtlSystemTimeToLocalTime", LogicalAbi::WinApi),
    ("RtlTestAndPublishWnfStateData", LogicalAbi::WinApi),
    ("RtlTestBit", LogicalAbi::WinApi),
    ("RtlTestBitEx", LogicalAbi::WinApi),
    ("RtlTestProtectedAccess", LogicalAbi::WinApi),
    ("RtlTimeFieldsToTime", LogicalAbi::WinApi),
    ("RtlTimeToElapsedTimeFields", LogicalAbi::WinApi),
    ("RtlTimeToSecondsSince1970", LogicalAbi::WinApi),
    ("RtlTimeToSecondsSince1980", LogicalAbi::WinApi),
    ("RtlTimeToTimeFields", LogicalAbi::WinApi),
    ("RtlTraceDatabaseAdd", LogicalAbi::WinApi),
    ("RtlTraceDatabaseCreate", LogicalAbi::WinApi),
    ("RtlTraceDatabaseDestroy", LogicalAbi::WinApi),
    ("RtlTraceDatabaseEnumerate", LogicalAbi::WinApi),
    ("RtlTraceDatabaseFind", LogicalAbi::WinApi),
    ("RtlTraceDatabaseLock", LogicalAbi::WinApi),
    ("RtlTraceDatabaseUnlock", LogicalAbi::WinApi),
    ("RtlTraceDatabaseValidate", LogicalAbi::WinApi),
    ("RtlTryAcquirePebLock", LogicalAbi::WinApi),
    ("RtlTryAcquireSRWLockExclusive", LogicalAbi::WinApi),
    ("RtlTryAcquireSRWLockShared", LogicalAbi::WinApi),
    (
        "RtlTryConvertSRWLockSharedToExclusiveOrRelease",
        LogicalAbi::WinApi,
    ),
    ("RtlUTF8StringToUnicodeString", LogicalAbi::WinApi),
    ("RtlUdiv128", LogicalAbi::WinApi),
    ("RtlUmsThreadYield", LogicalAbi::WinApi),
    ("RtlUnhandledExceptionFilter", LogicalAbi::WinApi),
    ("RtlUnicodeStringToAnsiSize", LogicalAbi::WinApi),
    ("RtlUnicodeStringToCountedOemString", LogicalAbi::WinApi),
    ("RtlUnicodeStringToOemSize", LogicalAbi::WinApi),
    ("RtlUnicodeStringToUTF8String", LogicalAbi::WinApi),
    ("RtlUnicodeToCustomCPN", LogicalAbi::WinApi),
    ("RtlUniform", LogicalAbi::WinApi),
    ("RtlUnlockBootStatusData", LogicalAbi::WinApi),
    ("RtlUnlockCurrentThread", LogicalAbi::WinApi),
    ("RtlUnlockMemoryBlockLookaside", LogicalAbi::WinApi),
    ("RtlUnlockMemoryStreamRegion", LogicalAbi::WinApi),
    ("RtlUnlockMemoryZone", LogicalAbi::WinApi),
    ("RtlUnlockModuleSection", LogicalAbi::WinApi),
    (
        "RtlUnregisterFeatureConfigurationChangeNotification",
        LogicalAbi::WinApi,
    ),
    (
        "RtlUnsubscribeFromFeatureUsageNotifications",
        LogicalAbi::WinApi,
    ),
    (
        "RtlUnsubscribeWnfNotificationWaitForCompletion",
        LogicalAbi::WinApi,
    ),
    (
        "RtlUnsubscribeWnfNotificationWithCompletionCallback",
        LogicalAbi::WinApi,
    ),
    ("RtlUpcaseUnicodeStringToAnsiString", LogicalAbi::WinApi),
    (
        "RtlUpcaseUnicodeStringToCountedOemString",
        LogicalAbi::WinApi,
    ),
    ("RtlUpcaseUnicodeStringToOemString", LogicalAbi::WinApi),
    ("RtlUpcaseUnicodeToCustomCPN", LogicalAbi::WinApi),
    ("RtlUpcaseUnicodeToMultiByteN", LogicalAbi::WinApi),
    ("RtlUpcaseUnicodeToOemN", LogicalAbi::WinApi),
    ("RtlUpdateClonedCriticalSection", LogicalAbi::WinApi),
    ("RtlUpdateClonedSRWLock", LogicalAbi::WinApi),
    ("RtlUpdateTimer", LogicalAbi::WinApi),
    ("RtlUpperString", LogicalAbi::WinApi),
    ("RtlUserFiberStart", LogicalAbi::WinApi),
    ("RtlUserThreadStart", LogicalAbi::WinApi),
    ("RtlValidProcessProtection", LogicalAbi::WinApi),
    ("RtlValidateCorrelationVector", LogicalAbi::WinApi),
    ("RtlValidateProcessHeaps", LogicalAbi::WinApi),
    ("RtlWaitForWnfMetaNotification", LogicalAbi::WinApi),
    ("RtlWaitOnAddress", LogicalAbi::WinApi),
    ("RtlWakeAddressAll", LogicalAbi::WinApi),
    ("RtlWakeAddressAllNoFence", LogicalAbi::WinApi),
    ("RtlWakeAddressSingle", LogicalAbi::WinApi),
    ("RtlWakeAddressSingleNoFence", LogicalAbi::WinApi),
    ("RtlWeaklyEnumerateEntryHashTable", LogicalAbi::WinApi),
    ("RtlWerpReportException", LogicalAbi::WinApi),
    ("RtlWnfCompareChangeStamp", LogicalAbi::WinApi),
    ("RtlWnfDllUnloadCallback", LogicalAbi::WinApi),
    ("RtlWow64CallFunction64", LogicalAbi::WinApi),
    ("RtlWow64EnableFsRedirection", LogicalAbi::WinApi),
    ("RtlWow64EnableFsRedirectionEx", LogicalAbi::WinApi),
    ("RtlWow64GetCpuAreaInfo", LogicalAbi::WinApi),
    ("RtlWow64GetCurrentCpuArea", LogicalAbi::WinApi),
    ("RtlWow64GetCurrentMachine", LogicalAbi::WinApi),
    ("RtlWow64GetEquivalentMachineCHPE", LogicalAbi::WinApi),
    ("RtlWow64GetProcessMachines", LogicalAbi::WinApi),
    ("RtlWow64GetSharedInfoProcess", LogicalAbi::WinApi),
    ("RtlWow64GetThreadContext", LogicalAbi::WinApi),
    ("RtlWow64GetThreadSelectorEntry", LogicalAbi::WinApi),
    ("RtlWow64IsWowGuestMachineSupported", LogicalAbi::WinApi),
    ("RtlWow64LogMessageInEventLogger", LogicalAbi::WinApi),
    (
        "RtlWow64PopAllCrossProcessWorkFromWorkList",
        LogicalAbi::WinApi,
    ),
    (
        "RtlWow64PopCrossProcessWorkFromFreeList",
        LogicalAbi::WinApi,
    ),
    (
        "RtlWow64PushCrossProcessWorkOntoFreeList",
        LogicalAbi::WinApi,
    ),
    (
        "RtlWow64PushCrossProcessWorkOntoWorkList",
        LogicalAbi::WinApi,
    ),
    ("RtlWow64RequestCrossProcessHeavyFlush", LogicalAbi::WinApi),
    ("RtlWow64SetThreadContext", LogicalAbi::WinApi),
    ("RtlWow64SuspendProcess", LogicalAbi::WinApi),
    ("RtlWow64SuspendThread", LogicalAbi::WinApi),
    ("RtlWriteMemoryStream", LogicalAbi::WinApi),
    ("RtlWriteNonVolatileMemory", LogicalAbi::WinApi),
    ("RtlZeroHeap", LogicalAbi::WinApi),
    ("RtlZombifyActivationContext", LogicalAbi::WinApi),
    ("RtlpApplyLengthFunction", LogicalAbi::WinApi),
    ("RtlpCheckDynamicTimeZoneInformation", LogicalAbi::WinApi),
    ("RtlpCleanupRegistryKeys", LogicalAbi::WinApi),
    (
        "RtlpConvertAbsoluteToRelativeSecurityAttribute",
        LogicalAbi::WinApi,
    ),
    ("RtlpConvertCultureNamesToLCIDs", LogicalAbi::WinApi),
    ("RtlpConvertLCIDsToCultureNames", LogicalAbi::WinApi),
    (
        "RtlpConvertRelativeToAbsoluteSecurityAttribute",
        LogicalAbi::WinApi,
    ),
    ("RtlpCreateProcessRegistryInfo", LogicalAbi::WinApi),
    ("RtlpEnsureBufferSize", LogicalAbi::WinApi),
    ("RtlpExecuteUmsThread", LogicalAbi::WinApi),
    ("RtlpFreezeTimeBias", LogicalAbi::WinApi),
    ("RtlpGetDeviceFamilyInfoEnum", LogicalAbi::WinApi),
    ("RtlpGetLCIDFromLangInfoNode", LogicalAbi::WinApi),
    ("RtlpGetNameFromLangInfoNode", LogicalAbi::WinApi),
    ("RtlpGetSystemDefaultUILanguage", LogicalAbi::WinApi),
    ("RtlpGetUserOrMachineUILanguage4NLS", LogicalAbi::WinApi),
    ("RtlpInitializeLangRegistryInfo", LogicalAbi::WinApi),
    ("RtlpIsQualifiedLanguage", LogicalAbi::WinApi),
    ("RtlpLoadMachineUIByPolicy", LogicalAbi::WinApi),
    ("RtlpLoadUserUIByPolicy", LogicalAbi::WinApi),
    ("RtlpMergeSecurityAttributeInformation", LogicalAbi::WinApi),
    ("RtlpMuiFreeLangRegistryInfo", LogicalAbi::WinApi),
    ("RtlpMuiRegCreateRegistryInfo", LogicalAbi::WinApi),
    ("RtlpMuiRegFreeRegistryInfo", LogicalAbi::WinApi),
    ("RtlpMuiRegLoadRegistryInfo", LogicalAbi::WinApi),
    ("RtlpNotOwnerCriticalSection", LogicalAbi::WinApi),
    ("RtlpNtCreateKey", LogicalAbi::WinApi),
    ("RtlpNtEnumerateSubKey", LogicalAbi::WinApi),
    ("RtlpNtMakeTemporaryKey", LogicalAbi::WinApi),
    ("RtlpNtOpenKey", LogicalAbi::WinApi),
    ("RtlpNtQueryValueKey", LogicalAbi::WinApi),
    ("RtlpNtSetValueKey", LogicalAbi::WinApi),
    ("RtlpQueryDefaultUILanguage", LogicalAbi::WinApi),
    (
        "RtlpQueryProcessDebugInformationFromWow64",
        LogicalAbi::WinApi,
    ),
    ("RtlpQueryProcessDebugInformationRemote", LogicalAbi::WinApi),
    ("RtlpRefreshCachedUILanguage", LogicalAbi::WinApi),
    ("RtlpSetInstallLanguage", LogicalAbi::WinApi),
    ("RtlpSetPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlpSetUserPreferredUILanguages", LogicalAbi::WinApi),
    ("RtlpTimeFieldsToTime", LogicalAbi::WinApi),
    ("RtlpTimeToTimeFields", LogicalAbi::WinApi),
    ("RtlpUmsExecuteYieldThreadEnd", LogicalAbi::WinApi),
    ("RtlpUmsThreadYield", LogicalAbi::WinApi),
    ("RtlpUnWaitCriticalSection", LogicalAbi::WinApi),
    ("RtlpVerifyAndCommitUILanguageSettings", LogicalAbi::WinApi),
    ("RtlpWaitForCriticalSection", LogicalAbi::WinApi),
    ("RtlpWow64CtxFromAmd64", LogicalAbi::WinApi),
    ("RtlpWow64GetContextOnAmd64", LogicalAbi::WinApi),
    ("RtlpWow64SetContextOnAmd64", LogicalAbi::WinApi),
    ("RtlxAnsiStringToUnicodeSize", LogicalAbi::WinApi),
    ("RtlxOemStringToUnicodeSize", LogicalAbi::WinApi),
    ("RtlxUnicodeStringToAnsiSize", LogicalAbi::WinApi),
    ("RtlxUnicodeStringToOemSize", LogicalAbi::WinApi),
    ("SbExecuteProcedure", LogicalAbi::WinApi),
    ("SbSelectProcedure", LogicalAbi::WinApi),
    ("ShipAssert", LogicalAbi::WinApi),
    ("ShipAssertGetBufferInfo", LogicalAbi::WinApi),
    ("ShipAssertMsgA", LogicalAbi::WinApi),
    ("ShipAssertMsgW", LogicalAbi::WinApi),
    ("TpAllocAlpcCompletion", LogicalAbi::WinApi),
    ("TpAllocAlpcCompletionEx", LogicalAbi::WinApi),
    ("TpAllocJobNotification", LogicalAbi::WinApi),
    ("TpAlpcRegisterCompletionList", LogicalAbi::WinApi),
    ("TpAlpcUnregisterCompletionList", LogicalAbi::WinApi),
    ("TpCallbackDetectedUnrecoverableError", LogicalAbi::WinApi),
    ("TpCallbackIndependent", LogicalAbi::WinApi),
    (
        "TpCallbackLeaveCriticalSectionOnCompletion",
        LogicalAbi::WinApi,
    ),
    ("TpCallbackReleaseMutexOnCompletion", LogicalAbi::WinApi),
    ("TpCallbackReleaseSemaphoreOnCompletion", LogicalAbi::WinApi),
    ("TpCallbackSendAlpcMessageOnCompletion", LogicalAbi::WinApi),
    ("TpCallbackSendPendingAlpcMessage", LogicalAbi::WinApi),
    ("TpCallbackSetEventOnCompletion", LogicalAbi::WinApi),
    ("TpCallbackUnloadDllOnCompletion", LogicalAbi::WinApi),
    ("TpCancelAsyncIoOperation", LogicalAbi::WinApi),
    ("TpCaptureCaller", LogicalAbi::WinApi),
    ("TpCheckTerminateWorker", LogicalAbi::WinApi),
    ("TpDbgDumpHeapUsage", LogicalAbi::WinApi),
    ("TpDbgSetLogRoutine", LogicalAbi::WinApi),
    ("TpDisablePoolCallbackChecks", LogicalAbi::WinApi),
    ("TpQueryPoolStackInformation", LogicalAbi::WinApi),
    ("TpReleaseAlpcCompletion", LogicalAbi::WinApi),
    ("TpReleaseJobNotification", LogicalAbi::WinApi),
    ("TpSetDefaultPoolMaxThreads", LogicalAbi::WinApi),
    ("TpSetDefaultPoolStackInformation", LogicalAbi::WinApi),
    ("TpSetPoolMaxThreads", LogicalAbi::WinApi),
    ("TpSetPoolMaxThreadsSoftLimit", LogicalAbi::WinApi),
    ("TpSetPoolMinThreads", LogicalAbi::WinApi),
    ("TpSetPoolStackInformation", LogicalAbi::WinApi),
    ("TpSetPoolThreadBasePriority", LogicalAbi::WinApi),
    ("TpSetPoolThreadCpuSets", LogicalAbi::WinApi),
    ("TpSetPoolWorkerThreadIdleTimeout", LogicalAbi::WinApi),
    ("TpSetWait", LogicalAbi::WinApi),
    ("TpSetWaitEx", LogicalAbi::WinApi),
    ("TpSimpleTryPost", LogicalAbi::WinApi),
    ("TpStartAsyncIoOperation", LogicalAbi::WinApi),
    ("TpTimerOutstandingCallbackCount", LogicalAbi::WinApi),
    ("TpTrimPools", LogicalAbi::WinApi),
    ("TpWaitForAlpcCompletion", LogicalAbi::WinApi),
    ("TpWaitForIoCompletion", LogicalAbi::WinApi),
    ("TpWaitForJobNotification", LogicalAbi::WinApi),
    ("VerSetConditionMask", LogicalAbi::WinApi),
    ("WerReportExceptionWorker", LogicalAbi::WinApi),
    ("WerReportSQMEvent", LogicalAbi::WinApi),
    ("WinSqmAddToAverageDWORD", LogicalAbi::WinApi),
    ("WinSqmAddToStream", LogicalAbi::WinApi),
    ("WinSqmAddToStreamEx", LogicalAbi::WinApi),
    ("WinSqmCheckEscalationAddToStreamEx", LogicalAbi::WinApi),
    ("WinSqmCheckEscalationSetDWORD", LogicalAbi::WinApi),
    ("WinSqmCheckEscalationSetDWORD64", LogicalAbi::WinApi),
    ("WinSqmCheckEscalationSetString", LogicalAbi::WinApi),
    ("WinSqmCommonDatapointDelete", LogicalAbi::WinApi),
    ("WinSqmCommonDatapointSetDWORD", LogicalAbi::WinApi),
    ("WinSqmCommonDatapointSetDWORD64", LogicalAbi::WinApi),
    ("WinSqmCommonDatapointSetStreamEx", LogicalAbi::WinApi),
    ("WinSqmCommonDatapointSetString", LogicalAbi::WinApi),
    ("WinSqmEndSession", LogicalAbi::WinApi),
    ("WinSqmEventEnabled", LogicalAbi::WinApi),
    ("WinSqmEventWrite", LogicalAbi::WinApi),
    ("WinSqmGetEscalationRuleStatus", LogicalAbi::WinApi),
    ("WinSqmGetInstrumentationProperty", LogicalAbi::WinApi),
    ("WinSqmIncrementDWORD", LogicalAbi::WinApi),
    ("WinSqmIsOptedIn", LogicalAbi::WinApi),
    ("WinSqmIsOptedInEx", LogicalAbi::WinApi),
    ("WinSqmIsSessionDisabled", LogicalAbi::WinApi),
    ("WinSqmSetDWORD", LogicalAbi::WinApi),
    ("WinSqmSetDWORD64", LogicalAbi::WinApi),
    ("WinSqmSetEscalationInfo", LogicalAbi::WinApi),
    ("WinSqmSetIfMaxDWORD", LogicalAbi::WinApi),
    ("WinSqmSetIfMinDWORD", LogicalAbi::WinApi),
    ("WinSqmSetString", LogicalAbi::WinApi),
    ("WinSqmStartSession", LogicalAbi::WinApi),
    ("WinSqmStartSessionForPartner", LogicalAbi::WinApi),
    ("WinSqmStartSqmOptinListener", LogicalAbi::WinApi),
    ("ZwAcceptConnectPort", LogicalAbi::WinApi),
    ("ZwAccessCheck", LogicalAbi::WinApi),
    ("ZwAccessCheckAndAuditAlarm", LogicalAbi::WinApi),
    ("ZwAccessCheckByType", LogicalAbi::WinApi),
    ("ZwAccessCheckByTypeAndAuditAlarm", LogicalAbi::WinApi),
    ("ZwAccessCheckByTypeResultList", LogicalAbi::WinApi),
    (
        "ZwAccessCheckByTypeResultListAndAuditAlarm",
        LogicalAbi::WinApi,
    ),
    (
        "ZwAccessCheckByTypeResultListAndAuditAlarmByHandle",
        LogicalAbi::WinApi,
    ),
    ("ZwAcquireCrossVmMutant", LogicalAbi::WinApi),
    ("ZwAcquireProcessActivityReference", LogicalAbi::WinApi),
    ("ZwAddAtom", LogicalAbi::WinApi),
    ("ZwAddAtomEx", LogicalAbi::WinApi),
    ("ZwAddBootEntry", LogicalAbi::WinApi),
    ("ZwAddDriverEntry", LogicalAbi::WinApi),
    ("ZwAdjustGroupsToken", LogicalAbi::WinApi),
    ("ZwAdjustTokenClaimsAndDeviceGroups", LogicalAbi::WinApi),
    ("ZwAlertResumeThread", LogicalAbi::WinApi),
    ("ZwAlertThread", LogicalAbi::WinApi),
    ("ZwAllocateReserveObject", LogicalAbi::WinApi),
    ("ZwAllocateUserPhysicalPages", LogicalAbi::WinApi),
    ("ZwAllocateUserPhysicalPagesEx", LogicalAbi::WinApi),
    ("ZwAllocateUuids", LogicalAbi::WinApi),
    ("ZwAllocateVirtualMemoryEx", LogicalAbi::WinApi),
    ("ZwAlpcAcceptConnectPort", LogicalAbi::WinApi),
    ("ZwAlpcCancelMessage", LogicalAbi::WinApi),
    ("ZwAlpcConnectPort", LogicalAbi::WinApi),
    ("ZwAlpcConnectPortEx", LogicalAbi::WinApi),
    ("ZwAlpcCreatePort", LogicalAbi::WinApi),
    ("ZwAlpcCreatePortSection", LogicalAbi::WinApi),
    ("ZwAlpcCreateResourceReserve", LogicalAbi::WinApi),
    ("ZwAlpcCreateSectionView", LogicalAbi::WinApi),
    ("ZwAlpcCreateSecurityContext", LogicalAbi::WinApi),
    ("ZwAlpcDeletePortSection", LogicalAbi::WinApi),
    ("ZwAlpcDeleteResourceReserve", LogicalAbi::WinApi),
    ("ZwAlpcDeleteSectionView", LogicalAbi::WinApi),
    ("ZwAlpcDeleteSecurityContext", LogicalAbi::WinApi),
    ("ZwAlpcDisconnectPort", LogicalAbi::WinApi),
    ("ZwAlpcImpersonateClientContainerOfPort", LogicalAbi::WinApi),
    ("ZwAlpcImpersonateClientOfPort", LogicalAbi::WinApi),
    ("ZwAlpcOpenSenderProcess", LogicalAbi::WinApi),
    ("ZwAlpcOpenSenderThread", LogicalAbi::WinApi),
    ("ZwAlpcQueryInformation", LogicalAbi::WinApi),
    ("ZwAlpcQueryInformationMessage", LogicalAbi::WinApi),
    ("ZwAlpcRevokeSecurityContext", LogicalAbi::WinApi),
    ("ZwAlpcSendWaitReceivePort", LogicalAbi::WinApi),
    ("ZwAlpcSetInformation", LogicalAbi::WinApi),
    ("ZwApphelpCacheControl", LogicalAbi::WinApi),
    ("ZwAreMappedFilesTheSame", LogicalAbi::WinApi),
    ("ZwAssignProcessToJobObject", LogicalAbi::WinApi),
    ("ZwAssociateWaitCompletionPacket", LogicalAbi::WinApi),
    ("ZwCallEnclave", LogicalAbi::WinApi),
    ("ZwCallbackReturn", LogicalAbi::WinApi),
    ("ZwCancelIoFile", LogicalAbi::WinApi),
    ("ZwCancelIoFileEx", LogicalAbi::WinApi),
    ("ZwCancelSynchronousIoFile", LogicalAbi::WinApi),
    ("ZwCancelTimer", LogicalAbi::WinApi),
    ("ZwCancelWaitCompletionPacket", LogicalAbi::WinApi),
    ("ZwClearEvent", LogicalAbi::WinApi),
    ("ZwCloseObjectAuditAlarm", LogicalAbi::WinApi),
    ("ZwCommitComplete", LogicalAbi::WinApi),
    ("ZwCommitEnlistment", LogicalAbi::WinApi),
    ("ZwCommitRegistryTransaction", LogicalAbi::WinApi),
    ("ZwCommitTransaction", LogicalAbi::WinApi),
    ("ZwCompactKeys", LogicalAbi::WinApi),
    ("ZwCompareObjects", LogicalAbi::WinApi),
    ("ZwCompareSigningLevels", LogicalAbi::WinApi),
    ("ZwCompareTokens", LogicalAbi::WinApi),
    ("ZwCompleteConnectPort", LogicalAbi::WinApi),
    ("ZwCompressKey", LogicalAbi::WinApi),
    ("ZwConnectPort", LogicalAbi::WinApi),
    ("ZwContinueEx", LogicalAbi::WinApi),
    (
        "ZwConvertBetweenAuxiliaryCounterAndPerformanceCounter",
        LogicalAbi::WinApi,
    ),
    ("ZwCopyFileChunk", LogicalAbi::WinApi),
    ("ZwCreateCrossVmEvent", LogicalAbi::WinApi),
    ("ZwCreateCrossVmMutant", LogicalAbi::WinApi),
    ("ZwCreateDebugObject", LogicalAbi::WinApi),
    ("ZwCreateDirectoryObject", LogicalAbi::WinApi),
    ("ZwCreateDirectoryObjectEx", LogicalAbi::WinApi),
    ("ZwCreateEnclave", LogicalAbi::WinApi),
    ("ZwCreateEnlistment", LogicalAbi::WinApi),
    ("ZwCreateEventPair", LogicalAbi::WinApi),
    ("ZwCreateIRTimer", LogicalAbi::WinApi),
    ("ZwCreateIoCompletion", LogicalAbi::WinApi),
    ("ZwCreateJobObject", LogicalAbi::WinApi),
    ("ZwCreateJobSet", LogicalAbi::WinApi),
    ("ZwCreateKeyTransacted", LogicalAbi::WinApi),
    ("ZwCreateKeyedEvent", LogicalAbi::WinApi),
    ("ZwCreateLowBoxToken", LogicalAbi::WinApi),
    ("ZwCreateMailslotFile", LogicalAbi::WinApi),
    ("ZwCreateNamedPipeFile", LogicalAbi::WinApi),
    ("ZwCreatePagingFile", LogicalAbi::WinApi),
    ("ZwCreatePartition", LogicalAbi::WinApi),
    ("ZwCreatePort", LogicalAbi::WinApi),
    ("ZwCreatePrivateNamespace", LogicalAbi::WinApi),
    ("ZwCreateProfile", LogicalAbi::WinApi),
    ("ZwCreateProfileEx", LogicalAbi::WinApi),
    ("ZwCreateRegistryTransaction", LogicalAbi::WinApi),
    ("ZwCreateResourceManager", LogicalAbi::WinApi),
    ("ZwCreateSectionEx", LogicalAbi::WinApi),
    ("ZwCreateSemaphore", LogicalAbi::WinApi),
    ("ZwCreateSymbolicLinkObject", LogicalAbi::WinApi),
    ("ZwCreateThread", LogicalAbi::WinApi),
    ("ZwCreateTimer", LogicalAbi::WinApi),
    ("ZwCreateTimer2", LogicalAbi::WinApi),
    ("ZwCreateToken", LogicalAbi::WinApi),
    ("ZwCreateTokenEx", LogicalAbi::WinApi),
    ("ZwCreateTransaction", LogicalAbi::WinApi),
    ("ZwCreateTransactionManager", LogicalAbi::WinApi),
    ("ZwCreateWaitCompletionPacket", LogicalAbi::WinApi),
    ("ZwCreateWaitablePort", LogicalAbi::WinApi),
    ("ZwCreateWnfStateName", LogicalAbi::WinApi),
    ("ZwCreateWorkerFactory", LogicalAbi::WinApi),
    ("ZwDebugContinue", LogicalAbi::WinApi),
    ("ZwDeleteAtom", LogicalAbi::WinApi),
    ("ZwDeleteBootEntry", LogicalAbi::WinApi),
    ("ZwDeleteDriverEntry", LogicalAbi::WinApi),
    ("ZwDeleteObjectAuditAlarm", LogicalAbi::WinApi),
    ("ZwDeletePrivateNamespace", LogicalAbi::WinApi),
    ("ZwDeleteWnfStateData", LogicalAbi::WinApi),
    ("ZwDeleteWnfStateName", LogicalAbi::WinApi),
    ("ZwDirectGraphicsCall", LogicalAbi::WinApi),
    ("ZwDisableLastKnownGood", LogicalAbi::WinApi),
    ("ZwDisplayString", LogicalAbi::WinApi),
    ("ZwDrawText", LogicalAbi::WinApi),
    ("ZwEnableLastKnownGood", LogicalAbi::WinApi),
    ("ZwEnumerateBootEntries", LogicalAbi::WinApi),
    ("ZwEnumerateDriverEntries", LogicalAbi::WinApi),
    ("ZwEnumerateSystemEnvironmentValuesEx", LogicalAbi::WinApi),
    ("ZwEnumerateTransactionObject", LogicalAbi::WinApi),
    ("ZwExtendSection", LogicalAbi::WinApi),
    ("ZwFilterBootOption", LogicalAbi::WinApi),
    ("ZwFilterToken", LogicalAbi::WinApi),
    ("ZwFilterTokenEx", LogicalAbi::WinApi),
    ("ZwFindAtom", LogicalAbi::WinApi),
    ("ZwFlushBuffersFile", LogicalAbi::WinApi),
    ("ZwFlushBuffersFileEx", LogicalAbi::WinApi),
    ("ZwFlushInstallUILanguage", LogicalAbi::WinApi),
    ("ZwFlushInstructionCache", LogicalAbi::WinApi),
    ("ZwFlushKey", LogicalAbi::WinApi),
    ("ZwFlushProcessWriteBuffers", LogicalAbi::WinApi),
    ("ZwFlushVirtualMemory", LogicalAbi::WinApi),
    ("ZwFlushWriteBuffer", LogicalAbi::WinApi),
    ("ZwFreeUserPhysicalPages", LogicalAbi::WinApi),
    ("ZwFreezeRegistry", LogicalAbi::WinApi),
    ("ZwFreezeTransactions", LogicalAbi::WinApi),
    ("ZwGetCachedSigningLevel", LogicalAbi::WinApi),
    ("ZwGetCompleteWnfStateSubscription", LogicalAbi::WinApi),
    ("ZwGetCurrentProcessorNumber", LogicalAbi::WinApi),
    ("ZwGetCurrentProcessorNumberEx", LogicalAbi::WinApi),
    ("ZwGetDevicePowerState", LogicalAbi::WinApi),
    ("ZwGetMUIRegistryInfo", LogicalAbi::WinApi),
    ("ZwGetNextProcess", LogicalAbi::WinApi),
    ("ZwGetNextThread", LogicalAbi::WinApi),
    ("ZwGetNlsSectionPtr", LogicalAbi::WinApi),
    ("ZwGetNotificationResourceManager", LogicalAbi::WinApi),
    ("ZwGetWriteWatch", LogicalAbi::WinApi),
    ("ZwImpersonateAnonymousToken", LogicalAbi::WinApi),
    ("ZwImpersonateClientOfPort", LogicalAbi::WinApi),
    ("ZwImpersonateThread", LogicalAbi::WinApi),
    ("ZwInitializeEnclave", LogicalAbi::WinApi),
    ("ZwInitializeNlsFiles", LogicalAbi::WinApi),
    ("ZwInitializeRegistry", LogicalAbi::WinApi),
    ("ZwInitiatePowerAction", LogicalAbi::WinApi),
    ("ZwIsProcessInJob", LogicalAbi::WinApi),
    ("ZwIsSystemResumeAutomatic", LogicalAbi::WinApi),
    ("ZwIsUILanguageComitted", LogicalAbi::WinApi),
    ("ZwListenPort", LogicalAbi::WinApi),
    ("ZwLoadDriver", LogicalAbi::WinApi),
    ("ZwLoadEnclaveData", LogicalAbi::WinApi),
    ("ZwLoadKey", LogicalAbi::WinApi),
    ("ZwLoadKey2", LogicalAbi::WinApi),
    ("ZwLoadKey3", LogicalAbi::WinApi),
    ("ZwLoadKeyEx", LogicalAbi::WinApi),
    ("ZwLockFile", LogicalAbi::WinApi),
    ("ZwLockProductActivationKeys", LogicalAbi::WinApi),
    ("ZwLockRegistryKey", LogicalAbi::WinApi),
    ("ZwLockVirtualMemory", LogicalAbi::WinApi),
    ("ZwMakePermanentObject", LogicalAbi::WinApi),
    ("ZwMakeTemporaryObject", LogicalAbi::WinApi),
    ("ZwManageHotPatch", LogicalAbi::WinApi),
    ("ZwManagePartition", LogicalAbi::WinApi),
    ("ZwMapCMFModule", LogicalAbi::WinApi),
    ("ZwMapUserPhysicalPages", LogicalAbi::WinApi),
    ("ZwMapUserPhysicalPagesScatter", LogicalAbi::WinApi),
    ("ZwMapViewOfSectionEx", LogicalAbi::WinApi),
    ("ZwModifyBootEntry", LogicalAbi::WinApi),
    ("ZwModifyDriverEntry", LogicalAbi::WinApi),
    ("ZwNotifyChangeDirectoryFile", LogicalAbi::WinApi),
    ("ZwNotifyChangeDirectoryFileEx", LogicalAbi::WinApi),
    ("ZwNotifyChangeKey", LogicalAbi::WinApi),
    ("ZwNotifyChangeMultipleKeys", LogicalAbi::WinApi),
    ("ZwNotifyChangeSession", LogicalAbi::WinApi),
    ("ZwOpenDirectoryObject", LogicalAbi::WinApi),
    ("ZwOpenEnlistment", LogicalAbi::WinApi),
    ("ZwOpenEvent", LogicalAbi::WinApi),
    ("ZwOpenEventPair", LogicalAbi::WinApi),
    ("ZwOpenIoCompletion", LogicalAbi::WinApi),
    ("ZwOpenJobObject", LogicalAbi::WinApi),
    ("ZwOpenKeyTransacted", LogicalAbi::WinApi),
    ("ZwOpenKeyTransactedEx", LogicalAbi::WinApi),
    ("ZwOpenKeyedEvent", LogicalAbi::WinApi),
    ("ZwOpenMutant", LogicalAbi::WinApi),
    ("ZwOpenObjectAuditAlarm", LogicalAbi::WinApi),
    ("ZwOpenPartition", LogicalAbi::WinApi),
    ("ZwOpenPrivateNamespace", LogicalAbi::WinApi),
    ("ZwOpenProcessTokenEx", LogicalAbi::WinApi),
    ("ZwOpenRegistryTransaction", LogicalAbi::WinApi),
    ("ZwOpenResourceManager", LogicalAbi::WinApi),
    ("ZwOpenSemaphore", LogicalAbi::WinApi),
    ("ZwOpenSession", LogicalAbi::WinApi),
    ("ZwOpenSymbolicLinkObject", LogicalAbi::WinApi),
    ("ZwOpenThreadTokenEx", LogicalAbi::WinApi),
    ("ZwOpenTimer", LogicalAbi::WinApi),
    ("ZwOpenTransaction", LogicalAbi::WinApi),
    ("ZwOpenTransactionManager", LogicalAbi::WinApi),
    ("ZwPlugPlayControl", LogicalAbi::WinApi),
    ("ZwPowerInformation", LogicalAbi::WinApi),
    ("ZwPrePrepareComplete", LogicalAbi::WinApi),
    ("ZwPrePrepareEnlistment", LogicalAbi::WinApi),
    ("ZwPrepareComplete", LogicalAbi::WinApi),
    ("ZwPrepareEnlistment", LogicalAbi::WinApi),
    ("ZwPrivilegeCheck", LogicalAbi::WinApi),
    ("ZwPrivilegeObjectAuditAlarm", LogicalAbi::WinApi),
    ("ZwPrivilegedServiceAuditAlarm", LogicalAbi::WinApi),
    ("ZwPropagationComplete", LogicalAbi::WinApi),
    ("ZwPropagationFailed", LogicalAbi::WinApi),
    ("ZwPssCaptureVaSpaceBulk", LogicalAbi::WinApi),
    ("ZwPulseEvent", LogicalAbi::WinApi),
    ("ZwQueryAttributesFile", LogicalAbi::WinApi),
    ("ZwQueryAuxiliaryCounterFrequency", LogicalAbi::WinApi),
    ("ZwQueryBootEntryOrder", LogicalAbi::WinApi),
    ("ZwQueryBootOptions", LogicalAbi::WinApi),
    ("ZwQueryDebugFilterState", LogicalAbi::WinApi),
    ("ZwQueryDefaultLocale", LogicalAbi::WinApi),
    ("ZwQueryDefaultUILanguage", LogicalAbi::WinApi),
    ("ZwQueryDirectoryFileEx", LogicalAbi::WinApi),
    ("ZwQueryDirectoryObject", LogicalAbi::WinApi),
    ("ZwQueryDriverEntryOrder", LogicalAbi::WinApi),
    ("ZwQueryEaFile", LogicalAbi::WinApi),
    ("ZwQueryEvent", LogicalAbi::WinApi),
    ("ZwQueryFullAttributesFile", LogicalAbi::WinApi),
    ("ZwQueryInformationAtom", LogicalAbi::WinApi),
    ("ZwQueryInformationByName", LogicalAbi::WinApi),
    ("ZwQueryInformationEnlistment", LogicalAbi::WinApi),
    ("ZwQueryInformationJobObject", LogicalAbi::WinApi),
    ("ZwQueryInformationPort", LogicalAbi::WinApi),
    ("ZwQueryInformationResourceManager", LogicalAbi::WinApi),
    ("ZwQueryInformationTransaction", LogicalAbi::WinApi),
    ("ZwQueryInformationTransactionManager", LogicalAbi::WinApi),
    ("ZwQueryInformationWorkerFactory", LogicalAbi::WinApi),
    ("ZwQueryInstallUILanguage", LogicalAbi::WinApi),
    ("ZwQueryIntervalProfile", LogicalAbi::WinApi),
    ("ZwQueryIoCompletion", LogicalAbi::WinApi),
    ("ZwQueryKey", LogicalAbi::WinApi),
    ("ZwQueryMultipleValueKey", LogicalAbi::WinApi),
    ("ZwQueryMutant", LogicalAbi::WinApi),
    ("ZwQueryOpenSubKeys", LogicalAbi::WinApi),
    ("ZwQueryOpenSubKeysEx", LogicalAbi::WinApi),
    ("ZwQueryPortInformationProcess", LogicalAbi::WinApi),
    ("ZwQueryQuotaInformationFile", LogicalAbi::WinApi),
    ("ZwQuerySection", LogicalAbi::WinApi),
    ("ZwQuerySecurityAttributesToken", LogicalAbi::WinApi),
    ("ZwQuerySecurityObject", LogicalAbi::WinApi),
    ("ZwQuerySecurityPolicy", LogicalAbi::WinApi),
    ("ZwQuerySemaphore", LogicalAbi::WinApi),
    ("ZwQuerySymbolicLinkObject", LogicalAbi::WinApi),
    ("ZwQuerySystemEnvironmentValue", LogicalAbi::WinApi),
    ("ZwQuerySystemEnvironmentValueEx", LogicalAbi::WinApi),
    ("ZwQuerySystemInformationEx", LogicalAbi::WinApi),
    ("ZwQuerySystemTime", LogicalAbi::WinApi),
    ("ZwQueryTimer", LogicalAbi::WinApi),
    ("ZwQueryTimerResolution", LogicalAbi::WinApi),
    ("ZwQueryVolumeInformationFile", LogicalAbi::WinApi),
    ("ZwQueryWnfStateData", LogicalAbi::WinApi),
    ("ZwQueryWnfStateNameInformation", LogicalAbi::WinApi),
    ("ZwQueueApcThreadEx", LogicalAbi::WinApi),
    ("ZwQueueApcThreadEx2", LogicalAbi::WinApi),
    ("ZwRaiseException", LogicalAbi::WinApi),
    ("ZwRaiseHardError", LogicalAbi::WinApi),
    ("ZwReadFileScatter", LogicalAbi::WinApi),
    ("ZwReadOnlyEnlistment", LogicalAbi::WinApi),
    ("ZwReadRequestData", LogicalAbi::WinApi),
    ("ZwRecoverEnlistment", LogicalAbi::WinApi),
    ("ZwRecoverResourceManager", LogicalAbi::WinApi),
    ("ZwRecoverTransactionManager", LogicalAbi::WinApi),
    ("ZwRegisterProtocolAddressInformation", LogicalAbi::WinApi),
    ("ZwRegisterThreadTerminatePort", LogicalAbi::WinApi),
    ("ZwReleaseKeyedEvent", LogicalAbi::WinApi),
    ("ZwReleaseSemaphore", LogicalAbi::WinApi),
    ("ZwReleaseWorkerFactoryWorker", LogicalAbi::WinApi),
    ("ZwRemoveIoCompletion", LogicalAbi::WinApi),
    ("ZwRemoveIoCompletionEx", LogicalAbi::WinApi),
    ("ZwRenameKey", LogicalAbi::WinApi),
    ("ZwRenameTransactionManager", LogicalAbi::WinApi),
    ("ZwReplaceKey", LogicalAbi::WinApi),
    ("ZwReplacePartitionUnit", LogicalAbi::WinApi),
    ("ZwReplyPort", LogicalAbi::WinApi),
    ("ZwReplyWaitReceivePort", LogicalAbi::WinApi),
    ("ZwReplyWaitReceivePortEx", LogicalAbi::WinApi),
    ("ZwReplyWaitReplyPort", LogicalAbi::WinApi),
    ("ZwRequestPort", LogicalAbi::WinApi),
    ("ZwRequestWaitReplyPort", LogicalAbi::WinApi),
    ("ZwResetEvent", LogicalAbi::WinApi),
    ("ZwResetWriteWatch", LogicalAbi::WinApi),
    ("ZwRestoreKey", LogicalAbi::WinApi),
    ("ZwResumeProcess", LogicalAbi::WinApi),
    ("ZwRevertContainerImpersonation", LogicalAbi::WinApi),
    ("ZwRollbackComplete", LogicalAbi::WinApi),
    ("ZwRollbackEnlistment", LogicalAbi::WinApi),
    ("ZwRollbackRegistryTransaction", LogicalAbi::WinApi),
    ("ZwRollbackTransaction", LogicalAbi::WinApi),
    ("ZwRollforwardTransactionManager", LogicalAbi::WinApi),
    ("ZwSaveKey", LogicalAbi::WinApi),
    ("ZwSaveKeyEx", LogicalAbi::WinApi),
    ("ZwSaveMergedKeys", LogicalAbi::WinApi),
    ("ZwSecureConnectPort", LogicalAbi::WinApi),
    ("ZwSerializeBoot", LogicalAbi::WinApi),
    ("ZwSetBootEntryOrder", LogicalAbi::WinApi),
    ("ZwSetBootOptions", LogicalAbi::WinApi),
    ("ZwSetCachedSigningLevel", LogicalAbi::WinApi),
    ("ZwSetCachedSigningLevel2", LogicalAbi::WinApi),
    ("ZwSetDebugFilterState", LogicalAbi::WinApi),
    ("ZwSetDefaultHardErrorPort", LogicalAbi::WinApi),
    ("ZwSetDefaultLocale", LogicalAbi::WinApi),
    ("ZwSetDefaultUILanguage", LogicalAbi::WinApi),
    ("ZwSetDriverEntryOrder", LogicalAbi::WinApi),
    ("ZwSetEaFile", LogicalAbi::WinApi),
    ("ZwSetEventBoostPriority", LogicalAbi::WinApi),
    ("ZwSetHighEventPair", LogicalAbi::WinApi),
    ("ZwSetHighWaitLowEventPair", LogicalAbi::WinApi),
    ("ZwSetIRTimer", LogicalAbi::WinApi),
    ("ZwSetInformationDebugObject", LogicalAbi::WinApi),
    ("ZwSetInformationEnlistment", LogicalAbi::WinApi),
    ("ZwSetInformationJobObject", LogicalAbi::WinApi),
    ("ZwSetInformationObject", LogicalAbi::WinApi),
    ("ZwSetInformationProcess", LogicalAbi::WinApi),
    ("ZwSetInformationResourceManager", LogicalAbi::WinApi),
    ("ZwSetInformationSymbolicLink", LogicalAbi::WinApi),
    ("ZwSetInformationToken", LogicalAbi::WinApi),
    ("ZwSetInformationTransaction", LogicalAbi::WinApi),
    ("ZwSetInformationTransactionManager", LogicalAbi::WinApi),
    ("ZwSetInformationVirtualMemory", LogicalAbi::WinApi),
    ("ZwSetInformationWorkerFactory", LogicalAbi::WinApi),
    ("ZwSetIntervalProfile", LogicalAbi::WinApi),
    ("ZwSetIoCompletion", LogicalAbi::WinApi),
    ("ZwSetIoCompletionEx", LogicalAbi::WinApi),
    ("ZwSetLdtEntries", LogicalAbi::WinApi),
    ("ZwSetLowEventPair", LogicalAbi::WinApi),
    ("ZwSetLowWaitHighEventPair", LogicalAbi::WinApi),
    ("ZwSetQuotaInformationFile", LogicalAbi::WinApi),
    ("ZwSetSecurityObject", LogicalAbi::WinApi),
    ("ZwSetSystemEnvironmentValue", LogicalAbi::WinApi),
    ("ZwSetSystemEnvironmentValueEx", LogicalAbi::WinApi),
    ("ZwSetSystemInformation", LogicalAbi::WinApi),
    ("ZwSetSystemPowerState", LogicalAbi::WinApi),
    ("ZwSetSystemTime", LogicalAbi::WinApi),
    ("ZwSetThreadExecutionState", LogicalAbi::WinApi),
    ("ZwSetTimer", LogicalAbi::WinApi),
    ("ZwSetTimerResolution", LogicalAbi::WinApi),
    ("ZwSetUuidSeed", LogicalAbi::WinApi),
    ("ZwSetVolumeInformationFile", LogicalAbi::WinApi),
    ("ZwSetWnfProcessNotificationEvent", LogicalAbi::WinApi),
    ("ZwShutdownSystem", LogicalAbi::WinApi),
    ("ZwShutdownWorkerFactory", LogicalAbi::WinApi),
    ("ZwSignalAndWaitForSingleObject", LogicalAbi::WinApi),
    ("ZwSinglePhaseReject", LogicalAbi::WinApi),
    ("ZwStartProfile", LogicalAbi::WinApi),
    ("ZwStopProfile", LogicalAbi::WinApi),
    ("ZwSubscribeWnfStateChange", LogicalAbi::WinApi),
    ("ZwSuspendProcess", LogicalAbi::WinApi),
    ("ZwSystemDebugControl", LogicalAbi::WinApi),
    ("ZwTerminateEnclave", LogicalAbi::WinApi),
    ("ZwTerminateJobObject", LogicalAbi::WinApi),
    ("ZwTestAlert", LogicalAbi::WinApi),
    ("ZwThawRegistry", LogicalAbi::WinApi),
    ("ZwThawTransactions", LogicalAbi::WinApi),
    ("ZwTraceControl", LogicalAbi::WinApi),
    ("ZwTraceEvent", LogicalAbi::WinApi),
    ("ZwTranslateFilePath", LogicalAbi::WinApi),
    ("ZwUmsThreadYield", LogicalAbi::WinApi),
    ("ZwUnloadDriver", LogicalAbi::WinApi),
    ("ZwUnloadKey", LogicalAbi::WinApi),
    ("ZwUnloadKey2", LogicalAbi::WinApi),
    ("ZwUnloadKeyEx", LogicalAbi::WinApi),
    ("ZwUnlockFile", LogicalAbi::WinApi),
    ("ZwUnlockVirtualMemory", LogicalAbi::WinApi),
    ("ZwUnmapViewOfSectionEx", LogicalAbi::WinApi),
    ("ZwUnsubscribeWnfStateChange", LogicalAbi::WinApi),
    ("ZwUpdateWnfStateData", LogicalAbi::WinApi),
    ("ZwVdmControl", LogicalAbi::WinApi),
    ("ZwWaitForDebugEvent", LogicalAbi::WinApi),
    ("ZwWaitForKeyedEvent", LogicalAbi::WinApi),
    ("ZwWaitForMultipleObjects32", LogicalAbi::WinApi),
    ("ZwWaitForWorkViaWorkerFactory", LogicalAbi::WinApi),
    ("ZwWaitHighEventPair", LogicalAbi::WinApi),
    ("ZwWaitLowEventPair", LogicalAbi::WinApi),
    ("ZwWorkerFactoryWorkerReady", LogicalAbi::WinApi),
    ("ZwWriteFileGather", LogicalAbi::WinApi),
    ("ZwWriteRequestData", LogicalAbi::WinApi),
    ("ZwYieldExecution", LogicalAbi::WinApi),
    ("__C_specific_handler", LogicalAbi::WinApi),
    ("__chkstk", LogicalAbi::WinApi),
    ("__iscsym", LogicalAbi::WinApi),
    ("__iscsymf", LogicalAbi::WinApi),
    ("__misaligned_access", LogicalAbi::WinApi),
    ("_errno", LogicalAbi::WinApi),
    ("_fltused", LogicalAbi::WinApi),
    ("_i64toa_s", LogicalAbi::WinApi),
    ("_i64tow_s", LogicalAbi::WinApi),
    ("_itoa", LogicalAbi::WinApi),
    ("_itoa_s", LogicalAbi::WinApi),
    ("_itow_s", LogicalAbi::WinApi),
    ("_lfind", LogicalAbi::WinApi),
    ("_local_unwind", LogicalAbi::WinApi),
    ("_ltoa", LogicalAbi::WinApi),
    ("_ltoa_s", LogicalAbi::WinApi),
    ("_ltow_s", LogicalAbi::WinApi),
    ("_makepath_s", LogicalAbi::WinApi),
    ("_memccpy", LogicalAbi::WinApi),
    ("_memicmp", LogicalAbi::WinApi),
    ("_setjmp", LogicalAbi::WinApi),
    ("_setjmpex", LogicalAbi::WinApi),
    ("_snprintf_s", LogicalAbi::WinApi),
    ("_snscanf_s", LogicalAbi::WinApi),
    ("_snwprintf_s", LogicalAbi::WinApi),
    ("_snwscanf_s", LogicalAbi::WinApi),
    ("_splitpath", LogicalAbi::WinApi),
    ("_splitpath_s", LogicalAbi::WinApi),
    ("_strcmpi", LogicalAbi::WinApi),
    ("_strlwr", LogicalAbi::WinApi),
    ("_strlwr_s", LogicalAbi::WinApi),
    ("_strnset_s", LogicalAbi::WinApi),
    ("_strset_s", LogicalAbi::WinApi),
    ("_strupr", LogicalAbi::WinApi),
    ("_strupr_s", LogicalAbi::WinApi),
    ("_swprintf", LogicalAbi::WinApi),
    ("_ui64toa_s", LogicalAbi::WinApi),
    ("_ui64tow_s", LogicalAbi::WinApi),
    ("_ultoa", LogicalAbi::WinApi),
    ("_ultoa_s", LogicalAbi::WinApi),
    ("_ultow_s", LogicalAbi::WinApi),
    ("_vscprintf", LogicalAbi::WinApi),
    ("_vscwprintf", LogicalAbi::WinApi),
    ("_vsnprintf_s", LogicalAbi::WinApi),
    ("_vsnwprintf_s", LogicalAbi::WinApi),
    ("_vswprintf", LogicalAbi::WinApi),
    ("_wcslwr", LogicalAbi::WinApi),
    ("_wcslwr_s", LogicalAbi::WinApi),
    ("_wcsnset_s", LogicalAbi::WinApi),
    ("_wcsset_s", LogicalAbi::WinApi),
    ("_wcstoi64", LogicalAbi::WinApi),
    ("_wcstoui64", LogicalAbi::WinApi),
    ("_wcsupr", LogicalAbi::WinApi),
    ("_wcsupr_s", LogicalAbi::WinApi),
    ("_wmakepath_s", LogicalAbi::WinApi),
    ("_wsplitpath_s", LogicalAbi::WinApi),
    ("atan", LogicalAbi::WinApi),
    ("atan2", LogicalAbi::WinApi),
    ("bsearch_s", LogicalAbi::WinApi),
    ("ceil", LogicalAbi::WinApi),
    ("cos", LogicalAbi::WinApi),
    ("fabs", LogicalAbi::WinApi),
    ("floor", LogicalAbi::WinApi),
    ("iswalnum", LogicalAbi::WinApi),
    ("iswalpha", LogicalAbi::WinApi),
    ("iswascii", LogicalAbi::WinApi),
    ("iswctype", LogicalAbi::WinApi),
    ("iswdigit", LogicalAbi::WinApi),
    ("iswgraph", LogicalAbi::WinApi),
    ("iswlower", LogicalAbi::WinApi),
    ("iswprint", LogicalAbi::WinApi),
    ("iswspace", LogicalAbi::WinApi),
    ("iswxdigit", LogicalAbi::WinApi),
    ("log", LogicalAbi::WinApi),
    ("longjmp", LogicalAbi::WinApi),
    ("mbstowcs", LogicalAbi::WinApi),
    ("memcpy_s", LogicalAbi::WinApi),
    ("memmove_s", LogicalAbi::WinApi),
    ("pow", LogicalAbi::WinApi),
    ("qsort_s", LogicalAbi::WinApi),
    ("sin", LogicalAbi::WinApi),
    ("sprintf_s", LogicalAbi::WinApi),
    ("sqrt", LogicalAbi::WinApi),
    ("sscanf_s", LogicalAbi::WinApi),
    ("strcat_s", LogicalAbi::WinApi),
    ("strcpy_s", LogicalAbi::WinApi),
    ("strncat_s", LogicalAbi::WinApi),
    ("strncpy_s", LogicalAbi::WinApi),
    ("strtok_s", LogicalAbi::WinApi),
    ("swprintf_s", LogicalAbi::WinApi),
    ("swscanf_s", LogicalAbi::WinApi),
    ("tan", LogicalAbi::WinApi),
    ("towlower", LogicalAbi::WinApi),
    ("towupper", LogicalAbi::WinApi),
    ("vDbgPrintEx", LogicalAbi::WinApi),
    ("vDbgPrintExWithPrefix", LogicalAbi::WinApi),
    ("vsprintf_s", LogicalAbi::WinApi),
    ("vswprintf_s", LogicalAbi::WinApi),
    ("wcscat_s", LogicalAbi::WinApi),
    ("wcscpy_s", LogicalAbi::WinApi),
    ("wcsncat_s", LogicalAbi::WinApi),
    ("wcsncpy_s", LogicalAbi::WinApi),
    ("wcstok_s", LogicalAbi::WinApi),
];
