use crate::hooks::base::HookLibrary;
use crate::hooks::registry::HookRegistry;
use crate::hooks::stub::stub_definitions;

const EXPORTS: &[(&str, &str, usize, crate::hooks::base::CallConv)] = &[
    (
        "mpr.dll",
        "MultinetGetConnectionPerformanceA",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "MultinetGetConnectionPerformanceW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetAddConnectionA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetAddConnectionW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetAddConnection2A",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetAddConnection2W",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetAddConnection3A",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetAddConnection3W",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetUseConnectionA",
        8,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetUseConnectionW",
        8,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetCancelConnectionA",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetCancelConnectionW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetCancelConnection2A",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetCancelConnection2W",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetOpenEnumA",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetOpenEnumW",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetEnumResourceA",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetEnumResourceW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetCloseEnum",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetConnectionA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetConnectionW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetLastErrorA",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetLastErrorW",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetNetworkInformationA",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetNetworkInformationW",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetProviderNameA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetProviderNameW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetResourceInformationA",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetResourceInformationW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetResourceParentA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetResourceParentW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetUniversalNameA",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetUniversalNameW",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetUserA",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "mpr.dll",
        "WNetGetUserW",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
];

/// Collects the generated hook definitions for this DLL family.
#[derive(Debug, Default, Clone, Copy)]
pub struct MprHookLibrary;

impl HookLibrary for MprHookLibrary {
    fn collect(&self) -> Vec<crate::hooks::base::HookDefinition> {
        stub_definitions(EXPORTS)
    }
}

/// Registers the generated hook definitions for this DLL family.
pub fn register_mpr_hooks(registry: &mut HookRegistry) {
    registry.register_library(&MprHookLibrary);
}
