//! Full `HookSignature` table for `mpr.dll` functions.
//!
//! Covers Windows Networking (WNet) API: connection management,
// resource enumeration, network information, provider queries,
// universal name resolution, and user retrieval.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static MPR_SIGNATURES: &[HookSignature] = &[
    // ── Connection Performance ────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "MultinetGetConnectionPerformanceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpConnectInfo", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "MultinetGetConnectionPerformanceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpConnectInfo", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Add Connection ────────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetAddConnectionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpRemoteName", PCStr),
            ParamSpec::new("lpPassword", PCStr),
            ParamSpec::new("lpLocalName", PCStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetAddConnectionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpRemoteName", PCWStr),
            ParamSpec::new("lpPassword", PCWStr),
            ParamSpec::new("lpLocalName", PCWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetAddConnection2A",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpPassword", PCStr),
            ParamSpec::new("lpUserName", PCStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetAddConnection2W",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpPassword", PCWStr),
            ParamSpec::new("lpUserName", PCWStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetAddConnection3A",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwndOwner", Handle),
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpPassword", PCStr),
            ParamSpec::new("lpUserName", PCStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetAddConnection3W",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwndOwner", Handle),
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpPassword", PCWStr),
            ParamSpec::new("lpUserName", PCWStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Use Connection ────────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetUseConnectionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwndOwner", Handle),
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpPassword", PCStr),
            ParamSpec::new("lpUserName", PCStr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpAccessName", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
            ParamSpec::new("lpResult", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetUseConnectionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hwndOwner", Handle),
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpPassword", PCWStr),
            ParamSpec::new("lpUserName", PCWStr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpAccessName", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
            ParamSpec::new("lpResult", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Cancel Connection ─────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetCancelConnectionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCStr),
            ParamSpec::new("fForce", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetCancelConnectionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("fForce", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetCancelConnection2A",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCStr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("fForce", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetCancelConnection2W",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("fForce", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Resource Enumeration ──────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetOpenEnumA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwScope", U32),
            ParamSpec::new("dwType", U32),
            ParamSpec::new("dwUsage", U32),
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lphEnum", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetOpenEnumW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwScope", U32),
            ParamSpec::new("dwType", U32),
            ParamSpec::new("dwUsage", U32),
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lphEnum", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetEnumResourceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hEnum", Handle),
            ParamSpec::new("lpcCount", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetEnumResourceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hEnum", Handle),
            ParamSpec::new("lpcCount", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetCloseEnum",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hEnum", Handle)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Connection Query ──────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetConnectionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocalName", PCStr),
            ParamSpec::new("lpRemoteName", GuestPtr),
            ParamSpec::new("lpnLength", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetConnectionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocalName", PCWStr),
            ParamSpec::new("lpRemoteName", GuestPtr),
            ParamSpec::new("lpnLength", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Error Retrieval ───────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetLastErrorA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpError", GuestPtr),
            ParamSpec::new("lpErrorBuf", GuestPtr),
            ParamSpec::new("nErrorBufSize", U32),
            ParamSpec::new("lpNameBuf", GuestPtr),
            ParamSpec::new("nNameBufSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetLastErrorW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpError", GuestPtr),
            ParamSpec::new("lpErrorBuf", GuestPtr),
            ParamSpec::new("nErrorBufSize", U32),
            ParamSpec::new("lpNameBuf", GuestPtr),
            ParamSpec::new("nNameBufSize", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Network Information ───────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetNetworkInformationA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpProvider", PCStr),
            ParamSpec::new("lpNetInfoStruct", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetNetworkInformationW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpProvider", PCWStr),
            ParamSpec::new("lpNetInfoStruct", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Provider Name ─────────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetProviderNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwNetType", U32),
            ParamSpec::new("lpProviderName", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetProviderNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("dwNetType", U32),
            ParamSpec::new("lpProviderName", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Resource Information ──────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetResourceInformationA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpcbBuffer", GuestPtr),
            ParamSpec::new("lplpSystem", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetResourceInformationW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpcbBuffer", GuestPtr),
            ParamSpec::new("lplpSystem", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Resource Parent ───────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetResourceParentA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpcbBuffer", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetResourceParentW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpNetResource", GuestPtr),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpcbBuffer", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Universal Name ────────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetUniversalNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocalPath", PCStr),
            ParamSpec::new("dwInfoLevel", U32),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetUniversalNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpLocalPath", PCWStr),
            ParamSpec::new("dwInfoLevel", U32),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("lpBufferSize", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── User Retrieval ────────────────────────────────────────────────────
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetUserA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCStr),
            ParamSpec::new("lpUserName", GuestPtr),
            ParamSpec::new("lpnLength", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "mpr.dll",
        function: "WNetGetUserW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::new("lpUserName", GuestPtr),
            ParamSpec::new("lpnLength", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
];
