//! Full `HookSignature` table for `netapi32.dll` functions.
//!
//! Covers Windows Network Management API: NetBIOS, buffer management,
// domain info, workstation/user/group enumeration, file/session/share
// management, server info, and DS role.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static NETAPI32_SIGNATURES: &[HookSignature] = &[
    // ── NetBIOS ───────────────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "Netbios",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pncb", OpaqueStructPtr("NCB"))],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Buffer Management ─────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetApiBufferFree",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Buffer", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Domain Information ────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetGetJoinInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpServer", PCWStr),
            ParamSpec::new("lpNameBuffer", GuestPtr),
            ParamSpec::new("BufferType", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetGetDCName",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("domainname", PCWStr),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetGetAnyDCName",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("domainname", PCWStr),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Workstation Info ──────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetWkstaGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── User Enumeration ──────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetUserEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("filter", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUserGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("username", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUserAdd",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("parm_err", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUserSetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("username", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("parm_err", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetLocalGroupAddMembers",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("groupname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("totalentries", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetLocalGroupDelMembers",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("groupname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("totalentries", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Group Enumeration ─────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetGroupEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetGroupGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("groupname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUserGetGroups",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("username", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetGroupGetUsers",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("groupname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Use (Redirection) Management ──────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetUseEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUseAdd",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("parm_err", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUseDel",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("usename", PCWStr),
            ParamSpec::new("forcecond", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUseGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("usename", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── File Management ───────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetFileEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("basepath", PCWStr),
            ParamSpec::new("username", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetFileGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("fileid", U32),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetFileClose",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("fileid", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Connection Enumeration ────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetConnectionEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("qualifier", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Share Management ──────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetShareCheck",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("device", PCWStr),
            ParamSpec::new("type", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetRemoteTOD",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetShareEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetShareGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("netname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Session Enumeration ───────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetSessionEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("UncClientName", PCWStr),
            ParamSpec::new("username", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Workstation User Enumeration ──────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetWkstaUserEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Local Group Enumeration ───────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetLocalGroupEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetUserGetLocalGroups",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("username", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("flags", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetLocalGroupGetMembers",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("localgroupname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetLocalGroupGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("groupname", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Server Information ────────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "NetServerGetInfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "NetServerEnum",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("servername", PCWStr),
            ParamSpec::new("level", U32),
            ParamSpec::new("bufptr", GuestPtr),
            ParamSpec::new("prefmaxlen", U32),
            ParamSpec::new("entriesread", GuestPtr),
            ParamSpec::new("totalentries", GuestPtr),
            ParamSpec::new("servertype", U32),
            ParamSpec::new("domain", PCWStr),
            ParamSpec::new("resume_handle", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── DS Role & Domain Trust ────────────────────────────────────────────
    HookSignature {
        module: "netapi32.dll",
        function: "DsRoleGetPrimaryDomainInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpServer", PCWStr),
            ParamSpec::new("InfoLevel", U32),
            ParamSpec::new("Buffer", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "DsGetDcNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ComputerName", PCStr),
            ParamSpec::new("DomainName", PCStr),
            ParamSpec::new("DomainGuid", GuidPtr),
            ParamSpec::new("SiteName", PCStr),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("DomainControllerInfo", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "DsGetDcNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ComputerName", PCWStr),
            ParamSpec::new("DomainName", PCWStr),
            ParamSpec::new("DomainGuid", GuidPtr),
            ParamSpec::new("SiteName", PCWStr),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("DomainControllerInfo", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "DsEnumerateDomainTrustsA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ServerName", PCStr),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("Domains", GuestPtr),
            ParamSpec::new("DomainCount", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "DsEnumerateDomainTrustsW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ServerName", PCWStr),
            ParamSpec::new("Flags", U32),
            ParamSpec::new("Domains", GuestPtr),
            ParamSpec::new("DomainCount", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "netapi32.dll",
        function: "DsRoleFreeMemory",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("Buffer", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
];
