//! Full `HookSignature` table for `wininet.dll` functions.
//!
//! Covers WinINet API: HTTP sessions, URL management, FTP operations,
//! cookie management, and Internet configuration.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(super) static WININET_SIGNATURES: &[HookSignature] = &[
    // ── Session Initialization ────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetOpenA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszAgent", PCStr),
            ParamSpec::new("dwAccessType", U32),
            ParamSpec::new("lpszProxy", PCStr),
            ParamSpec::new("lpszProxyBypass", PCStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetOpenW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszAgent", PCWStr),
            ParamSpec::new("dwAccessType", U32),
            ParamSpec::new("lpszProxy", PCWStr),
            ParamSpec::new("lpszProxyBypass", PCWStr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Connection Management ─────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetConnectA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("lpszServerName", PCStr),
            ParamSpec::new("nServerPort", U16),
            ParamSpec::new("lpszUserName", PCStr),
            ParamSpec::new("lpszPassword", PCStr),
            ParamSpec::new("dwService", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetConnectW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("lpszServerName", PCWStr),
            ParamSpec::new("nServerPort", U16),
            ParamSpec::new("lpszUserName", PCWStr),
            ParamSpec::new("lpszPassword", PCWStr),
            ParamSpec::new("dwService", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── URL Opening ───────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetOpenUrlA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("lpszUrl", PCStr),
            ParamSpec::new("lpszHeaders", PCStr),
            ParamSpec::new("dwHeadersLength", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetOpenUrlW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("lpszUrl", PCWStr),
            ParamSpec::new("lpszHeaders", PCWStr),
            ParamSpec::new("dwHeadersLength", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── HTTP Request ──────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "HttpOpenRequestA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hConnect", Handle),
            ParamSpec::new("lpszVerb", PCStr),
            ParamSpec::new("lpszObjectName", PCStr),
            ParamSpec::new("lpszVersion", PCStr),
            ParamSpec::new("lpszReferrer", PCStr),
            ParamSpec::new("lplpszAcceptTypes", GuestPtr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "HttpOpenRequestW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hConnect", Handle),
            ParamSpec::new("lpszVerb", PCWStr),
            ParamSpec::new("lpszObjectName", PCWStr),
            ParamSpec::new("lpszVersion", PCWStr),
            ParamSpec::new("lpszReferrer", PCWStr),
            ParamSpec::new("lplpszAcceptTypes", GuestPtr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "HttpSendRequestA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hRequest", Handle),
            ParamSpec::new("lpszHeaders", PCStr),
            ParamSpec::new("dwHeadersLength", U32),
            ParamSpec::new("lpOptional", GuestPtr),
            ParamSpec::new("dwOptionalLength", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "HttpSendRequestW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hRequest", Handle),
            ParamSpec::new("lpszHeaders", PCWStr),
            ParamSpec::new("dwHeadersLength", U32),
            ParamSpec::new("lpOptional", GuestPtr),
            ParamSpec::new("dwOptionalLength", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── URL Utilities ─────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetCanonicalizeUrlA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszUrl", PCStr),
            ParamSpec::new("lpszBuffer", PStr),
            ParamSpec::with_dir("lpdwBufferLength", GuestPtr, InOut),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetCanonicalizeUrlW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszUrl", PCWStr),
            ParamSpec::new("lpszBuffer", PWStr),
            ParamSpec::with_dir("lpdwBufferLength", GuestPtr, InOut),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Data Transfer ─────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetReadFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("dwNumberOfBytesToRead", U32),
            ParamSpec::with_dir("lpdwNumberOfBytesRead", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Handle Management ─────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetCloseHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hInternet", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Internet Options ──────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetSetOptionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("dwOption", U32),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("dwBufferLength", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetSetOptionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("dwOption", U32),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::new("dwBufferLength", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetQueryOptionA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("dwOption", U32),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::with_dir("lpdwBufferLength", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetQueryOptionW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hInternet", Handle),
            ParamSpec::new("dwOption", U32),
            ParamSpec::new("lpBuffer", GuestPtr),
            ParamSpec::with_dir("lpdwBufferLength", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── URL Cracking ──────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetCrackUrlA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszUrl", PCStr),
            ParamSpec::new("dwUrlLength", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpUrlComponents", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "InternetCrackUrlW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszUrl", PCWStr),
            ParamSpec::new("dwUrlLength", U32),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpUrlComponents", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Connectivity ──────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetGetConnectedState",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpdwFlags", GuestPtr, InOut),
            ParamSpec::new("dwReserved", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Data Query ────────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "InternetQueryDataAvailable",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hFile", Handle),
            ParamSpec::with_dir("lpdwNumberOfBytesAvailable", GuestPtr, Out),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("dwContext", PointerSizedUInt),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── HTTP Query ────────────────────────────────────────────────────────
    HookSignature {
        module: "wininet.dll",
        function: "HttpQueryInfoA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hRequest", Handle),
            ParamSpec::new("dwInfoLevel", U32),
            ParamSpec::new("lpvBuffer", GuestPtr),
            ParamSpec::with_dir("lpdwBufferLength", GuestPtr, InOut),
            ParamSpec::with_dir("lpdwIndex", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wininet.dll",
        function: "HttpQueryInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hRequest", Handle),
            ParamSpec::new("dwInfoLevel", U32),
            ParamSpec::new("lpvBuffer", GuestPtr),
            ParamSpec::with_dir("lpdwBufferLength", GuestPtr, InOut),
            ParamSpec::with_dir("lpdwIndex", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
