//! Full `HookSignature` table for `wldap32.dll` functions.
//!
//! Covers LDAP (Lightweight Directory Access Protocol) API:
//! session management, binding, searching, result iteration,
//! value extraction, and memory management.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static WLDAP32_SIGNATURES: &[HookSignature] = &[
    // ── Session Initialization ────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_openA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("HostName", PCStr),
            ParamSpec::new("PortNumber", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_openW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("HostName", PCWStr),
            ParamSpec::new("PortNumber", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_initA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("HostName", PCStr),
            ParamSpec::new("PortNumber", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_initW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("HostName", PCWStr),
            ParamSpec::new("PortNumber", U32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_sslinitA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("HostName", PCStr),
            ParamSpec::new("PortNumber", U32),
            ParamSpec::new("secure", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_sslinitW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("HostName", PCWStr),
            ParamSpec::new("PortNumber", U32),
            ParamSpec::new("secure", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Connection & Binding ──────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_connect",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("timeout", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_bindA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("dn", PCStr),
            ParamSpec::new("cred", GuestPtr),
            ParamSpec::new("method", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_bindW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("dn", PCWStr),
            ParamSpec::new("cred", GuestPtr),
            ParamSpec::new("method", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_bind_sA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("dn", PCStr),
            ParamSpec::new("cred", GuestPtr),
            ParamSpec::new("method", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_bind_sW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("dn", PCWStr),
            ParamSpec::new("cred", GuestPtr),
            ParamSpec::new("method", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_simple_bind_sA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("dn", PCStr),
            ParamSpec::new("passwd", PCStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_simple_bind_sW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("dn", PCWStr),
            ParamSpec::new("passwd", PCWStr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Search Operations ─────────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_searchA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("base", PCStr),
            ParamSpec::new("scope", U32),
            ParamSpec::new("filter", PCStr),
            ParamSpec::new("attrs", GuestPtr),
            ParamSpec::new("attrsonly", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_searchW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("base", PCWStr),
            ParamSpec::new("scope", U32),
            ParamSpec::new("filter", PCWStr),
            ParamSpec::new("attrs", GuestPtr),
            ParamSpec::new("attrsonly", U32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_search_sA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("base", PCStr),
            ParamSpec::new("scope", U32),
            ParamSpec::new("filter", PCStr),
            ParamSpec::new("attrs", GuestPtr),
            ParamSpec::new("attrsonly", U32),
            ParamSpec::new("res", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_search_sW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("base", PCWStr),
            ParamSpec::new("scope", U32),
            ParamSpec::new("filter", PCWStr),
            ParamSpec::new("attrs", GuestPtr),
            ParamSpec::new("attrsonly", U32),
            ParamSpec::new("res", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Result Processing ─────────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_result",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("msgid", U32),
            ParamSpec::new("all", U32),
            ParamSpec::new("timeout", GuestPtr),
            ParamSpec::new("res", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_first_entry",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("res", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_next_entry",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_count_entries",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("res", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── DN & Value Extraction ─────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_dnA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_dnW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_valuesA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
            ParamSpec::new("attr", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_valuesW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
            ParamSpec::new("attr", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_values_lenA",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
            ParamSpec::new("attr", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_values_lenW",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("entry", GuestPtr),
            ParamSpec::new("attr", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Value Counting & Freeing ──────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_count_valuesA",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("vals", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_count_valuesW",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("vals", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_count_values_len",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("vals", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_value_freeA",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("vals", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_value_freeW",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("vals", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_value_free_len",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("vals", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Memory Management ─────────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_msgfree",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("res", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_memfree",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("ptr", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── Options ───────────────────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_get_option",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("option", I32),
            ParamSpec::new("outvalue", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_set_option",
        abi: LogicalAbi::Cdecl,
        params: &[
            ParamSpec::new("ld", GuestPtr),
            ParamSpec::new("option", I32),
            ParamSpec::new("invalue", GuestPtr),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Session Teardown ──────────────────────────────────────────────────
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_unbind",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("ld", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "wldap32.dll",
        function: "ldap_unbind_s",
        abi: LogicalAbi::Cdecl,
        params: &[ParamSpec::new("ld", GuestPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
];
