use crate::hooks::base::HookLibrary;
use crate::hooks::registry::HookRegistry;
use crate::hooks::stub::stub_definitions;

const EXPORTS: &[(&str, &str, usize, crate::hooks::base::CallConv)] = &[
    (
        "wldap32.dll",
        "ldap_openA",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_openW",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_initA",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_initW",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_sslinitA",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_sslinitW",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_connect",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_bindA",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_bindW",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_bind_sA",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_bind_sW",
        4,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_simple_bind_sA",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_simple_bind_sW",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_searchA",
        6,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_searchW",
        6,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_search_sA",
        7,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_search_sW",
        7,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_result",
        5,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_first_entry",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_next_entry",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_count_entries",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_dnA",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_dnW",
        2,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_valuesA",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_valuesW",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_values_lenA",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_values_lenW",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_count_valuesA",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_count_valuesW",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_count_values_len",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_value_freeA",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_value_freeW",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_value_free_len",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_msgfree",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_memfree",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_get_option",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_set_option",
        3,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_unbind",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
    (
        "wldap32.dll",
        "ldap_unbind_s",
        1,
        crate::hooks::base::CallConv::Cdecl,
    ),
];

/// Collects the generated hook definitions for this DLL family.
#[derive(Debug, Default, Clone, Copy)]
pub struct Wldap32HookLibrary;

impl HookLibrary for Wldap32HookLibrary {
    fn collect(&self) -> Vec<crate::hooks::base::HookDefinition> {
        stub_definitions(EXPORTS)
    }
}

/// Registers the generated hook definitions for this DLL family.
pub fn register_wldap32_hooks(registry: &mut HookRegistry) {
    registry.register_library(&Wldap32HookLibrary);
}
