//! Full `HookSignature` table for `ws2_32.dll` functions.
//!
//! Covers Winsock 2 API: socket creation, connection, data transfer,
//! name resolution, and WSA extended functions.

use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamType::*};

pub(super) static WS2_32_SIGNATURES: &[HookSignature] = &[
    // ── WSA Startup / Cleanup / Error ─────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAStartup",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("wVersionRequested", U16),
            ParamSpec::new("lpWSAData", OpaqueStructPtr("WSADATA")),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSACleanup",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAGetLastError",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSASetLastError",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("iError", I32)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    // ── WSA Event Management ──────────────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "WSACreateEvent",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSACloseEvent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hEvent", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAEnumNetworkEvents",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("hEventObject", Handle),
            ParamSpec::new("lpNetworkEvents", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAEventSelect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("hEventObject", Handle),
            ParamSpec::new("lNetworkEvents", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAResetEvent",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hEvent", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAWaitForMultipleEvents",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("cEvents", U32),
            ParamSpec::new("lphEvents", GuestPtr),
            ParamSpec::new("fWaitAll", Bool32),
            ParamSpec::new("dwTimeout", U32),
            ParamSpec::new("fAlertable", Bool32),
        ],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── WSA I/O Control ───────────────────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "WSAIoctl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("dwIoControlCode", U32),
            ParamSpec::new("lpvInBuffer", GuestPtr),
            ParamSpec::new("cbInBuffer", U32),
            ParamSpec::new("lpvOutBuffer", GuestPtr),
            ParamSpec::new("cbOutBuffer", U32),
            ParamSpec::new("lpcbBytesReturned", GuestPtr),
            ParamSpec::new("lpOverlapped", GuestPtr),
            ParamSpec::new("lpCompletionRoutine", FunctionPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── WSA Extended Send/Recv ────────────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "WSARecv",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("lpBuffers", GuestPtr),
            ParamSpec::new("dwBufferCount", U32),
            ParamSpec::new("lpNumberOfBytesRecvd", GuestPtr),
            ParamSpec::new("lpFlags", GuestPtr),
            ParamSpec::new("lpOverlapped", GuestPtr),
            ParamSpec::new("lpCompletionRoutine", FunctionPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSASend",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("lpBuffers", GuestPtr),
            ParamSpec::new("dwBufferCount", U32),
            ParamSpec::new("lpNumberOfBytesSent", GuestPtr),
            ParamSpec::new("dwFlags", U32),
            ParamSpec::new("lpOverlapped", GuestPtr),
            ParamSpec::new("lpCompletionRoutine", FunctionPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "WSASocketW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("af", I32),
            ParamSpec::new("type", I32),
            ParamSpec::new("protocol", I32),
            ParamSpec::new("lpProtocolInfo", GuestPtr),
            ParamSpec::new("g", GuestPtr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Ordinal exports ───────────────────────────────────────────────────
    // ordinal_1 = accept
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_1",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("addr", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("addrlen", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ordinal_2 = bind
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("addr", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_3 = closesocket
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_3",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("s", Handle)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_4 = connect
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_4",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("name", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_5 = getpeername
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_5",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("name", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_6 = getsockname
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_6",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("name", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_7 = getsockopt
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_7",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("level", I32),
            ParamSpec::new("optname", I32),
            ParamSpec::new("optval", GuestPtr),
            ParamSpec::new("optlen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_8 = htonl
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_8",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hostlong", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ordinal_9 = htons
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_9",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hostshort", U16)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    // ordinal_10 = ioctlsocket
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_10",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("cmd", I32),
            ParamSpec::new("argp", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_11 = inet_addr
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_11",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("cp", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ordinal_12 = inet_ntoa
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_12",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("in_addr", U32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ordinal_13 = listen
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_13",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("s", Handle), ParamSpec::new("backlog", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_14 = ntohl
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_14",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("netlong", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ordinal_15 = ntohs
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_15",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("netshort", U16)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    // ordinal_16 = recv
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_16",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_17 = recvfrom
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_17",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
            ParamSpec::new("from", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("fromlen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_18 = select
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_18",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nfds", I32),
            ParamSpec::new("readfds", GuestPtr),
            ParamSpec::new("writefds", GuestPtr),
            ParamSpec::new("exceptfds", GuestPtr),
            ParamSpec::new("timeout", OpaqueStructPtr("timeval")),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_19 = send
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_19",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_20 = sendto
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_20",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
            ParamSpec::new("to", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("tolen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_21 = setsockopt
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_21",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("level", I32),
            ParamSpec::new("optname", I32),
            ParamSpec::new("optval", GuestPtr),
            ParamSpec::new("optlen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_22 = shutdown
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_22",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("s", Handle), ParamSpec::new("how", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_23 = socket
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_23",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("af", I32),
            ParamSpec::new("type", I32),
            ParamSpec::new("protocol", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Ordinal: Name Resolution ──────────────────────────────────────────
    // ordinal_51 = gethostbyname
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_51",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("name", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ordinal_52 = gethostbyaddr
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_52",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("addr", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("type", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ordinal_53 = getprotobyname
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_53",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("name", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ordinal_55 = getservbyname
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_55",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("name", PCStr),
            ParamSpec::new("proto", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ordinal_56 = getservbyport
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_56",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("port", I32), ParamSpec::new("proto", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ordinal_57 = gethostname
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_57",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("name", GuestPtr),
            ParamSpec::new("namelen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Ordinal: WSA Async Functions ──────────────────────────────────────
    // ordinal_71 = WSAAsyncSelect (s, hWnd, wMsg, lEvent) — 4 params but EXPORTS says 7
    // Using EXPORTS param count (7) as authoritative
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_71",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", Handle),
            ParamSpec::new("p2", GuestPtr),
            ParamSpec::new("p3", U32),
            ParamSpec::new("p4", I32),
            ParamSpec::new("p5", GuestPtr),
            ParamSpec::new("p6", GuestPtr),
            ParamSpec::new("p7", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_76 = WSAAsyncGetHostByName or similar — 7 params per EXPORTS
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_76",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", Handle),
            ParamSpec::new("p2", GuestPtr),
            ParamSpec::new("p3", U32),
            ParamSpec::new("p4", GuestPtr),
            ParamSpec::new("p5", I32),
            ParamSpec::new("p6", GuestPtr),
            ParamSpec::new("p7", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ordinal_83 = WSAAsyncGetHostByAddr or similar — 6 params per EXPORTS
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_83",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", Handle),
            ParamSpec::new("p2", GuestPtr),
            ParamSpec::new("p3", U32),
            ParamSpec::new("p4", GuestPtr),
            ParamSpec::new("p5", I32),
            ParamSpec::new("p6", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    // ── Ordinal: Internal WSA Helpers ─────────────────────────────────────
    // ordinal_111 = internal helper — 0 params
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_111",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_112 = internal helper — 1 param
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_112",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("p1", GuestPtr)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_115 = internal helper — 2 params
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_115",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("p1", GuestPtr),
            ParamSpec::new("p2", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_116 = internal helper — 0 params
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_116",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ordinal_151 = internal helper — 0 params
    HookSignature {
        module: "ws2_32.dll",
        function: "ordinal_151",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Named exports: Socket Core ────────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "socket",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("af", I32),
            ParamSpec::new("type", I32),
            ParamSpec::new("protocol", I32),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "closesocket",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("s", Handle)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "bind",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("addr", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "connect",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("name", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "listen",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("s", Handle), ParamSpec::new("backlog", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "accept",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("addr", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("addrlen", GuestPtr),
        ],
        ret: ReturnSpec::Handle,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getpeername",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("name", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getsockname",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("name", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("namelen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Named exports: Data Transfer ──────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "send",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "recv",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "sendto",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
            ParamSpec::new("to", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("tolen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "recvfrom",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("flags", I32),
            ParamSpec::new("from", OpaqueStructPtr("sockaddr")),
            ParamSpec::new("fromlen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "shutdown",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("s", Handle), ParamSpec::new("how", I32)],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "select",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("nfds", I32),
            ParamSpec::new("readfds", GuestPtr),
            ParamSpec::new("writefds", GuestPtr),
            ParamSpec::new("exceptfds", GuestPtr),
            ParamSpec::new("timeout", OpaqueStructPtr("timeval")),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Named exports: Socket Options ─────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "ioctlsocket",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("cmd", I32),
            ParamSpec::new("argp", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "setsockopt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("level", I32),
            ParamSpec::new("optname", I32),
            ParamSpec::new("optval", GuestPtr),
            ParamSpec::new("optlen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getsockopt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("s", Handle),
            ParamSpec::new("level", I32),
            ParamSpec::new("optname", I32),
            ParamSpec::new("optval", GuestPtr),
            ParamSpec::new("optlen", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    // ── Named exports: Byte Order ─────────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "htons",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hostshort", U16)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "ntohs",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("netshort", U16)],
        ret: ReturnSpec::U16,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "htonl",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hostlong", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "ntohl",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("netlong", U32)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    // ── Named exports: Address Conversion ─────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "inet_addr",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("cp", PCStr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "inet_ntop",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Family", I32),
            ParamSpec::new("pAddr", GuestPtr),
            ParamSpec::new("pStringBuf", GuestPtr),
            ParamSpec::new("StringBufSize", SizeT),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "inet_ntoa",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("in_addr", U32)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    // ── Named exports: Name Resolution ────────────────────────────────────
    HookSignature {
        module: "ws2_32.dll",
        function: "gethostbyaddr",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("addr", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::new("type", I32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "gethostbyname",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("name", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getprotobyname",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("name", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getservbyname",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("name", PCStr),
            ParamSpec::new("proto", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getservbyport",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("port", I32), ParamSpec::new("proto", PCStr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "gethostname",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("name", GuestPtr),
            ParamSpec::new("namelen", I32),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "getaddrinfo",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pNodeName", PCStr),
            ParamSpec::new("pServiceName", PCStr),
            ParamSpec::new("pHints", GuestPtr),
            ParamSpec::new("ppResult", GuestPtr),
        ],
        ret: ReturnSpec::I32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "ws2_32.dll",
        function: "freeaddrinfo",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pAddrInfo", GuestPtr)],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
];
