use crate::hooks::base::HookLibrary;
use crate::hooks::registry::HookRegistry;
use crate::hooks::stub::stub_definitions;

const EXPORTS: &[(&str, &str, usize, crate::hooks::base::CallConv)] = &[
    (
        "ws2_32.dll",
        "WSAStartup",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSACleanup",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSAGetLastError",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSASetLastError",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSACreateEvent",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSACloseEvent",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSAEnumNetworkEvents",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSAEventSelect",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSAResetEvent",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSAWaitForMultipleEvents",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSAIoctl",
        9,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSARecv",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSASend",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "WSASocketW",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_1",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_2",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_3",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_4",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_5",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_6",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_7",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_8",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_9",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_10",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_11",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_12",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_13",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_14",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_15",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_16",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_17",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_18",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_19",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_20",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_21",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_22",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_23",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_51",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_52",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_53",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_55",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_56",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_57",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_71",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_76",
        7,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_83",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_111",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_112",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_115",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_116",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ordinal_151",
        0,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "socket",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "closesocket",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "bind",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "connect",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "listen",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "accept",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getpeername",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getsockname",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "send",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "recv",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "sendto",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "recvfrom",
        6,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "shutdown",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "select",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ioctlsocket",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "setsockopt",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getsockopt",
        5,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "htons",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ntohs",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "htonl",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "ntohl",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "inet_addr",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "inet_ntoa",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "gethostbyaddr",
        3,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "gethostbyname",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getprotobyname",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getservbyname",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getservbyport",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "gethostname",
        2,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "getaddrinfo",
        4,
        crate::hooks::base::CallConv::Stdcall,
    ),
    (
        "ws2_32.dll",
        "freeaddrinfo",
        1,
        crate::hooks::base::CallConv::Stdcall,
    ),
];

/// Collects the generated hook definitions for this DLL family.
#[derive(Debug, Default, Clone, Copy)]
pub struct Ws232HookLibrary;

impl HookLibrary for Ws232HookLibrary {
    fn collect(&self) -> Vec<crate::hooks::base::HookDefinition> {
        stub_definitions(EXPORTS)
    }
}

/// Registers the generated hook definitions for this DLL family.
pub fn register_ws2_32_hooks(registry: &mut HookRegistry) {
    registry.register_library(&Ws232HookLibrary);
}

#[cfg(test)]
mod tests {
    use super::register_ws2_32_hooks;
    use crate::hooks::registry::HookRegistry;

    #[test]
    fn registers_ws2_named_exports_used_by_runtime_dispatch() {
        let mut registry = HookRegistry::for_tests();
        register_ws2_32_hooks(&mut registry);

        for function in [
            "getpeername",
            "getsockname",
            "sendto",
            "recvfrom",
            "gethostbyaddr",
            "gethostname",
            "getprotobyname",
            "getservbyname",
            "getservbyport",
        ] {
            assert!(
                registry.definition("ws2_32.dll", function).is_some(),
                "missing ws2_32 registration for {function}"
            );
        }
    }
}
