use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{HookFlags, LogicalAbi, ParamDirection::*, ParamType::*};

pub(crate) static ADVAPI32_SIGS_2: &[HookSignature] = &[
    HookSignature {
        module: "advapi32.dll",
        function: "GetUserNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpBuffer", PStr, Out),
            ParamSpec::with_dir("pcbBuffer", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "GetUserNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("lpBuffer", PWStr, Out),
            ParamSpec::with_dir("pcbBuffer", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Service Manager ──────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "OpenSCManagerA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpMachineName", PCStr),
            ParamSpec::new("lpDatabaseName", PCStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "OpenSCManagerW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpMachineName", PCWStr),
            ParamSpec::new("lpDatabaseName", PCWStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CreateServiceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("lpServiceName", PCStr),
            ParamSpec::new("lpDisplayName", PCStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("dwServiceType", Hex32),
            ParamSpec::new("dwStartType", Hex32),
            ParamSpec::new("dwErrorControl", Hex32),
            ParamSpec::new("lpBinaryPathName", PCStr),
            ParamSpec::new("lpLoadOrderGroup", PCStr),
            ParamSpec::with_dir("lpdwTagId", GuestPtr, Out),
            ParamSpec::new("lpDependencies", PCStr),
            ParamSpec::new("lpServiceStartName", PCStr),
            ParamSpec::new("lpPassword", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CreateServiceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("lpServiceName", PCWStr),
            ParamSpec::new("lpDisplayName", PCWStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
            ParamSpec::new("dwServiceType", Hex32),
            ParamSpec::new("dwStartType", Hex32),
            ParamSpec::new("dwErrorControl", Hex32),
            ParamSpec::new("lpBinaryPathName", PCWStr),
            ParamSpec::new("lpLoadOrderGroup", PCWStr),
            ParamSpec::with_dir("lpdwTagId", GuestPtr, Out),
            ParamSpec::new("lpDependencies", PCWStr),
            ParamSpec::new("lpServiceStartName", PCWStr),
            ParamSpec::new("lpPassword", PCWStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "OpenServiceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("lpServiceName", PCStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "OpenServiceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("lpServiceName", PCWStr),
            ParamSpec::new("dwDesiredAccess", Hex32),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CloseServiceHandle",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hSCObject", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ControlService",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::new("dwControl", Hex32),
            ParamSpec::with_dir("lpServiceStatus", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "StartServiceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::new("dwNumServiceArgs", U32),
            ParamSpec::new("lpServiceArgVectors", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "StartServiceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::new("dwNumServiceArgs", U32),
            ParamSpec::new("lpServiceArgVectors", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryServiceStatus",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::with_dir("lpServiceStatus", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryServiceStatusEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::new("InfoLevel", U32),
            ParamSpec::with_dir("lpBuffer", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "GetServiceDisplayNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("lpServiceName", PCStr),
            ParamSpec::with_dir("lpDisplayName", PStr, Out),
            ParamSpec::with_dir("cchBuffer", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryServiceConfigA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::with_dir("lpServiceConfig", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryServiceConfigW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::with_dir("lpServiceConfig", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryServiceConfig2A",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::new("dwInfoLevel", U32),
            ParamSpec::with_dir("lpBuffer", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryServiceConfig2W",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hService", Handle),
            ParamSpec::new("dwInfoLevel", U32),
            ParamSpec::with_dir("lpBuffer", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EnumServicesStatusW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("dwServiceType", Hex32),
            ParamSpec::new("dwServiceState", Hex32),
            ParamSpec::with_dir("lpServices", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
            ParamSpec::with_dir("lpServicesReturned", GuestPtr, Out),
            ParamSpec::with_dir("lpResumeHandle", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EnumServicesStatusExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("InfoLevel", U32),
            ParamSpec::new("dwServiceType", Hex32),
            ParamSpec::new("dwServiceState", Hex32),
            ParamSpec::with_dir("lpServices", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
            ParamSpec::with_dir("lpServicesReturned", GuestPtr, Out),
            ParamSpec::with_dir("lpResumeHandle", GuestPtr, InOut),
            ParamSpec::new("pszGroupName", PCStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EnumServicesStatusExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hSCManager", Handle),
            ParamSpec::new("InfoLevel", U32),
            ParamSpec::new("dwServiceType", Hex32),
            ParamSpec::new("dwServiceState", Hex32),
            ParamSpec::with_dir("lpServices", GuestPtr, Out),
            ParamSpec::new("cbBufSize", U32),
            ParamSpec::with_dir("pcbBytesNeeded", GuestPtr, Out),
            ParamSpec::with_dir("lpServicesReturned", GuestPtr, Out),
            ParamSpec::with_dir("lpResumeHandle", GuestPtr, InOut),
            ParamSpec::new("pszGroupName", PCWStr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Registry (extended) ──────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "RegEnumKeyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::with_dir("lpName", PWStr, Out),
            ParamSpec::new("cchName", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegQueryValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
            ParamSpec::with_dir("lpValue", PWStr, Out),
            ParamSpec::with_dir("lpcbValue", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegQueryInfoKeyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::with_dir("lpClass", PWStr, Out),
            ParamSpec::with_dir("lpcchClass", GuestPtr, InOut),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::with_dir("lpcSubKeys", GuestPtr, Out),
            ParamSpec::with_dir("lpcbMaxSubKeyLen", GuestPtr, Out),
            ParamSpec::with_dir("lpcbMaxClassLen", GuestPtr, Out),
            ParamSpec::with_dir("lpcValues", GuestPtr, Out),
            ParamSpec::with_dir("lpcbMaxValueNameLen", GuestPtr, Out),
            ParamSpec::with_dir("lpcbMaxValueLen", GuestPtr, Out),
            ParamSpec::with_dir("lpcbSecurityDescriptor", GuestPtr, Out),
            ParamSpec::with_dir("lpftLastWriteTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegNotifyChangeKeyValue",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("bWatchSubtree", Bool32),
            ParamSpec::new("dwNotifyFilter", Hex32),
            ParamSpec::new("hEvent", Handle),
            ParamSpec::new("fAsynchronous", Bool32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Crypto (extended) ────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "CryptAcquireContextA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("phProv", GuestPtr, Out),
            ParamSpec::new("szContainer", PCStr),
            ParamSpec::new("szProvider", PCStr),
            ParamSpec::new("dwProvType", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptExportKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("hExpKey", Handle),
            ParamSpec::new("dwBlobType", U32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pbData", GuestPtr, Out),
            ParamSpec::with_dir("pdwDataLen", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptImportKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProv", Handle),
            ParamSpec::new("pbData", GuestPtr),
            ParamSpec::new("dwDataLen", U32),
            ParamSpec::new("hImportKey", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptSetHashParam",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("dwParam", U32),
            ParamSpec::new("pbData", GuestPtr),
            ParamSpec::new("dwFlags", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptSetKeyParam",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwParam", U32),
            ParamSpec::new("pbData", GuestPtr),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptSignHashW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("dwKeySpec", U32),
            ParamSpec::new("szDescription", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pbSignature", GuestPtr, Out),
            ParamSpec::with_dir("pdwSigLen", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptVerifySignatureW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("pbSignature", GuestPtr),
            ParamSpec::new("dwSigLen", U32),
            ParamSpec::new("hPubKey", Handle),
            ParamSpec::new("szDescription", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Event Logging ────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "RegisterEventSourceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpUNCServerName", PCStr),
            ParamSpec::new("lpSourceName", PCStr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ReportEventA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hEventLog", Handle),
            ParamSpec::new("wType", U32),
            ParamSpec::new("wCategory", U32),
            ParamSpec::new("dwEventID", U32),
            ParamSpec::new("lpUserSid", SidPtr),
            ParamSpec::new("wNumStrings", U32),
            ParamSpec::new("dwDataSize", U32),
            ParamSpec::new("lpStrings", GuestPtr),
            ParamSpec::new("lpRawData", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "DeregisterEventSource",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hEventLog", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── ETW Trace ────────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "StartTraceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pTraceHandle", GuestPtr, Out),
            ParamSpec::new("lpTraceName", PCStr),
            ParamSpec::with_dir("pTraceInfo", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "StartTraceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pTraceHandle", GuestPtr, Out),
            ParamSpec::new("lpTraceName", PCWStr),
            ParamSpec::with_dir("pTraceInfo", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ControlTraceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pTraceHandle", PointerSizedUInt),
            ParamSpec::new("lpTraceName", PCStr),
            ParamSpec::with_dir("pTraceInfo", GuestPtr, InOut),
            ParamSpec::new("dwControlCode", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ControlTraceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pTraceHandle", PointerSizedUInt),
            ParamSpec::new("lpTraceName", PCWStr),
            ParamSpec::with_dir("pTraceInfo", GuestPtr, InOut),
            ParamSpec::new("dwControlCode", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "StopTraceA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pTraceHandle", PointerSizedUInt),
            ParamSpec::new("lpTraceName", PCStr),
            ParamSpec::with_dir("pTraceInfo", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "StopTraceW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pTraceHandle", PointerSizedUInt),
            ParamSpec::new("lpTraceName", PCWStr),
            ParamSpec::with_dir("pTraceInfo", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryAllTracesA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pTraceInfoArray", GuestPtr, Out),
            ParamSpec::new("cTraceCount", U32),
            ParamSpec::with_dir("pcTraceCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "QueryAllTracesW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pTraceInfoArray", GuestPtr, Out),
            ParamSpec::new("cTraceCount", U32),
            ParamSpec::with_dir("pcTraceCount", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "TraceSetInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pTraceHandle", PointerSizedUInt),
            ParamSpec::new("InformationClass", U32),
            ParamSpec::new("TraceInformation", GuestPtr),
            ParamSpec::new("InformationLength", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EnableTraceEx2",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pTraceHandle", PointerSizedUInt),
            ParamSpec::new("pProviderId", GuidPtr),
            ParamSpec::new("ControlCode", Hex32),
            ParamSpec::new("Level", U32),
            ParamSpec::new("MatchAnyKeyword", U64),
            ParamSpec::new("MatchAllKeyword", U64),
            ParamSpec::new("Timeout", U32),
            ParamSpec::new("pEnableParameters", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EnumerateTraceGuidsEx",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TraceQueryInfoClass", U32),
            ParamSpec::new("InBuffer", GuestPtr),
            ParamSpec::new("InBufferSize", U32),
            ParamSpec::with_dir("OutBuffer", GuestPtr, Out),
            ParamSpec::new("OutBufferSize", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "OpenTraceA",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("pLogfile", GuestPtr, InOut)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "OpenTraceW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::with_dir("pLogfile", GuestPtr, InOut)],
        ret: ReturnSpec::PointerSizedUInt,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ProcessTrace",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("HandleArray", GuestPtr),
            ParamSpec::new("HandleCount", U32),
            ParamSpec::new("StartTime", FileTimePtr),
            ParamSpec::new("EndTime", FileTimePtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CloseTrace",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pTraceHandle", PointerSizedUInt)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── ETW Event ────────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "EventRegister",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pProviderId", GuidPtr),
            ParamSpec::new("pEnableCallback", FunctionPtr),
            ParamSpec::new("pCallbackContext", GuestPtr),
            ParamSpec::with_dir("pRegHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EventSetInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RegHandle", PointerSizedUInt),
            ParamSpec::new("InformationClass", U32),
            ParamSpec::new("EventInformation", GuestPtr),
            ParamSpec::new("InformationLength", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EventUnregister",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("RegHandle", PointerSizedUInt)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EventWriteTransfer",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("RegHandle", PointerSizedUInt),
            ParamSpec::new("pEventDescriptor", GuestPtr),
            ParamSpec::new("pActivityId", GuidPtr),
            ParamSpec::new("pRelatedActivityId", GuidPtr),
            ParamSpec::new("UserDataCount", U32),
            ParamSpec::new("pUserData", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Misc ─────────────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "IsTextUnicode",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("buf", GuestPtr),
            ParamSpec::new("len", I32),
            ParamSpec::with_dir("lpfResult", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CreateProcessAsUserW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hToken", Handle),
            ParamSpec::new("lpApplicationName", PCWStr),
            ParamSpec::with_dir("lpCommandLine", PWStr, InOut),
            ParamSpec::new("lpProcessAttributes", SecurityAttributesPtr),
            ParamSpec::new("lpThreadAttributes", SecurityAttributesPtr),
            ParamSpec::new("bInheritHandles", Bool32),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::new("lpEnvironment", GuestPtr),
            ParamSpec::new("lpCurrentDirectory", PCWStr),
            ParamSpec::new("lpStartupInfo", StartupInfoPtr),
            ParamSpec::with_dir("lpProcessInfo", ProcessInformationPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CreateProcessWithLogonW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpUsername", PCWStr),
            ParamSpec::new("lpDomain", PCWStr),
            ParamSpec::new("lpPassword", PCWStr),
            ParamSpec::new("dwLogonFlags", Hex32),
            ParamSpec::new("lpApplicationName", PCWStr),
            ParamSpec::with_dir("lpCommandLine", PWStr, InOut),
            ParamSpec::new("dwCreationFlags", Hex32),
            ParamSpec::new("lpEnvironment", GuestPtr),
            ParamSpec::new("lpCurrentDirectory", PCWStr),
            ParamSpec::new("lpStartupInfo", StartupInfoPtr),
            ParamSpec::with_dir("lpProcessInfo", ProcessInformationPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "DuplicateEncryptionInfoFile",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pSrcFileName", PCWStr),
            ParamSpec::new("pDstFileName", PCWStr),
            ParamSpec::new("dwCreationDistribution", U32),
            ParamSpec::new("dwAttributes", Hex32),
            ParamSpec::new("pSecurityAttributes", SecurityAttributesPtr),
            ParamSpec::new("pExtendedError", Handle),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EventAccessQuery",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pGuid", GuidPtr),
            ParamSpec::with_dir(
                "pSecurityDescriptor",
                OpaqueStructPtr("SECURITY_DESCRIPTOR"),
                Out,
            ),
            ParamSpec::with_dir("pSecurityDescriptorSize", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EventAccessRemove",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pGuid", GuidPtr)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "EventAccessControl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pGuid", GuidPtr),
            ParamSpec::new("operation", Hex32),
            ParamSpec::new("pSid", SidPtr),
            ParamSpec::new("pRights", Hex32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
];
