use crate::hooks::signature::{HookSignature, ParamSpec, ReturnSpec};
use crate::hooks::types::{
    HookFlags, LogicalAbi, ParamDirection::*, ParamType::*, ParamTypeDiscriminant,
};

pub(crate) static ADVAPI32_SIGS_1: &[HookSignature] = &[
    // ── Registry ──────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "RegOpenKeyExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
            ParamSpec::new("ulOptions", U32),
            ParamSpec::new("samDesired", Hex32),
            ParamSpec::with_dir("phkResult", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegOpenKeyExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCStr),
            ParamSpec::new("ulOptions", U32),
            ParamSpec::new("samDesired", Hex32),
            ParamSpec::with_dir("phkResult", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegCreateKeyExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("lpClass", PCWStr),
            ParamSpec::new("dwOptions", Hex32),
            ParamSpec::new("samDesired", Hex32),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
            ParamSpec::with_dir("phkResult", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
            ParamSpec::with_dir(
                "lpdwDisposition",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegCreateKeyExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCStr),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("lpClass", PCStr),
            ParamSpec::new("dwOptions", Hex32),
            ParamSpec::new("samDesired", Hex32),
            ParamSpec::new("lpSecurityAttributes", SecurityAttributesPtr),
            ParamSpec::with_dir("phkResult", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
            ParamSpec::with_dir(
                "lpdwDisposition",
                GuestPtrTo(ParamTypeDiscriminant::U32),
                Out,
            ),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegCreateKeyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
            ParamSpec::with_dir("phkResult", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegCreateKeyA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCStr),
            ParamSpec::with_dir("phkResult", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegQueryValueExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpValueName", PCWStr),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::with_dir("lpType", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("lpData", OutBuffer { len_param: 5 }),
            ParamSpec::with_dir("lpcbData", GuestPtrTo(ParamTypeDiscriminant::U32), InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegQueryValueExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpValueName", PCStr),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::with_dir("lpType", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
            ParamSpec::new("lpData", OutBuffer { len_param: 5 }),
            ParamSpec::with_dir("lpcbData", GuestPtrTo(ParamTypeDiscriminant::U32), InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegSetValueExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpValueName", PCWStr),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("dwType", Hex32),
            ParamSpec::new("lpData", GuestPtr),
            ParamSpec::new("cbData", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegSetValueExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpValueName", PCStr),
            ParamSpec::new("Reserved", U32),
            ParamSpec::new("dwType", Hex32),
            ParamSpec::new("lpData", GuestPtr),
            ParamSpec::new("cbData", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegDeleteValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpValueName", PCWStr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegDeleteValueA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpValueName", PCStr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegEnumKeyExW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::new("lpName", PWStr),
            ParamSpec::with_dir("lpcchName", GuestPtr, InOut),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::new("lpClass", PWStr),
            ParamSpec::with_dir("lpcchClass", GuestPtr, InOut),
            ParamSpec::with_dir("lpftLastWriteTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegEnumKeyExA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::new("lpName", PStr),
            ParamSpec::with_dir("lpcchName", GuestPtr, InOut),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::new("lpClass", PStr),
            ParamSpec::with_dir("lpcchClass", GuestPtr, InOut),
            ParamSpec::with_dir("lpftLastWriteTime", FileTimePtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegEnumValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::new("lpValueName", PWStr),
            ParamSpec::with_dir("lpcchValueName", GuestPtr, InOut),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::with_dir("lpType", GuestPtr, Out),
            ParamSpec::with_dir("lpData", GuestPtr, Out),
            ParamSpec::with_dir("lpcbData", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegEnumValueA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwIndex", U32),
            ParamSpec::new("lpValueName", PStr),
            ParamSpec::with_dir("lpcchValueName", GuestPtr, InOut),
            ParamSpec::new("lpReserved", GuestPtr),
            ParamSpec::with_dir("lpType", GuestPtr, Out),
            ParamSpec::with_dir("lpData", GuestPtr, Out),
            ParamSpec::with_dir("lpcbData", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegGetValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hkey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
            ParamSpec::new("lpValue", PCWStr),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pdwType", GuestPtr, Out),
            ParamSpec::with_dir("pvData", GuestPtr, Out),
            ParamSpec::with_dir("pcbData", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegGetValueA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hkey", Handle),
            ParamSpec::new("lpSubKey", PCStr),
            ParamSpec::new("lpValue", PCStr),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pdwType", GuestPtr, Out),
            ParamSpec::with_dir("pvData", GuestPtr, Out),
            ParamSpec::with_dir("pcbData", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegCloseKey",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hKey", Handle)],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegOverridePredefKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("hNewHKey", Handle),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegSetKeyValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
            ParamSpec::new("lpValueName", PCWStr),
            ParamSpec::new("dwType", Hex32),
            ParamSpec::new("lpData", GuestPtr),
            ParamSpec::new("cbData", U32),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegDeleteKeyW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("lpSubKey", PCWStr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    // ── Token / Privilege ─────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "OpenProcessToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ProcessHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::with_dir(
                "TokenHandle",
                GuestPtrTo(ParamTypeDiscriminant::Handle),
                Out,
            ),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "OpenThreadToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ThreadHandle", Handle),
            ParamSpec::new("DesiredAccess", Hex32),
            ParamSpec::new("OpenAsSelf", Bool32),
            ParamSpec::with_dir(
                "TokenHandle",
                GuestPtrTo(ParamTypeDiscriminant::Handle),
                Out,
            ),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "GetTokenInformation",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("TokenInformationClass", U32),
            ParamSpec::new("TokenInformation", OutBuffer { len_param: 3 }),
            ParamSpec::new("TokenInformationLength", U32),
            ParamSpec::with_dir("ReturnLength", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "AdjustTokenPrivileges",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("TokenHandle", Handle),
            ParamSpec::new("DisableAllPrivileges", Bool32),
            ParamSpec::new("NewState", GuestPtr),
            ParamSpec::new("BufferLength", U32),
            ParamSpec::new("PreviousState", OutBuffer { len_param: 3 }),
            ParamSpec::with_dir("ReturnLength", GuestPtrTo(ParamTypeDiscriminant::U32), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LookupPrivilegeValueW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemName", PCWStr),
            ParamSpec::new("lpName", PCWStr),
            ParamSpec::with_dir("lpLuid", OpaqueStructPtr("LUID"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LookupPrivilegeValueA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemName", PCStr),
            ParamSpec::new("lpName", PCStr),
            ParamSpec::with_dir("lpLuid", OpaqueStructPtr("LUID"), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Crypto ────────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "CryptAcquireContextW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("phProv", GuestPtr, Out),
            ParamSpec::new("szContainer", PCWStr),
            ParamSpec::new("szProvider", PCWStr),
            ParamSpec::new("dwProvType", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptReleaseContext",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProv", Handle),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptGenRandom",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProv", Handle),
            ParamSpec::new("dwLen", U32),
            ParamSpec::with_dir("pbBuffer", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptCreateHash",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProv", Handle),
            ParamSpec::new("Algid", U32),
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("phHash", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptHashData",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("pbData", Buffer { len_param: 2 }),
            ParamSpec::new("dwDataLen", U32),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptGetHashParam",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("dwParam", U32),
            ParamSpec::with_dir("pbData", GuestPtr, Out),
            ParamSpec::with_dir("pdwDataLen", GuestPtr, InOut),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptGetKeyParam",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("dwParam", U32),
            ParamSpec::with_dir("pbData", GuestPtr, Out),
            ParamSpec::with_dir("pdwDataLen", GuestPtr, InOut),
            ParamSpec::new("dwFlags", Hex32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptDeriveKey",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hProv", Handle),
            ParamSpec::new("Algid", U32),
            ParamSpec::new("hBaseData", Handle),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("phKey", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptEncrypt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("Final", Bool32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pbData", GuestPtr, InOut),
            ParamSpec::with_dir("pdwDataLen", GuestPtr, InOut),
            ParamSpec::new("dwBufLen", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptDecrypt",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hKey", Handle),
            ParamSpec::new("hHash", Handle),
            ParamSpec::new("Final", Bool32),
            ParamSpec::new("dwFlags", Hex32),
            ParamSpec::with_dir("pbData", GuestPtr, InOut),
            ParamSpec::with_dir("pdwDataLen", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptDestroyHash",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hHash", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CryptDestroyKey",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hKey", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Service ───────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "StartServiceCtrlDispatcherW",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("lpServiceTable", GuestPtr)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RegisterServiceCtrlHandlerW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpServiceName", PCWStr),
            ParamSpec::new("lpHandlerProc", FunctionPtr),
        ],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "SetServiceStatus",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("hServiceStatus", Handle),
            ParamSpec::new("lpServiceStatus", GuestPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── SID ──────────────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "AllocateAndInitializeSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pIdentifierAuthority", GuestPtr),
            ParamSpec::new("nSubAuthorityCount", U32),
            ParamSpec::new("nSubAuthority0", U32),
            ParamSpec::new("nSubAuthority1", U32),
            ParamSpec::new("nSubAuthority2", U32),
            ParamSpec::new("nSubAuthority3", U32),
            ParamSpec::new("nSubAuthority4", U32),
            ParamSpec::new("nSubAuthority5", U32),
            ParamSpec::new("nSubAuthority6", U32),
            ParamSpec::new("nSubAuthority7", U32),
            ParamSpec::with_dir("pSid", SidPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "FreeSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pSid", SidPtr)],
        ret: ReturnSpec::Pointer,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "GetLengthSid",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("pSid", SidPtr)],
        ret: ReturnSpec::U32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CopySid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("cbDestinationSidLength", U32),
            ParamSpec::with_dir("pDestinationSid", SidPtr, Out),
            ParamSpec::new("pSourceSid", SidPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "CreateWellKnownSid",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("WellKnownSidType", U32),
            ParamSpec::new("DomainSid", SidPtr),
            ParamSpec::with_dir("pSid", SidPtr, Out),
            ParamSpec::with_dir("cbSid", GuestPtr, InOut),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Trustee / ACL ────────────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "BuildTrusteeWithSidW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::with_dir("pTrustee", GuestPtr, Out),
            ParamSpec::new("pSid", SidPtr),
        ],
        ret: ReturnSpec::Void,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "GetEffectiveRightsFromAclW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pacl", GuestPtr),
            ParamSpec::new("pTrustee", GuestPtr),
            ParamSpec::with_dir("pAccessRights", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "SetEntriesInAclW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("cCountOfExplicitEntries", U32),
            ParamSpec::new("pListOfExplicitEntries", GuestPtr),
            ParamSpec::new("OldAcl", GuestPtr),
            ParamSpec::with_dir("NewAcl", GuestPtr, Out),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ConvertStringSecurityDescriptorToSecurityDescriptorW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringSecurityDescriptor", PCWStr),
            ParamSpec::new("StringSDRevision", U32),
            ParamSpec::with_dir(
                "SecurityDescriptor",
                OpaqueStructPtr("SECURITY_DESCRIPTOR"),
                Out,
            ),
            ParamSpec::with_dir("SecurityDescriptorSize", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Security Descriptor ──────────────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "GetNamedSecurityInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pObjectName", PCWStr),
            ParamSpec::new("ObjectType", U32),
            ParamSpec::new("SecurityInfo", Hex32),
            ParamSpec::with_dir("ppsidOwner", SidPtr, Out),
            ParamSpec::with_dir("ppsidGroup", SidPtr, Out),
            ParamSpec::with_dir("ppDacl", GuestPtr, Out),
            ParamSpec::with_dir("ppSacl", GuestPtr, Out),
            ParamSpec::with_dir(
                "ppSecurityDescriptor",
                OpaqueStructPtr("SECURITY_DESCRIPTOR"),
                Out,
            ),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "SetNamedSecurityInfoW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pObjectName", PWStr),
            ParamSpec::new("ObjectType", U32),
            ParamSpec::new("SecurityInfo", Hex32),
            ParamSpec::new("psidOwner", SidPtr),
            ParamSpec::new("psidGroup", SidPtr),
            ParamSpec::new("pDacl", GuestPtr),
            ParamSpec::new("pSacl", GuestPtr),
        ],
        ret: ReturnSpec::Win32Error,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "InitializeSecurityDescriptor",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new(
                "pSecurityDescriptor",
                OpaqueStructPtr("SECURITY_DESCRIPTOR"),
            ),
            ParamSpec::new("dwRevision", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "InitializeAcl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pAcl", GuestPtr),
            ParamSpec::new("nAclLength", U32),
            ParamSpec::new("dwAclRevision", U32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "AddAccessAllowedAce",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("pAcl", GuestPtr),
            ParamSpec::new("dwAceRevision", U32),
            ParamSpec::new("AccessMask", Hex32),
            ParamSpec::new("pSid", SidPtr),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "SetSecurityDescriptorDacl",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new(
                "pSecurityDescriptor",
                OpaqueStructPtr("SECURITY_DESCRIPTOR"),
            ),
            ParamSpec::new("bDaclPresent", Bool32),
            ParamSpec::new("pDacl", GuestPtr),
            ParamSpec::new("bDaclDefaulted", Bool32),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    // ── Token / Privilege (extended) ─────────────────────────────────────────
    HookSignature {
        module: "advapi32.dll",
        function: "ImpersonateSelf",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("ImpersonationLevel", U32)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "RevertToSelf",
        abi: LogicalAbi::WinApi,
        params: &[],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "DuplicateToken",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("ExistingTokenHandle", Handle),
            ParamSpec::new("ImpersonationLevel", U32),
            ParamSpec::with_dir("DuplicateTokenHandle", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ImpersonateLoggedOnUser",
        abi: LogicalAbi::WinApi,
        params: &[ParamSpec::new("hToken", Handle)],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LogonUserA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszUsername", PCStr),
            ParamSpec::new("lpszDomain", PCStr),
            ParamSpec::new("lpszPassword", PCStr),
            ParamSpec::new("dwLogonType", U32),
            ParamSpec::new("dwLogonProvider", U32),
            ParamSpec::with_dir("phToken", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LogonUserW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpszUsername", PCWStr),
            ParamSpec::new("lpszDomain", PCWStr),
            ParamSpec::new("lpszPassword", PCWStr),
            ParamSpec::new("dwLogonType", U32),
            ParamSpec::new("dwLogonProvider", U32),
            ParamSpec::with_dir("phToken", GuestPtrTo(ParamTypeDiscriminant::Handle), Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LookupAccountNameA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemName", PCStr),
            ParamSpec::new("lpAccountName", PCStr),
            ParamSpec::with_dir("Sid", SidPtr, Out),
            ParamSpec::with_dir("cbSid", GuestPtr, InOut),
            ParamSpec::with_dir("ReferencedDomainName", PStr, Out),
            ParamSpec::with_dir("cchReferencedDomainName", GuestPtr, InOut),
            ParamSpec::with_dir("peUse", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LookupAccountNameW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemName", PCWStr),
            ParamSpec::new("lpAccountName", PCWStr),
            ParamSpec::with_dir("Sid", SidPtr, Out),
            ParamSpec::with_dir("cbSid", GuestPtr, InOut),
            ParamSpec::with_dir("ReferencedDomainName", PWStr, Out),
            ParamSpec::with_dir("cchReferencedDomainName", GuestPtr, InOut),
            ParamSpec::with_dir("peUse", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LookupAccountSidA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemName", PCStr),
            ParamSpec::new("Sid", SidPtr),
            ParamSpec::with_dir("Name", PStr, Out),
            ParamSpec::with_dir("cchName", GuestPtr, InOut),
            ParamSpec::with_dir("ReferencedDomainName", PStr, Out),
            ParamSpec::with_dir("cchReferencedDomainName", GuestPtr, InOut),
            ParamSpec::with_dir("peUse", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "LookupAccountSidW",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("lpSystemName", PCWStr),
            ParamSpec::new("Sid", SidPtr),
            ParamSpec::with_dir("Name", PWStr, Out),
            ParamSpec::with_dir("cchName", GuestPtr, InOut),
            ParamSpec::with_dir("ReferencedDomainName", PWStr, Out),
            ParamSpec::with_dir("cchReferencedDomainName", GuestPtr, InOut),
            ParamSpec::with_dir("peUse", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ConvertStringSidToSidA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("StringSid", PCStr),
            ParamSpec::with_dir("Sid", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
    HookSignature {
        module: "advapi32.dll",
        function: "ConvertSidToStringSidA",
        abi: LogicalAbi::WinApi,
        params: &[
            ParamSpec::new("Sid", GuestPtr),
            ParamSpec::with_dir("StringSid", GuestPtr, Out),
        ],
        ret: ReturnSpec::Bool32,
        flags: HookFlags::empty(),
    },
];
